### ISSUE TITLE
`amplifyPush --simple` failed with error `TypeError: Cannot read property 'join' of null`

### ISSUE THREAD

**Issue by netmarkjp** [aws-amplify/amplify-console#1031]
** Please describe which feature you have a question about? **

- amplify: 4.29.0
- amplifyPush.sh: 82724ef
- frontend: react(typescript), yarn
- backend: API, function(go)
- build/deploy on amplify console

I've got the error "TypeError: Cannot read property 'join' of null" while `amplifyPush --simple`.
Finally, I found workaround below.
I don't know why these errors occurred, and why I can avoid that...
Anyway, I want to share my experience, and I hope that amplify will be more sophisticated.
(I think that this issue should be closed after maintainers read this.)

- Remove `--yes` from `amplify init`
- Add `"defaultEditor": "none"` to variable `AMPLIFY`

```patch
--- /tmp/amplifyPush.sh 2020-09-07 02:57:55.208869400 +0900
+++ docker/amplifyPush.sh       2020-09-07 02:58:21.848869400 +0900
@@ -21,7 +21,7 @@
     if [[ -z ${STACKINFO} ]];
     then
         echo "# Initializing new Amplify environment: ${ENV} (amplify init)"
-        [[ -z ${CATEGORIES} ]] && amplify init --amplify ${AMPLIFY} --providers ${PROVIDERS} --codegen ${CODEGEN} --yes || amplify init --amplify ${AMPLIFY} --providers ${PROVIDERS} --codegen ${CODEGEN} --categories ${CATEGORIES} --yes
+        [[ -z ${CATEGORIES} ]] && amplify init --amplify ${AMPLIFY} --providers ${PROVIDERS} --codegen ${CODEGEN} || amplify init --amplify ${AMPLIFY} --providers ${PROVIDERS} --codegen ${CODEGEN} --categories ${CATEGORIES}
         echo "# Environment ${ENV} details:"
         amplify env get --name ${ENV}
     else
@@ -29,7 +29,7 @@
         echo "# Importing Amplify environment: ${ENV} (amplify env import)"
         amplify env import --name ${ENV} --config "${STACKINFO}" --awsInfo ${AWSCONFIG} --yes;
         echo "# Initializing existing Amplify environment: ${ENV} (amplify init)"
-        [[ -z ${CATEGORIES} ]] && amplify init --amplify ${AMPLIFY} --providers ${PROVIDERS} --codegen ${CODEGEN} --yes || amplify init --amplify ${AMPLIFY} --providers ${PROVIDERS} --codegen ${CODEGEN} --categories ${CATEGORIES} --yes
+        [[ -z ${CATEGORIES} ]] && amplify init --amplify ${AMPLIFY} --providers ${PROVIDERS} --codegen ${CODEGEN} || amplify init --amplify ${AMPLIFY} --providers ${PROVIDERS} --codegen ${CODEGEN} --categories ${CATEGORIES}
         echo "# Environment ${ENV} details:"
         amplify env get --name ${ENV}
     fi
@@ -87,6 +87,7 @@
 \"AmplifyAppId\":\"${AWS_APP_ID}\"\
 }"
 AMPLIFY="{\
+\"defaultEditor\":\"none\",\
 \"envName\":\"${ENV}\",\
 \"appId\":\"${AWS_APP_ID}\"\
 }"
```

** Provide additional details**

I've got these errors below in `backend` phase(at the time `amplifyPush --simple`).

```
2020-09-06T13:58:14.470Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-09-06T13:58:20.369Z [INFO]: 
2020-09-06T13:58:20.370Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html
2020-09-06T13:58:20.638Z [INFO]: Amplify AppID found: <APP_ID>. Amplify App name is: <APP_NAME>
2020-09-06T13:58:20.717Z [INFO]: Backend environment dev found in Amplify Console app: <APP_NAME>
2020-09-06T13:58:24.157Z [INFO]: 
2020-09-06T13:58:24.160Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2020-09-06T13:58:25.190Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2020-09-06T13:58:26.017Z [WARNING]: go: downloading github.com/aws/aws-sdk-go v1.34.13
2020-09-06T13:58:26.019Z [WARNING]: go: downloading github.com/aws/aws-lambda-go v1.19.1
2020-09-06T13:58:27.976Z [WARNING]: go: downloading github.com/jmespath/go-jmespath v0.3.0
2020-09-06T13:58:31.561Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2020-09-06T13:58:31.563Z [WARNING]: ✖ There was an error initializing your environment.
2020-09-06T13:58:31.570Z [INFO]: Failed to pull the backend.
2020-09-06T13:58:31.572Z [INFO]: Cannot read property 'join' of null
2020-09-06T13:58:31.580Z [INFO]: TypeError: Cannot read property 'join' of null
                                 at runPackageManager (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:54:47)
                                 at installDependencies (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:38:3)
                                 at Object.buildResource (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:12:5)
                                 at Object.build (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/index.ts:44:22)
                                 at buildResource (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/build-resources.js:49:36)
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
2020-09-06T13:58:31.593Z [ERROR]: !!! Build failed
2020-09-06T13:58:31.709Z [ERROR]: !!! Non-Zero Exit Code detected
2020-09-06T13:58:31.709Z [INFO]: # Starting environment caching...
2020-09-06T13:58:31.709Z [INFO]: # Environment caching completed
Terminating logging...
```

**Comment by nimacks** [comment]
Thank you for the feedback, we'll use this information to improve how Amplify works.

**Comment by PeteDuncanson** [comment]
I'm having a similar error when our CI is trying to do a pull. Any pointers on what the issue actually is and what I can do to clear it?

```
 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-10-05T14:00:22.505Z [INFO]: 
2020-10-05T14:00:22.507Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html
2020-10-05T14:00:22.519Z [WARNING]: (node:1969) ExperimentalWarning: The fs.promises API is experimental
2020-10-05T14:00:22.790Z [INFO]: Amplify AppID found: MY_ID. Amplify App name is: MY_APP_NAME
2020-10-05T14:00:22.851Z [INFO]: Backend environment dev found in Amplify Console app: MY_APP_NAME
2020-10-05T14:00:25.542Z [INFO]: 
2020-10-05T14:00:25.545Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2020-10-05T14:00:27.748Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2020-10-05T14:00:27.956Z [INFO]: Adding Lambda layer myDataImporterLayer to dev environment.
2020-10-05T14:00:28.918Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2020-10-05T14:00:28.920Z [WARNING]: ✖ There was an error initializing your environment.
2020-10-05T14:00:28.984Z [INFO]: Failed to pull the backend.
2020-10-05T14:00:28.986Z [INFO]: Cannot read property 'join' of null
2020-10-05T14:00:28.997Z [INFO]: TypeError: Cannot read property 'join' of null
                                 at runPackageManager (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:54:47)
                                 at installDependencies (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:38:3)
                                 at Object.buildResource (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:12:5)
                                 at Object.build (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/index.ts:44:22)
                                 at buildResource (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/build-resources.js:49:36)
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
2020-10-05T14:00:29.011Z [ERROR]: !!! Build failed
2020-10-05T14:00:29.011Z [ERROR]: !!! Non-Zero Exit Code detected
2020-10-05T14:00:29.011Z [INFO]: # Starting environment caching...
2020-10-05T14:00:29.012Z [INFO]: # Environment caching completed
```

**Comment by prog585** [comment]
For me it seems a problem in autogenerated schema file in build folder. I deleted auto generated schema file and recompiled using amplify api gql-compile pushed the changes again and that problem gone. That file was modified by a team members to add comments in it.
