### ISSUE TITLE
Unable to get npm package building react app with react-app-rewired in monorepo

### ISSUE THREAD

**Issue by hoffination** [aws-amplify/amplify-console#1092]
** Please describe which feature you have a question about? **
I can't get a React app to build in AWS amplify. I've tried a couple of different things but it seems like npm isn't set up to source from local `node_modules`

** Provide additional details**
I used the monorepo settings first to get my build running within my app. I have a package.json command to build my `react-client` folder:

```
"build": "react-app-rewired build",
```

When setting up the console gave me an easy interface but started crashing because the `react-app-rewired` call could not be found. As I result I updated my script to use `npx` instead:

```
"build": "npx react-app-rewired build",
```

However now I'm getting a new error:

`Cannot find module 'react-dev-utils/crossSpawn'`

I've tried adding a specific install above (using both global and local installs) which didn't resolve the issue and so I'm left thinking that something isn't right about the npm configuration in the build pipeline.
Here's my build settings YAML

```yaml
version: 1
applications:
  - backend:
      phases:
        build:
          commands:
            - '# Execute Amplify CLI with the helper script'
            - amplifyPush --simple
    frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - npm i -g react-dev-utils
            - npm run build
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: /react-client
```

Anything I'm not doing that I should be? My CircleCI script by comparison is dead simple

<details><summary>The build logs</summary>

```
                                 ## Completed Backend Build
2020-09-26T21:40:32.408Z [INFO]: ## Starting Frontend Build
                                 # Starting phase: preBuild
                                 # Executing command: npm ci
2020-09-26T21:40:47.988Z [INFO]: > core-js@3.6.5 postinstall /codebuild/output/src241834028/src/our-story-game/react-client/node_modules/yup-phone/node_modules/core-js
                                 > node -e "try{require('./postinstall')}catch(e){}"
2020-09-26T21:40:48.077Z [INFO]: > styled-components@4.4.1 postinstall /codebuild/output/src241834028/src/our-story-game/react-client/node_modules/styled-components
                                 > node ./scripts/postinstall.js || exit 0
2020-09-26T21:40:48.134Z [INFO]: Use styled-components at work? Consider supporting our development efforts at https://opencollective.com/styled-components
2020-09-26T21:40:48.151Z [INFO]: > core-js@2.6.11 postinstall /codebuild/output/src241834028/src/our-story-game/react-client/node_modules/babel-runtime/node_modules/core-js
                                 > node -e "try{require('./postinstall')}catch(e){}"
2020-09-26T21:40:48.299Z [INFO]: > fsevents@1.2.13 install /codebuild/output/src241834028/src/our-story-game/react-client/node_modules/webpack-dev-server/node_modules/fsevents
                                 > node install.js
2020-09-26T21:40:48.357Z [INFO]: 
2020-09-26T21:40:48.358Z [INFO]: Skipping 'fsevents' build as platform linux is not supported
2020-09-26T21:40:48.392Z [INFO]: > fsevents@1.2.12 install /codebuild/output/src241834028/src/our-story-game/react-client/node_modules/watchpack/node_modules/fsevents
                                 > node-gyp rebuild
2020-09-26T21:40:48.510Z [WARNING]: gyp
2020-09-26T21:40:48.511Z [WARNING]: 
2020-09-26T21:40:48.512Z [WARNING]: info it worked if it ends with ok
2020-09-26T21:40:48.513Z [WARNING]: gyp
2020-09-26T21:40:48.513Z [WARNING]: info using node-gyp@3.8.0
                                    gyp info using node@10.16.0 | linux | x64
2020-09-26T21:40:49.593Z [WARNING]: gyp
2020-09-26T21:40:49.595Z [WARNING]: info spawn /usr/bin/python2
                                    gyp info spawn args [ '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
                                    gyp info spawn args   'binding.gyp',
                                    gyp info spawn args   '-f',
                                    gyp info spawn args   'make',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/codebuild/output/src241834028/src/our-story-game/react-client/node_modules/watchpack/node_modules/fsevents/build/config.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.node-gyp/10.16.0/include/node/common.gypi',
                                    gyp info spawn args   '-Dlibrary=shared_library',
                                    gyp info spawn args   '-Dvisibility=default',
                                    gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.16.0',
                                    gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp',
                                    gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/10.16.0/<(target_arch)/node.lib',
                                    gyp info spawn args   '-Dmodule_root_dir=/codebuild/output/src241834028/src/our-story-game/react-client/node_modules/watchpack/node_modules/fsevents',
                                    gyp info spawn args   '-Dnode_engine=v8',
                                    gyp info spawn args   '--depth=.',
                                    gyp info spawn args   '--no-parallel',
                                    gyp info spawn args   '--generator-output',
                                    gyp info spawn args   'build',
                                    gyp info spawn args   '-Goutput_dir=.' ]
2020-09-26T21:40:50.140Z [WARNING]: gyp info spawn make
2020-09-26T21:40:50.141Z [WARNING]: gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2020-09-26T21:40:50.144Z [INFO]: make: Entering directory `/codebuild/output/src241834028/src/our-story-game/react-client/node_modules/watchpack/node_modules/fsevents/build'
2020-09-26T21:40:50.145Z [INFO]: SOLINK_MODULE(target) Release/obj.target/.node
2020-09-26T21:40:50.783Z [INFO]: COPY Release/.node
2020-09-26T21:40:50.790Z [INFO]: make: Leaving directory `/codebuild/output/src241834028/src/our-story-game/react-client/node_modules/watchpack/node_modules/fsevents/build'
2020-09-26T21:40:50.793Z [WARNING]: gyp info ok
2020-09-26T21:40:50.875Z [INFO]: > core-js@3.6.4 postinstall /codebuild/output/src241834028/src/our-story-game/react-client/node_modules/core-js
                                 > node -e "try{require('./postinstall')}catch(e){}"
2020-09-26T21:40:51.003Z [INFO]: > fsevents@1.2.13 install /codebuild/output/src241834028/src/our-story-game/react-client/node_modules/jest-haste-map/node_modules/fsevents
                                 > node install.js
2020-09-26T21:40:51.061Z [INFO]: 
2020-09-26T21:40:51.062Z [INFO]: Skipping 'fsevents' build as platform linux is not supported
2020-09-26T21:40:51.114Z [INFO]: > core-js-pure@3.6.4 postinstall /codebuild/output/src241834028/src/our-story-game/react-client/node_modules/core-js-pure
                                 > node -e "try{require('./postinstall')}catch(e){}"
2020-09-26T21:40:51.286Z [INFO]: > node-sass@4.14.1 install /codebuild/output/src241834028/src/our-story-game/react-client/node_modules/node-sass
                                 > node scripts/install.js
2020-09-26T21:40:52.159Z [INFO]: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-64_binding.node
2020-09-26T21:40:52.305Z [INFO]: Download complete
2020-09-26T21:40:52.308Z [INFO]: Binary saved to /codebuild/output/src241834028/src/our-story-game/react-client/node_modules/node-sass/vendor/linux-x64-64/binding.node
2020-09-26T21:40:52.345Z [INFO]: > node-sass@4.14.1 postinstall /codebuild/output/src241834028/src/our-story-game/react-client/node_modules/node-sass
                                 > node scripts/build.js
2020-09-26T21:40:52.352Z [WARNING]: (node:1988) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
2020-09-26T21:40:52.486Z [INFO]: Binary found at /codebuild/output/src241834028/src/our-story-game/react-client/node_modules/node-sass/vendor/linux-x64-64/binding.node
2020-09-26T21:40:52.487Z [INFO]: Testing binary
2020-09-26T21:40:52.580Z [INFO]: Binary is fine
2020-09-26T21:40:52.597Z [INFO]: > fast-xml-parser@3.17.4 postinstall /codebuild/output/src241834028/src/our-story-game/react-client/node_modules/fast-xml-parser
                                 > node tasks/postinstall.js || exit 0
2020-09-26T21:40:52.651Z [INFO]: [96m[1mLove fast-xml-parser? Check [32mhttps://amitkumargupta.work [96m[1mfor more projects and contribution.[0m
2020-09-26T21:40:52.675Z [INFO]: added 2002 packages in 19.883s
2020-09-26T21:40:52.688Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
                                 # Executing command: pwd
2020-09-26T21:40:52.688Z [INFO]: /codebuild/output/src241834028/src/our-story-game/react-client
                                 # Executing command: npm i -g react-dev-utils
2020-09-26T21:40:57.672Z [WARNING]: npm
2020-09-26T21:40:57.673Z [WARNING]: WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/react-dev-utils/node_modules/chokidar/node_modules/fsevents):
                                    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2020-09-26T21:40:57.674Z [INFO]: + react-dev-utils@10.2.1
                                 added 256 packages from 166 contributors in 4.631s
2020-09-26T21:40:57.682Z [INFO]: # Executing command: npm run build
2020-09-26T21:40:57.868Z [INFO]: > react-client@0.1.0 build /codebuild/output/src241834028/src/our-story-game/react-client
                                 > npx react-app-rewired build
2020-09-26T21:40:58.826Z [WARNING]: npx: installed 2 in 0.892s
2020-09-26T21:40:58.828Z [WARNING]: Cannot find module 'react-dev-utils/crossSpawn'
2020-09-26T21:40:58.839Z [WARNING]: npm
2020-09-26T21:40:58.840Z [WARNING]: ERR! code ELIFECYCLE
                                    npm ERR! errno 1
                                    npm ERR! react-client@0.1.0 build: `npx react-app-rewired build`
                                    npm ERR! Exit status 1
                                    npm ERR!
                                    npm ERR! Failed at the react-client@0.1.0 build script.
2020-09-26T21:40:58.841Z [WARNING]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-26T21:40:58.847Z [WARNING]: 
2020-09-26T21:40:58.848Z [WARNING]: npm ERR! A complete log of this run can be found in:
                                    npm ERR!     /root/.npm/_logs/2020-09-26T21_40_58_841Z-debug.log
2020-09-26T21:40:58.848Z [HELP]: Outputting the npm debug log
                                 0 info it worked if it ends with ok
                                 1 verbose cli [ '/root/.nvm/versions/node/v10.16.0/bin/node',
                                 1 verbose cli   '/root/.nvm/versions/node/v10.16.0/bin/npm',
                                 1 verbose cli   'run',
                                 1 verbose cli   'build' ]
                                 2 info using npm@6.9.0
                                 3 info using node@v10.16.0
                                 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
                                 5 info lifecycle react-client@0.1.0~prebuild: react-client@0.1.0
                                 6 info lifecycle react-client@0.1.0~build: react-client@0.1.0
                                 7 verbose lifecycle react-client@0.1.0~build: unsafe-perm in lifecycle true
                                 8 verbose lifecycle react-client@0.1.0~build: PATH: /root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/codebuild/output/src241834028/src/our-story-game/react-client/node_modules/.bin:/usr/local/rvm/gems/ruby-2.4.6/bin:/usr/local/rvm/gems/ruby-2.4.6@global/bin:/usr/local/rvm/rubies/ruby-2.4.6/bin:/usr/local/rvm/bin:/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:/root/.nvm/versions/node/v10.16.0/bin:/root/.local/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
                                 9 verbose lifecycle react-client@0.1.0~build: CWD: /codebuild/output/src241834028/src/our-story-game/react-client
                                 10 silly lifecycle react-client@0.1.0~build: Args: [ '-c', 'npx react-app-rewired build' ]
                                 11 silly lifecycle react-client@0.1.0~build: Returned: code: 1  signal: null
                                 12 info lifecycle react-client@0.1.0~build: Failed to exec build script
                                 13 verbose stack Error: react-client@0.1.0 build: `npx react-app-rewired build`
                                 13 verbose stack Exit status 1
                                 13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
                                 13 verbose stack     at EventEmitter.emit (events.js:198:13)
                                 13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
                                 13 verbose stack     at ChildProcess.emit (events.js:198:13)
                                 13 verbose stack     at maybeClose (internal/child_process.js:982:16)
                                 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
                                 14 verbose pkgid react-client@0.1.0
                                 15 verbose cwd /codebuild/output/src241834028/src/our-story-game/react-client
                                 16 verbose Linux 4.14.193-113.317.amzn1.x86_64
                                 17 verbose argv "/root/.nvm/versions/node/v10.16.0/bin/node" "/root/.nvm/versions/node/v10.16.0/bin/npm" "run" "build"
                                 18 verbose node v10.16.0
                                 19 verbose npm  v6.9.0
                                 20 error code ELIFECYCLE
                                 21 error errno 1
                                 22 error react-client@0.1.0 build: `npx react-app-rewired build`
                                 22 error Exit status 1
                                 23 error Failed at the react-client@0.1.0 build script.
                                 23 error This is probably not a problem with npm. There is likely additional logging output above.
                                 24 verbose exit [ 1, true ]
2020-09-26T21:40:58.850Z [ERROR]: !!! Build failed
2020-09-26T21:40:58.945Z [ERROR]: !!! Non-Zero Exit Code detected
2020-09-26T21:40:58.945Z [INFO]: # Starting environment caching...
2020-09-26T21:40:58.946Z [INFO]: # Environment caching completed
Terminating logging...
```
</details>

**Comment by ganipcanot** [comment]
@hoffination Could you share your `appId` and `region` please?

**Comment by ganipcanot** [comment]
Also can you confirm: It looks like you're using a build setting YAML for monorepo but it looks like you only have 1 application defined.  Is that your intention?  [Here is the reference doc for mono repo config](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#monorepo-configuration).

**Comment by hoffination** [comment]
@ganipcanot my region is `us-east-1` and appId is`d2kf333b37g83y`

Ah, yes. I'm in a monorepo with only one Amplify app. The other folder in the repo has a AWS CDK configuration. I went with this approach because I wanted to access everything in the subfolder and thought that `appRoot` was a good way of getting at the subfolder without having to change directory across the each command.

I can give that change a shot if you think it might resolve the issue.

**Comment by litwicki** [comment]
@hoffination are you still experiencing issues?

**Comment by hoffination** [comment]
@litwicki I decided to go with the AWS CDK to simply my deployment with other parts of my architecture. Revisiting my existing setup there is now an error where appRoot wasn't found. I'll try a couple of things and message back if I get to a new spot with this working.

**Comment by victorccccc** [comment]
Hi, sorry for the inconvenience. We've updated Monorepo feature and you can specify `appRoot` via `AMPLIFY_MONOREPO_APP_ROOT` environment variable. In your case, you might need to set `appRoot` to  `react-client`

Docs for reference: https://docs.aws.amazon.com/amplify/latest/userguide/monorepo-configuration.html

Feel free to reopen this if issue persists. Thanks!
