### ISSUE TITLE
Cannot find module '@ionic-native/Camera/ngx' on remote build service

### ISSUE THREAD

**Issue by duiliodaniele** [aws-amplify/amplify-console#1110]
hello,
I'm a noob on amplify, I use that about 10 month, now I add on my project angular/ionic a Camera module, but from that moment the build on aws amplify console failed,

that's the log:

2020-10-03T20:12:45.524Z [INFO]: # Starting phase: preBuild
                                 # Executing command: npm ci
2020-10-03T20:12:45.907Z [WARNING]: npm
2020-10-03T20:12:45.907Z [WARNING]: WARN prepare removing existing node_modules/ before installation
2020-10-03T20:13:09.954Z [INFO]: > core-js@2.6.11 postinstall /codebuild/output/src159509456/src/ilMioProvino/node_modules/core-js
                                 > node -e "try{require('./postinstall')}catch(e){}"
2020-10-03T20:13:10.267Z [INFO]: > fsevents@1.2.11 install /codebuild/output/src159509456/src/ilMioProvino/node_modules/karma/node_modules/fsevents
                                 > node-gyp rebuild
2020-10-03T20:13:10.418Z [WARNING]: gyp
2020-10-03T20:13:10.419Z [WARNING]: 
2020-10-03T20:13:10.419Z [WARNING]: info it worked if it ends with ok
2020-10-03T20:13:10.420Z [WARNING]: gyp
2020-10-03T20:13:10.421Z [WARNING]: info using node-gyp@3.8.0
                                    gyp info using node@10.16.0 | linux | x64
2020-10-03T20:13:12.258Z [WARNING]: gyp
2020-10-03T20:13:12.260Z [WARNING]: info spawn /usr/bin/python2
                                    gyp info spawn args [ '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
                                    gyp info spawn args   'binding.gyp',
                                    gyp info spawn args   '-f',
                                    gyp info spawn args   'make',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/codebuild/output/src159509456/src/ilMioProvino/node_modules/karma/node_modules/fsevents/build/config.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.node-gyp/10.16.0/include/node/common.gypi',
                                    gyp info spawn args   '-Dlibrary=shared_library',
                                    gyp info spawn args   '-Dvisibility=default',
                                    gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.16.0',
                                    gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp',
                                    gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/10.16.0/<(target_arch)/node.lib',
                                    gyp info spawn args   '-Dmodule_root_dir=/codebuild/output/src159509456/src/ilMioProvino/node_modules/karma/node_modules/fsevents',
                                    gyp info spawn args   '-Dnode_engine=v8',
                                    gyp info spawn args   '--depth=.',
                                    gyp info spawn args   '--no-parallel',
                                    gyp info spawn args   '--generator-output',
                                    gyp info spawn args   'build',
                                    gyp info spawn args   '-Goutput_dir=.' ]
2020-10-03T20:13:13.085Z [WARNING]: gyp info spawn make
2020-10-03T20:13:13.085Z [WARNING]: gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2020-10-03T20:13:13.087Z [INFO]: make: Entering directory `/codebuild/output/src159509456/src/ilMioProvino/node_modules/karma/node_modules/fsevents/build'
2020-10-03T20:13:13.089Z [INFO]: SOLINK_MODULE(target) Release/obj.target/.node
2020-10-03T20:13:14.025Z [INFO]: COPY Release/.node
2020-10-03T20:13:14.031Z [INFO]: make: Leaving directory `/codebuild/output/src159509456/src/ilMioProvino/node_modules/karma/node_modules/fsevents/build'
2020-10-03T20:13:14.032Z [WARNING]: gyp info ok
2020-10-03T20:13:14.073Z [INFO]: > fsevents@1.2.11 install /codebuild/output/src159509456/src/ilMioProvino/node_modules/@angular/compiler-cli/node_modules/fsevents
                                 > node-gyp rebuild
2020-10-03T20:13:14.162Z [WARNING]: gyp
2020-10-03T20:13:14.163Z [WARNING]: info it worked if it ends with ok
2020-10-03T20:13:14.164Z [WARNING]: gyp
2020-10-03T20:13:14.164Z [WARNING]: info using node-gyp@3.8.0
                                    gyp info using node@10.16.0 | linux | x64
2020-10-03T20:13:14.295Z [WARNING]: gyp
2020-10-03T20:13:14.295Z [WARNING]: info spawn /usr/bin/python2
                                    gyp info spawn args [ '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
                                    gyp info spawn args   'binding.gyp',
                                    gyp info spawn args   '-f',
                                    gyp info spawn args   'make',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/codebuild/output/src159509456/src/ilMioProvino/node_modules/@angular/compiler-cli/node_modules/fsevents/build/config.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2020-10-03T20:13:14.296Z [WARNING]: gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.node-gyp/10.16.0/include/node/common.gypi',
                                    gyp info spawn args   '-Dlibrary=shared_library',
                                    gyp info spawn args   '-Dvisibility=default',
                                    gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.16.0',
                                    gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp',
                                    gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/10.16.0/<(target_arch)/node.lib',
                                    gyp info spawn args   '-Dmodule_root_dir=/codebuild/output/src159509456/src/ilMioProvino/node_modules/@angular/compiler-cli/node_modules/fsevents',
                                    gyp info spawn args   '-Dnode_engine=v8',
                                    gyp info spawn args   '--depth=.',
                                    gyp info spawn args   '--no-parallel',
                                    gyp info spawn args   '--generator-output',
                                    gyp info spawn args   'build',
                                    gyp info spawn args   '-Goutput_dir=.' ]
2020-10-03T20:13:14.341Z [WARNING]: gyp
2020-10-03T20:13:14.341Z [WARNING]: info spawn make
                                    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2020-10-03T20:13:14.342Z [INFO]: make: Entering directory `/codebuild/output/src159509456/src/ilMioProvino/node_modules/@angular/compiler-cli/node_modules/fsevents/build'
2020-10-03T20:13:14.342Z [INFO]: SOLINK_MODULE(target) Release/obj.target/.node
2020-10-03T20:13:14.389Z [INFO]: COPY Release/.node
2020-10-03T20:13:14.396Z [INFO]: make: Leaving directory `/codebuild/output/src159509456/src/ilMioProvino/node_modules/@angular/compiler-cli/node_modules/fsevents/build'
2020-10-03T20:13:14.396Z [WARNING]: gyp info ok
2020-10-03T20:13:14.396Z [WARNING]: 
2020-10-03T20:13:14.434Z [INFO]: > @angular/cli@8.3.29 postinstall /codebuild/output/src159509456/src/ilMioProvino/node_modules/@angular/cli
                                 > node ./bin/postinstall/script.js
2020-10-03T20:13:14.797Z [INFO]: > fsevents@1.2.11 install /codebuild/output/src159509456/src/ilMioProvino/node_modules/webpack-dev-server/node_modules/fsevents
                                 > node-gyp rebuild
2020-10-03T20:13:14.885Z [WARNING]: gyp
2020-10-03T20:13:14.885Z [WARNING]: 
2020-10-03T20:13:14.885Z [WARNING]: info it worked if it ends with ok
2020-10-03T20:13:14.887Z [WARNING]: gyp
2020-10-03T20:13:14.887Z [WARNING]: info using node-gyp@3.8.0
                                    gyp info using node@10.16.0 | linux | x64
2020-10-03T20:13:15.015Z [WARNING]: gyp
2020-10-03T20:13:15.015Z [WARNING]: info spawn /usr/bin/python2
                                    gyp info spawn args [ '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
                                    gyp info spawn args   'binding.gyp',
                                    gyp info spawn args   '-f',
                                    gyp info spawn args   'make',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/codebuild/output/src159509456/src/ilMioProvino/node_modules/webpack-dev-server/node_modules/fsevents/build/config.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.node-gyp/10.16.0/include/node/common.gypi',
                                    gyp info spawn args   '-Dlibrary=shared_library',
                                    gyp info spawn args   '-Dvisibility=default',
                                    gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.16.0',
                                    gyp info
2020-10-03T20:13:15.015Z [WARNING]: spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp',
                                    gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/10.16.0/<(target_arch)/node.lib',
                                    gyp info spawn args   '-Dmodule_root_dir=/codebuild/output/src159509456/src/ilMioProvino/node_modules/webpack-dev-server/node_modules/fsevents',
                                    gyp info spawn args   '-Dnode_engine=v8',
                                    gyp info spawn args   '--depth=.',
                                    gyp info spawn args   '--no-parallel',
                                    gyp info spawn args   '--generator-output',
                                    gyp info spawn args   'build',
                                    gyp info spawn args   '-Goutput_dir=.' ]
2020-10-03T20:13:15.060Z [WARNING]: gyp
2020-10-03T20:13:15.060Z [WARNING]: info spawn make
                                    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2020-10-03T20:13:15.061Z [INFO]: make: Entering directory `/codebuild/output/src159509456/src/ilMioProvino/node_modules/webpack-dev-server/node_modules/fsevents/build'
2020-10-03T20:13:15.062Z [INFO]: SOLINK_MODULE(target) Release/obj.target/.node
2020-10-03T20:13:15.107Z [INFO]: COPY Release/.node
2020-10-03T20:13:15.113Z [INFO]: make: Leaving directory `/codebuild/output/src159509456/src/ilMioProvino/node_modules/webpack-dev-server/node_modules/fsevents/build'
2020-10-03T20:13:15.114Z [WARNING]: gyp
2020-10-03T20:13:15.114Z [WARNING]: info ok
2020-10-03T20:13:15.147Z [INFO]: > fsevents@1.2.11 install /codebuild/output/src159509456/src/ilMioProvino/node_modules/watchpack/node_modules/fsevents
                                 > node-gyp rebuild
2020-10-03T20:13:15.235Z [WARNING]: gyp
2020-10-03T20:13:15.236Z [WARNING]: info it worked if it ends with ok
2020-10-03T20:13:14.162Z [WARNING]: gyp
2020-10-03T20:13:14.163Z [WARNING]: info it worked if it ends with ok
2020-10-03T20:13:14.164Z [WARNING]: gyp
2020-10-03T20:13:14.164Z [WARNING]: info using node-gyp@3.8.0
                                    gyp info using node@10.16.0 | linux | x64
2020-10-03T20:13:14.295Z [WARNING]: gyp
2020-10-03T20:13:14.295Z [WARNING]: info spawn /usr/bin/python2
                                    gyp info spawn args [ '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
                                    gyp info spawn args   'binding.gyp',
                                    gyp info spawn args   '-f',
                                    gyp info spawn args   'make',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/codebuild/output/src159509456/src/ilMioProvino/node_modules/@angular/compiler-cli/node_modules/fsevents/build/config.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2020-10-03T20:13:14.296Z [WARNING]: gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.node-gyp/10.16.0/include/node/common.gypi',
                                    gyp info spawn args   '-Dlibrary=shared_library',
                                    gyp info spawn args   '-Dvisibility=default',
                                    gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.16.0',
                                    gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp',
                                    gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/10.16.0/<(target_arch)/node.lib',
                                    gyp info spawn args   '-Dmodule_root_dir=/codebuild/output/src159509456/src/ilMioProvino/node_modules/@angular/compiler-cli/node_modules/fsevents',
                                    gyp info spawn args   '-Dnode_engine=v8',
                                    gyp info spawn args   '--depth=.',
                                    gyp info spawn args   '--no-parallel',
                                    gyp info spawn args   '--generator-output',
                                    gyp info spawn args   'build',
                                    gyp info spawn args   '-Goutput_dir=.' ]
2020-10-03T20:13:14.341Z [WARNING]: gyp
2020-10-03T20:13:14.341Z [WARNING]: info spawn make
                                    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2020-10-03T20:13:14.342Z [INFO]: make: Entering directory `/codebuild/output/src159509456/src/ilMioProvino/node_modules/@angular/compiler-cli/node_modules/fsevents/build'
2020-10-03T20:13:14.342Z [INFO]: SOLINK_MODULE(target) Release/obj.target/.node
2020-10-03T20:13:14.389Z [INFO]: COPY Release/.node
2020-10-03T20:13:14.396Z [INFO]: make: Leaving directory `/codebuild/output/src159509456/src/ilMioProvino/node_modules/@angular/compiler-cli/node_modules/fsevents/build'
2020-10-03T20:13:14.396Z [WARNING]: gyp info ok
2020-10-03T20:13:14.396Z [WARNING]: 
2020-10-03T20:13:14.434Z [INFO]: > @angular/cli@8.3.29 postinstall /codebuild/output/src159509456/src/ilMioProvino/node_modules/@angular/cli
                                 > node ./bin/postinstall/script.js
2020-10-03T20:13:14.797Z [INFO]: > fsevents@1.2.11 install /codebuild/output/src159509456/src/ilMioProvino/node_modules/webpack-dev-server/node_modules/fsevents
                                 > node-gyp rebuild
2020-10-03T20:13:14.885Z [WARNING]: gyp
2020-10-03T20:13:14.885Z [WARNING]: 
2020-10-03T20:13:14.885Z [WARNING]: info it worked if it ends with ok
2020-10-03T20:13:14.887Z [WARNING]: gyp
2020-10-03T20:13:14.887Z [WARNING]: info using node-gyp@3.8.0
                                    gyp info using node@10.16.0 | linux | x64
2020-10-03T20:13:15.015Z [WARNING]: gyp
2020-10-03T20:13:15.015Z [WARNING]: info spawn /usr/bin/python2
                                    gyp info spawn args [ '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
                                    gyp info spawn args   'binding.gyp',
                                    gyp info spawn args   '-f',
                                    gyp info spawn args   'make',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/codebuild/output/src159509456/src/ilMioProvino/node_modules/webpack-dev-server/node_modules/fsevents/build/config.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.node-gyp/10.16.0/include/node/common.gypi',
                                    gyp info spawn args   '-Dlibrary=shared_library',
                                    gyp info spawn args   '-Dvisibility=default',
                                    gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.16.0',
                                    gyp info
2020-10-03T20:13:15.015Z [WARNING]: spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp',
                                    gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/10.16.0/<(target_arch)/node.lib',
                                    gyp info spawn args   '-Dmodule_root_dir=/codebuild/output/src159509456/src/ilMioProvino/node_modules/webpack-dev-server/node_modules/fsevents',
                                    gyp info spawn args   '-Dnode_engine=v8',
                                    gyp info spawn args   '--depth=.',
                                    gyp info spawn args   '--no-parallel',
                                    gyp info spawn args   '--generator-output',
                                    gyp info spawn args   'build',
                                    gyp info spawn args   '-Goutput_dir=.' ]
2020-10-03T20:13:15.060Z [WARNING]: gyp
2020-10-03T20:13:15.060Z [WARNING]: info spawn make
                                    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2020-10-03T20:13:15.061Z [INFO]: make: Entering directory `/codebuild/output/src159509456/src/ilMioProvino/node_modules/webpack-dev-server/node_modules/fsevents/build'
2020-10-03T20:13:15.062Z [INFO]: SOLINK_MODULE(target) Release/obj.target/.node
2020-10-03T20:13:15.107Z [INFO]: COPY Release/.node
2020-10-03T20:13:15.113Z [INFO]: make: Leaving directory `/codebuild/output/src159509456/src/ilMioProvino/node_modules/webpack-dev-server/node_modules/fsevents/build'
2020-10-03T20:13:15.114Z [WARNING]: gyp
2020-10-03T20:13:15.114Z [WARNING]: info ok
2020-10-03T20:13:15.147Z [INFO]: > fsevents@1.2.11 install /codebuild/output/src159509456/src/ilMioProvino/node_modules/watchpack/node_modules/fsevents
                                 > node-gyp rebuild
2020-10-03T20:13:15.235Z [WARNING]: gyp
2020-10-03T20:13:15.236Z [WARNING]: info it worked if it ends with ok
2020-10-03T20:13:15.237Z [WARNING]: gyp info using
2020-10-03T20:13:15.238Z [WARNING]: node-gyp@3.8.0
                                    gyp info using node@10.16.0 | linux | x64
2020-10-03T20:13:15.366Z [WARNING]: gyp
2020-10-03T20:13:15.367Z [WARNING]: info spawn /usr/bin/python2
                                    gyp info spawn args [ '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
                                    gyp info spawn args   'binding.gyp',
                                    gyp info spawn args   '-f',
                                    gyp info spawn args   'make',
                                    gyp info
2020-10-03T20:13:15.367Z [WARNING]: spawn args   '-I',
                                    gyp info spawn args   '/codebuild/output/src159509456/src/ilMioProvino/node_modules/watchpack/node_modules/fsevents/build/config.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args
2020-10-03T20:13:15.367Z [WARNING]: '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.node-gyp/10.16.0/include/node/common.gypi',
                                    gyp info spawn args   '-Dlibrary=shared_library',
2020-10-03T20:13:15.367Z [WARNING]: gyp info spawn args   '-Dvisibility=default',
                                    gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.16.0',
                                    gyp info spawn args
2020-10-03T20:13:15.367Z [WARNING]: '-Dnode_gyp_dir=/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp',
                                    gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/10.16.0/<(target_arch)/node.lib',
                                    gyp info spawn args   '-Dmodule_root_dir=/codebuild/output/src159509456/src/ilMioProvino/node_modules/watchpack/node_modules/fsevents',
                                    gyp info
2020-10-03T20:13:15.367Z [WARNING]: spawn args   '-Dnode_engine=v8',
                                    gyp info spawn args   '--depth=.',
                                    gyp info spawn args   '--no-parallel',
                                    gyp
2020-10-03T20:13:15.368Z [WARNING]: info spawn args   '--generator-output',
                                    gyp info spawn args   'build',
                                    gyp info spawn args   '-Goutput_dir=.' ]
2020-10-03T20:13:15.411Z [WARNING]: gyp
2020-10-03T20:13:15.412Z [WARNING]: info spawn make
                                    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2020-10-03T20:13:15.413Z [INFO]: make: Entering directory `/codebuild/output/src159509456/src/ilMioProvino/node_modules/watchpack/node_modules/fsevents/build'
2020-10-03T20:13:15.414Z [INFO]: SOLINK_MODULE(target) Release/obj.target/.node
2020-10-03T20:13:15.460Z [INFO]: COPY Release/.node
2020-10-03T20:13:15.466Z [INFO]: make: Leaving directory `/codebuild/output/src159509456/src/ilMioProvino/node_modules/watchpack/node_modules/fsevents/build'
2020-10-03T20:13:15.466Z [WARNING]: gyp info
2020-10-03T20:13:15.467Z [WARNING]: ok
2020-10-03T20:13:15.524Z [INFO]: > core-js@3.1.4 postinstall /codebuild/output/src159509456/src/ilMioProvino/node_modules/@angular-devkit/build-angular/node_modules/core-js
                                 > node scripts/postinstall || echo "ignore"
2020-10-03T20:13:15.580Z [INFO]: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
2020-10-03T20:13:15.580Z [INFO]: The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
                                 > https://opencollective.com/core-js
                                 > https://www.patreon.com/zloirock
                                 Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
2020-10-03T20:13:15.595Z [INFO]: added 1679 packages in 29.706s
2020-10-03T20:13:15.608Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
2020-10-03T20:13:15.609Z [INFO]: # Executing command: npm run build
2020-10-03T20:13:15.784Z [INFO]: > prova@0.0.1 build /codebuild/output/src159509456/src/ilMioProvino
                                 > ng build
2020-10-03T20:13:32.014Z [INFO]: chunk {main} main-es2015.js, main-es2015.js.map (main) 645 bytes [initial] [rendered]
                                 chunk {polyfills} polyfills-es2015.js, polyfills-es2015.js.map (polyfills) 149 kB [initial] [rendered]
                                 chunk {runtime} runtime-es2015.js, runtime-es2015.js.map (runtime) 6.09 kB [entry] [rendered]
                                 chunk {scripts} scripts.js, scripts.js.map (scripts) 439 kB [entry] [rendered]
                                 chunk {styles} styles-es2015.js, styles-es2015.js.map (styles) 3.28 MB [initial] [rendered]
                                 Date: 2020-10-03T20:13:32.013Z - Hash: d96aae5f0916b1fb5364 - Time: 13620ms
2020-10-03T20:13:32.015Z [INFO]: 
2020-10-03T20:13:32.016Z [WARNING]: ERROR in [96msrc/app/app.module.ts[0m:[93m32[0m:[93m24[0m - [91merror[0m[90m TS2307: [0mCannot find module '@ionic-native/Camera/ngx'.
                                    [7m32[0m import { Camera } from '@ionic-native/Camera/ngx';
                                    [7m  [0m [91m                       ~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
                                    [96msrc/app/my-profile/my-profile.component.ts[0m:[93m19[0m:[93m39[0m - [91merror[0m[90m TS2307: [0mCannot find module '@ionic-native/Camera/ngx'.
                                    [7m19[0m import { Camera, CameraOptions } from '@ionic-native/Camera/ngx';
                                    [7m  [0m [91m                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
2020-10-03T20:13:32.060Z [WARNING]: npm
2020-10-03T20:13:32.061Z [WARNING]: ERR! code ELIFECYCLE
                                    npm ERR! errno 1
                                    npm ERR! prova@0.0.1 build: `ng build`
                                    npm ERR! Exit status 1
                                    npm ERR!
                                    npm ERR! Failed at the prova@0.0.1 build script.
                                    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-10-03T20:13:32.066Z [WARNING]: npm ERR! A complete log of this run can be found in:
                                    npm ERR!     /root/.npm/_logs/2020-10-03T20_13_32_062Z-debug.log
2020-10-03T20:13:32.066Z [HELP]: Outputting the npm debug log
                                 0 info it worked if it ends with ok
                                 1 verbose cli [ '/root/.nvm/versions/node/v10.16.0/bin/node',
                                 1 verbose cli   '/root/.nvm/versions/node/v10.16.0/bin/npm',
                                 1 verbose cli   'run',
                                 1 verbose cli   'build' ]
                                 2 info using npm@6.9.0
                                 3 info using node@v10.16.0
                                 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
                                 5 info lifecycle prova@0.0.1~prebuild: prova@0.0.1
                                 6 info lifecycle prova@0.0.1~build: prova@0.0.1
                                 7 verbose lifecycle prova@0.0.1~build: unsafe-perm in lifecycle true
                                 8 verbose lifecycle prova@0.0.1~build: PATH: /root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/codebuild/output/src159509456/src/ilMioProvino/node_modules/.bin:/usr/local/rvm/gems/ruby-2.4.6/bin:/usr/local/rvm/gems/ruby-2.4.6@global/bin:/usr/local/rvm/rubies/ruby-2.4.6/bin:/usr/local/rvm/bin:/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:/root/.nvm/versions/node/v10.16.0/bin:/root/.local/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
                                 9 verbose lifecycle prova@0.0.1~build: CWD: /codebuild/output/src159509456/src/ilMioProvino
                                 10 silly lifecycle prova@0.0.1~build: Args: [ '-c', 'ng build' ]
                                 11 silly lifecycle prova@0.0.1~build: Returned: code: 1  signal: null
                                 12 info lifecycle prova@0.0.1~build: Failed to exec build script
                                 13 verbose stack Error: prova@0.0.1 build: `ng build`
                                 13 verbose stack Exit status 1
                                 13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
                                 13 verbose stack     at EventEmitter.emit (events.js:198:13)
                                 13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
                                 13 verbose stack     at ChildProcess.emit (events.js:198:13)
                                 13 verbose stack     at maybeClose (internal/child_process.js:982:16)
                                 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
                                 14 verbose pkgid prova@0.0.1
                                 15 verbose cwd /codebuild/output/src159509456/src/ilMioProvino
                                 16 verbose Linux 4.14.193-113.317.amzn1.x86_64
                                 17 verbose argv "/root/.nvm/versions/node/v10.16.0/bin/node" "/root/.nvm/versions/node/v10.16.0/bin/npm" "run" "build"
                                 18 verbose node v10.16.0
                                 19 verbose npm  v6.9.0
                                 20 error code ELIFECYCLE
                                 21 error errno 1
                                 22 error prova@0.0.1 build: `ng build`
                                 22 error Exit status 1
                                 23 error Failed at the prova@0.0.1 build script.
                                 23 error This is probably not a problem with npm. There is likely additional logging output above.
                                 24 verbose exit [ 1, true ]
2020-10-03T20:13:32.069Z [ERROR]: !!! Build failed
2020-10-03T20:13:32.140Z [ERROR]: !!! Non-Zero Exit Code detected
2020-10-03T20:13:32.140Z [INFO]: # Starting environment caching...
2020-10-03T20:13:32.141Z [INFO]: # Environment caching completed
Terminating logging...

on local all works fine, I tried to remove and add the package but notting to do.

plase help me.

**Comment by ganipcanot** [comment]
Could you share your `appId` and `region` please?

Also have you tried [this](https://forum.ionicframework.com/t/cannot-find-module-ionic-native-camera-ngx/190719)?

**Comment by duiliodaniele** [comment]
> Could you share your `appId` and `region` please?
> 
> Also have you tried [this](https://forum.ionicframework.com/t/cannot-find-module-ionic-native-camera-ngx/190719)?

o my god! .. I see that 3d but I didn't see the difference .. I try just now it works!!

thank you very much!
