### ISSUE TITLE
amplify console appears to fail build looking for function layer version

### ISSUE THREAD

**Issue by meop** [aws-amplify/amplify-console#1152]
Hello, we have an Amplify project that builds / deploy the backend fine with the CLI locally, but fails with this error in the console CI/CD setup:

`
2020-10-21T03:20:28.714Z [INFO]: Adding Lambda layer nodejsapilayer to prod environment.
2020-10-21T03:20:28.728Z [INFO]: 
2020-10-21T03:20:29.712Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-10-21T03:20:33.090Z [WARNING]: - Initializing your environment: prod
2020-10-21T03:20:33.576Z [WARNING]: ✔ Initialized provider successfully.
2020-10-21T03:20:36.340Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2020-10-21T03:20:36.350Z [WARNING]: ✖ There was an error initializing your environment.
2020-10-21T03:20:36.375Z [INFO]: init failed
2020-10-21T03:20:36.377Z [INFO]: TypeError: Cannot convert undefined or null to object
                                 at Function.entries (<anonymous>)
                                 at new LayerState (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/layerParams.ts:92:12)
                                 at /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/layerParams.ts:249:12
                                 at ensureLayerVersion (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts:90:54)
                                 at packageLayer (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts:27:9)
                                 at packageResource (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.js:298:68)
                                 at packageResources (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.js:370:19)
                                 at Object.run (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.js:47:11)
                                 at Object.pushResources (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/index.ts:43:25)
                                 at /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/src/initialize-env.ts:88:53
2020-10-21T03:20:36.393Z [ERROR]: !!! Build failed
2020-10-21T03:20:36.393Z [ERROR]: !!! Non-Zero Exit Code detected
`

The build's custom Docker image is a clone of the official build image, switching from Node 10 to 12 and updating a few other packages. I believe this error occurs in the default Amazon Linux 2 build image though, so that does not seem to be the issue.

Any ideas on how to fix this? It seems to fail processing a Lambda Layer.
Thank you.

**Comment by litwicki** [comment]
@meop are you seeing this after running `amplify push` or is this happening *in* the Amplify Console build step?

**Comment by meop** [comment]
@litwicki yes, _in_ the console during the build step.

CLI `amplify push` has no errors locally deploying the backend.

**Comment by litwicki** [comment]
Are you using a specific version of the CLI or the latest 4.30.0?

**Comment by meop** [comment]
The latest locally. The console build setting has the option set to overlay the latest on the image. The console has not been successful building the backend ever since I added the NodeJS function layer and functions using it.

**Comment by litwicki** [comment]
@meop are you still experiencing this issue? If so can you verify your `team-provider.json` file part of your build?

**Comment by meop** [comment]
I manually triggered a build and this time it worked. Not sure what changed. I can reopen if it happens again. Thank you.
