### ISSUE TITLE
Backend Deployment Failing with 'not in a valid amplify project'

### ISSUE THREAD

**Issue by amalik18** [aws-amplify/amplify-console#1189]
**App Id**: do1m04bp6tvo2
**Region**: us-east-1
**Step**:
**Status**:

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
So when I deploy my Amplify app it gets to the `BUILD` section and keeps failing under the `Backend` section.

**Error message**
Here is the full-stack trace for the error:
```
/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13
                                    throw up;
                                    ^
                                    Error: You are not working inside a valid amplify project.
                                    Use 'amplify init' in the root of your app directory to initialize your project with Amplify
                                    at getAmplifyDirPath (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/path-manager.js:57:9)
                                    at Object.getProviderInfoFilePath (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/path-manager.js:126:5)
                                    at Object.getEnvDetails (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/get-env-details.js:6:43)
                                    at Command.run (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/src/commands/env/import.js:33:37)
                                    at Runtime.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:117:58)
                                    at step (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:43:23)
                                    at Object.next (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:24:53)
                                    at fulfilled (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:15:58)
                                    at process._tickCallback (internal/process/next_tick.js:68:7)
                                    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
                                    at startup (internal/bootstrap/node.js:283:19)
                                    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
2020-11-01T06:12:06.949Z [ERROR]: !!! Build failed
2020-11-01T06:12:06.950Z [ERROR]: !!! Non-Zero Exit Code detected
```

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

 additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**Comment by Athena96** [comment]
Hi @amalik18 it looks like you have since deleted your project. If you are still facing the issue, can you please share your new appId and/or your build spec so we can attempt to repo. thanks!

**Comment by amalik18** [comment]
Hey yea, i thought that maybe deleting and restarting would help but unfortunately it hasn't.

New AppID: d2v7a8w6dj2azu
Region: us-east-1

**Comment by Athena96** [comment]
Great thanks! Can you also share the folder structure of your app folders/files please

**Comment by amalik18** [comment]
Of course,

amplifydemo:
* amplify/
** .config/
*** local-aws-info.json
*** local-env-info.json
*** project-config.json
** #current-cloud-backend/
*** auth/
**** amplifydemo52ac9539/
***** amplifydemo52ac9539-cloudformation-template.yml
***** parameters.json
**** amplify-meta.json
**** backend-config.json
**** tags.json
** backend/
*** auth/
**** amplifydemo52ac9539/
***** amplifydemo52ac9539-cloudformation-template.yml
***** parameters.json
*** awscloudformation/
**** nested-cloudformation-stack.yml
**** amplify-meta.json
**** backend-config.json
**** tags.json
** cli.json
** team-provider-info.json
* public/
** favicon.ico
** index.html
** logo192.png
** logo512.png
** manifest.json
** robots.txt
* src/
** App.css
** App.js
** App.test.js
** aws-exports.json
** index.css
** index.js
** logo.svg
** reportWebVitals.js
** setupTests.js

**Comment by Athena96** [comment]
Thanks for the info. Can you also share your build spec. You can view this from the console by selecting your app, then clicking "Build settings" in the left hand corner.

**Comment by amalik18** [comment]
Yep here you go. I only added the backend section.

```
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```

**Comment by Hayden-Neilson** [comment]
I am getting the same issue with my react app and not sure where to go or how to fix this Please help?

**Comment by amalik18** [comment]
@Athena96 Any luck?

**Comment by Hayden-Neilson** [comment]
Not yet I have looked at some forums and the aws site for it but no I not found a fix yet.

**Comment by StrayCat1** [comment]
I'm having the same problem.

Started a react app with auth. Got it to build once, then the subsequent build (on the same commit) caused the backend build to throw
```
2020-11-24T22:48:28.170Z [WARNING]: /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13
                                    throw up;
                                    ^
                                    Error: You are not working inside a valid amplify project.
                                    Use 'amplify init' in the root of your app directory to initialize your project with Amplify
                                    at getAmplifyDirPath (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/path-manager.js:57:9)
                                    at Object.getProviderInfoFilePath (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/path-manager.js:126:5)
                                    at Object.getEnvDetails (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/get-env-details.js:6:43)
                                    at Command.run (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/src/commands/env/import.js:33:37)
                                    at Runtime.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:117:58)
                                    at step (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:43:23)
                                    at Object.next (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:24:53)
                                    at fulfilled (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:15:58)
                                    at process._tickCallback (internal/process/next_tick.js:68:7)
                                    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
                                    at startup (internal/bootstrap/node.js:283:19)
                                    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by amalik18** [comment]
Can anyone help out?

**Comment by litwicki** [comment]
@amalik18 I know this was mentioned above, but based on the error log `Error: You are not working inside a valid amplify project.` indicates the `amplify` folder is not part of your build. Can you verify the `amplify` folder is not part of `gitignore` and *is* in the build?

**Comment by amalik18** [comment]
@litwicki Yep that was the issue. The `amplify/` directory was in the `.gitignore`file. Thanks for that. I'm gonna close this out.
