### ISSUE TITLE
Project stops building on Amplify and says project is not configured with Amplify

### ISSUE THREAD

**Issue by subhashnalluru** [aws-amplify/amplify-console#1220]
Similar to #115 

Hi, I seem to be facing an issue when I try to link my project with Amplify. The build works the first time and fails thereafter. I even try to redeploy a previously working build and it fails again and I get the following error:

```
# Importing Amplify environment: master (amplify env import)
2020-11-12T23:55:30.934Z [WARNING]: /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13
                                    throw up;
                                    ^
                                    Error: You are not working inside a valid amplify project.
                                    Use 'amplify init' in the root of your app directory to initialize your project with Amplify
                                    at getAmplifyDirPath (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/path-manager.js:57:9)
                                    at Object.getProviderInfoFilePath (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/path-manager.js:126:5)
                                    at Object.getEnvDetails (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/get-env-details.js:6:43)
                                    at Command.run (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/src/commands/env/import.js:33:37)
                                    at Runtime.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:117:58)
                                    at step (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:43:23)
                                    at Object.next (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:24:53)
                                    at fulfilled (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/runtime/run.js:15:58)
                                    at process._tickCallback (internal/process/next_tick.js:68:7)
                                    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
                                    at startup (internal/bootstrap/node.js:283:19)
                                    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
2020-11-12T23:55:30.943Z [ERROR]: !!! Build failed
2020-11-12T23:55:30.943Z [ERROR]: !!! Non-Zero Exit Code detected
2020-11-12T23:55:30.944Z [INFO]: # Starting environment caching...
2020-11-12T23:55:30.944Z [INFO]: # Uploading environment cache artifact...
2020-11-12T23:55:31.045Z [INFO]: # Environment caching completed
Terminating logging...
```

AppID: d3d1uv58phsfdw 
eu-west-2 (London)

@litwicki I noticed you assisted a lot in resolving #115 and was wondering if you could help me out with this. Any help is greatly appreciated

**Comment by litwicki** [comment]
@subhashnalluru I'll have the team take a look at this. Can you verify your build has `aws-exports` in the build environment?

**Comment by subhashnalluru** [comment]
Thanks @litwicki for getting back to me on this. This is actually my first time using Amplify. Can I just verify whether you mean if I have aws-exports on my repo? Because, I do not have the file in my repo. When I did amplify init, followed by an amplify add auth later, I ensured to also run amplify push. In my build settings, I also have backend: phases: build: commands: amplifyPush --simple. Does this help?

**Comment by litwicki** [comment]
This will include your environment cache and app details, but will not include the parameters necessary to build your backend. Try including `aws-exports` in your build, and if that doesn't work we'll have the team take a look tomorrow.

**Comment by StrayCat1** [comment]
I'm having the same issue. 

Started a new react app, added auth, and it built successfully once. Then without making any changes my backend started failing to build with the same error. 

```
2020-11-25T06:11:49.259Z [WARNING]: /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13
                                    throw up;
                                    ^
                                    Error: You are not working inside a valid amplify project.
                                    Use 'amplify init' in the root of your app directory to initialize your project with Amplify
```

This appears to be the same issue as this one- https://github.com/aws-amplify/amplify-console/issues/1189

**Comment by litwicki** [comment]
@StrayCat1 can you verify your build contains the `amplify` directory, and the `aws-exports` file please?

**Comment by StrayCat1** [comment]
Thanks for the quick response!

Well I thought I had the amplify dir checked in but I guess not... Here is the repo - https://github.com/StrayCat1/archive-amplified

As for the aws-exports, I was having an issue with that not being found when the front end built, but then I added that build configuration for the backend that does `amplifyPush --simple` and it built fine, everything worked. Then I triggered the same commit to build again and this happened. 

Ill try checking in my amplify directory, but if that works, Im confused how it ever built.

**Comment by StrayCat1** [comment]
Yeah that fixed it for me. Should have considered that wasn't checked in, but I was thrown off by the fact that it had built once before. Thanks for the help and keep up the good work! Only been using amplify for 24 hours, but I love it already.

**Comment by subhashnalluru** [comment]
Are we supposed to check in the aws-exports file as file? I assumed that we shouldn't since it has information regarding pool IDs, etc

**Comment by StrayCat1** [comment]
@subhashnalluru there are a couple issues around that and from what I understand that file shouldn't be checked in, it should be first built by the backend. 

See https://github.com/aws-amplify/docs/issues/503 

The solution is to add this to your CI/CD settings before `frontend`. 

```
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
```

**Comment by subhashnalluru** [comment]
Ahh perfect, thanks @StrayCat1 . I've added this now and it works, cheers

**Comment by litwicki** [comment]
@StrayCat1 @subhashnalluru is there anything else we can help with here? Please let us know or we can close this issue if you're all set. Thanks!

**Comment by subhashnalluru** [comment]
Hey @litwicki I think we can close this issue. Thanks a bunch for helping with this!

**Comment by StrayCat1** [comment]
You can close this, thanks!
