### ISSUE TITLE
Frontend build error: TypeError: Cannot read property 'join' of null - at runPackageManager

### ISSUE THREAD

**Issue by redBaron23** [aws-amplify/amplify-console#1267]
**Describe the bug**
Frontend build doesn't work anymore. I tried creating a new branch and uploading it to amplify but build always fail.

> 2020-11-23T00:37:07.417Z [INFO]: Git SSH Key acquired
2020-11-23T00:37:07.489Z [INFO]: # Cloning repository: git@github.com:redBaron23/nora.git
2020-11-23T00:37:07.498Z [INFO]: Agent pid 122
2020-11-23T00:37:07.529Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2020-11-23T00:37:07.744Z [INFO]: Cloning into 'nora'...
2020-11-23T00:37:08.035Z [INFO]: Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
2020-11-23T00:37:08.445Z [INFO]: # Checking for Git submodules at: /codebuild/output/src660939898/src/nora/.gitmodules
2020-11-23T00:37:08.476Z [INFO]: # Retrieving cache...
2020-11-23T00:37:08.520Z [INFO]: # Extracting cache...
2020-11-23T00:37:08.531Z [INFO]: # Extraction completed
2020-11-23T00:37:08.531Z [INFO]: # Retrieving environment cache...
2020-11-23T00:37:08.571Z [INFO]: # Retrieved environment cache
2020-11-23T00:37:08.572Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2020-11-23T00:37:17.810Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 1.12.0 to 4.34.0...
2020-11-23T00:38:08.813Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
2020-11-23T00:38:13.134Z [INFO]: ## Successfully created new backend environment
2020-11-23T00:38:14.171Z [INFO]: ## Starting Backend Build
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-11-23T00:38:20.725Z [INFO]: 
2020-11-23T00:38:20.728Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html
2020-11-23T00:38:20.742Z [WARNING]: (node:1957) ExperimentalWarning: The fs.promises API is experimental
2020-11-23T00:38:21.193Z [INFO]: Amplify AppID found: d2bb32f3rz72uu. Amplify App name is: nora
2020-11-23T00:38:21.256Z [INFO]: Backend environment dev found in Amplify Console app: nora
2020-11-23T00:38:21.651Z [INFO]: 
2020-11-23T00:38:21.654Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2020-11-23T00:38:21.934Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2020-11-23T00:38:21.990Z [INFO]: 
2020-11-23T00:38:23.330Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-11-23T00:38:28.335Z [WARNING]: - Initializing your environment: dev
2020-11-23T00:38:28.356Z [WARNING]: (node:1968) ExperimentalWarning: The fs.promises API is experimental
2020-11-23T00:38:28.620Z [WARNING]: ✔ Initialized provider successfully.
2020-11-23T00:38:28.774Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2020-11-23T00:38:28.774Z [WARNING]: ✖ There was an error initializing your environment.
2020-11-23T00:38:28.779Z [INFO]: init failed
2020-11-23T00:38:28.780Z [INFO]: TypeError: Cannot read property 'join' of null
                                 at runPackageManager (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:54:47)
                                 at installDependencies (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:38:3)
                                 at Object.buildResource (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:12:5)
                                 at Object.build (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/index.ts:44:22)
                                 at buildResource (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/build-resources.js:49:36)
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
2020-11-23T00:38:28.799Z [ERROR]: !!! Build failed
2020-11-23T00:38:28.799Z [ERROR]: !!! Non-Zero Exit Code detected
2020-11-23T00:38:28.799Z [INFO]: # Starting environment caching...
2020-11-23T00:38:28.800Z [INFO]: # Environment caching completed
Terminating logging...

**To Reproduce**
Unfortunately I am not sure how to guide you to reproduce. Should I try to create another branch / env ?

**Expected behavior**
Build successfully, like it did before :)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device:  PC
 - OS: Arch Linux
 - Browser Opera
 - Version [e.g. 22 No idea]

**Additional context**

**Comment by kahdojay** [comment]
Hi, based on the error it looks to be related to the amplify cli version, which has since been patched
https://github.com/aws-amplify/amplify-console/issues/749
https://github.com/aws-amplify/amplify-cli/issues/4688
https://github.com/aws-amplify/amplify-cli/issues/4372

Closing this one for now, please re-open and provide appId and build number if you're still experiencing the issue.
