### ISSUE TITLE
Build failing: Failed to pull the backend.

### ISSUE THREAD

**Issue by jeyashankher** [aws-amplify/amplify-console#1285]
**Describe the bug**
I'm using Console to automatically trigger builds from my github. I'm getting the following error (tried this three times). It built fine until yesterday.

```
2020-11-26T08:12:13.536Z [INFO]: Cannot read property 'projects' of undefined
2020-11-26T08:12:13.540Z [INFO]: TypeError: Cannot read property 'projects' of undefined
                                 at recursiveOmit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/deploymentSecretsHelper.ts:34:20)
                                 at recursiveOmit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/deploymentSecretsHelper.ts:34:3)
                                 at recursiveOmit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/deploymentSecretsHelper.ts:34:3)
                                 at Object.exports.removeFromDeploymentSecrets (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/deploymentSecretsHelper.ts:20:5)
                                 at AmplifyToolkit.saveEnvResourceParameters [as _saveEnvResourceParameters] (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/envResourceParams.ts:93:9)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/index.ts:116:15
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
```

**To Reproduce**
Amplify console build logs showing this error

**Expected behavior**
Expect build to complete, but it is failing

**Screenshots**
Attached
![Screenshot 2020-11-26 at 1 47 09 PM](https://user-images.githubusercontent.com/6544174/100324921-e4f5ca00-2fed-11eb-8b1f-40a6dd27d254.png)

**Comment by jeyashankher** [comment]
I noticed that @aws-amplify/cli package is 4.36.0 for the failed current build, but was 4.35.0 for the previous successful build.

Successful build:
```
2020-11-25T10:43:21.785Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2020-11-25T10:43:30.755Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 1.12.0 to 4.35.0...
```

Failed current build:
```
2020-11-26T08:42:27.236Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2020-11-26T08:42:35.316Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 1.12.0 to 4.36.0...
```

**Comment by jeyashankher** [comment]
Update: I overrode the cli version in Amplify Console -> Build Settings to 4.35.0 and the build went through.

**Comment by allanitis** [comment]
Same problem but at a different key broken with 4.36.0

`TypeError: Cannot read property 'hostedUIProviderCreds' of undefined
`

What command did you use to override the cli version in Build settings?

**Comment by allanitis** [comment]
Update: at the bottom of the Build setting page. 4.34 solved my problem. 

<img width="967" alt="Screenshot 2020-11-27 at 01 16 51" src="https://user-images.githubusercontent.com/10580223/100361408-3f267780-304e-11eb-92a9-0e051e6c24f6.png">

In the meantime, I discovered that 4.36 (latest) is aggressively marked "NOT FOR PRODUCTION". A reminder to pin dependency versions. 

<img width="954" alt="Screenshot 2020-11-27 at 01 18 03" src="https://user-images.githubusercontent.com/10580223/100361560-6715db00-304e-11eb-824b-32b65748c804.png">

**Comment by jeyashankher** [comment]
Yes. That's exactly what I did as well.

**Comment by litwicki** [comment]
@jeyashankher we've updated this with the latest 4.39.0 release of Amplify CLI. Please let us know if you experience any other issues.
