### ISSUE TITLE
AWS Amplify console fails to build:  ✖ There was an error initializing your environment.

### ISSUE THREAD

**Issue by contractorwolf** [aws-amplify/amplify-console#1298]
**Describe the bug**
This was a previous working project that suddenly as on yesterday (Nov 25th) has issues building.

The build process fails with the following:
```
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-11-27T04:28:02.575Z [INFO]: 
2020-11-27T04:28:02.577Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html
2020-11-27T04:28:02.588Z [WARNING]: (node:1969) ExperimentalWarning: The fs.promises API is experimental
2020-11-27T04:28:03.681Z [INFO]: Amplify AppID found: d2y0bndwty1i0h. Amplify App name is: amplifynewsscraper
2020-11-27T04:28:03.741Z [INFO]: Backend environment dev found in Amplify Console app: amplifynewsscraper
2020-11-27T04:28:04.202Z [INFO]: 
2020-11-27T04:28:04.205Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2020-11-27T04:28:04.608Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2020-11-27T04:28:04.666Z [WARNING]: ✖ There was an error initializing your environment.
2020-11-27T04:28:04.671Z [INFO]: Failed to pull the backend.
2020-11-27T04:28:04.672Z [INFO]: Cannot read property 'newsarticlebuildwordcloud' of undefined
2020-11-27T04:28:04.676Z [INFO]: TypeError: Cannot read property 'newsarticlebuildwordcloud' of undefined
                                 at recursiveOmit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/deploymentSecretsHelper.ts:34:20)
                                 at recursiveOmit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/deploymentSecretsHelper.ts:34:3)
                                 at recursiveOmit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/deploymentSecretsHelper.ts:34:3)
                                 at Object.exports.removeFromDeploymentSecrets (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/deploymentSecretsHelper.ts:20:5)
                                 at AmplifyToolkit.saveEnvResourceParameters [as _saveEnvResourceParameters] (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/envResourceParams.ts:93:9)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/index.ts:116:15
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
2020-11-27T04:28:04.695Z [ERROR]: !!! Build failed
2020-11-27T04:28:04.695Z [ERROR]: !!! Non-Zero Exit Code detected
2020-11-27T04:28:04.695Z [INFO]: # Starting environment caching...
2020-11-27T04:28:04.696Z [INFO]: # Environment caching completed
Terminating logging...
```
The "newsarticlebuildwordcloud" is one of my functions and hasnt had any changes and can be run using amplify mock function without issues.  Initially it had one of my other functions listed as failing so I removed to function (in the hopes of getting it to deploy) but then I get the same issue with this function.  Again, they both were working and can be mock tested locally without issues so I am not sure what is suddenly missing or what "2020-11-27T04:28:04.672Z [INFO]: Cannot read property 'newsarticlebuildwordcloud' of undefined" really means.  The function is there and working (locally) so where does the issue lie?

**Expected behavior**
The error should state what is missing of from where it is missing.

**Comment by Johannes-Engler** [comment]
I had the same error. Downgrading the amplify-cli fixed it for me:

![image](https://user-images.githubusercontent.com/30771235/100474057-0df68780-30e0-11eb-887d-a127952784c7.png)

**Comment by contractorwolf** [comment]
Hey @Johannes-Engler that fixed it for me thx.  On a side note looks like there is a bug in the "latest" version of Amplify CLI.  To reiterate the fix that solved this issue I went to the Build Settings in the menu and updated to 4.34.0 like @Johannes-Engler  suggested.  Then I just re-ran the build and the issue was fixed and the build completed.  

<img width="672" alt="Screen Shot 2020-11-27 at 12 58 01 PM" src="https://user-images.githubusercontent.com/4690960/100475313-c73d6900-30b0-11eb-8645-0d8e2877396f.png">

**Comment by ganipcanot** [comment]
Closing for now based on CLI issue please re-open if you are still experiencing issues.

**Comment by jrheling** [comment]
FWIW I had this problem start out of the blue yesterday midday (US/Central). After hours of researching and reverting unrelated changes and banging my head into the figurative wall I found this thread and tried setting the AWS CLI version to 4.34.0 as described, and it worked.

I'm quite surprised that 6 months later this is still needed, *and interestingly* as recently as ~1700 UTC yesterday it worked without the version override. Makes me suspect a new version was pushed yesterday that reintroduced some problem, or something like that.

**Comment by darellchua2** [comment]
I am having a similar issue. 

My last successful build was on Amplify 4.52.0. but with the latest amplify, it is not working at 5.1.1.

The main difference starts when i added google OAuth to my amplify Auth.
![amplify-error](https://user-images.githubusercontent.com/63179677/125602944-4a2a6313-cc15-4907-a814-70ae8e037cf2.PNG)

**Comment by Fitux** [comment]
Is there any update on this issue.
I'm having the same issue after integrating OAuth into my project

**Comment by NoahKr** [comment]
Same issue here.

**Comment by dperconti** [comment]
Experiencing this with numerous versions. Unable to deploy and am receiving the same error.

**Comment by geoox** [comment]
I am also experiencing the sam problem. Why is the issue Closed?

**Comment by irSteve** [comment]
This was working on a previous project and now I am experiencing this on every new project. It is a blocker as nothing can be done on AWS Amplify!

**Comment by Fitux** [comment]
For anyone wondering and future references, the fix for us was not to downgrade the CLI version but to set some environment variables in the amplify console

Similar to the image below

<img width="668" alt="Screen Shot 2021-12-03 at 11 49 29" src="https://user-images.githubusercontent.com/5275409/144649599-6d537185-8f99-48d2-9f01-907e7fd40664.png">

There are no specific documentation about this being needed but that fixed my issue

https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#amplify-console-environment-variables

In the link above you can see the name of the variables names for each one of the different social sign ins

**Comment by zachar-maximov** [comment]
Has a similar issue during the first deployment:

`2022-01-04T16:42:13.470Z [WARNING]: ✔ Successfully pulled backend environment develop from the cloud.
2022-01-04T16:42:13.481Z [WARNING]: ✖ There was an error initializing your environment.
2022-01-04T16:42:13.489Z [INFO]: [31mFailed to pull the backend.[39m
2022-01-04T16:42:13.493Z [INFO]: [31mFile at path: '/codebuild/output/src715392117/src/qizify-e-learning/amplify/backend/auth/qizifyelearning067fe909/parameters.json' does not exist[39m
2022-01-04T16:42:13.501Z [INFO]: [0mError: File at path: '/codebuild/output/src715392117/src/qizify-e-learning/amplify/backend/auth/qizifyelearning067fe909/parameters.json' does not exist[0m
                                 [0m    at Function.JSONUtilities.readJson (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/jsonUtilities.ts:25:15)[0m
                                 [0m    at StateManager.getData (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:399:32)[0m
                                 [0m    at StateManager.getResourceParametersJson (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:147:17)[0m
                                 [0m    at ensureAmplifyMetaFrontendConfig (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.ts:84:55)[0m
                                 [0m    at AmplifyToolkit.onCategoryOutputsChange [as _onCategoryOutputsChange] (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/on-category-outputs-change.ts:18:5)[0m
                                 [0m    at initializeEnv (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/initialize-env.ts:103:27)[0m
                                 [0m    at onSuccess (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/attach-backend.ts:88:7)[0m
                                 [0m    at attachBackend (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/attach-backend.ts:31:5)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/commands/pull.ts:59:5)[0m
                                 [0m    at Object.executeAmplifyCommand (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)[0m
                                 [0m    at executePluginModuleCommand (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)[0m
                                 [0m    at executeCommand (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)[0m
2022-01-04T16:42:13.530Z [ERROR]: !!! Build failed
2022-01-04T16:42:13.530Z [ERROR]: !!! Non-Zero Exit Code detected
2022-01-04T16:42:13.530Z [INFO]: # Starting environment caching...
2022-01-04T16:42:13.531Z [INFO]: # Environment caching completed
`

I wonder why it tries to use /amplify/backend/auth/qizifyelearning067fe909/parameters.json instead of /amplify/backend/auth/qizifyelearning067fe909/build/parameters.json which is generated locally.
