### ISSUE TITLE
Build failure in Amplify Console using 4.37.1 CLI (.NET function)

### ISSUE THREAD

**Issue by kjones** [aws-amplify/amplify-console#1333]
**Describe the bug**
Amplify project with a React frontend and a combination of JS and .NET backend fails to build and deploy the backend when Amplify CLI 4.37.1 is used.

**To Reproduce**
1. Commit to GitHub or hit Redeploy this Version to start a new build
2. Build fails stating it can't find the file `package.json` on a .NET Core 3.1 Lambda function during `amplify push --simple`

**Expected behavior**
.NET Lambda function builds and deploys.

**Additional context**
If I peg the Amplify CLI to 4.32.1 the build completes successfully.
.NET tools are installed at the start of each build.
```yaml
backend:
  phases:
    preBuild:
      commands:
        - curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh
        - chmod +x *.sh
        - ./dotnet-install.sh
        - export PATH=$PATH:/root/.dotnet:/root/.dotnet/tools
        - export DOTNET_ROOT="/root/.dotnet"
        - dotnet --version
        - dotnet tool install -g Amazon.Lambda.Tools
        - dotnet tool install -g Amazon.Lambda.TestTool-3.1
```
Build logs:
```
2020-12-04T01:20:07.818Z [INFO]: # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-12-04T01:20:07.823Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2020-12-04T01:20:07.830Z [INFO]: # Start initializing Amplify environment: kj
2020-12-04T01:20:07.831Z [INFO]: # Initializing new Amplify environment: kj (amplify init)
2020-12-04T01:20:11.093Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-12-04T01:20:15.823Z [INFO]: 
2020-12-04T01:20:15.828Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html
2020-12-04T01:20:15.928Z [WARNING]: - Initializing your environment: kj
2020-12-04T01:20:29.803Z [WARNING]: ✔ Initialized provider successfully.
2020-12-04T01:20:30.110Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2020-12-04T01:20:30.110Z [WARNING]: ✖ There was an error initializing your environment.
2020-12-04T01:20:30.110Z [INFO]: init failed
2020-12-04T01:20:30.112Z [INFO]: { Error: ENOENT: no such file or directory, stat '/codebuild/output/src423147733/src/nxt/amplify/backend/function/GarminConnect/src/package.json'
                                 at Object.statSync (fs.js:855:3)
                                 at Object.statSync (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graceful-fs/polyfills.js:308:16)
                                 at buildResource (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/build-resources.js:23:30)
                                 at packageResource (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:215:12)
                                 at packageResources (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:269:19)
                                 at Object.run (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:35:10)
                                 at Object.pushResources (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/index.js:32:25)
                                 at providerPushTasks.push (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/src/lib/initialize-env.js:81:53)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
                                 errno: -2,
                                 syscall: 'stat',
                                 code: 'ENOENT',
                                 path:
                                 '/codebuild/output/src423147733/src/nxt/amplify/backend/function/GarminConnect/src/package.json' }
2020-12-04T01:20:30.170Z [ERROR]: !!! Build failed
2020-12-04T01:20:30.170Z [ERROR]: !!! Non-Zero Exit Code detected
2020-12-04T01:20:30.170Z [INFO]: # Starting environment caching...
2020-12-04T01:20:30.171Z [INFO]: # Environment caching completed
Terminating logging...
```

**Comment by abhi7cr** [comment]
@kjones, we have updated our build image with the following changes (_including adding dotnet_ support):

- dotnet-host-3.1.4
- dotnet-sdk-3.1
- Amazon.Lambda.Tools (_dotnet amazon tools_)
- Amazon.Lambda.TestTool-3.1 (_dotnet amazon tools_)
- python3.8
- node v12 as the default
- amplify 4.29.4
- hugo 0.75.1

Let me know if you are able to build your project.

**Comment by kjones** [comment]
Looks good.
- Removed the 4.32.1 CLI peg
- Removed the .NET install
