### ISSUE TITLE
Build fails due to File project: data should NOT have additional properties: 'graphqltransformer'

### ISSUE THREAD

**Issue by icecog** [aws-amplify/amplify-console#1340]
**Describe the bug**
Amplify backend build fails during deployment with the error: ' File project: data should NOT have additional properties: 'graphqltransformer''. This should probably not happen. 
I might be wrong, but I don't think it failed prior to updating amplify-cli.

**To Reproduce**
`amplify --version 4.37.1`
Running AWS Amplify with 'amplify add codegen --apiId <apiId>' results in a graphqltransformer object being created in cli.json features object.

```json
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": false
    }
  }
}
```

During build 'AmplifyPush --simple' fails with following error:

```
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-12-06T07:21:26.361Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2020-12-06T07:21:26.365Z [INFO]: # Start initializing Amplify environment: cleopatra
2020-12-06T07:21:26.366Z [INFO]: # Initializing new Amplify environment: cleopatra (amplify init)
2020-12-06T07:21:27.226Z [INFO]: File project: data should NOT have additional properties: 'graphqltransformer'
2020-12-06T07:21:27.227Z [INFO]: JSONValidationError: File project: data should NOT have additional properties: 'graphqltransformer'
                                 at validator (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:136:27)
                                 at featureFlagsValidator (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:140:17)
                                 at FeatureFlags.validateFlags (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:146:17)
                                 at FeatureFlags.loadValues (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:204:18)
                                 at async Function.FeatureFlags.initialize (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:267:5)
                                 at async Object.run (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/lib/index.js:73:9)
2020-12-06T07:21:28.091Z [INFO]: File project: data should NOT have additional properties: 'graphqltransformer'
2020-12-06T07:21:28.092Z [INFO]: JSONValidationError: File project: data should NOT have additional properties: 'graphqltransformer'
                                 at validator (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:136:27)
                                 at featureFlagsValidator (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:140:17)
                                 at FeatureFlags.validateFlags (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:146:17)
                                 at FeatureFlags.loadValues (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:204:18)
                                 at async Function.FeatureFlags.initialize (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:267:5)
                                 at async Object.run (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/lib/index.js:73:9)
2020-12-06T07:21:28.098Z [ERROR]: !!! Build failed
2020-12-06T07:21:28.098Z [ERROR]: !!! Non-Zero Exit Code detected
2020-12-06T07:21:28.098Z [INFO]: # Starting environment caching...
2020-12-06T07:21:28.099Z [INFO]: # Environment caching completed
Terminating logging...
```

**Expected behavior**
I expect Amplify backend to build (AmplifyPush --simple to complete) when importing a GraphQL API using Amplify codegen.

**Additional context**
Removing 'graphqltransformer' object from cli.json - 'features' object results in build failing for a [different reason](https://github.com/aws-amplify/amplify-console/issues/1341).

**Comment by icecog** [comment]
Turns out I needed get a newer version of Amplify-CLI to be used in the console.
Added this environmental variable:

_LIVE_UPDATES | [{"name":"Amplify CLI","pkg":"@aws-amplify/cli","type":"npm","version":"latest"}] | All branches

Also see [this](https://github.com/aws-amplify/amplify-console/issues/1341)

**Comment by Rolando-Barbella** [comment]
I ran `curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL` and it works

**Comment by Jarrettgohh** [comment]
For whoever got another error Build fails due to File project: data should NOT have additional properties: 'frontend-ios', i managed to solve it by just opening the admin ui and under the tab 'functions' just copy whatever commands they give.

**Comment by michaelpaulcuccia** [comment]
File project: data should NOT have additional properties: 'graphqltransformer'
JSONValidationError: File project: data should NOT have additional properties: 'graphqltransformer' at validator

what is the fix???

**Comment by slefcourt27** [comment]
> File project: data should NOT have additional properties: 'graphqltransformer'
> JSONValidationError: File project: data should NOT have additional properties: 'graphqltransformer' at validator
> 
> what is the fix???

@michaelpaulcuccia Were you able to find a solution?

**Comment by michaelpaulcuccia** [comment]
> > File project: data should NOT have additional properties: 'graphqltransformer'
> > JSONValidationError: File project: data should NOT have additional properties: 'graphqltransformer' at validator
> > what is the fix???
> 
> @michaelpaulcuccia Were you able to find a solution?

I ended up doing the tutorial in the Amplify Docs instead - https://docs.amplify.aws/start/q/integration/react

**Comment by slefcourt27** [comment]
> > > File project: data should NOT have additional properties: 'graphqltransformer'
> > > JSONValidationError: File project: data should NOT have additional properties: 'graphqltransformer' at validator
> > > what is the fix???
> > 
> > 
> > @michaelpaulcuccia Were you able to find a solution?
> 
> I ended up doing the tutorial in the Amplify Docs instead - https://docs.amplify.aws/start/q/integration/react

@michaelpaulcuccia Thank you for the response!

**Comment by justnow-cpu** [comment]
hi , I have the same problem. I just follow the document 
https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-three/?e=gs2020&p=build-a-react-app-two
I read the document slefcourt27 suggested
https://docs.amplify.aws/start/q/integration/react
I found this is right document.

**Comment by Stvad** [comment]
see also #6117 that has explanation on how to update version from ui

**Comment by seankovacs** [comment]
To fix this error I updated cli.json to be an empty object {} .

**Comment by mckennapaul27** [comment]
Also have the same problem whilst following the tutorial https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-three/?e=gs2020&p=build-a-react-app-two

**Comment by mckennapaul27** [comment]
> hi , I have the same problem. I just follow the document
> https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-three/?e=gs2020&p=build-a-react-app-two
> I read the document slefcourt27 suggested
> https://docs.amplify.aws/start/q/integration/react
> I found this is right document.

I also just did the mentioned tutorial instead - thanks for the tip.

**Comment by Jaqito** [comment]
To sort out the problem you just need to set your Amplify CLI version to use the latest on the build.  There's some better discussion here:  https://github.com/aws-amplify/amplify-cli/issues/6117
