### ISSUE TITLE
 Template error: instance of Fn::GetAtt references undefined resource <imported Auth ID>

### ISSUE THREAD

**Issue by icecog** [aws-amplify/amplify-console#1341]
**Describe the bug**
Amplify backend build fails during deployment with the error: ' Template error: instance of Fn::GetAtt references undefined resource <imported Auth ID> '. This should probably not happen. 

**To Reproduce**
`amplify --version 4.37.1`
Running AWS Amplify with 'amplify **import** auth' results in error below when deploying. It runs fine locally.

During build 'AmplifyPush --simple' fails with following error:

```
2020-12-06T07:31:11.414Z [INFO]: ## Starting Backend Build
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-12-06T07:31:27.025Z [INFO]: 
2020-12-06T07:31:27.029Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html
2020-12-06T07:31:27.362Z [INFO]: Amplify AppID found: <AppID>. Amplify App name is: portal-website
2020-12-06T07:31:27.425Z [INFO]: Backend environment dev found in Amplify Console app: portal-website
2020-12-06T07:31:27.800Z [INFO]: 
2020-12-06T07:31:27.807Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2020-12-06T07:31:27.984Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2020-12-06T07:31:28.000Z [WARNING]: - Updating resources in the cloud. This may take a few minutes...
2020-12-06T07:31:28.654Z [WARNING]: Error updating cloudformation stack
2020-12-06T07:31:28.655Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2020-12-06T07:31:28.656Z [WARNING]: ✖ There was an error initializing your environment.
2020-12-06T07:31:28.657Z [INFO]: Failed to pull the backend.
2020-12-06T07:31:28.658Z [INFO]: Template error: instance of Fn::GetAtt references undefined resource authportal_website<ID>
2020-12-06T07:31:28.660Z [INFO]: ValidationError: Template error: instance of Fn::GetAtt references undefined resource authportal_website<ID>
                                 at Request.extractError (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
                                 at Request.callListeners (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
                                 at Request.transition (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
2020-12-06T07:31:28.673Z [ERROR]: !!! Build failed
2020-12-06T07:31:28.674Z [ERROR]: !!! Non-Zero Exit Code detected
2020-12-06T07:31:28.674Z [INFO]: # Starting environment caching...
2020-12-06T07:31:28.674Z [INFO]: # Environment caching completed
Terminating logging...

```

**Expected behavior**
I expect Amplify backend to build (AmplifyPush --simple to complete) when importing a User Pool and Identity Pool using Amplify import Auth.

**Comment by icecog** [comment]
@renebrandel I've been following your tutorial, but then I run into this issue. I hope it's just me that's messing up.
https://aws.amazon.com/blogs/mobile/use-existing-cognito-resources-for-your-amplify-api-storage-and-more/

**Comment by icecog** [comment]
Fixed this.
Added this environmental variable:
```table
_LIVE_UPDATES | [{"name":"Amplify CLI","pkg":"@aws-amplify/cli","type":"npm","version":"latest"}] | All branches
```
Conclusion: Amplify was using version 4.29.4 (could be seen in the logs, if you check during the provision stage, or download the logs.

This caused a different error to appear thought, but at least there is progress.

New error:
````
2020-12-06T13:45:07.193Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2020-12-06T13:45:07.347Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2020-12-06T13:45:07.376Z [WARNING]: ✖ There was an error initializing your environment.
2020-12-06T13:45:07.377Z [INFO]: Failed to pull the backend.
2020-12-06T13:45:07.379Z [INFO]: auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId, identityPoolId
2020-12-06T13:45:07.388Z [INFO]: Error: auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId, identityPoolId
                                 at ensureHeadlessParameters (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1265:11)
                                 at headlessImport (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1122:40)
                                 at exports.importedAuthEnvInit (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:898:18)
                                 at processTicksAndRejections (internal/process/task_queues.js:97:5)
                                 at updateConfigOnEnvInit (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/index.js:51:72)
                                 at /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/index.js:300:22
2020-12-06T13:45:07.403Z [ERROR]: !!! Build failed
2020-12-06T13:45:07.403Z [ERROR]: !!! Non-Zero Exit Code detected
2020-12-06T13:45:07.403Z [INFO]: # Starting environment caching...
2020-12-06T13:45:07.404Z [INFO]: # Uploading environment cache artifact...
2020-12-06T13:45:07.480Z [INFO]: # Environment caching completed
Terminating logging...
````

I fix this after reading [this post](https://github.com/aws-amplify/amplify-cli/issues/4806), that pointed me to [this answer](https://github.com/aws-amplify/amplify-cli/issues/4790#issuecomment-656422252), but the final solution was [this question and answer](https://github.com/aws-amplify/amplify-console/issues/1271#issue-749498297).

I updated my environment variables with:

````
AMPLIFY_IDENTITYPOOL_ID | <identityPoolId> | All branches
AMPLIFY_NATIVECLIENT_ID | <Native Client Id> | All branches
AMPLIFY_USERPOOL_ID | <User Pool Id> | All branches
AMPLIFY_WEBCLIENT_ID | <Web Client Id> | All branches
````
Most of which I found in the aws-exports.js locally.

And then added myamplifyPush.sh from [here](https://github.com/aws-amplify/amplify-console/issues/1271#issue-749498297)

To reiterate: this was a `Amplify **import** auth` using Identity Pool to federate signIns.

I find this solution quite bad, and the fact that I can find discussions around similar things going back a few years is troubling.

Here is the myamplifyPush.sh I ended up using:
````shell
#!/usr/bin/env bash
set -e
IFS='|'

help_output () {
    echo "usage: amplify-push <--environment|-e <name>> <--simple|-s>"
    echo "  --environment  The name of the Amplify environment to use"
    echo "  --simple  Optional simple flag auto-includes stack info from env cache"
    exit 1
}

init_env () {
    ENV=$1
    AMPLIFY=$2
    PROVIDERS=$3
    CODEGEN=$4
    AWSCONFIG=$5
    CATEGORIES=$6

    echo "# Start initializing Amplify environment: ${ENV}"
    if [[ -z ${STACKINFO} ]];
    then
        echo "# Initializing new Amplify environment: ${ENV} (amplify init)"
        [[ -z ${CATEGORIES} ]] && amplify init --amplify ${AMPLIFY} --providers ${PROVIDERS} --codegen ${CODEGEN} --yes || amplify init --amplify ${AMPLIFY} --providers ${PROVIDERS} --codegen ${CODEGEN} --categories ${CATEGORIES} --yes
        echo "# Environment ${ENV} details:"
        amplify env get --name ${ENV}
    else
        echo "STACKINFO="${STACKINFO}
        echo "# Importing Amplify environment: ${ENV} (amplify env import)"
        amplify env import --name ${ENV} --config "${STACKINFO}" --awsInfo ${AWSCONFIG} --yes;
        echo "# Initializing existing Amplify environment: ${ENV} (amplify init)"
        [[ -z ${CATEGORIES} ]] && amplify init --amplify ${AMPLIFY} --providers ${PROVIDERS} --codegen ${CODEGEN} --yes || amplify init --amplify ${AMPLIFY} --providers ${PROVIDERS} --codegen ${CODEGEN} --categories ${CATEGORIES} --yes
        echo "# Environment ${ENV} details:"
        amplify env get --name ${ENV}
    fi
    echo "# Done initializing Amplify environment: ${ENV}"
}

ENV=""
IS_SIMPLE=false
POSITIONAL=()

while [[ $# -gt 0 ]]
    do
    key="$1"
    case ${key} in
        -e|--environment)
        ENV=$2
        shift
        ;;
        -r|--region)
        REGION=$2
        shift
        ;;
        -s|--simple)
        IS_SIMPLE=true
        shift
        ;;
        *)
        POSITIONAL+=("$1")
        shift
        ;;
    esac
done
echo "# Initial value of ENV: ${ENV}, AWS_BRANCH: ${AWS_BRANCH}, USER_BRANCH: ${USER_BRANCH}, POSITIONAL ${POSITIONAL[@]}"
set -- "${POSITIONAL[@]}"

# if no provided environment name, use default env variable, then user override
if [[ ${ENV} = "" ]];
then
    ENV=${AWS_BRANCH}
fi

if [[ ${USER_BRANCH} != "" ]];
then
    ENV=${USER_BRANCH}
fi

# strip slashes, limit to 10 chars
ENV=$(echo ${ENV} | sed 's;\\;;g' | sed 's;\/;;g' | cut -c -10)

# Check valid environment name
if [[ -z ${ENV} || "${ENV}" =~ [^a-zA-Z0-9\-]+ ]] ; then help_output ; fi

AWSCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":true,\
\"profileName\":\"default\",\
\"AmplifyAppId\":\"${AWS_APP_ID}\"\
}"
AMPLIFY="{\
\"envName\":\"${ENV}\",\
\"appId\":\"${AWS_APP_ID}\"\
}"
PROVIDERS="{\
\"awscloudformation\":${AWSCONFIG}\
}"
CODEGEN="{\
\"generateCode\":false,\
\"generateDocs\":false\
}"
CATEGORIES=""

if [[ -z ${AMPLIFY_FACEBOOK_CLIENT_ID} && -z ${AMPLIFY_GOOGLE_CLIENT_ID} && -z ${AMPLIFY_AMAZON_CLIENT_ID} ]]; then
    AUTHCONFIG="{\
    \"userPoolId\":\"${AMPLIFY_USERPOOL_ID}\",\
    \"webClientId\":\"${AMPLIFY_WEBCLIENT_ID}\",\
    \"nativeClientId\":\"${AMPLIFY_NATIVECLIENT_ID}\",\
    \"identityPoolId\":\"${AMPLIFY_IDENTITYPOOL_ID}\"\
    }"
    CATEGORIES="{\
    \"auth\":${AUTHCONFIG}\
}"
else
    AUTHCONFIG="{\
    \"facebookAppIdUserPool\":\"${AMPLIFY_FACEBOOK_CLIENT_ID}\",\
    \"facebookAppSecretUserPool\":\"${AMPLIFY_FACEBOOK_CLIENT_SECRET}\",\
    \"googleAppIdUserPool\":\"${AMPLIFY_GOOGLE_CLIENT_ID}\",\
    \"googleAppSecretUserPool\":\"${AMPLIFY_GOOGLE_CLIENT_SECRET}\",\
    \"amazonAppIdUserPool\":\"${AMPLIFY_AMAZON_CLIENT_ID}\",\
    \"amazonAppSecretUserPool\":\"${AMPLIFY_AMAZON_CLIENT_SECRET}\"\
    }"
    CATEGORIES="{\
    \"auth\":$AUTHCONFIG\
    }"
fi
# Handle old or new config file based on simple flag
if [[ ${IS_SIMPLE} ]];
then
    echo "# Getting Amplify CLI Cloud-Formation stack info from environment cache"
    export STACKINFO="$(envCache --get stackInfo)"
    init_env ${ENV} ${AMPLIFY} ${PROVIDERS} ${CODEGEN} ${AWSCONFIG} ${CATEGORIES}
    echo "# Store Amplify CLI Cloud-Formation stack info in environment cache"
    STACKINFO="$(amplify env get --json --name ${ENV})"
    envCache --set stackInfo ${STACKINFO}
    echo "STACKINFO="${STACKINFO}
else
    # old config file, above steps performed outside of this script
    init_env ${ENV} ${AMPLIFY} ${PROVIDERS} ${CODEGEN} ${AWSCONFIG} ${CATEGORIES}
fi
````
