### ISSUE TITLE
Build Failed with "Reason: Parameter ScheduleExpression is not valid"

### ISSUE THREAD

**Issue by contractorwolf** [aws-amplify/amplify-console#1357]
**Describe the bug**
I am CLI version 4.21.3 and just created a new simple function that just does some scraping on a schedule and logs data to console log (all runs fine when mocking the new function), but when attempting to deploy via the CLI it fails with the following in the log on the command line:

```
Following resources failed

Resource Name: lambdaexecutionpolicy (AWS::IAM::Policy)
Event Type: create
Reason: Resource creation cancelled


Resource Name: ampli-Ampl-1CG7N52TAUEOP (AWS::IAM::Policy)
Event Type: create
Reason: Resource creation cancelled


Resource Name: CloudWatchEvent (AWS::Events::Rule)
Event Type: create
Reason: Parameter ScheduleExpression is not valid. (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: 75a4c102-bd04-4c80-aafc-2cb6523135e7; Proxy: null)


✖ An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occured during the push operation: Resource is not in the state stackUpdateComplete
```

When I push my project up to github to deploy my front end and amplify I get this

```
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-12-09T23:43:49.150Z [INFO]: 
2020-12-09T23:43:49.153Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html
2020-12-09T23:43:49.735Z [INFO]: Amplify AppID found: d2y0bndwty1i0h. Amplify App name is: amplifynewsscraper
2020-12-09T23:43:49.893Z [INFO]: Backend environment dev found in Amplify Console app: amplifynewsscraper
2020-12-09T23:43:50.589Z [INFO]: 
2020-12-09T23:43:50.592Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2020-12-09T23:43:51.009Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2020-12-09T23:43:51.078Z [INFO]: 
2020-12-09T23:43:52.251Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-12-09T23:43:56.697Z [WARNING]: - Initializing your environment: dev
2020-12-09T23:43:57.167Z [WARNING]: ✔ Initialized provider successfully.
2020-12-09T23:44:01.190Z [WARNING]: - Uploading files...
2020-12-09T23:44:01.265Z [WARNING]: - Uploading files...
2020-12-09T23:44:02.541Z [WARNING]: - Uploading files...
2020-12-09T23:44:02.834Z [WARNING]: - Uploading files...
2020-12-09T23:44:03.018Z [INFO]: The following types do not have '@auth' enabled. Consider using @auth with @model
2020-12-09T23:44:03.018Z [INFO]: - Scrape
                                 - NewsArticle
                                 - DailyWordCloudList
                                 Learn more about @auth here: https://docs.amplify.aws/cli/graphql-transformer/directives#auth
2020-12-09T23:44:03.164Z [INFO]: GraphQL schema compiled successfully.
                                 Edit your schema at /codebuild/output/src115007284/src/amplifynewsscraper/amplify/backend/api/amplifynewsscraper/schema.graphql or place .graphql files in a directory at /codebuild/output/src115007284/src/amplifynewsscraper/amplify/backend/api/amplifynewsscraper/schema
2020-12-09T23:44:03.170Z [WARNING]: - Uploading files...
2020-12-09T23:44:03.559Z [WARNING]: - Updating resources in the cloud. This may take a few minutes...
2020-12-09T23:44:09.278Z [INFO]: 
2020-12-09T23:44:09.279Z [INFO]: UPDATE_IN_PROGRESS amplify-amplifynewsscraper-dev-231429 AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:04 GMT+0000 (Coordinated Universal Time) User Initiated
2020-12-09T23:44:14.239Z [INFO]: 
2020-12-09T23:44:14.241Z [INFO]: UPDATE_COMPLETE    authamplifynewsscrapere0220fb9 AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:10 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS authamplifynewsscrapere0220fb9 AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:09 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS apiamplifynewsscraper          AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:09 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:44:14.330Z [INFO]: 
2020-12-09T23:44:14.330Z [INFO]: UPDATE_IN_PROGRESS amplify-amplifynewsscraper-dev-231429-apiamplifynewsscraper-1450RKRNPV9G5 AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:10 GMT+0000 (Coordinated Universal Time) User Initiated
2020-12-09T23:44:19.300Z [INFO]: 
2020-12-09T23:44:19.303Z [INFO]: UPDATE_COMPLETE    DailyWordCloudList AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:18 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE    Scrape             AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:18 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS GraphQLAPIKey      AWS::AppSync::ApiKey       Wed Dec 09 2020 23:44:18 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS NewsArticle        AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:18 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS Scrape             AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:18 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS DailyWordCloudList AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:18 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:44:19.606Z [INFO]: 
2020-12-09T23:44:19.606Z [INFO]: UPDATE_COMPLETE NewsArticle AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:19 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:44:24.298Z [INFO]: 
2020-12-09T23:44:24.299Z [INFO]: UPDATE_COMPLETE    ConnectionStack AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:22 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS ConnectionStack AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:22 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE    GraphQLAPIKey   AWS::AppSync::ApiKey       Wed Dec 09 2020 23:44:20 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:44:29.521Z [INFO]: 
2020-12-09T23:44:29.522Z [INFO]: UPDATE_COMPLETE    CustomResourcesjson AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:26 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS CustomResourcesjson AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:25 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:44:34.234Z [INFO]: 
2020-12-09T23:44:34.235Z [INFO]: UPDATE_COMPLETE apiamplifynewsscraper AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:32 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:44:39.215Z [INFO]: 
2020-12-09T23:44:39.217Z [INFO]: UPDATE_COMPLETE    functionnewsarticlebuildwordcloud  AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:35 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE    functionnewsarticlemainscrape      AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:35 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS functionnewsarticlepublisherscrape AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:35 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 UPDATE_COMPLETE    functionnewsarticlehydrate         AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:35 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS functionnewsarticlebuildwordcloud  AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:35 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS functionnewsarticlemainscrape      AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:35 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS functionnewsarticlehydrate         AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:34 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS functionnewsarticlepublisherscrape AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:34 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:44:39.256Z [INFO]: 
2020-12-09T23:44:39.256Z [INFO]: CREATE_IN_PROGRESS amplify-amplifynewsscraper-dev-231429-functionnewsarticlepublisherscrape-1H2AR5J0J98PI AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:35 GMT+0000 (Coordinated Universal Time) User Initiated
2020-12-09T23:44:44.273Z [INFO]: 
2020-12-09T23:44:44.274Z [INFO]: CREATE_IN_PROGRESS LambdaExecutionRole AWS::IAM::Role Wed Dec 09 2020 23:44:40 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_IN_PROGRESS LambdaExecutionRole AWS::IAM::Role Wed Dec 09 2020 23:44:39 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:44:54.279Z [INFO]: 
2020-12-09T23:44:54.281Z [INFO]: CREATE_COMPLETE LambdaExecutionRole AWS::IAM::Role Wed Dec 09 2020 23:44:53 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:44:59.281Z [INFO]: 
2020-12-09T23:44:59.283Z [INFO]: CREATE_IN_PROGRESS AmplifyResourcesPolicy AWS::IAM::Policy Wed Dec 09 2020 23:44:58 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:45:04.421Z [INFO]: 
2020-12-09T23:45:04.422Z [INFO]: CREATE_COMPLETE    LambdaFunction         AWS::Lambda::Function Wed Dec 09 2020 23:45:01 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS LambdaFunction         AWS::Lambda::Function Wed Dec 09 2020 23:45:00 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_IN_PROGRESS AmplifyResourcesPolicy AWS::IAM::Policy      Wed Dec 09 2020 23:45:00 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_IN_PROGRESS LambdaFunction         AWS::Lambda::Function Wed Dec 09 2020 23:44:59 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:45:09.290Z [INFO]: 
2020-12-09T23:45:09.292Z [INFO]: CREATE_FAILED      amplify-amplifynewsscraper-dev-231429-functionnewsarticlepublisherscrape-1H2AR5J0J98PI AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:08 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to create: [lambdaexecutionpolicy, CloudWatchEvent, AmplifyResourcesPolicy].
                                 CREATE_FAILED      AmplifyResourcesPolicy                                                                 AWS::IAM::Policy           Wed Dec 09 2020 23:45:07 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
                                 CREATE_FAILED      lambdaexecutionpolicy                                                                  AWS::IAM::Policy           Wed Dec 09 2020 23:45:07 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
                                 CREATE_IN_PROGRESS lambdaexecutionpolicy                                                                  AWS::IAM::Policy           Wed Dec 09 2020 23:45:06 GMT+0000 (Coordinated Universal Time)
                                 CREATE_FAILED      CloudWatchEvent                                                                        AWS::Events::Rule          Wed Dec 09 2020 23:45:06 GMT+0000 (Coordinated Universal Time) Parameter ScheduleExpression is not valid. (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: ae4e477c-c8c9-468b-8ca3-19f91fd5325c; Proxy: null)
                                 CREATE_IN_PROGRESS CloudWatchEvent                                                                        AWS::Events::Rule          Wed Dec 09 2020 23:45:05 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:45:14.242Z [INFO]: 
2020-12-09T23:45:14.243Z [INFO]: UPDATE_ROLLBACK_IN_PROGRESS amplify-amplifynewsscraper-dev-231429 AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:10 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to create: [functionnewsarticlepublisherscrape].
                                 CREATE_FAILED               functionnewsarticlepublisherscrape    AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:09 GMT+0000 (Coordinated Universal Time) Embedded stack arn:aws:cloudformation:us-east-1:237169730438:stack/amplify-amplifynewsscraper-dev-231429-functionnewsarticlepublisherscrape-1H2AR5J0J98PI/7e256ac0-3a78-11eb-8eaf-0ada7ccc8ac7 was not successfully created: The following resource(s) failed to create: [lambdaexecutionpolicy, CloudWatchEvent, AmplifyResourcesPolicy].
2020-12-09T23:45:39.287Z [INFO]: 
2020-12-09T23:45:39.289Z [INFO]: UPDATE_COMPLETE    authamplifynewsscrapere0220fb9 AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:37 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS authamplifynewsscrapere0220fb9 AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:36 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS apiamplifynewsscraper          AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:36 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:45:39.380Z [INFO]: 
2020-12-09T23:45:39.380Z [INFO]: UPDATE_ROLLBACK_IN_PROGRESS         amplify-amplifynewsscraper-dev-231429-apiamplifynewsscraper-1450RKRNPV9G5 AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:37 GMT+0000 (Coordinated Universal Time) User Initiated
                                 UPDATE_COMPLETE_CLEANUP_IN_PROGRESS amplify-amplifynewsscraper-dev-231429-apiamplifynewsscraper-1450RKRNPV9G5 AWS::CloudFormation::Stack Wed Dec 09 2020 23:44:29 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:45:44.391Z [INFO]: 
2020-12-09T23:45:44.395Z [INFO]: UPDATE_IN_PROGRESS CustomResourcesjson AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:43 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE    ConnectionStack     AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:43 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE    GraphQLAPIKey       AWS::AppSync::ApiKey       Wed Dec 09 2020 23:45:42 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS ConnectionStack     AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:42 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE    DailyWordCloudList  AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:41 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE    Scrape              AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:41 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE    NewsArticle         AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:41 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS GraphQLAPIKey       AWS::AppSync::ApiKey       Wed Dec 09 2020 23:45:41 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS DailyWordCloudList  AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:41 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS Scrape              AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:41 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS NewsArticle         AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:41 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:45:44.751Z [INFO]: 
2020-12-09T23:45:44.752Z [INFO]: UPDATE_COMPLETE CustomResourcesjson AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:44 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:45:49.265Z [INFO]: 
2020-12-09T23:45:49.267Z [INFO]: UPDATE_IN_PROGRESS functionnewsarticlebuildwordcloud AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:49 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS functionnewsarticlemainscrape     AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:49 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE    apiamplifynewsscraper             AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:48 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:45:49.565Z [INFO]: 
2020-12-09T23:45:49.566Z [INFO]: UPDATE_IN_PROGRESS functionnewsarticlehydrate AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:48 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:45:54.279Z [INFO]: 
2020-12-09T23:45:54.281Z [INFO]: UPDATE_COMPLETE                              functionnewsarticlebuildwordcloud     AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:52 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE                              functionnewsarticlemainscrape         AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:52 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE                              functionnewsarticlehydrate            AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:51 GMT+0000 (Coordinated Universal Time)
                                 DELETE_IN_PROGRESS                           functionnewsarticlepublisherscrape    AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:51 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE                              authamplifynewsscrapere0220fb9        AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:51 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS amplify-amplifynewsscraper-dev-231429 AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:50 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE                              functionnewsarticlebuildwordcloud     AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:49 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE                              functionnewsarticlehydrate            AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:49 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE                              functionnewsarticlemainscrape         AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:49 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:45:54.324Z [INFO]: 
2020-12-09T23:45:54.325Z [INFO]: DELETE_IN_PROGRESS amplify-amplifynewsscraper-dev-231429-functionnewsarticlepublisherscrape-1H2AR5J0J98PI AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:52 GMT+0000 (Coordinated Universal Time) User Initiated
2020-12-09T23:45:59.356Z [INFO]: 
2020-12-09T23:45:59.358Z [INFO]: DELETE_COMPLETE    LambdaExecutionRole    AWS::IAM::Role        Wed Dec 09 2020 23:45:58 GMT+0000 (Coordinated Universal Time)
                                 DELETE_IN_PROGRESS LambdaExecutionRole    AWS::IAM::Role        Wed Dec 09 2020 23:45:57 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE    LambdaFunction         AWS::Lambda::Function Wed Dec 09 2020 23:45:56 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE    AmplifyResourcesPolicy AWS::IAM::Policy      Wed Dec 09 2020 23:45:55 GMT+0000 (Coordinated Universal Time)
                                 DELETE_IN_PROGRESS LambdaFunction         AWS::Lambda::Function Wed Dec 09 2020 23:45:55 GMT+0000 (Coordinated Universal Time)
                                 DELETE_IN_PROGRESS AmplifyResourcesPolicy AWS::IAM::Policy      Wed Dec 09 2020 23:45:54 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE    CloudWatchEvent        AWS::Events::Rule     Wed Dec 09 2020 23:45:54 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE    lambdaexecutionpolicy  AWS::IAM::Policy      Wed Dec 09 2020 23:45:54 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:45:59.570Z [INFO]: 
2020-12-09T23:45:59.571Z [INFO]: DELETE_COMPLETE amplify-amplifynewsscraper-dev-231429-functionnewsarticlepublisherscrape-1H2AR5J0J98PI AWS::CloudFormation::Stack Wed Dec 09 2020 23:45:59 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:46:04.293Z [INFO]: 
2020-12-09T23:46:04.295Z [INFO]: DELETE_COMPLETE functionnewsarticlepublisherscrape AWS::CloudFormation::Stack Wed Dec 09 2020 23:46:03 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:46:19.309Z [INFO]: 
2020-12-09T23:46:19.310Z [INFO]: UPDATE_ROLLBACK_COMPLETE amplify-amplifynewsscraper-dev-231429 AWS::CloudFormation::Stack Wed Dec 09 2020 23:46:14 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE          apiamplifynewsscraper                 AWS::CloudFormation::Stack Wed Dec 09 2020 23:46:14 GMT+0000 (Coordinated Universal Time)
2020-12-09T23:46:34.419Z [WARNING]: Error updating cloudformation stack
2020-12-09T23:46:39.425Z [INFO]: Following resources failed
                                 Resource Name: ampli-Ampl-1JAY69E6GOD69 (AWS::IAM::Policy)
                                 Event Type: create
                                 Reason: Resource creation cancelled
2020-12-09T23:46:39.427Z [INFO]: Resource Name: lambdaexecutionpolicy (AWS::IAM::Policy)
                                 Event Type: create
                                 Reason: Resource creation cancelled
                                 Resource Name: CloudWatchEvent (AWS::Events::Rule)
                                 Event Type: create
                                 Reason: Parameter ScheduleExpression is not valid. (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: ae4e477c-c8c9-468b-8ca3-19f91fd5325c; Proxy: null)
2020-12-09T23:46:39.427Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
                                    ✖ There was an error initializing your environment.
2020-12-09T23:46:39.428Z [INFO]: init failed
2020-12-09T23:46:39.432Z [INFO]: ResourceNotReady: Resource is not in the state stackUpdateComplete
                                 at constructor.setError (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/resource_waiter.js:182:47)
                                 at Request.CHECK_ACCEPTORS (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/resource_waiter.js:44:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
                                 at Request.transition (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12) {
                                 code: 'ResourceNotReady',
                                 retryable: false,
                                 time: 2020-12-09T23:46:34.419Z,
                                 statusCode: 200,
                                 retryDelay: 30000
                                 }
2020-12-09T23:46:39.463Z [ERROR]: !!! Build failed
2020-12-09T23:46:39.464Z [ERROR]: !!! Non-Zero Exit Code detected
2020-12-09T23:46:39.464Z [INFO]: # Starting environment caching...
2020-12-09T23:46:39.464Z [INFO]: # Environment caching completed
Terminating logging...
```

Really not sure what to try, those messages dont really spell it out for me.  Anyone got a guess?  Something I could test out?

**Comment by contractorwolf** [comment]
UPDATE: I looked up the "Parameter ScheduleExpression is not valid" and found that it seemed to suggest that the cron schedule I had used may have been invalid.  I had used the CLI to add scheduling to the function and it seemed to have no issues with the numbers I had used when using the CLI, but I decided to go back through them by using:
> amplify update function 
and then making sure the number I chose for the schedule was sensible (I chose 2 this time).  After updating and repushing everything seemed to be corrected and I didnt see the error again.  

After thinking about it there maybe a bug in the CLI because I think my initial choice may have been "hours" and 24, which maybe processed wrong since that should be "days" and 1 instead?

**Comment by hsspain** [comment]
@contractorwolf Thank you for this feedback. We will look into this specific scenario and update where necessary.

**Comment by akshbhu** [comment]
Hi @contractorwolf 

Thanks for reporting it.

When asked this question in CLI workflow:
```
which interval should the function be invoked
❯ Minutes 
  Hourly 
  Daily 
  Weekly 
  Monthly 
  Yearly 
  Custom AWS cron expression 
```

Did you selected the   "Hourly": "rate(24 hours)" when it failed for you or you selected an option for Custom AWS cron expression?. The latter option enables you to write your own cron expression.

AFAIK "CloudWatchRule": "rate(24 hours)" is a valid Schedule Expression.

**Comment by contractorwolf** [comment]
I did NOT do a custom cron, I thought I chose "hourly" and then a rate of 24

**Comment by contractorwolf** [comment]
I am going to close this issue since it is now working
