### ISSUE TITLE
Execution failed for task ':amplifyPush'.

### ISSUE THREAD

**Issue by reddy9698** [aws-amplify/amplify-console#1444]
I'm fairly new to amplify and Android app development 
I was following the tutorial mentioned on their website (https://docs.amplify.aws/start/getting-started/add-api/q/integration/android)
I followed the tutorial completely, However I get this error and I'm unable to understand how to overcome the problem.
![Screenshot (120)](https://user-images.githubusercontent.com/30919564/104103906-d1b36b00-52ca-11eb-8f2d-714de11900f0.png)

**Comment by hsspain** [comment]
@reddy9698 If you can provide more logs for the error, we can better help you.  Can you look at your console logs and paste them here?

**Comment by simone40love** [comment]
> Task :amplifyPush
Note: It is recommended to run this command from the root of your app directory

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

init failed
Error: Profile configuration is missing for: default
    at Object.getProfiledAwsConfig (C:\Users\phili\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\src\system-config-manager.js:90:17)
    at Object.getAwsConfig (C:\Users\phili\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\src\configuration-manager.ts:727:45)
    at Object.run (C:\Users\phili\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\amplify-provider-awscloudformation\src\initializer.js:27:50)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

> Task :amplifyPush FAILED

Execution failed for task ':amplifyPush'.
> Process 'command 'amplify.cmd'' finished with non-zero exit value 1
