### ISSUE TITLE
Amplify project Gneral Settings unable to set Role

### ISSUE THREAD

**Issue by slackgadget** [aws-amplify/amplify-console#1480]
I created a Dev build and I have configured an IAM Role to Admin Amplify - but I must have missed something. When I go into the AWS Amplify Console > App Settings > General for my **dev** build, I don't see any Roles appearing in the dropdown list box to set the Service Role. 

My build is currently failing because there's no IAM role:
`2021-01-21T17:42:14.112Z [INFO]: init failed
2021-01-21T17:42:14.136Z [INFO]: Error: AWS access credentials can not be found.
                                 at newUserCheck (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/configuration-manager.js:567:15)
                                 at Object.init (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/configuration-manager.js:26:9)
                                 at Object.run (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/initializer.js:17:30)
                                 at Object.init (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/index.js:22:22)
                                 at /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/src/init-steps/s2-initProviders.ts:14:51
                                 at /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
2021-01-21T17:42:14.136Z [HELP]: You do not have a role attached to your app
2021-01-21T17:42:15.063Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2021-01-21T17:42:18.461Z [INFO]: init failed`
![image](https://user-images.githubusercontent.com/10155368/105500506-e58fa180-5cba-11eb-86e1-01227e1a17eb.png)

** Provide additional details**
![image](https://user-images.githubusercontent.com/10155368/105498397-0e626780-5cb8-11eb-9347-0def1d704dd5.png)

**Comment by slackgadget** [comment]
My Bad - RTFM

**Comment by slackgadget** [comment]
FYI 
"In the role selection screen find Amplify and choose the **Amplify-Backend Deploymen**t role. Accept all the defaults and choose a name for your role (e.g. AmplifyConsoleServiceRole-AmplifyRole)."
