### ISSUE TITLE
Build Error after Import an existing DynamoDB table: storage headless is missing the following inputParams tables, region

### ISSUE THREAD

**Issue by ddotx** [aws-amplify/amplify-console#1544]
To resolve this error please add the following variables to your environment variables in your build:

AMPLIFY_STORAGE_BUCKET_NAME
AMPLIFY_STORAGE_REGION

These values should correlate to the bucket name and region for your imported storage.

This documentation will guide you to the right page to add these settings:

https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html

Please let us know if there are further issues.

_Originally posted by @hsspain in https://github.com/aws-amplify/amplify-console/issues/1359#issuecomment-745626000_

@hsspain But not work for me when import dynamo and build
Error: storage headless is missing the following inputParams tables, region

and after i add ENV like this

AMPLIFY_STORAGE_REGION
AMPLIFY_STORAGE_TABLES

Not Work, Same Error
```
2021-02-06T12:15:53.731Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2021-02-06T12:15:54.353Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2021-02-06T12:15:54.578Z [WARNING]: ✖ There was an error initializing your environment.
2021-02-06T12:15:54.591Z [INFO]: [31mFailed to pull the backend.[39m
2021-02-06T12:15:54.592Z [INFO]: [31mstorage headless is missing the following inputParams tables, region[39m
2021-02-06T12:15:54.596Z [INFO]: [0mError: storage headless is missing the following inputParams tables, region[0m
                                 [0m    at ensureHeadlessParameters (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/provider-utils/awscloudformation/import/import-dynamodb.ts:439:11)[0m
                                 [0m    at headlessImport (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/provider-utils/awscloudformation/import/import-dynamodb.ts:387:40)[0m
                                 [0m    at exports.importedDynamoDBEnvInit (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/provider-utils/awscloudformation/import/import-dynamodb.ts:277:18)[0m
                                 [0m    at runMicrotasks (<anonymous>)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at updateConfigOnEnvInit (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/provider-utils/awscloudformation/index.js:84:72)[0m
                                 [0m    at /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/index.js:147:22[0m
2021-02-06T12:15:54.614Z [ERROR]: !!! Build failed
2021-02-06T12:15:54.615Z [ERROR]: !!! Non-Zero Exit Code detected
```

**Comment by davinanaya** [comment]
Same here

**Comment by Kriz1618** [comment]
I got the same error, but adding those variants don't solve it, any thoughts?

**Comment by zeheeba** [comment]
I'm receiving the same error after importing my own DynamoDB into my Amplify setup.  Any assistance would be appreciated!
`2021-02-21T21:04:08.412Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2021-02-21T21:04:08.797Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2021-02-21T21:04:08.861Z [WARNING]: ✖ There was an error initializing your environment.
2021-02-21T21:04:08.864Z [INFO]: [31mFailed to pull the backend.[39m
2021-02-21T21:04:08.866Z [INFO]: [31mstorage headless is missing the following inputParams tables, region[39m
2021-02-21T21:04:08.870Z [INFO]: [0mError: storage headless is missing the following inputParams tables, region[0m
                                 [0m    at ensureHeadlessParameters (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/provider-utils/awscloudformation/import/import-dynamodb.ts:439:11)[0m
                                 [0m    at headlessImport (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/provider-utils/awscloudformation/import/import-dynamodb.ts:387:40)[0m
                                 [0m    at importedDynamoDBEnvInit (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/provider-utils/awscloudformation/import/import-dynamodb.ts:277:18)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at updateConfigOnEnvInit (/root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/provider-utils/awscloudformation/index.js:84:72)[0m
                                 [0m    at /root/.nvm/versions/node/v12.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/index.js:150:22[0m
2021-02-21T21:04:08.887Z [ERROR]: !!! Build failed
2021-02-21T21:04:08.887Z [ERROR]: !!! Non-Zero Exit Code detected`

**Comment by skilenton** [comment]
hello have anyone found a fix for this yet?

**Comment by samueuh** [comment]
I have the same problem. Are there any updates?

**Comment by burntsugar** [comment]
Also following this issue.

**Comment by zeheeba** [comment]
I bumped this issue through Twitter today and received a positive reply.  So I'm hopeful something will shake loose with this.
https://twitter.com/Z55_Studios/status/1374838470150131714

**Comment by victorccccc** [comment]
Hello folks, thanks for reporting this issue. We are currently investigating this, and will provide update here ASAP.

**Comment by tomhewitt03** [comment]
Any idea when we can expect a fix for this? Thanks

**Comment by samgates3** [comment]
I have tried everything I can think of to work around this with no luck. Commenting to stay updated

**Comment by victorccccc** [comment]
Hello folks, We apologize for the delay. Fix is rolling out and should be in Live in a few days. I'll update the status here when deployment completed

**Comment by victorccccc** [comment]
Update: You can now set `AMPLIFY_STORAGE_REGION`, and `AMPLIFY_STORAGE_TABLES` environment variable to address this issue. 

Format of `AMPLIFY_STORAGE_TABLES` is `{"Resources Name":"Table Name"}`, you can find resource name and table name in your `/amplify/team-provider-info.json` file 

Example: 
```
AMPLIFY_STORAGE_REGION : us-west-2
```
```
AMPLIFY_STORAGE_TABLES: {"testResourceName":"test-table"}
```

`team-provider-info.json` File: 
```
{
...
"categories": {
      "storage": {
        "testResourceName": {
          "tableName": "test-table",
          "region": "us-west-2",
          "arn": "*****",
          "streamArn": "****",
          "partitionKeyName": "***"
          "partitionKeyType": "*",
          "sortKeyName": "****",
          "sortKeyType": "*"
          }
      }
  }
...
}
```

**Comment by zeheeba** [comment]
@victorccccc Thanks for the fix and the update!  I can confirm that this fix works and deployment completes successfully.

**Comment by stefanmcshane** [comment]
Issue still exists with amplify version 4.52.0

**Comment by christophersutton** [comment]
I'm receiving this error as well, even though I no longer have any imported storage in the amplify project. I already ran a remove command on the storage, and it's no longer showing up in any cloudformation files etc. So now if I run e.g.
```
> amplify remove storage
No resources added for this category
```
So despite not having any storage anywhere visible in any configuration that I can find, builds are erroring out for this headless storage missing inputParams error

**Comment by jianupetrut** [comment]
Issue still exists

**Comment by reedshea** [comment]
I am also still seeing a related issue, even after including environment variables as described above. In the Amplify Console (not Admin UI), the build succeeds and deploys fine. On the home page of the Amplify Admin UI, however, in the "Deployment activity" table, I see one failed job:

    Category: jobCategory.GenerateBackendAPIModels
    Status: FAILED
    Reason: storage headless is missing the following inputParams tables, region

As a result of this, I believe, I am unable to modify my schema via the Amplify Admin UI. Making changes and clicking "Save and deploy" results in an message:
```
Command failed with exit code 1: /root/.amplify/bin/amplify pull --amplify 	{"envName":"dev","defaultEditor":"code",...
Deployment status: Failed
- Fetching updates to backend environment: dev from the cloud.
✔ Successfully pulled backend environment dev from the cloud.
✖ There was an error initializing your environment.
...
[32mGraphQL schema compiled successfully.[39m
...
[0mSuccessfully generated models. Generated models can be found in /tmp/amplify...
[31mFailed to pull the backend.
[31mstorage headless is missing the following inputParams tables, region
[0mError: storage headless is missing the following inputParams tables, region
[0m    at ensureHeadlessParameters (/snapshot/node_modules/amplify-category-storage/lib/provider-utils/awscloudformation/import/import-dynamodb.js:367:11)
[0m    at ensureHeadlessParameters (/snapshot/node_modules/amplify-category-storage/lib/provider-utils/awscloudformation/import/import-dynamodb.js:367:11)[0m
[0m    at headlessImport (/snapshot/node_modules/amplify-category-storage/lib/provider-utils/awscloudformation/import/import-dynamodb.js:327:40)[0m
[0m    at importedDynamoDBEnvInit (/snapshot/node_modules/amplify-category-storage/lib/provider-utils/awscloudformation/import/import-dynamodb.js:227:18)[0m
[0m    at runMicrotasks (<anonymous>)[0m
[0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
[0m    at Object.updateConfigOnEnvInit (/snapshot/node_modules/amplify-category-storage/lib/provider-utils/awscloudformation/index.js:157:9)[0m
[0m    at /snapshot/node_modules/amplify-category-storage/lib/index.js:216:22[0m
```

@victorccccc , thank you for the guidance above. That helped substantially, as I was able to get the build working. This seems like it's related. I would like to be able to use the Amplify Admin UI to build out a GraphQL schema, so I'd be grateful for any suggestions or assistance.

**Comment by JGillam** [comment]
@victorccccc (or anyone else) Any idea when this is supposed to get rolled into the latest build?  I'm experiencing the issue exactly as described by the OP, so I assume this has not been pushed to the latest production Amplify code.  For a little more context:

I started with an existing Amplify project with auth, apis, and functions on the backend.  This was deploying perfectly out of a github branch using the default amplify.yml.

Then I imported a dynamo table (i.e. `amplify import storage`), which deploys fine in dev using `amplify push`.

But when I merged the changes to my deploying branch, I got the error message regarding `storage headless is missing the following inputParams tables, region`.  Then I found this thread and added `AMPLIFY_STORAGE_REGION` and `AMPLIFY_STORAGE_TABLES` environment variables in the Amplify console, [as you described above](https://github.com/aws-amplify/amplify-console/issues/1544#issuecomment-833691049).  But I am still getting the error.

Is it possible I am missing some other configuration steps?

**Comment by JGillam** [comment]
An alternative solution that worked for me was to set a CATAGORIES environment variable with a value such as:

```
{"storage":{"region": "us-east-1", "tables": {"mytableresource":"mytablename"}}}
```
The values are:
- region value: should be wherever the storage is (e.g. us-east-1, us-west-2, etc...)
- mytableresource: is the name of the resource as found in team-provider-info.json.  In my case it was the same as the table name.
- mytablename: is the name of the table as found in team-provider-info.json

It seems a side effect of this approach broke auth configuration on the frontend, which I fixed with a `Auth.configure(awsconfig)` as described [in this issue comment](https://github.com/aws-amplify/amplify-js/issues/4315#issuecomment-629736223).
