### ISSUE TITLE
Cannot destructure property 'timeout' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by volkanunsal** [aws-amplify/amplify-console#1652]
**Describe the bug**

 I'm trying to start the local development server. I followed the instructions in the manual and ran:

```
amplify mock
amplify mock function
```

This is the error I'm getting:

```
➜  showcase (ruby-2.5.5) git:(master) amplify mock function
? Provide the path to the event JSON object relative to /Users/newuser/x/rcv/showcase/amplify/backend/function/rcvce175542 src/event.json
Ensuring latest function changes are built...
Starting execution...
rcvce175542 failed with the following error:
TypeError: Cannot destructure property 'timeout' of 'undefined' as it is undefined.
    at getCancellableTimer (/Users/newuser/.volta/tools/image/packages/@aws-amplify/cli/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/func/index.ts:73:32)
    at Object.timeConstrainedInvoker (/Users/newuser/.volta/tools/image/packages/@aws-amplify/cli/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/func/index.ts:65:29)
    at Object.start (/Users/newuser/.volta/tools/image/packages/@aws-amplify/cli/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/func/index.ts:48:26)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at Object.run (/Users/newuser/.volta/tools/image/packages/@aws-amplify/cli/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/commands/mock/function.ts:14:5)
    at Object.executeAmplifyCommand (/Users/newuser/.volta/tools/image/packages/@aws-amplify/cli/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/amplify-plugin-index.ts:8:3)
    at executePluginModuleCommand (/Users/newuser/.volta/tools/image/packages/@aws-amplify/cli/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:181:3)
    at Object.executeCommand (/Users/newuser/.volta/tools/image/packages/@aws-amplify/cli/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:28:5)
    at Object.run (/Users/newuser/.volta/tools/image/packages/@aws-amplify/cli/lib/node_modules/@aws-amplify/cli/src/index.ts:105:5)
```

**Comment by volkanunsal** [comment]
It looks like `context.input.options` is undefined in this line:

```js
const result = await exports.timeConstrainedInvoker(invoker({ event }), context.input.options);
```

...around here:

```
 Object.timeConstrainedInvoker (/Users/newuser/.volta/tools/image/packages/@aws-amplify/cli/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/func/index.ts:65:29)
```

I worked around it by adding a fallback option , i.e.`{ timeout: 10 }`.


btw, I'm using CLI v4.44.0.
