### ISSUE TITLE
React app with Python based Lambda function fails to deploy correctly.

### ISSUE THREAD

**Issue by rbagdazian** [aws-amplify/amplify-console#1687]
**Which Specific Feature is your question related to?**
CI/CD management of amplify app using React as a front end and a lambda function backend written in Python.

I have successfully worked through the example provided in this video by nader dabit with my own particular lambda function:
https://egghead.io/lessons/javascript-creating-a-full-stack-serverless-app-with-python-react-hooks-and-aws-amplify-functions

I did the development in Cloud9 and updated the python version to 3.8.6. When I executed >>amplify push the lambda function was deployed successfully and I was able to subsequently run >> npm start and in the preview pane received the expected response from my lambda function implementation.

At that point I attempted to issue the usual git update sequence ending with the >>git push origin master to push the project to my git repository. The AWS Amplify console indicated that it was provisioning which completed successfully. The following build step failed while apparently trying to compile my python lambda app. The build error log is as follows:

```
----------------------------------------------------------------------------------------------------------------
2021-03-23T19:21:39.957Z [INFO]: Git SSH Key acquired
2021-03-23T19:21:40.031Z [INFO]: # Cloning repository: git@github.com:**********/**********.git
2021-03-23T19:21:40.040Z [INFO]: Agent pid 133
2021-03-23T19:21:40.067Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2021-03-23T19:21:40.358Z [INFO]: Cloning into '**********'...
2021-03-23T19:21:40.528Z [INFO]: Warning: Permanently added the RSA host key for IP address '140.82.112.4' to the list of known hosts.
2021-03-23T19:21:40.777Z [INFO]: # Switching to commit: bbf89001543105a11ea1b84a5f04efd928cb9489
2021-03-23T19:21:40.784Z [INFO]: Agent pid 146
2021-03-23T19:21:40.788Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2021-03-23T19:21:40.794Z [INFO]: Note: switching to 'bbf89001543105a11ea1b84a5f04efd928cb9489'.
                                 You are in 'detached HEAD' state. You can look around, make experimental
                                 changes and commit them, and you can discard any commits you make in this
                                 state without impacting any branches by switching back to a branch.
                                 If you want to create a new branch to retain commits you create, you may
                                 do so (now or later) by using -c with the switch command. Example:
                                 git switch -c <new-branch-name>
                                 Or undo this operation with:
                                 git switch -
                                 Turn off this advice by setting config variable advice.detachedHead to false
2021-03-23T19:21:40.794Z [INFO]: HEAD is now at bbf8900 working lambda backend
2021-03-23T19:21:40.800Z [INFO]: Successfully cleaned up Git credentials
2021-03-23T19:21:40.800Z [INFO]: # Checking for Git submodules at: /codebuild/output/src126550711/src/amplifyapp/.gitmodules
2021-03-23T19:21:40.823Z [INFO]: # Retrieving cache...
2021-03-23T19:21:46.303Z [INFO]: # Extracting cache...
2021-03-23T19:21:51.208Z [INFO]: # Extraction completed
2021-03-23T19:21:51.635Z [INFO]: # Retrieving environment cache...
2021-03-23T19:21:51.684Z [INFO]: # Retrieved environment cache
2021-03-23T19:22:04.231Z [INFO]: ## Starting Backend Build
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2021-03-23T19:22:17.338Z [INFO]: 
2021-03-23T19:22:17.341Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html
2021-03-23T19:22:17.514Z [INFO]: Amplify AppID found: d2r5on3g7plyuj. Amplify App name is: amplifyapp
2021-03-23T19:22:17.562Z [INFO]: Backend environment staging found in Amplify Console app: amplifyapp
2021-03-23T19:22:17.889Z [INFO]: 
2021-03-23T19:22:17.892Z [WARNING]: - Fetching updates to backend environment: staging from the cloud.
2021-03-23T19:22:18.331Z [WARNING]: ✔ Successfully pulled backend environment staging from the cloud.
2021-03-23T19:22:18.815Z [INFO]: python3 found but version Python 3.7.9 is less than the minimum required version.
                                 You must have python >= 3.8 installed and available on your PATH as "python3". It can be installed from https://www.python.org/downloads
                                 You must have pipenv installed and available on your PATH as "pipenv". It can be installed by running "pip3 install --user pipenv".
2021-03-23T19:22:18.815Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
                                    ✖ There was an error initializing your environment.
2021-03-23T19:22:18.818Z [INFO]: Failed to pull the backend.
2021-03-23T19:22:18.819Z [INFO]: Missing required dependencies to package lambdaTestFunction
2021-03-23T19:22:18.846Z [INFO]: Error: Missing required dependencies to package lambdaTestFunction
                                 at buildResource (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/build-resources.js:30:11)
                                 at processTicksAndRejections (internal/process/task_queues.js:97:5)
                                 at async Promise.all (index 0)
                                 at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.js:47:5)
2021-03-23T19:22:18.858Z [ERROR]: !!! Build failed
2021-03-23T19:22:18.858Z [ERROR]: !!! Non-Zero Exit Code detected
2021-03-23T19:22:18.859Z [INFO]: # Starting environment caching...
2021-03-23T19:22:18.859Z [INFO]: # Environment caching completed
Terminating logging...
------------------------------------------------------------------------------------------------
```
I'm hoping someone can enlighten me as to how to get the frontend and other backend things like auth functionality, etc to be ported as I was doing with the CI/CD approach before i added the lambda function. You can see above where it is complaining that it has found an old version of python, but I don't know where it is running or how to fix it.

Thanks in advance!

**Comment by ganipcanot** [comment]
Please check this FAQ section: https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md#how-do-i-run-amplify-functions-with-python-runtime

Feel free to re-open if you are still having issues.
