### ISSUE TITLE
Trouble adding aurora mysql graphql datasource

### ISSUE THREAD

**Issue by georgeleeventures** [aws-amplify/amplify-console#1709]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

When trying to add mysql graphql datasource (https://docs.amplify.aws/cli/graphql-transformer/relational), a non-descript error is being given to me (redaction = XXXXXXXXXX)

george:~/environment/(dev) $ amplify api add-graphql-datasource
Using datasource: Aurora Serverless, provided by: awscloudformation
? Provide the region in which your cluster is located: us-east-1
? Select the Aurora Serverless cluster that will be used as the data source for your AP
I: XXXXXXXXXX
✔ Fetched Aurora Serverless cluster.
? Select the database to use as the datasource: XXXXXXXXXX
Error: ENOENT: no such file or directory, open '/home/ec2-user/environment/XXXXXXXXXX/amplify/backend/api/XXXXXXXXXX/resolvers/Mutation.XXXXXXXXXX.req.vtl'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at RelationalDBResolverGenerator.makeCreateRelationalResolver (/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/graphql-relational-schema-transformer/src/RelationalDBResolverGenerator.ts:109:8)
    at typePrimaryKeyMap.forEach (/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/graphql-relational-schema-transformer/src/RelationalDBResolverGenerator.ts:51:54)
    at Map.forEach (<anonymous>)
    at RelationalDBResolverGenerator.createRelationalResolvers (/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/graphql-relational-schema-transformer/src/RelationalDBResolverGenerator.ts:47:28)
    at RelationalDBTemplateGenerator.addRelationalResolvers (/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/graphql-relational-schema-transformer/src/RelationalDBTemplateGenerator.ts:52:72)
    at datasourceSelectionPrompt.then.then.then.graphqlSchemaContext (/home/ec2-user/.nvm/versions/node/v10.23.2/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-api/src/commands/api/add-graphql-datasource.js:146:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
There was an error adding the datasource

### Expected behavior

Expected that adding the aurora mysql graphql datasource would succeed as demonstrated here: https://docs.amplify.aws/cli/graphql-transformer/relational

### Reproduction steps

1. Follow directions and add mysql aurora datasource
2. run from the project directory: amplify api add-graphql-datasource
3. follow the prompts to select region, cluster, and database name

### Build Settings

```yaml
_No response_
```

Could this issue be a result of a naming conflict? I have 2 tables with the same name in mysql and dynamodb, so could it be a naming conflict? Another issue I noticed is: I do not have a resolvers folder in my api/XXXXXXXXXX directory -- when is this to be created?
I have the latest amplify CLI as well. 

Error: ENOENT: no such file or directory, open '/home/ec2-user/environment/XXXXXXXXXX/amplify/backend/api/XXXXXXXXXX/resolvers/Mutation.XXXXXXXXXX.req.vtl'

**Comment by siegerts** [comment]
Hi @georgeleeventures :wave:, thanks for raising. I'm going to transfer to the CLI repo to get some more eyes on it.

In the meantime, do you mind verifying that: 

- You're you're using the latest version of the Amplify CLI (<img src="https://img.shields.io/npm/v/@aws-amplify/cli.svg" />). Run `amplify version` to check.

- Check to see if any similar issues exist in that repo
