### ISSUE TITLE
amplify init fails for angular projects working inside a container

### ISSUE THREAD

**Issue by Karmavil** [aws-amplify/amplify-console#1736]
### Before opening, please confirm:

I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

```console
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project frontend
The following configuration will be applied:

Project information
| Name: frontend
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
TypeError: Cannot read property 'projectPath' of undefined
    at getAngularConfig (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/framework-config-mapping.js:57:52)
    at getProjectConfiguration (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/framework-config-mapping.js:85:14)
    at Object.displayFrontendDefaults (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/lib/configuration-manager.js:173:32)
    at Object.displayFrontendDefaults (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-javascript/index.js:40:24)
    at displayAndSetDefaults (/usr/local/lib/node_modules/@aws-amplify/cli/lib/init-steps/s0-analyzeProject.js:83:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async analyzeProject (/usr/local/lib/node_modules/@aws-amplify/cli/lib/init-steps/s0-analyzeProject.js:99:9)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/commands/init.js:29:13)
    at async Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:236:9)
    at async executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:164:5)
    at async Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:112:9)
```

### Expected behavior

```console
Project information
| Name: chorrimanguera
| Environment: dev
| Default editor: Visual Studio Code
| App type: javascript
| Javascript framework: none
| Source Directory Path: src
| Distribution Directory Path: dist
| Build Command: npm run-script build

? Initialize the project with the above configuration? No
? Enter a name for the environment (dev) 
```

### Reproduction steps

I have no idea.. let's see
1) Launch a container: node14.16-buster
2) Install globally npm packages: angular/cli 11.2.3 and aws-amplify/cli (4.47.1)
3) Start a new angular app.
4) Run amplify configure an set the credentials
5) In the app directory run amplify init

### Additional information

* I tried creating new IAM users but it does not help.
* The IAM user has admin rights but also the git user has full access to codecommit.

**Comment by Karmavil** [comment]
Oh sorry guys I forgot I was using almost the latest version.. I will check which angular version is working correctly as well as node later today. Let me know if I should tag this issue for future releases or something like that

**Comment by siegerts** [comment]
Hi  @Karmavil  :wave:, thanks for raising. I'm going to transfer to the CLI repo repo to get some more eyes on it.

In the meantime, do you mind verifying if you're following a similar process as outlined below to init the Angular project with the CLI?

- https://docs.amplify.aws/start/getting-started/setup/q/integration/angular
