### ISSUE TITLE
problem with Build a Full-Stack React Application learn module part 3 ~ add authentication

### ISSUE THREAD

**Issue by rmasonh18** [aws-amplify/amplify-console#1843]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d24v30ethdkds1

### Region

us-east-1

### Amplify Console feature

Backend builds

### Describe the bug

I have done the module 4 times today ~ get the following build error on completion of item 3 above learn module to use react with amplify 
         # Starting phase: build
                                 # Executing command: amplifyPush --simple
2021-05-17T04:24:45.877Z [INFO]: File project: data should NOT have additional properties: 'graphqltransformer'
2021-05-17T04:24:45.878Z [INFO]: JSONValidationError: File project: data should NOT have additional properties: 'graphqltransformer'
                                 at validator (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:136:27)
                                 at featureFlagsValidator (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:140:17)
                                 at FeatureFlags.validateFlags (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:146:17)
                                 at FeatureFlags.loadValues (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:204:18)
                                 at async Function.FeatureFlags.initialize (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:267:5)
                                 at async Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/lib/index.js:73:9)
2021-05-17T04:24:45.883Z [ERROR]: !!! Build failed
2021-05-17T04:24:45.883Z [ERROR]: !!! Non-Zero Exit Code detected
2021-05-17T04:24:45.883Z [INFO]: # Starting environment caching...
2021-05-17T04:24:45.883Z [INFO]: # Uploading environment cache artifact...
2021-05-17T04:24:45.970Z [INFO]: # Environment caching completed

### Expected behavior

build with no error so I can do next part or module 4.

### Reproduction steps

follow module 1-3

### Additional information

Little more info in doc's

**Comment by siegerts** [comment]
Hi @rmasonh18, thanks for raising. That error usually indicates that the build is using an older version of the Amplify CLI.  

The steps outlined in this comment (below) should help unblock you, specifically the CLI version

> Adjusted the build settings by adding:
> Build Settings -> Build image settings -> Live package updates -> Amplify CLI -> latest


https://github.com/aws-amplify/amplify-console/issues/1726#issuecomment-814571075
