### ISSUE TITLE
Build failed to complete successfully 

### ISSUE THREAD

**Issue by GregoryNEUT** [aws-amplify/amplify-console#1874]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

da3v9ctzdeq5j

### Region

us-east-2

### Amplify Console feature

Not applicable

### Describe the bug

The build of my application fail.

### Expected behavior

The build should work.

### Reproduction steps

`All apps > xxxx-website > master`  clicks on  **Redeploy this version**

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

```
2021-05-24T15:02:52.048Z [INFO]: Git SSH Key acquired
2021-05-24T15:02:52.131Z [INFO]: # Cloning repository: git@github.com:GregoryNEUT/aory-website.git
2021-05-24T15:02:52.170Z [INFO]: Agent pid 133
2021-05-24T15:02:52.197Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2021-05-24T15:02:52.397Z [INFO]: Cloning into 'aory-website'...
2021-05-24T15:02:52.643Z [INFO]: Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
2021-05-24T15:02:53.142Z [INFO]: # Checking for Git submodules at: /codebuild/output/src866360281/src/aory-website/.gitmodules
2021-05-24T15:02:53.165Z [INFO]: # Retrieving cache...
2021-05-24T15:02:53.195Z [INFO]: # Extracting cache...
2021-05-24T15:02:53.202Z [INFO]: # Extraction completed
2021-05-24T15:02:53.203Z [INFO]: # Retrieving environment cache...
2021-05-24T15:02:53.220Z [INFO]: # Retrieved environment cache
2021-05-24T15:03:04.639Z [INFO]: ## Starting Frontend Build
                                 # Starting phase: preBuild
                                 # Executing command: npm ci
2021-05-24T15:03:09.875Z [INFO]: > core-js@3.12.1 postinstall /codebuild/output/src866360281/src/aory-website/node_modules/core-js
                                 > node -e "try{require('./postinstall')}catch(e){}"
2021-05-24T15:03:10.052Z [INFO]: [96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
                                 [96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
                                 [96m>[94m https://opencollective.com/core-js [0m
                                 [96m>[94m https://www.patreon.com/zloirock [0m
                                 [96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
2021-05-24T15:03:10.157Z [INFO]: added 515 packages in 4.839s
2021-05-24T15:03:10.167Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
2021-05-24T15:03:10.168Z [INFO]: # Executing command: npm run build
2021-05-24T15:03:10.321Z [INFO]: > learn-starter@0.1.0 build /codebuild/output/src866360281/src/aory-website
                                 > next build
2021-05-24T15:03:10.853Z [INFO]: info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
2021-05-24T15:03:11.019Z [INFO]: warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
2021-05-24T15:03:11.030Z [INFO]: Attention: Next.js now collects completely anonymous telemetry regarding usage.
2021-05-24T15:03:11.031Z [INFO]: This information is used to shape Next.js' roadmap and prioritize features.
                                 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
                                 https://nextjs.org/telemetry
2021-05-24T15:03:11.061Z [INFO]: info  - Checking validity of types...
2021-05-24T15:03:11.064Z [INFO]: info  - Creating an optimized production build...
2021-05-24T15:03:20.987Z [INFO]: info  - Compiled successfully
2021-05-24T15:03:20.989Z [INFO]: info  - Collecting page data...
2021-05-24T15:03:21.235Z [INFO]: info  - Generating static pages (0/11)
2021-05-24T15:03:21.502Z [INFO]: info  - Generating static pages (2/11)
2021-05-24T15:03:21.525Z [INFO]: info  - Generating static pages (5/11)
2021-05-24T15:03:21.534Z [INFO]: info  - Generating static pages (8/11)
2021-05-24T15:03:21.545Z [INFO]: info  - Generating static pages (11/11)
2021-05-24T15:03:21.546Z [INFO]: info  - Finalizing page optimization...
2021-05-24T15:03:21.550Z [INFO]: 
2021-05-24T15:03:21.559Z [INFO]: Page                                                           Size     First Load JS
                                 ┌ ● /                                                          21.4 kB         102 kB
                                 ├   └ css/bf57cc8b1db073d580c8.css                             2.05 kB
                                 ├   /_app                                                      0 B            80.7 kB
                                 └ ○ /404                                                       3.07 kB        83.8 kB
                                 + First Load JS shared by all                                  80.7 kB
                                 ├ chunks/71247caf95475e3ea7f9a0f8a30beb258b23d005.420be3.js  16.4 kB
                                 ├ chunks/commons.8da185.js                                   14.2 kB
                                 ├ chunks/framework.36a632.js                                 41.8 kB
                                 ├ chunks/main.81566b.js                                      7.08 kB
                                 ├ chunks/pages/_app.5f1a5a.js                                513 B
                                 ├ chunks/webpack.50bee0.js                                   751 B
                                 └ css/ac145e89b393cc641892.css                               438 B
2021-05-24T15:03:21.559Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
                                 ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
                                 (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
2021-05-24T15:03:21.668Z [INFO]: Starting SSR Build...
2021-05-24T15:04:14.230Z [INFO]: Error
Terminating logging...
```

----

![image](https://user-images.githubusercontent.com/22965416/119369860-eeb66c80-bcb4-11eb-9523-0d6f3e8312bf.png)

**Comment by GregoryNEUT** [comment]
![image](https://user-images.githubusercontent.com/22965416/119370696-dc88fe00-bcb5-11eb-9d3c-6d9d6567028a.png)

**Comment by Athena96** [comment]
Hi @GregoryNEUT I'm seeing this build error: 
`2021-05-24T15:29:44.094Z [WARNING]: ERR! fsevents not accessible from chokidar`

**Comment by GregoryNEUT** [comment]
Hello @Athena96 , thank you for the info. I've seen that some debug messages appeared on build now, allowing me to debug the issue.

**Comment by GregoryNEUT** [comment]
I've seen that `chokidar` is a dependency of `next`.

**Comment by nimacks** [comment]
@GregoryNEUT , I'm seeing this error in the log 
```
Error: Cannot find module '/codebuild/output/src132505150/src/XXXX-website/next-i18next.config.js'
```
Did you check in all dependencies?

**Comment by GregoryNEUT** [comment]
Hello,

I did create the project on windows 10 with the ubuntu terminal and everything works fine.

To be sure, I just did clone my repository on my Ubuntu 20.04.2 LTS and run `npm ci` + `npm run build` +  `npm run start` and it works.

I'm not sure about the dependencies that would be an issue. Should I try to configure a use of an other Docker image ? 

![image](https://user-images.githubusercontent.com/22965416/119551562-103d5400-bd9a-11eb-96f7-bd7fe534d323.png)

**Comment by GregoryNEUT** [comment]
Rewritten my app in ``react` instead of in `nextjs`

Region : `us-east-2`
App Id : `d1xxftpukkgyc8`

Still not working, I don't know ...

```
                                 # Starting phase: preBuild
                                 # Executing command: npm install
tinstall /codebuild/output/src928945262/src/aory-website-react/node_modules/babel-runtime/node_modules/core-js
                                 > node -e "try{require('./postinstall')}catch(e){}"
021-05-26T11:57:36.734Z [INFO]: Git SSH Key acquired
2021-05-26T11:57:36.809Z [INFO]: # Cloning repository: git@github.com:GregoryNEUT/aory-website-react.git
2021-05-26T11:57:36.841Z [INFO]: Agent pid 132
2021-05-26T11:57:36.865Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2021-05-26T11:57:37.095Z [INFO]: Cloning into 'aory-website-react'...
2021-05-26T11:57:37.395Z [INFO]: Warning: Permanently added the RSA host key for IP address '140.82.112.3' to the list of known hosts.
2021-05-26T11:57:37.948Z [INFO]: # Switching to commit: 903e6182221831591df02c31d90e10fc93c47c69
2021-05-26T11:57:37.976Z [INFO]: # Retrieving cache...
2021-05-26T11:57:37.978Z [INFO]: Agent pid 145
2021-05-26T11:57:37.979Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2021-05-26T11:57:37.987Z [INFO]: Note: switching to '903e6182221831591df02c31d90e10fc93c47c69'.
                                 You are in 'detached HEAD' state. You can look around, make experimental
                                 changes and commit them, and you can discard any commits you make in this
                                 state without impacting any branches by switching back to a branch.
                                 If you want to create a new branch to retain commits you create, you may
                                 do so (now or later) by using -c with the switch command. Example:
                                 git switch -c <new-branch-name>
                                 Or undo this operation with:
                                 git switch -
                                 Turn off this advice by setting config variable advice.detachedHead to false
2021-05-26T11:57:37.988Z [INFO]: HEAD is now at 903e618 fix
2021-05-26T11:57:37.993Z [INFO]: Successfully cleaned up Git credentials
2021-05-26T11:57:37.993Z [INFO]: # Checking for Git submodules at: /codebuild/output/src928945262/src/aory-website-react/.gitmodules
2021-05-26T11:57:38.003Z [INFO]: # Extracting cache...
2021-05-26T11:57:38.010Z [INFO]: # Extraction completed
2021-05-26T11:57:38.011Z [INFO]: # Retrieving environment cache...
2021-05-26T11:57:38.040Z [INFO]: # Retrieved environment cache
                                 # Starting phase: preBuild
                                 # Executing command: npm install
2021-05-26T11:58:09.040Z [INFO]: > core-js@2.6.12 postinstall /codebuild/output/src928945262/src/aory-website-react/node_modules/babel-runtime/node_modules/core-js
                                 > node -e "try{require('./postinstall')}catch(e){}"
2021-05-26T11:58:09.087Z [INFO]: [96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
                                 [96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
                                 [96m>[94m https://opencollective.com/core-js [0m
                                 [96m>[94m https://www.patreon.com/zloirock [0m
                                 [96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
2021-05-26T11:58:09.217Z [INFO]: > core-js@3.13.0 postinstall /codebuild/output/src928945262/src/aory-website-react/node_modules/core-js
                                 > node -e "try{require('./postinstall')}catch(e){}"
                                 > core-js-pure@3.13.0 postinstall /codebuild/output/src928945262/src/aory-website-react/node_modules/core-js-pure
                                 > node -e "try{require('./postinstall')}catch(e){}"
                                 > ejs@2.7.4 postinstall /codebuild/output/src928945262/src/aory-website-react/node_modules/ejs
                                 > node ./postinstall.js
2021-05-26T11:58:09.253Z [INFO]: Thank you for installing [35mEJS[0m: built with the [32mJake[0m JavaScript build tool ([32mhttps://jakejs.com/[0m)
2021-05-26T11:58:10.813Z [WARNING]: npm WARN
2021-05-26T11:58:10.813Z [WARNING]: optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
                                    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2021-05-26T11:58:10.820Z [WARNING]: npm
2021-05-26T11:58:10.820Z [WARNING]: WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
                                    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2021-05-26T11:58:10.827Z [WARNING]: npm
2021-05-26T11:58:10.828Z [WARNING]: WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
                                    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2021-05-26T11:58:10.828Z [WARNING]: 
2021-05-26T11:58:10.832Z [INFO]: added 1834 packages from 745 contributors and audited 1838 packages in 20.633s
2021-05-26T11:58:11.845Z [INFO]: 138 packages are looking for funding
                                 run `npm fund` for details
2021-05-26T11:58:11.846Z [INFO]: found 81 vulnerabilities (80 moderate, 1 high)
                                 run `npm audit fix` to fix them, or `npm audit` for details
2021-05-26T11:58:11.871Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
2021-05-26T11:58:11.871Z [INFO]: # Executing command: npm run build
2021-05-26T11:58:12.026Z [INFO]: > aory@0.1.0 build /codebuild/output/src928945262/src/aory-website-react
                                 > react-scripts build
2021-05-26T11:58:12.983Z [INFO]: Creating an optimized production build...
/bin:/root/.local/bin:/root/.local/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.dotnet/tools
                                 9 verbose lifecycle aory@0.1.0~build: CWD: /codebuild/output/src928945262/src/aory-website-react
                                 10 silly lifecycle aory@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
                                 11 silly lifecycle aory@0.1.0~build: Returned: code: 1  signal: null
                                 12 info lifecycle aory@0.1.0~build: Failed to exec build script
                                 13 verbose stack Error: aory@0.1.0 build: `react-scripts build`
                                 13 verbose stack Exit status 1
                                 13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
                                 13 verbose stack     at EventEmitter.emit (events.js:314:20)
                                 13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
                                 13 verbose stack     at ChildProcess.emit (events.js:314:20)
                                 13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
                                 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
                                 14 verbose pkgid aory@0.1.0
                                 15 verbose cwd /codebuild/output/src928945262/src/aory-website-react
                                 16 verbose Linux 4.14.225-121.362.amzn1.x86_64
                                 17 verbose argv "/root/.nvm/versions/node/v12.21.0/bin/node" "/root/.nvm/versions/node/v12.21.0/bin/npm" "run" "build"
                                 18 verbose node v12.21.0
                                 19 verbose npm  v6.14.11
                                 20 error code ELIFECYCLE
                                 21 error errno 1
                                 22 error aory@0.1.0 build: `react-scripts build`
                                 22 error Exit status 1
                                 23 error Failed at the aory@0.1.0 build script.
                                 23 error This is probably not a problem with npm. There is likely additional logging output above.
                                 24 verbose exit [ 1, true ]
2021-05-26T11:58:16.725Z [ERROR]: !!! Build failed
2021-05-26T11:58:16.726Z [ERROR]: !!! Non-Zero Exit Code detected
2021-05-26T11:58:16.726Z [INFO]: # Starting environment caching...
2021-05-26T11:58:16.726Z [INFO]: # Environment caching completed
Terminating logging...
```
