### ISSUE TITLE
Next js deploy error

### ISSUE THREAD

**Issue by sudarshann** [aws-amplify/amplify-console#1876]
Region=ap-south-1
Id=d3rx4fur1b76fm

```
2021-05-23T11:46:38.872Z [INFO]: Done in 24.98s.
2021-05-23T11:46:38.876Z [INFO]: Starting SSR Build...
2021-05-23T11:47:56.230Z [INFO]: AccessDenied 
```
I am trying to deploy a starter next js app which I just created and added amplify I get the above error. Everything else deployed perfectly. Even it built successfully. But I get the above error. I have followed all steps as per this https://aws.amazon.com/blogs/mobile/host-a-next-js-ssr-app-with-real-time-data-on-aws-amplify/

I have double checked the IAM role too its perfectly set up with full permission. I think its an issue with configuring cloudfront probably ?

Any clues ?

_Originally posted by @sudarshann in https://github.com/aws-amplify/amplify-console/issues/412#issuecomment-846551092_

**Comment by nimacks** [comment]
Hi @sudarshann, you mentioned that you have the IAM role setup. Can you confirm this is the service role. Also, how many CloudFront distributions  in your account have Lambda@Edge distributions attached. There is a limit documented here.
https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#troubleshooting-ssr-deployment

```
CloudFront service quotas limit your AWS account to 25 distributions with attached Lambda@Edge functions. If you exceed this quota, you can either delete any unused CloudFront distributions from your account or request a quota increase. For more information, see Requesting a quota increase in the Service Quotas User Guide.
```

**Comment by sudarshann** [comment]
I have no cloudfront services created across my entire account across all regions

**Comment by sunglee** [comment]
Any updates on this? I got the same message too.

```
2021-06-05T01:10:51.872Z [INFO]: Starting SSR Build...
2021-06-05T01:11:45.333Z [INFO]: AccessDenied
```

**Comment by JimLiu** [comment]
same error too

**Comment by zugger14** [comment]
i am facing the same issue my app id = d3dh32c6fp1s0y

**Comment by Athena96** [comment]
Hi all, we've recently made improvements to our SSR error logging and have added support for Next.js 10/11. 
Please follow this guide to upgrade to our latest support of Next.js: https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#update-app-nextjs-version

**Comment by zugger14** [comment]
hi @Athena96 i am still getting AccessDenied while starting my SSR Build..Can you please help me on this. my app id =d3dh32c6fp1s0y and region=eu-central-1.

**Comment by timclark97** [comment]
Any updates on this? I am running into this too.

**Comment by swaminator** [comment]
@timclark97 can you try this: https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md#error-accessdenied-access-denied

**Comment by timclark97** [comment]
@swaminator I changed the app to SSG so it is working now. Prior to doing that though, I followed [this tutorial](https://docs.aws.amazon.com/amplify/latest/userguide/how-to-service-role-amplify-console.html) to create an IAM role with the `AdministratorAccess-Amplify` policy, which I assume had all the permissions listed in that FAQ you shared. Does that policy not have all the necessary permissions?

**Comment by ferdingler** [comment]
@timclark97 the `AdministratorAccess-Amplify` policy is useful for creating your backend environments via the Amplify CLI. But with SSR apps we create a CloudFront distribution, an S3 bucket and Lambda@Edge functions in your account without using CloudFormation, which is why that policy doesn't work.

We are working on making this experience with IAM permissions and SSR apps smoother. In the meantime, I recommend to create your own policy with these permissions if you need to deploy an SSR app again: https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md#error-accessdenied-access-denied.

**Comment by kenchoong** [comment]
I using Nextjs SSR, but the deployment always failed, with Access Denied error 

1. I already create a new policy named: `Amplify-additional-policy` as below, which I follow this, literally copy and paste from here: https://github.com/aws-amplify/amplify-console/blob/main/FAQ.md#error-accessdenied-access-denied

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "lambda:CreateFunction",
                "iam:UpdateAssumeRolePolicy",
                "lambda:TagResource",
                "cloudfront:ListFieldLevelEncryptionConfigs",
                "iam:CreateRole",
                "s3:CreateBucket",
                "iam:AttachRolePolicy",
                "lambda:GetFunctionConfiguration",
                "iam:PutRolePolicy",
                "route53:ListHostedZonesByName",
                "cloudfront:CreateInvalidation",
                "lambda:EnableReplication",
                "cloudfront:GetDistribution",
                "acm:RequestCertificate",
                "route53:ListResourceRecordSets",
                "lambda:DeleteFunction",
                "cloudfront:GetDistributionConfig",
                "amplify:GetApp",
                "iam:GetRole",
                "cloudfront:TagResource",
                "route53:ChangeResourceRecordSets",
                "sqs:GetQueueAttributes",
                "lambda:UpdateFunctionCode",
                "s3:PutObject",
                "s3:GetObject",
                "acm:DescribeCertificate",
                "cloudfront:ListTagsForResource",
                "cloudfront:ListInvalidations",
                "lambda:ListEventSourceMappings",
                "sqs:DeleteQueue",
                "lambda:PublishVersion",
                "cloudfront:ListDistributionsByWebACLId",
                "cloudfront:ListCloudFrontOriginAccessIdentities",
                "s3:GetBucketTagging",
                "s3:PutAccelerateConfiguration",
                "s3:ListBucket",
                "s3:GetAccelerateConfiguration",
                "lambda:CreateEventSourceMapping",
                "lambda:UntagResource",
                "cloudfront:CreateCloudFrontOriginAccessIdentity",
                "amplify:GetBranch",
                "iam:PassRole",
                "lambda:ListTags",
                "s3:PutBucketTagging",
                "iam:DeleteRolePolicy",
                "acm:ListCertificates",
                "cloudfront:UpdateDistribution",
                "sqs:SetQueueAttributes",
                "amplify:UpdateApp",
                "cloudfront:UntagResource",
                "lambda:GetFunction",
                "cloudfront:ListDistributionsByLambdaFunction",
                "lambda:UpdateFunctionConfiguration",
                "amplify:UpdateBranch",
                "cloudfront:CreateDistribution",
                "cloudfront:ListPublicKeys",
                "iam:CreateServiceLinkedRole",
                "cloudfront:ListDistributions",
                "cloudfront:ListFieldLevelEncryptionProfiles",
                "s3:PutBucketPolicy",
                "sqs:CreateQueue",
                "cloudfront:ListStreamingDistributions"
            ],
            "Resource": "*"
        }
    ]
}

```

2. Then I attached this newly created policy into the role. So the role look like this: 

New Role Name: amplifyconsole-backend-role1
Attached policies: Amplify-additional-policy and also AdministratorAccess-Amplify

3. Build the stuff then get the following error 

```
2021-12-22T15:33:14.842Z [INFO]: Done in 97.04s.
2021-12-22T15:33:14.846Z [INFO]: Starting SSR Build...
2021-12-22T15:37:55.449Z [ERROR]: AccessDenied: Access Denied
                                  at Request.extractError (/root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/services/s3.js:699:35)
                                  at Request.callListeners (/root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                  at Request.emit (/root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                  at Request.emit (/root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/request.js:686:14)
                                  at Request.transition (/root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/request.js:22:10)
                                  at AcceptorStateMachine.runTo (/root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                  at /root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/state_machine.js:26:10
                                  at Request.<anonymous> (/root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/request.js:38:9)
                                  at Request.<anonymous> (/root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/request.js:688:12)
                                  at Request.callListeners (/root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                  at Request.emit (/root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                  at Request.emit (/root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/request.js:686:14)
                                  at Request.transition (/root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/request.js:22:10)
                                  at AcceptorStateMachine.runTo (/root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                  at /root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/state_machine.js:26:10
                                  at Request.<anonymous> (/root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/request.js:38:9)
                                  at Request.<anonymous> (/root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/request.js:688:12)
                                  at Request.callListeners (/root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                  at callNextListener (/root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
                                  at IncomingMessage.onEnd (/root/.//node_modules/@sls-next/aws-s3/node_modules/aws-sdk/lib/event_listeners.js:335:13)
                                  at IncomingMessage.emit (events.js:412:35)
                                  at IncomingMessage.emit (domain.js:475:12)
                                  at endReadableNT (internal/streams/readable.js:1334:12)
                                  at processTicksAndRejections (internal/process/task_queues.js:82:21) {
                                  code: 'AccessDenied',
                                  region: null,
                                  time: 2021-12-22T15:37:55.189Z,
                                  requestId: '7YG3Y9H22YZY92YZ',
                                  extendedRequestId: 'e61XrGC0bWdFvy7vBWuTZh+yQvKjcdi2aih58fKSrh3xG1t75R5CzV/XuZqomjv72CJUiVOAxqc=',
                                  cfId: undefined,
                                  statusCode: 403,
                                  retryable: false,
                                  retryDelay: 45.0836004027408
                                  }
Terminating logging...
```

My code is able to build in local and also the build logs shown my code is done being built. Just when deploy it keep ACCESS DENIED. I even add `AdministratorAccess` policy into the role, but still the same. 

The very funny part is, before this, I have deploy Nextjs endless of time using the same role, different project, all successfully deployed, but TODAY, it have this error, I dont know why. 

Can anybody tell me why it is still Access denied even though I already attached the policy stated here https://github.com/aws-amplify/amplify-console/blob/main/FAQ.md#error-accessdenied-access-denied? This is VERY PAINFUL, cause it happened suddenly

**Comment by kenchoong** [comment]
> @timclark97 can you try this: https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md#error-accessdenied-access-denied

Already try this sir, I even detached `AdministratorAccess` to the role, but still not success

**Comment by kenchoong** [comment]
I think found the root cause, which is this https://github.com/aws-amplify/amplify-console/issues/2086#issuecomment-932103935. 

The problem is my account cannot enable  Transfer Acceleration at all for ANY BUCKET. Even a newly created bucket in S3 console, also cannot enabled that, having the same ACCESS Denied error in S3 console. Therefore the SSR deployment always cannot deploy to CloudFront although the service role having `AdminstratorAccess`. 

So the question now is, where to get help to solve this? How to solve this? What should I do?

**Comment by kenchoong** [comment]
> I think found the root cause, which is this [#2086 (comment)](https://github.com/aws-amplify/amplify-console/issues/2086#issuecomment-932103935).
> 
> The problem is my account cannot enable Transfer Acceleration at all for ANY BUCKET. Even a newly created bucket in S3 console, also cannot enabled that, having the same ACCESS Denied error in S3 console. Therefore the SSR deployment always cannot deploy to CloudFront although the service role having `AdminstratorAccess`.
> 
> So the question now is, where to get help to solve this? How to solve this? What should I do? Can I disable the transfer acceleration thing?

Ok, for anyone who experience this, fastest way to solve this is:  **Deploy your app into a new AWS account**

**Comment by nenjamin2405** [comment]
I've just created my new AWS account and followed exactly what is suggested above with no luck. I use the recommended permissions and attached the new created policy to the role. Hi @ferdingler, could you please help us to check this issue?

**Comment by nallibtermatrac** [comment]
Same here. I followed every step in Amplify Studio.
When I deploy... permission denied.
<Code>AccessDenied</Code>
<Message>Access Denied</Message>

**Comment by GabrielOnike** [comment]
Same Issue; ACCESS DENIED during FrontEnd Stage build

**Comment by GabrielOnike** [comment]
> Same Issue; ACCESS DENIED during FrontEnd Stage build
If your build works locally but fails on Amplify, you probably need to try it on a new account. That was my final solution.
Sucks especially when you're hosting an app suite under one account. 
In my case i tried different policies and roles and also used the policy in the troubleshoot. Also; Tried changing the regions, Tried changing basedirectory, Tried Full Admin privileges for s3, tried to rework the transfer Acceleration but some things are not fully accessible for free Tier such as that and Support.  

I suspect that if one has another installation on the account such as a separate private VPS instance like LightSail or such, its rules might affect other installations on the same account. In that case, this is an internal problem. I had to escalate to support.

**Comment by GabrielOnike** [comment]
> Same Issue; ACCESS DENIED during FrontEnd Stage build

If your build works locally but fails on Amplify, you probably need to try it on a new account. That was my final solution.

Sucks especially when you're hosting an app suite under one account.
In my case i tried different policies and roles and also used the policy in the troubleshoot. Also, Tried changing the regions, Tried changing basedirectory, Tried Full Admin privileges for s3, tried to rework the transfer Acceleration but some things are not fully accessible for free Tier such as that and Support.

I suspect that if one has another installation on the account such as a separate private VPS instance like LightSail or such, its rules might affect other installations on the same account. In that case, this is an internal problem. I had to escalate to support.

**Comment by ferdingler** [comment]
Hi, this issue happens only for AWS accounts that were created recently, as it turns out that S3 transfer acceleration takes a while to be available for a new account to prevent abuse of the feature. While we figure out a solution, [please contact AWS Support](https://aws.amazon.com/contact-us) and ask them to enable S3 Transfer Acceleration for you.

**Comment by antoniogiordano** [comment]
I want to share my experience as well, since nothing worked for me until an AWS assistance guy helped me.
Basically I was using a different pair of AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in my .env file.
Since I was not setting them by the Amplify Console, they passed their checks (you cannot use AWS_ keys as env vars).
Since my pair of keys had only some specific permissions, these keys of mine were replacing the ones set by Amplify in order to deploy the application (because amplify environment to deploy and the nextjs app share it).
To fix I only had to rename my keys in my .env file to something else, and it worked as a charm!
I'm using node 14.18.1 and next 12.1.6 btw.
