### ISSUE TITLE
amplifyPush Script Error

### ISSUE THREAD

**Issue by sytolk** [aws-amplify/amplify-console#1930]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3orrkifxj956a

### Region

eu-central-1

### Amplify Console feature

Backend builds

### Describe the bug

aws-exports.js is not generated from amplifyPush.sh 

this is the error log:
```
 # Starting phase: build
                                 # Executing command: if [[ ! "with-tsLambdaLayer" =~ ^develop\/.* ]]; then amplifyPush -e dev -s; else amplifyPush -s; fi
2021-06-07T17:02:14.250Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2021-06-07T17:02:14.255Z [INFO]: # Start initializing Amplify environment: dev
2021-06-07T17:02:14.255Z [INFO]: # Initializing new Amplify environment: dev (amplify init)
2021-06-07T17:02:15.373Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2021-06-07T17:02:26.388Z [INFO]: init failed
2021-06-07T17:02:26.416Z [INFO]: Error: AWS access credentials can not be found.
                                 at newUserCheck (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/configuration-manager.js:567:15)
                                 at Object.init (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/configuration-manager.js:26:9)
                                 at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/initializer.js:17:30)
                                 at Object.init (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/index.js:22:22)
                                 at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/init-steps/s2-initProviders.ts:14:51
                                 at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
2021-06-07T17:02:26.416Z [HELP]: You do not have a role attached to your app
2021-06-07T17:02:27.330Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2021-06-07T17:02:30.827Z [INFO]: init failed
2021-06-07T17:02:30.855Z [INFO]: Error: AWS access credentials can not be found.
                                 at newUserCheck (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/configuration-manager.js:567:15)
                                 at Object.init (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/configuration-manager.js:26:9)
                                 at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/initializer.js:17:30)
                                 at Object.init (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/index.js:22:22)
                                 at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/init-steps/s2-initProviders.ts:14:51
                                 at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
2021-06-07T17:02:30.855Z [HELP]: You do not have a role attached to your app
2021-06-07T17:02:30.866Z [ERROR]: !!! Build failed
2021-06-07T17:02:30.866Z [ERROR]: !!! Non-Zero Exit Code detected
2021-06-07T17:02:30.866Z [INFO]: # Starting environment caching...
2021-06-07T17:02:30.867Z [INFO]: # Uploading environment cache artifact...
2021-06-07T17:02:30.941Z [INFO]: # Environment caching completed
```

### Expected behavior

aws-exports.js to be generated:
https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md#build-fails-with-cannot-find-module-aws-exports

### Reproduction steps

1. amplify add hosting -> with github Continuous deploys
2. set amplify.yml with amplifyPush script
3. git push 

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - if [[ ! "${AWS_BRANCH}" =~ ^develop\/.* ]]; then amplifyPush -e dev -s; else amplifyPush -s; fi
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run ts-clone
        - git clone https://$tagspaces_pro_user:$tagspaces_pro_pass@github.com/tagspaces/tagspacespro ./tagspaces/extensions/tagspacespro
        - yarn run build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /tagspaces/web
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by brnmye** [comment]
Hello It looks like the error is being caused by your app not being able to find your AWS access credentials, (i.e: Error: AWS access credentials can not be found.)

**Comment by sytolk** [comment]
Hi @brnmye 
The main goal is to generate aws-exports.js on AWS docker container where App build is running and I follow this doc: https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md#build-fails-with-cannot-find-module-aws-exports
If you know how to generate aws-exports.js on AWS without amplifyPush script let me know

**Comment by cslogan-red** [comment]
Hi @sytolk, in this particular case the exception being thrown was due to lack of an IAM role for Amplify Console to provision backend resources on your behalf, when starting with a frontend only repo that does not contain an `amplify` folder in it, the selection for a backend role is not displayed. You can [create and set one manually](https://docs.aws.amazon.com/amplify/latest/userguide/how-to-service-role-amplify-console.html) by selecting your app, going to App settings > General > Edit and selecting a backend service role.

Additionally, now available in you region is the functionality described [here](https://github.com/aws-amplify/amplify-console/issues/1966#issuecomment-862550502), your backend statement can be simplified to `amplifyPush --simple`, and Amplify Console will run a pull to generate the `aws-exports.js` file for you based on the backend environment associated with your branch, likewise you can edit your frontend branch(es) to point to different backend environment(s) via the Console as outlined [here](https://github.com/aws-amplify/amplify-console/issues/1966#issuecomment-862505677), the docs update that describes this enhancement should be available tomorrow.

**Comment by sytolk** [comment]
@cslogan-red I cant confirm that "backend environment associated with your branch" work. 
![EDDF800C-F5BF-4AAD-978C-40FC162E9FDD](https://user-images.githubusercontent.com/1415463/123383099-6a992280-d59b-11eb-8bab-0cf164b4660b.png)
I have try with `amplifyPush --simple` and new backend env was created with random name "lavinie". Next if I try to go back to my env "dev" associated with branch its have build exception: 
```
2021-06-25T06:47:50.660Z [INFO]: AlreadyExistsException: Stack [amplify-tsamplify-dev-94401] already exists
                                 at Request.extractError (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
                                 at Request.callListeners (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
                                 at Request.transition (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
                                 code: 'AlreadyExistsException',
                                 time: 2021-06-25T06:47:50.652Z,
                                 requestId: 'f8935813-ae75-4f5d-91c4-58a0842fd579',
                                 statusCode: 400,
                                 retryable: false,
                                 retryDelay: 23.36493022817645
                                 }
2021-06-25T06:47:50.671Z [ERROR]: !!! Build failed
```

**Comment by sytolk** [comment]
```
[                                 # Starting phase: build
                                 # Executing command: amplifyPush -s
2021-06-25T07:29:51.272Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2021-06-25T07:29:51.301Z [INFO]: # Start initializing Amplify environment: with-tsLam
2021-06-25T07:29:51.301Z [INFO]: # Initializing new Amplify environment: with-tsLam (amplify init)
2021-06-25T07:29:52.557Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2021-06-25T07:29:52.559Z [INFO]: Environment name must be between 2 and 10 characters, and lowercase only.
2021-06-25T07:29:52.565Z [INFO]: ? Enter a name for the environment (dev)
2021-06-25T07:29:52.566Z [INFO]: [41D
2021-06-25T07:29:52.566Z [INFO]: [41C
2021-06-25T07:29:52.570Z [INFO]: 
2021-06-25T07:29:53.523Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2021-06-25T07:29:53.524Z [INFO]: Environment name must be between 2 and 10 characters, and lowercase only.
2021-06-25T07:29:53.531Z [INFO]: ? Enter a name for the environment (dev)
2021-06-25T07:29:53.532Z [INFO]: [41D
2021-06-25T07:29:53.532Z [INFO]: [41C
2021-06-25T07:29:53.535Z [INFO]: 
2021-06-25T07:29:53.539Z [ERROR]: !!! Build failed
2021-06-25T07:29:53.539Z [ERROR]: !!! Non-Zero Exit Code detected
2021-06-25T07:29:53.540Z [INFO]: # Starting environment caching...
2021-06-25T07:29:53.540Z [INFO]: # Uploading environment cache artifact...
2021-06-25T07:29:53.641Z [INFO]: # Environment caching completed
Terminating logging...](url)
```

**Comment by cslogan-red** [comment]
> @cslogan-red I cant confirm that "backend environment associated with your branch" work.
> ![EDDF800C-F5BF-4AAD-978C-40FC162E9FDD](https://user-images.githubusercontent.com/1415463/123383099-6a992280-d59b-11eb-8bab-0cf164b4660b.png)
> I have try with `amplifyPush --simple` and new backend env was created with random name "lavinie". Next if I try to go back to my env "dev" associated with branch its have build exception:
> 
> ```
> 2021-06-25T06:47:50.660Z [INFO]: AlreadyExistsException: Stack [amplify-tsamplify-dev-94401] already exists
>                                  at Request.extractError (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
>                                  at Request.callListeners (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
>                                  at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
>                                  at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
>                                  at Request.transition (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
>                                  at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
>                                  at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
>                                  at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
>                                  at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)
>                                  at Request.callListeners (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
>                                  code: 'AlreadyExistsException',
>                                  time: 2021-06-25T06:47:50.652Z,
>                                  requestId: 'f8935813-ae75-4f5d-91c4-58a0842fd579',
>                                  statusCode: 400,
>                                  retryable: false,
>                                  retryDelay: 23.36493022817645
>                                  }
> 2021-06-25T06:47:50.671Z [ERROR]: !!! Build failed
> ```

@sytolk, uncheck the full-stack CI/CD box on this modal and hit Save, since you're reusing an existing backend, you only want this to run an `amplify pull` (box unchecked) so your frontend can still build, the `amplify pull && amplify init` (box checked) results in the `AlreadyExistsException`, likewise, make sure to change the command to exactly `amplifyPush --simple`, not the abbreviated `amplifyPush -s`, we only use `amplifyPush --simple` as a marker to insert the generated amplify commands the Console creates if your amplify.yml has a backend section, it's not actually executing a script and hasn't for a long time now. Our blog post and docs update explaining this release and these options has been pushed to 6/29, but will explain this functionality in detail.

**Comment by cslogan-red** [comment]
Our updated [docs](https://docs.aws.amazon.com/amplify/latest/userguide/amplify-config-autogeneration.html) and [blog post](https://aws.amazon.com/blogs/mobile/complete-guide-to-full-stack-ci-cd-workflows-with-aws-amplify/) have been published, for anyone's future reference.
