### ISSUE TITLE
Amplify build fails with no error given in console, both push initiated and manually

### ISSUE THREAD

**Issue by IcedNet** [aws-amplify/amplify-console#1989]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1tz522m96bzo6 

### Region

us-east-1

### Amplify Console feature

Backend builds

### Describe the bug

Push to the frontend initiates a Build, but the build fails in the Backend Stage with no errors evident in the console

### Expected behavior

Push, Build, Deploy

### Reproduction steps

push new code, wait for build 

### Build Settings

```yaml
version: 1
frontend:
  phases:
    # prebuild:
    #   commands: ["npm i"]
    build:
      commands:
        [
          'node --version',
          'npm install @quasar/cli',
          'npm install',
          'npm run build',
        ]
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /dist/spa
    files:
      - '**/*'
  cache:
    paths: []
```

## Backend environment association found
2021-06-23T12:58:55.112Z [INFO]: [0mAmplify AppID found: d1tz522m96bzo6. Amplify App name is: lifegoals[0m
2021-06-23T12:57:25.446Z [INFO]: Git SSH Key acquired
2021-06-23T12:57:25.522Z [INFO]: # Cloning repository: git@gitlab.com:arbormoon/um/lifegoals/mobile.git
2021-06-23T12:57:25.532Z [INFO]: Agent pid 134
2021-06-23T12:57:25.593Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2021-06-23T12:57:25.879Z [INFO]: Cloning into 'mobile'...
2021-06-23T12:57:26.247Z [INFO]: Warning: Permanently added the ECDSA host key for IP address '172.65.251.78' to the list of known hosts.
2021-06-23T12:57:36.848Z [INFO]: # Switching to commit: 3ce07e9a3dd576a0057e3f0cc3943d21835a1f26
2021-06-23T12:57:36.964Z [INFO]: # Retrieving cache...
2021-06-23T12:57:36.966Z [INFO]: Agent pid 147
2021-06-23T12:57:36.966Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2021-06-23T12:57:37.007Z [INFO]: Note: switching to '3ce07e9a3dd576a0057e3f0cc3943d21835a1f26'.
                                 You are in 'detached HEAD' state. You can look around, make experimental
                                 changes and commit them, and you can discard any commits you make in this
                                 state without impacting any branches by switching back to a branch.
                                 If you want to create a new branch to retain commits you create, you may
                                 do so (now or later) by using -c with the switch command. Example:
                                 git switch -c <new-branch-name>
                                 Or undo this operation with:
                                 git switch -
                                 Turn off this advice by setting config variable advice.detachedHead to false
                                 HEAD is now at 3ce07e9 added group for build sake
2021-06-23T12:57:37.013Z [INFO]: Successfully cleaned up Git credentials
2021-06-23T12:57:37.014Z [INFO]: # Checking for Git submodules at: /codebuild/output/src800996640/src/mobile/.gitmodules
2021-06-23T12:57:37.016Z [INFO]: # Extracting cache...
2021-06-23T12:57:37.023Z [INFO]: # Extraction completed
2021-06-23T12:57:37.024Z [INFO]: # Retrieving environment cache...
2021-06-23T12:57:37.080Z [INFO]: # Retrieved environment cache
2021-06-23T12:57:37.160Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: '4.51.1'
2021-06-23T12:57:42.526Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 4.29.4 to 4.51.1...
2021-06-23T12:58:34.146Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
                                 ## Checking for associated backend environment...
                                 ## Backend environment association found
2021-06-23T12:58:55.112Z [INFO]: [0mAmplify AppID found: d1tz522m96bzo6. Amplify App name is: lifegoals[0m

**Comment by IcedNet** [comment]
Above output is from the Git push build

This is the manual retry:

                                 ## Checking for associated backend environment...
                                 ## Backend environment association found
2021-06-23T13:39:05.433Z [INFO]: [0mAmplify AppID found: d1tz522m96bzo6. Amplify App name is:[0m
2021-06-23T13:39:05.487Z [INFO]: [0mBackend environment production found in Amplify Console app:[0m
2021-06-23T13:39:07.022Z [INFO]: App not deployed yet.
2021-06-23T13:39:07.215Z [INFO]: App not deployed yet.
2021-06-23T13:39:07.298Z [INFO]: [32m[39m
                                 [32mGraphQL schema compiled successfully.[39m
                                 [32mEdit your schema at /codebuild/output/src790323669/src/mobile/amplify/backend/api/dev/schema.graphql or place .graphql files in a directory at /codebuild/output/src790323669/src/mobile/amplify/backend/api/dev/schema[39m
2021-06-23T13:39:07.299Z [INFO]: App not deployed yet.
2021-06-23T13:39:07.371Z [INFO]: [0mSuccessfully generated models. Generated models can be found in /codebuild/output/src790323669/src/mobile/src[0m
2021-06-23T13:39:07.377Z [WARNING]: - Fetching updates to backend environment: production from the cloud.
2021-06-23T13:39:08.372Z [WARNING]: ✔ Successfully pulled backend environment production from the cloud.
2021-06-23T13:39:08.387Z [WARNING]: - Retrieving channel information for APNS.
2021-06-23T13:39:08.465Z [WARNING]: ✔ Channel information retrieved for APNS
2021-06-23T13:39:08.466Z [WARNING]: - Retrieving channel information for FCM.
2021-06-23T13:39:08.519Z [WARNING]: ✔ Channel information retrieved for FCM
2021-06-23T13:39:08.519Z [WARNING]: - Retrieving channel information for Email.

**Comment by IcedNet** [comment]
Well, I reverted to the default amplify package in the build settings (was using 4.51), and it finally threw errors back - now to sort out why the env isn't giving up my FCM key - maybe a newer version of CLI? 
fairly frustrating tool you guys are stuck maintaining.

                                 ## Checking for associated backend environment...
                                 ## Backend environment association found
2021-06-23T15:46:45.456Z [INFO]: 
2021-06-23T15:46:45.458Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html
2021-06-23T15:46:45.645Z [INFO]: Amplify AppID found: d1tz522m96bzo6. Amplify App name is: lifegoals
2021-06-23T15:46:45.694Z [INFO]: Backend environment production found in Amplify Console app: lifegoals
2021-06-23T15:46:46.562Z [INFO]: 
2021-06-23T15:46:46.566Z [WARNING]: - Fetching updates to backend environment: production from the cloud.
2021-06-23T15:46:47.527Z [WARNING]: ✔ Successfully pulled backend environment production from the cloud.
2021-06-23T15:46:47.566Z [WARNING]: - Retrieving channel information for APNS.
2021-06-23T15:46:47.635Z [WARNING]: ✔ Channel information retrieved for APNS
2021-06-23T15:46:47.636Z [WARNING]: - Retrieving channel information for FCM.
2021-06-23T15:46:47.689Z [WARNING]: ✔ Channel information retrieved for FCM
2021-06-23T15:46:47.689Z [WARNING]: - Retrieving channel information for Email.
2021-06-23T15:46:47.775Z [WARNING]: ✔ Channel is not setup for Email
2021-06-23T15:46:47.775Z [WARNING]: - Retrieving channel information for SMS.
2021-06-23T15:46:47.814Z [WARNING]: ✔ Channel is not setup for SMS
2021-06-23T15:46:47.852Z [WARNING]: - Updating FCM channel.
2021-06-23T15:46:47.854Z [WARNING]: ✖ update channel error
2021-06-23T15:46:47.854Z [WARNING]: ✖ There was an error initializing your environment.
2021-06-23T15:46:47.865Z [INFO]: Failed to pull the backend.
2021-06-23T15:46:47.872Z [INFO]: Missing required key 'ApiKey' in params.GCMChannelRequest
2021-06-23T15:46:47.872Z [INFO]: MissingRequiredParameter: Missing required key 'ApiKey' in params.GCMChannelRequest
                                 at ParamValidator.fail (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:50:37)
                                 at ParamValidator.validateStructure (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:61:14)
                                 at ParamValidator.validateMember (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:88:21)
                                 at ParamValidator.validateStructure (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:75:14)
                                 at ParamValidator.validateMember (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:88:21)
                                 at ParamValidator.validate (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/param_validator.js:34:10)
                                 at Request.VALIDATE_PARAMETERS (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:132:42)
                                 at Request.callListeners (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at callNextListener (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
                                 at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:86:9
2021-06-23T15:46:47.887Z [ERROR]: !!! Build failed
2021-06-23T15:46:47.888Z [ERROR]: !!! Non-Zero Exit Code detected
2021-06-23T15:46:47.888Z [INFO]: # Starting environment caching...
2021-06-23T15:46:47.888Z [INFO]: # Uploading environment cache artifact...
2021-06-23T15:46:47.975Z [INFO]: # Environment caching completed
Terminating logging...

**Comment by IcedNet** [comment]
amplify notifications update
choose to update FCM
re-enter key
commit json changes
push to repo
Build succeeds...
Well then.
Have a better day than I did, though the end is what counts!
