### ISSUE TITLE
Fail to deploy Gatsby without error message

### ISSUE THREAD

**Issue by alacret** [aws-amplify/amplify-console#2018]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d11sorihqky0fe

### Region

us-east-1

### Amplify Console feature

Backend builds

### Describe the bug

The console is failing to build the Gatsby project: https://github.com/cobuildlab/cobuildlab-web/

Sometimes the build fails with any message only: 

`[WARNING]: error Command failed with exit code 1.`

Some other times is:

```
2021-07-01T14:27:13.609Z [WARNING]: npm ERR!
2021-07-01T14:27:13.609Z [WARNING]: code ELIFECYCLE
2021-07-01T14:27:13.611Z [WARNING]: npm
2021-07-01T14:27:13.611Z [WARNING]: ERR! errno 1
2021-07-01T14:27:13.613Z [WARNING]: npm
2021-07-01T14:27:13.613Z [WARNING]: ERR! @cobuildlab/cobuildlab-web@1.0.0 build: `node ./node_modules/.bin/gatsby build`
                                    npm ERR! Exit status 1
                                    npm ERR!
                                    npm ERR! Failed at the @cobuildlab/cobuildlab-web@1.0.0 build script.
                                    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-07-01T14:27:13.660Z [WARNING]: 
2021-07-01T14:27:13.660Z [WARNING]: npm ERR! A complete log of this run can be found in:
                                    npm ERR!     /root/.npm/_logs/2021-07-01T14_27_13_614Z-debug.log
2021-07-01T14:27:13.660Z [HELP]: Outputting the npm debug log
                                 0 info it worked if it ends with ok
                                 1 verbose cli [
                                 1 verbose cli   '/root/.nvm/versions/node/v12.21.0/bin/node',
                                 1 verbose cli   '/root/.nvm/versions/node/v12.21.0/bin/npm',
                                 1 verbose cli   'run',
                                 1 verbose cli   'build'
                                 1 verbose cli ]
                                 2 info using npm@6.14.11
                                 3 info using node@v12.21.0
                                 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
                                 5 info lifecycle @cobuildlab/cobuildlab-web@1.0.0~prebuild: @cobuildlab/cobuildlab-web@1.0.0
                                 6 info lifecycle @cobuildlab/cobuildlab-web@1.0.0~build: @cobuildlab/cobuildlab-web@1.0.0
                                 7 verbose lifecycle @cobuildlab/cobuildlab-web@1.0.0~build: unsafe-perm in lifecycle true
                                 8 verbose lifecycle @cobuildlab/cobuildlab-web@1.0.0~build: PATH: /root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/codebuild/output/src337115232/src/cobuildlab-web/node_modules/.bin:/usr/local/rvm/gems/ruby-2.4.6/bin:/usr/local/rvm/gems/ruby-2.4.6@global/bin:/usr/local/rvm/rubies/ruby-2.4.6/bin:/usr/local/rvm/bin:/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:/root/.nvm/versions/node/v12.21.0/bin:/root/.local/bin:/root/.local/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.dotnet/tools
                                 9 verbose lifecycle @cobuildlab/cobuildlab-web@1.0.0~build: CWD: /codebuild/output/src337115232/src/cobuildlab-web
                                 10 silly lifecycle @cobuildlab/cobuildlab-web@1.0.0~build: Args: [ '-c', 'node ./node_modules/.bin/gatsby build' ]
                                 11 silly lifecycle @cobuildlab/cobuildlab-web@1.0.0~build: Returned: code: 1  signal: null
                                 12 info lifecycle @cobuildlab/cobuildlab-web@1.0.0~build: Failed to exec build script
                                 13 verbose stack Error: @cobuildlab/cobuildlab-web@1.0.0 build: `node ./node_modules/.bin/gatsby build`
                                 13 verbose stack Exit status 1
                                 13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
                                 13 verbose stack     at EventEmitter.emit (events.js:314:20)
                                 13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
                                 13 verbose stack     at ChildProcess.emit (events.js:314:20)
                                 13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
                                 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
                                 14 verbose pkgid @cobuildlab/cobuildlab-web@1.0.0
                                 15 verbose cwd /codebuild/output/src337115232/src/cobuildlab-web
                                 16 verbose Linux 4.14.225-121.362.amzn1.x86_64
                                 17 verbose argv "/root/.nvm/versions/node/v12.21.0/bin/node" "/root/.nvm/versions/node/v12.21.0/bin/npm" "run" "build"
                                 18 verbose node v12.21.0
                                 19 verbose npm  v6.14.11
                                 20 error code ELIFECYCLE
                                 21 error errno 1
                                 22 error @cobuildlab/cobuildlab-web@1.0.0 build: `node ./node_modules/.bin/gatsby build`
                                 22 error Exit status 1
                                 23 error Failed at the @cobuildlab/cobuildlab-web@1.0.0 build script.
                                 23 error This is probably not a problem with npm. There is likely additional logging output above.
                                 24 verbose exit [ 1, true ]
2021-07-01T14:27:13.663Z [ERROR]: !!! Build failed
2021-07-01T14:27:13.663Z [ERROR]: !!! Non-Zero Exit Code detected
2021-07-01T14:27:13.663Z [INFO]: # Starting environment caching...
2021-07-01T14:27:13.663Z [INFO]: # Environment caching completed
```

- I've tried to change the NODE version to 14, also tried to change the Gatsby version without any luck. 
- The Gatsby version that is in the package.json was the only version that it was working with the console.

### Expected behavior

Build normally, or throw an error

### Reproduction steps

1. Push master or main branch as they are

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        #- printenv > .env.production
        - nvm use 12
        - npm install
    build:
      commands:
        #- printenv > .env.production
        - nvm use 12
        - npm run build
        # - GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true gatsby build --log-pages
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
#   cache:
#     paths:
#       - node_modules/**/*
#       - public/**/*
#       - .cache/**/*
```

**Comment by multibdoyle** [comment]
It looks like the issue is at npm ERR! Failed at the @cobuildlab/cobuildlab-web@1.0.0 build script. 

I have a similar issue where I'm getting a non-zero exit code error, I'm not sure why though.

**Comment by Jay2113** [comment]
Hi @alacret and @multibdoyle 👋 , thanks for your continued patience and we apologize for the delayed response on this thread.

It seems that the Amplify app `d11sorihqky0fe` has been deleted and thus we wont be able to review the build logs for it from our end. @multibdoyle has correctly pointed out at a potential root cause for the build failure: 
```
npm ERR! Failed at the @cobuildlab/cobuildlab-web@1.0.0
``` 

Our recommendation would be to build your application locally via `npm run build` to see if a similar error is observed locally too. 

I am going to close this thread but please feel free to open a new GitHub issue if you are experiencing any issues with Amplify Hosting. Thanks!
