### ISSUE TITLE
Creating a backend via the console and importing Auth from Cognito causes "auth headless is missing the following inputParams" when running "amplify pull"

### ISSUE THREAD

**Issue by eddiekeller** [aws-amplify/amplify-console#2040]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3cbhlqhrq2d8

### Region

us-east-1

### Amplify Console feature

Backend builds

### Describe the bug

1. I logged into the AWS console and went to the AWS Amplify console.
2. I created a new backend and then opened up the Amplify Admin UI for that created backend.
3. I added Authentication by importing from Cognito. No errors came up during the import. I see the details (user pool id, web client id, native client id, etc.) correctly in the Admin UI.
4. When I try to pull down the app locally via the CLI, I get the following error --

```
✖ There was an error initializing your environment.
Failed to pull the backend.
auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId
Error: auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId
```

Full log from when I run the command --

```
➜  auth-with-totp-mfa git:(main) ✗ amplify pull --appId d3cbhlqhrq2d8 --envName staging --yes
Opening link: https://us-east-1.admin.amplifyapp.com/admin/d3cbhlqhrq2d8/staging/verify/
✔ Successfully received Amplify Admin tokens.
Amplify AppID found: d3cbhlqhrq2d8. Amplify App name is: auth-with-totp-mfa
Backend environment staging found in Amplify Console app: auth-with-totp-mfa
✔ Successfully pulled backend environment staging from the cloud.
✖ There was an error initializing your environment.
Failed to pull the backend.
auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId
Error: auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId
    at ensureHeadlessParameters (/Users/keledwin/.nvm/versions/node/v14.16.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1269:11)
    at Object.headlessImport (/Users/keledwin/.nvm/versions/node/v14.16.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1126:40)
    at importedAuthEnvInit (/Users/keledwin/.nvm/versions/node/v14.16.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:903:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at updateConfigOnEnvInit (/Users/keledwin/.nvm/versions/node/v14.16.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/index.js:50:72)
    at /Users/keledwin/.nvm/versions/node/v14.16.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/index.js:306:22
```

### Expected behavior

It should not produce an error. If everything looks correct and can be "built" inside the Admin UI without issue, then pulling it down should not produce an error at all.

### Reproduction steps

Reproduction steps mentioned in the bug description ^^

**Comment by eddiekeller** [comment]
Also - while the Authentication configuration shows correctly the in Amplify Admin UI, it does *not* show correctly in the AWS Amplify Console. When I click on the dropdown for my `staging` backend environment and choose "View details", the `Overview` shows that the `Authentication` category has been added. However, if I click on the `Authentication` tab to see the details of the category, it does not show anything and instead gives me instructions to run `amplify add auth` via the cli.

But! When I look at the network requests, I see a call to `s3` that is fetching the `Authentication` details for the Amplify app, and it *does* correctly get the Cognito configuration, including the `UserPoolId`, `AppClientID`, and `AppClientIDWeb`.

So it looks like somewhere...someone's wires are getting crossed and not detecting these clearly present and existing values.

**Comment by eddiekeller** [comment]
Workaround - was able to weirdly get past this issue by setting some environment variables on the command line for each of the missing values and then omitting the `--yes` flag from the `amplify pull` command. But this behavior is clearly still buggy.

**Comment by thevangelist** [comment]
Hope to see this fixed. I am facing this issue.
