### ISSUE TITLE
Electron builds failing while connecting Electron app to Github branch

### ISSUE THREAD

**Issue by amey91** [aws-amplify/amplify-console#210]
**Describe the bug**
This is possibly due to a missing dependency in the kernel used by Amplify as detailed below.
While trying to build my Electron app on Amplify, the build keeps failing with this error:

```
2019-10-24T01:22:19.228Z [WARNING]: ERROR  Error: Exit code: 1. Command failed: /root/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/fpm -s dir -t deb --architecture amd64 --name My-ProjectXYZ --force --after-install /tmp/t-UlNNvQ/0-after-install --after-remove /tmp/t-UlNNvQ/1-after-remove --description
                                    project --version 0.1.0 --package /codebuild/output/src813289574/src/DataModeler/dist_electron/project-linux-amd64-0.1.0.deb --maintainer a@a.com --url someUrl --vendor someVendor --deb-compression xz --depends gconf2 --depends gconf-service --depends libnotify4 --depends libappindicator1 --depends libxtst6 --depends libnss3 --depends libxss1 /codebuild/output/src813289574/src/DataModeler/dist_electron/linux-unpacked/=/opt/My-ProjectXYZ /codebuild/output/src813289574/src/DataModeler/dist_electron/.icon-set/icon_16x16.png=/usr/share/icons/hicolor/16x16/apps/my-projectxyz.png /codebuild/output/src813289574/src/DataModeler/dist_electron/.icon-set/icon_24x24.png=/usr/share/icons/hicolor/24x24/apps/my-projectxyz.png /codebuild/output/src813289574/src/DataModeler/dist_electron/.icon-set/icon_32.png=/usr/share/icons/hicolor/32x32/apps/my-projectxyz.png /codebuild/output/src813289574/src/DataModeler/dist_electron/.icon-set/icon_48x48.png=/usr/share/icons/hicolor/48x48/apps/my-projectxyz.png /codebuild/output/src813289574/src/DataModeler/dist_electron/.icon-set/icon_64.png=/usr/share/icons/hicolor/64x64/apps/my-projectxyz.png /codebuild/output/src813289574/src/DataModeler/dist_electron/.icon-set/icon_96x96.png=/usr/share/icons/hicolor/96x96/apps/my-projectxyz.png /codebuild/output/src813289574/src/DataModeler/dist_electron/.icon-set/icon_128.png=/usr/share/icons/hicolor/128x128/apps/my-projectxyz.png /codebuild/output/src813289574/src/DataModeler/dist_electron/.icon-set/icon_256.png=/usr/share/icons/hicolor/256x256/apps/my-projectxyz.png /codebuild/output/src813289574/src/DataModeler/dist_electron/.icon-set/icon_512.png=/usr/share/icons/hicolor/512x512/apps/my-projectxyz.png /codebuild/output/src813289574/src/DataModeler/dist_electron/.icon-set/icon_1024.png=/usr/share/icons/hicolor/1024x1024/apps/my-projectxyz.png /tmp/t-UlNNvQ/2-My-ProjectXYZ.desktop=/usr/share/applications/my-projectxyz.desktop

                                    {:timestamp=>"2019-10-24T01:22:18.823102+0000", :message=>"Debian tools (dpkg/apt) don't do well with packages that use capital letters in the name. In some cases it will automatically downcase them, in others it will not. It is confusing. Best to not use any capital letters at all. I have downcased the package name for you just to be safe.", :oldname=>"My-ProjectXYZ", :fixedname=>"my-projectxyz", :level=>:warn}
                                    {:timestamp=>"2019-10-24T01:22:18.828348+0000", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:warn}
                                    {:timestamp=>"2019-10-24T01:22:19.183583+0000", :message=>"Process failed: tar failed (exit code 13). Full command was:[\"tar\", \"-C\", \"/tmp/package-dir-staging-e6f7264a9df04a653175038de79a72d8ce8dc8efaca10aa0ced9dd138bcd\", \"-I'/codebuild/output/src813289574/src/DataModeler/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-bin/linux/x64/app-builder'\", \"--numeric-owner\", \"--owner\", \"0\", \"--numeric-owner\", \"--group\", \"0\", \"-cf\", \"/tmp/package-deb-build-7bdfab0720c34cada40b273d963666eab5be332891d967e1cccc2cf89dcb/data.tar.xz\", \".\"]", :level=>:error}
                                    at /codebuild/output/src813289574/src/DataModeler/node_modules/vue-cli-plugin-electron-builder/node_modules/builder-util/src/util.ts:126:16
                                    at ChildProcess.exithandler (child_process.js:301:5)
                                    at ChildProcess.emit (events.js:198:13)
                                    at ChildProcess.EventEmitter.emit (domain.js:448:20)
                                    at maybeClose (internal/child_process.js:982:16)
                                    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
                                    From previous event:
                                    at FpmTarget.build (/codebuild/output/src813289574/src/DataModeler/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/targets/fpm.ts:93:44)
                                    at /codebuild/output/src813289574/src/DataModeler/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:131:24
                                    From previous event:
                                    at AsyncTaskManager.add (/codebuild/output/src813289574/src/DataModeler/node_modules/vue-cli-plugin-electron-builder/node_modules/builder-util/src/asyncTaskManager.ts:14:20)
                                    at LinuxPackager.packageInDistributableFormat (/codebuild/output/src813289574/src/DataModeler/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:123:17)
                                    at /codebuild/output/src813289574/src/DataModeler/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:114:10
                                    at Generator.next (<anonymous>)
                                    at runCallback (timers.js:705:18)
                                    at tryOnImmediate (timers.js:676:5)
                                    at processImmediate (timers.js:658:5)
                                    at process.topLevelDomainCallback (domain.js:126:23)
                                    From previous event:
                                    at LinuxPackager.pack (/codebuild/output/src813289574/src/DataModeler/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
                                    at /codebuild/output/src813289574/src/DataModeler/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/packager.ts:430:24
                                    at Generator.next (<anonymous>)
                                    at xfs.stat (/codebuild/output/src813289574/src/DataModeler/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
                                    at callback (/codebuild/output/src813289574/src/DataModeler/node_modules/graceful-fs/polyfills.js:295:20)
                                    at FSReqWrap.oncomplete (fs.js:154:5)
                                    From previous event:
                                    at Packager.doBuild (/codebuild/output/src813289574/src/DataModeler/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/packager.ts:396:24)
                                    at /codebuild/output/src813289574/src/DataModeler/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/packager.ts:366:57
                                    From previous event:
                                    at Packager._build (/codebuild/output/src813289574/src/DataModeler/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/packager.ts:335:133)
                                    at /codebuild/output/src813289574/src/DataModeler/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/packager.ts:331:23
                                    at Generator.next (<anonymous>)
                                    at runCallback (timers.js:705:18)
                                    at tryOnImmediate (timers.js:676:5)
                                    at processImmediate (timers.js:658:5)
                                    at process.topLevelDomainCallback (domain.js:126:23)
                                    From previous event:
                                    at Packager.build (/codebuild/output/src813289574/src/DataModeler/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/packager.ts:288:14)
                                    at build (/codebuild/output/src813289574/src/DataModeler/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/src/index.ts:59:28)
                                    at Object.build (/codebuild/output/src813289574/src/DataModeler/node_modules/vue-cli-plugin-electron-builder/node_modules/electron-builder/src/builder.ts:228:10)
                                    at buildApp (/codebuild/output/src813289574/src/DataModeler/node_modules/vue-cli-plugin-electron-builder/index.js:205:14)
                                    at bundle.run (/codebuild/output/src813289574/src/DataModeler/node_modules/vue-cli-plugin-electron-builder/index.js:187:15)
                                    at finalCallback (/codebuild/output/src813289574/src/DataModeler/node_modules/webpack/lib/Compiler.js:214:39)
                                    at hooks.done.callAsync.err (/codebuild/output/src813289574/src/DataModeler/node_modules/webpack/lib/Compiler.js:263:14)
                                    at AsyncSeriesHook.eval [as callAsync] (eval at create (/codebuild/output/src813289574/src/DataModeler/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
                                    at AsyncSeriesHook.lazyCompileHook (/codebuild/output/src813289574/src/DataModeler/node_modules/tapable/lib/Hook.js:154:20)
                                    at emitRecords.err (/codebuild/output/src813289574/src/DataModeler/node_modules/webpack/lib/Compiler.js:261:22)
                                    at Compiler.emitRecords (/codebuild/output/src813289574/src/DataModeler/node_modules/webpack/lib/Compiler.js:375:39)
                                    at emitAssets.err (/codebuild/output/src813289574/src/DataModeler/node_modules/webpack/lib/Compiler.js:255:10)
                                    at hooks.afterEmit.callAsync.err (/codebuild/output/src813289574/src/DataModeler/node_modules/webpack/lib/Compiler.js:361:14)
                                    at AsyncSeriesHook.eval [as callAsync] (eval at create (/codebuild/output/src813289574/src/DataModeler/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
                                    at AsyncSeriesHook.lazyCompileHook (/codebuild/output/src813289574/src/DataModeler/node_modules/tapable/lib/Hook.js:154:20)
                                    at asyncLib.forEach.err (/codebuild/output/src813289574/src/DataModeler/node_modules/webpack/lib/Compiler.js:358:27)
                                    at /codebuild/output/src813289574/src/DataModeler/node_modules/neo-async/async.js:2830:7
                                    at done (/codebuild/output/src813289574/src/DataModeler/node_modules/neo-async/async.js:2865:11)
                                    at /codebuild/output/src813289574/src/DataModeler/node_modules/neo-async/async.js:2818:7
                                    at /codebuild/output/src813289574/src/DataModeler/node_modules/graceful-fs/graceful-fs.js:45:10
                                    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
2019-10-24T01:22:19.303Z [WARNING]: npm ERR! code ELIFECYCLE
                                    npm ERR! errno 1
                                    npm ERR! app@0.1.0 electron:build: `vue-cli-service electron:build`
                                    npm ERR! Exit status 1

```

**To Reproduce**
1. You will have to build the app on your infrastructure

**Expected behavior**
The build should succeed.

**Additional context**
A similar problem has been reported and solved here: https://github.com/electron-userland/electron-builder/issues/309

*The solution probably is to install xz compression utility on the machines that run this command.*

**Comment by anatonie** [comment]
Hi @amey91 

You are correct, xz is not installed on our build image at this time.
You can install it by adding **yum install -y xz** into your build commands. You can do the same for any other dependencies that are missing to build your Electron app!

Thanks

**Comment by amey91** [comment]
I tried doing that but still the build fails at the same command

```
                                    {:timestamp=>"2019-11-08T21:23:53.797452+0000", :message=>"Process failed: tar failed (exit code 13). Full command was:[\"tar\", \"-C\", \"/tmp/package-dir-staging-be3c2b4fe381908644d57d48ccf5403c71b50aebf372b5957cbc0a8e04e4\", \"-I'/codebuild/output/src055252908/src/DataModeler/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-bin/linux/x64/app-builder'\", \"--numeric-owner\", \"--owner\", \"0\", \"--numeric-owner\", \"--group\", \"0\", \"-cf\", \"/tmp/package-deb-build-b86208f561d0507cdd2b3603049f7be0ef19e6fb91392368470c7d0d9041/data.tar.xz\", \".\"]", :level=>:error}

```

**Comment by swaminator** [comment]
We currently do not have plans to support Electron app builds in the Console. Closing this issue as won't fix.

**Comment by amey91** [comment]
Are there any timelines for Electron support?

**Comment by icemioi** [comment]
how can you  solve this problems？ @amey91
