### ISSUE TITLE
Amplify Stack Push cannot update my stack anymore, fail on resources not even being updated

### ISSUE THREAD

**Issue by dcfranca** [aws-amplify/amplify-console#2106]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dr30qdghmfhdu

### Region

us-east-1

### Amplify Console feature

Backend builds

### Describe the bug

I have opened this bug a while ago: https://github.com/aws-amplify/amplify-console/issues/1469
For some divine mystery it was closed without anyone ever addressing my issue, and now I'm facing a much worse situation

As you can see on my original bug report, that report was making all my deployments through the Amplify CI/CD to fail on a specific function, even if I don't touch this  function... it loses its dependencies

To fix, this I had to always manually push the backend from my local client (amplify push) with some small change on the function (ie: increment a variable)

However, now what is happening is that I'm unable to make it work
All my attempts to push are failing now, and I have my application with limited features due to this function being in a bad state

Every time I run `amplify push` I get the following errors:

> UPDATE_FAILED               HostedUIProvidersCustomResourceInputs               Custom::LambdaCallout      Wed Jul 28 2021 20:26:41 GMT+0200 (Central European Summer Time) Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2021/07/28/[$LATEST]8bec139d4824430c8718ef3e9f725370 (RequestId: 6f759a93-d797-4a79-853a-4de43e5dd453)

> UPDATE_FAILED authlexis AWS::CloudFormation::Stack Wed Jul 28 2021 20:26:50 GMT+0200 (Central European Summer Time) Embedded stack arn:aws:cloudformation:us-east-1:679504623344:stack/amplify-lexis-staging-112559-authlexis-QLWRGJ5SZGMO/45458600-9b4e-11ea-a51d-1271b8f35690 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [HostedUIProvidersCustomResourceInputs].

> UPDATE_FAILED               functionThumbnailsGenerator  AWS::CloudFormation::Stack Wed Jul 28 2021 20:27:02 GMT+0200 (Central European Summer Time) Resource update cancelled

If I check my stack, there is nothing in progress like it said there, and I can't find this log stream on the log groups

It seems to be related to this layer that I have introduced some time ago, then I have tried to remove it, but I can't remove it... there was only one function using it, I have remove it from there, but every time I try to remove the layer it says there is this function yet using it

I have tried adding/removing it, but now I get this error every time I try to remove the layer
```

Cannot read property 'filter' of undefined
TypeError: Cannot read property 'filter' of undefined
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts:248:33
    at Array.filter (<anonymous>)
    at Object.getLambdaFunctionsDependentOnLayerFromMeta (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/layerHelpers.ts:245:45)
    at Object.removeWalkthrough (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/service-walkthroughs/removeLayerWalkthrough.ts:25:43)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/commands/function/remove.ts:30:29)
    at Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/index.ts:248:3)
    at executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:177:3)
    at Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:29:5)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/src/index.ts:151:5)
```

Now I have an application without some of its most important features, and I can't push my backend manually to fix it

I have also tried running `amplify pull -restore`, then just updating the variable increment on my function... still fails

I'm out of ideas what else to try

PLEASE DON'T CLOSE THIS ISSUE BEFORE IT IS SOLVED, IT IS EXTREMELY IMPORTANT

### Expected behavior

The amplify push should finish without any issues

### Reproduction steps

Update the lambda function in order to push the changes
push the changes with `amplify push`

EDIT: I have ran again pull --restore, and then changing the single file, but now I get this error:

> UPDATE_FAILED      authlexis                    AWS::CloudFormation::Stack Wed Jul 28 2021 20:55:35 GMT+0200 (Central European Summer Time) Parameters: [breakCircularDependency] must have values

> UPDATE_FAILED functiondownloadDocx AWS::CloudFormation::Stack Wed Jul 28 2021 20:55:46 GMT+0200 (Central European Summer Time) Resource update cancelled
> ⠇ Updating resources in the cloud. This may take a few minutes...
> 

> UPDATE_FAILED               functionThumbnailsGenerator  AWS::CloudFormation::Stack Wed Jul 28 2021 20:55:46 GMT+0200 (Central European Summer Time) Resource update cancelled

I found out that this `breakCircularDependency` is a [feature flag](https://docs.amplify.aws/cli/reference/feature-flags#breakCircularDependency)
It says to add it on the cli.json... I didn't have this file on my amplify folder, so I have created it with the example values:
```

{
  "features": {
    "graphQLTransformer": {
      "addMissingOwnerFields": true,
      "validateTypeNameReservedWords": true,
      "useExperimentalPipelinedTransformer": false,
      "enableIterativeGSIUpdates": false
    },
    "frontend-ios": {
      "enableXcodeIntegration": true
    },
    "auth": {
      "enableCaseInsensitivity": true,
      "useInclusiveTerminology": true,
      "breakCircularDependency": true
    },
    "codegen": {
      "useAppSyncModelgenPlugin": true
    }
  }
}
```

Then ran `amplify push` again... same error

**Comment by dcfranca** [comment]
amplify --version
5.2.0

**Comment by dcfranca** [comment]
I'll open it on amplify-cli as it is more related
