### ISSUE TITLE
Build failure after importing existing DynamoDB tables: "storage headless is missing the following inputParams tables, region"

### ISSUE THREAD

**Issue by reedshea** [aws-amplify/amplify-console#2150]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d27icsr3ctg4rb

### Region

us-east-1

### Amplify Console feature

Backend builds, Build settings, Environment variables

### Describe the bug

After importing several existing DynamoDB tables via `amplify import storage`, I attempted to push my changes & rebuild. The build failed with an error, "storage headless is missing the following inputParams tables, region"

        2021-08-11T02:52:32.424Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
        2021-08-11T02:52:32.915Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
        2021-08-11T02:52:32.969Z [WARNING]: ✖ There was an error initializing your environment.
        2021-08-11T02:52:32.976Z [INFO]: [31mFailed to pull the backend.[39m
        2021-08-11T02:52:32.977Z [INFO]: [31mstorage headless is missing the following inputParams tables, region[39m
        2021-08-11T02:52:32.981Z [INFO]: [0mError: storage headless is missing the following inputParams tables, region[0m
                                         [0m    at ensureHeadlessParameters (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/provider-utils/awscloudformation/import/import-dynamodb.ts:439:11)[0m
                                         [0m    at headlessImport (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/provider-utils/awscloudformation/import/import-dynamodb.ts:387:40)[0m
                                         [0m    at importedDynamoDBEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/provider-utils/awscloudformation/import/import-dynamodb.ts:277:18)[0m
                                         [0m    at runMicrotasks (<anonymous>)[0m
                                         [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                         [0m    at updateConfigOnEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/provider-utils/awscloudformation/index.js:84:72)[0m
                                         [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-storage/src/index.js:150:22[0m
        2021-08-11T02:52:32.998Z [ERROR]: !!! Build failed

This seems to be similar or identical to #1359, although in this case I imported DynamoDB tables rather than S3 storage. The guidance in that issue led to an Amplify documentation page that discussed environment variables, but I've been unable to find specifics about the "tables" and "region" parameters or environment variables that are necessary. Adding an environment variable of `AMPLIFY_STORAGE_REGION = 'us-east-1'` via the Amplify UI and rebuilding did not change the build failure.

### Expected behavior

After following the Amplify CLI steps to import storage, I expect the application to build successfully (and for the DynamoDB table to be more readily available for reading & writing from a Lambda function).

### Reproduction steps

See description above.

### Additional information

Thank you for any guidance - it is very possible that I overlooked something or took a wrong turn somewhere.

**Comment by amandarose42** [comment]
I had this same issue, adding table && region env variables fixed it. 

reference: https://github.com/aws-amplify/amplify-console/issues/1544#issuecomment-833691049

**Comment by reedshea** [comment]
Oh, that's so helpful - thank you! That comment with the environment variables & format worked great. I'm curious whether `amplify import storage` works in some cases but not others. I'll close this issue in favor of #1544.
