### ISSUE TITLE
[INFO]: Starting SSR Build...  [ERROR]: AccessDenied: Access Denied

### ISSUE THREAD

**Issue by Dovalization** [aws-amplify/amplify-console#2212]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d19yd7pp02iva7

### Region

us-east-1

### Describe the bug

Just as a proof of sanity, I've tried this across various next versions, different projects, even boilerplate code refuses to build.

I've checked and the bucket has no blocking policies, and the IAM role responsible has the proper previleges.
I have no idea how to get this working, I need it to be SSR in order to supporte Image Optimization and ISR.

2021-08-30T04:10:46.999Z [INFO]: Done in 16.75s.
2021-08-30T04:10:47.006Z [INFO]: Starting SSR Build...
2021-08-30T04:11:46.634Z [ERROR]: AccessDenied: Access Denied
                                  at Request.extractError (/root/.//node_modules/aws-sdk/lib/services/s3.js:714:35)
                                  at Request.callListeners (/root/.//node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                  at Request.emit (/root/.//node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                  at Request.emit (/root/.//node_modules/aws-sdk/lib/request.js:688:14)
                                  at Request.transition (/root/.//node_modules/aws-sdk/lib/request.js:22:10)
                                  at AcceptorStateMachine.runTo (/root/.//node_modules/aws-sdk/lib/state_machine.js:14:12)
                                  at /root/.//node_modules/aws-sdk/lib/state_machine.js:26:10
                                  at Request.<anonymous> (/root/.//node_modules/aws-sdk/lib/request.js:38:9)
                                  at Request.<anonymous> (/root/.//node_modules/aws-sdk/lib/request.js:690:12)
                                  at Request.callListeners (/root/.//node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
                                  code: 'AccessDenied',
                                  region: null,
                                  time: 2021-08-30T04:11:46.581Z,
                                  requestId: 'PRJBW28GMH7C21PS',
                                  extendedRequestId: '6hqsbCi3RWa1EVr2Wfp5uOoOVaoDfv9UHvnGIjiqMTpKkvmGemwcwgU6vppKU33Gzk0ZErqTHbA=',
                                  cfId: undefined,
                                  statusCode: 403,
                                  retryable: false,
                                  retryDelay: 82.1077914203651
                                  }
Terminating logging...

### Expected behavior

SSR Build Success

### Reproduction steps

This  is consistently happening with any NextJs App I try to use from my repos.

### Build Settings

```yaml
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by ferdingler** [comment]
Hi @Dovalization, thank you for reaching out. 

I see that you currently have specified support for NextJs v9 in your Amplify App settings. However, your project is using NextJs v10 and I also see that you want to leverage Image Optimization and ISR. Can you please update your settings to use either `v10` or `latest` and try again? I suspect the access denied you are seeing is related to this misconfiguration of the versions. 

Please update us when you have more information. I will leave the ticket open.

**Comment by Dovalization** [comment]
I feel like this issue can be closed, as I eventually gave up and deleted my aws account and created a new one, which worked and Next was deployed pretty much automatically without any issues.
