### ISSUE TITLE
Always get a auto-build failure after a git commit

### ISSUE THREAD

**Issue by yhvh009** [aws-amplify/amplify-console#2220]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dvmxne0bgmgzv

### Region

us-east-2

### Amplify Console feature

Backend builds

### Describe the bug

I usually update some code on local and run 'amplify push' to push to the server, and get successful.
And then, I commit the code to git, and the console start auto-build after git commit
And It ends with 
```
Error [ValidationError]: Stack:arn:aws:cloudformation:us-east-2:xxx:stack/amplify-xxx-staging-xxx/xxxxx is in UPDATE_IN_PROGRESS state and can not be updated.[0m
```

And I click the rebuild button, the rebuild of the same version ends successfully

### Expected behavior

auto-build can perform successfully, won't need me to manual click the rebuild button

### Reproduction steps

1. do some change on local
2. run "amplify push" and get success
3. commit code into git repo
4. the amplify console auto-build and get failed

### Additional information

the whole output in the console
```
                                 # Starting phase: build
2021-08-31T16:32:46.349Z [INFO]: [0mAmplify AppID found: dvmxne0bgmgzv. Amplify App name is: GPPNew[0m
2021-08-31T16:32:46.517Z [INFO]: [0mBackend environment staging found in Amplify Console app: GPPNew[0m
2021-08-31T16:32:47.281Z [WARNING]: - Fetching updates to backend environment: staging from the cloud.
2021-08-31T16:32:47.824Z [WARNING]: ✔ Successfully pulled backend environment staging from the cloud.
2021-08-31T16:32:47.901Z [INFO]: 
2021-08-31T16:32:51.211Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2021-08-31T16:32:56.783Z [WARNING]: - Initializing your environment: staging
2021-08-31T16:32:57.334Z [WARNING]: ✔ Initialized provider successfully.
2021-08-31T16:33:06.805Z [WARNING]: - Uploading files...
2021-08-31T16:33:06.846Z [WARNING]: - Uploading files...
2021-08-31T16:33:07.083Z [WARNING]: - Uploading files...
2021-08-31T16:33:08.312Z [INFO]: [32m[39m
                                 [32mGraphQL schema compiled successfully.[39m
                                 [32mEdit your schema at /codebuild/output/srcxxx/amplify/backend/api/gqlapi/schema.graphql or place .graphql files in a directory at /codebuild/output/srcxxx/amplify/backend/api/gqlapi/schema[39m
2021-08-31T16:33:08.446Z [WARNING]: - Uploading files...
2021-08-31T16:33:08.911Z [WARNING]: - Updating resources in the cloud. This may take a few minutes...
2021-08-31T16:33:09.495Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2021-08-31T16:33:09.496Z [WARNING]: ✖ There was an error initializing your environment.
2021-08-31T16:33:09.507Z [INFO]: [0mError [ValidationError]: Stack:arn:aws:cloudformation:us-east-2:xxx:stack/amplify-xxx-staging-xxx/xxxx is in UPDATE_IN_PROGRESS state and can not be updated.[0m
                                 [0m    at Request.extractError (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)[0m
                                 [0m    at Request.callListeners (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)[0m
                                 [0m    at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)[0m
                                 [0m    at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)[0m
                                 [0m    at Request.transition (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)[0m
                                 [0m    at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10[0m
                                 [0m    at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)[0m
                                 [0m    at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)[0m
                                 [0m    at Request.callListeners (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)[0m
                                 [0m    at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)[0m
                                 [0m    at Request.emit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)[0m
                                 [0m    at Request.transition (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)[0m
                                 [0m    at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10[0m
                                 [0m    at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)[0m
                                 [0m    at Request.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)[0m
                                 [0m    at Request.callListeners (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)[0m
                                 [0m    at callNextListener (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)[0m
                                 [0m    at IncomingMessage.onEnd (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:336:13)[0m
                                 [0m    at IncomingMessage.emit (events.js:326:22)[0m
                                 [0m    at IncomingMessage.EventEmitter.emit (domain.js:483:12)[0m
                                 [0m    at endReadableNT (_stream_readable.js:1241:12)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:84:21) {[0m
                                 [0m  code: 'ValidationError',[0m
                                 [0m  time: 2021-08-31T16:33:09.494Z,[0m
                                 [0m  requestId: '80a1ba1b-eee1-4bf3-a3fd-05e7a20f6cf6',[0m
                                 [0m  statusCode: 400,[0m
                                 [0m  retryable: false,[0m
                                 [0m  retryDelay: 74.29387478843748[0m
                                 [0m}[0m
2021-08-31T16:33:09.566Z [ERROR]: !!! Build failed
2021-08-31T16:33:09.566Z [ERROR]: !!! Non-Zero Exit Code detected
2021-08-31T16:33:09.566Z [INFO]: # Starting environment caching...
2021-08-31T16:33:09.567Z [INFO]: # Uploading environment cache artifact...
2021-08-31T16:33:09.634Z [INFO]: # Environment caching completed
Terminating logging...
```

**Comment by yhvh009** [comment]
And this env keeps facing this issue, while another env with the exactly same code works fine every time

**Comment by behrooziAWS** [comment]
Hi, it seems like this same backend is associated with 2 apps the one you listed above and: d33z6<snip> When you commit, both of these apps cause the backend to build resulting in this error.  If you configure one with the environment variable `PROCESS_SKIP_BACKEND` set to true, only one of them will build the backend and you will not receive this error.

**Comment by yhvh009** [comment]
> Hi, it seems like this same backend is associated with 2 apps the one you listed above and: d33z6 When you commit, both of these apps cause the backend to build resulting in this error. If you configure one with the environment variable `PROCESS_SKIP_BACKEND` set to true, only one of them will build the backend and you will not receive this error.

Oh, I get it, there's an old project assosiated with the same git repo, i've deleted the old one, and i'll check if it worked. Thanks a lot.
