### ISSUE TITLE
Getting CredentialsError when deploying nextjs app

### ISSUE THREAD

**Issue by guykogel** [aws-amplify/amplify-console#2247]
**Please describe which feature you have a question about?**
nextjs SSR app

**Provide additional details**
Following this guide:
https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html

I am trying to deploy my nextjs app and I am getting the following error after the `Starting SSR Build...` step:

```
Error [CredentialsError]: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
                                  at credError (/root/.//node_modules/aws-sdk/lib/config.js:390:40)
                                  at getStaticCredentials (/root/.//node_modules/aws-sdk/lib/config.js:411:15)
                                  at Config.getCredentials (/root/.//node_modules/aws-sdk/lib/config.js:420:9)
                                  at Request.VALIDATE_CREDENTIALS (/root/.//node_modules/aws-sdk/lib/event_listeners.js:81:26)
                                  at Request.callListeners (/root/.//node_modules/aws-sdk/lib/sequential_executor.js:102:18)
                                  at Request.emit (/root/.//node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                  at Request.emit (/root/.//node_modules/aws-sdk/lib/request.js:688:14)
                                  at Request.transition (/root/.//node_modules/aws-sdk/lib/request.js:22:10)
                                  at AcceptorStateMachine.runTo (/root/.//node_modules/aws-sdk/lib/state_machine.js:14:12)
                                  at Request.runTo (/root/.//node_modules/aws-sdk/lib/request.js:408:15) {
                                  code: 'CredentialsError',
                                  time: 2021-09-10T07:07:04.171Z,
                                  originalError: {
                                  message: 'Missing credentials',
                                  code: 'CredentialsError',
                                  time: 2021-09-10T07:07:04.171Z
```

What am I missing?

**Comment by siegerts** [comment]
Hi @guykogel, thanks for raising. Can you provide a bit [more information](https://github.com/aws-amplify/amplify-console/issues/new?assignees=&labels=&template=1.bug_report.yaml) on the steps to reproduce this? Any app customizations, build spec, first deployment, etc? Thanks!

**Comment by ferdingler** [comment]
Hi @guykogel, apologies, this fell out of my radar and I missed your response. I assume you  no longer have this issue but just for future reference: There is no need to manually configure any AWS credentials during your build. We assume the IAM role that you attach to your Amplify App and those credentials are automatically available during a build. This is how we are able to deploy SSR resources into your account. The error you showed leads me to believe that we weren't able to assume such role, perhaps the role doesn't have the proper Trust Policy to let us assume it. 

Feel free to re-open the ticket if you are still facing the same issue.

**Comment by igpastor** [comment]
Hi @ferdingler 

I'm having the same issue but I have the service role created with all the permissions and the trust you mentioned. It is associated with the amplify app and the weird thing is that in IAM it shows that this role it has not been used, but I tried several deployments and made sure the app in General/Settings/Service role has the role I created. Do you think on another thing I could be missing?

Thanks
