### ISSUE TITLE
The "path" argument must be of type string. Received undefined. Backend build.

### ISSUE THREAD

**Issue by newilu** [aws-amplify/amplify-console#2306]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:eu-west-1:114719936836:apps/dvbqrelkacp23

### Region

eu-west-1 (Ireland)

### Amplify Console feature

Backend builds

### Describe the bug

```
2021-10-07T05:00:20.923Z [INFO]: Git SSH Key acquired
2021-10-07T05:00:21.000Z [INFO]: # Cloning repository: git@github.com:Effector-Ltd/EffectorEcommerce.git
2021-10-07T05:00:21.034Z [INFO]: Agent pid 138
2021-10-07T05:00:21.061Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2021-10-07T05:00:21.257Z [INFO]: Cloning into 'EffectorEcommerce'...
2021-10-07T05:00:21.775Z [INFO]: Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
2021-10-07T05:00:24.603Z [INFO]: # Checking for Git submodules at: /codebuild/output/src482109772/src/EffectorEcommerce/.gitmodules
2021-10-07T05:00:24.906Z [INFO]: # Retrieving environment cache...
2021-10-07T05:00:24.939Z [INFO]: # Retrieved environment cache
2021-10-07T05:00:24.939Z [INFO]: ---- Setting Up SSM Secrets ----
2021-10-07T05:00:24.939Z [INFO]: SSM params {"Path":"/amplify/dvbqrelkacp23/staging/","WithDecryption":true}
2021-10-07T05:00:24.985Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2021-10-07T05:00:29.311Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 4.29.4 to 6.1.1...
2021-10-07T05:02:25.938Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
2021-10-07T05:02:26.461Z [INFO]: # Retrieving cache...
2021-10-07T05:02:26.495Z [INFO]: # Extracting cache...
2021-10-07T05:02:26.509Z [INFO]: # Extraction completed
2021-10-07T05:02:33.481Z [INFO]: ## Starting Backend Build
                                 # Starting phase: build
2021-10-07T05:02:42.467Z [INFO]: [0mAmplify AppID found: dvbqrelkacp23. Amplify App name is: effector[0m
2021-10-07T05:02:42.562Z [INFO]: [0mBackend environment staging found in Amplify Console app: effector[0m
2021-10-07T05:02:43.295Z [WARNING]: - Fetching updates to backend environment: staging from the cloud.
2021-10-07T05:02:43.545Z [WARNING]: ✔ Successfully pulled backend environment staging from the cloud.
2021-10-07T05:02:44.260Z [WARNING]: ✖ There was an error initializing your environment.
2021-10-07T05:02:44.262Z [INFO]: [31mFailed to pull the backend.[39m
2021-10-07T05:02:44.264Z [INFO]: [31mThe "path" argument must be of type string. Received undefined[39m
2021-10-07T05:02:44.264Z [INFO]: [0mTypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined[0m
                                 [0m    at validateString (internal/validators.js:120:11)[0m
                                 [0m    at Object.join (path.js:1039:7)[0m
                                 [0m    at PathManager.constructPath (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/pathManager.ts:177:34)[0m
                                 [0m    at PathManager.getResourceDirectoryPath (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/pathManager.ts:124:10)[0m
                                 [0m    at PathManager.getResourceParametersFilePath (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/pathManager.ts:127:20)[0m
                                 [0m    at StateManager.setResourceParametersJson (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:261:34)[0m
                                 [0m    at updateStateFiles (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:704:16)[0m
                                 [0m    at Object.headlessImport (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1253:26)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at importedAuthEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:922:12)[0m
                                 [0m    at updateConfigOnEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/index.js:50:72)[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/index.js:304:22[0m
2021-10-07T05:02:44.284Z [ERROR]: !!! Build failed
2021-10-07T05:02:44.284Z [ERROR]: !!! Non-Zero Exit Code detected
2021-10-07T05:02:44.284Z [INFO]: # Starting environment caching...
2021-10-07T05:02:44.285Z [INFO]: # Environment caching completed
Terminating logging...
```

### Expected behavior

The project was expected to build

### Reproduction steps

I've created new app in amplify console, connected my github, added env variables, tried to build and got an error.

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

PLEASE HELP ME - I'VE CHECKED ALL ISSUES WITH THE SAME PROBLEM BUT THEY ARE NOT WORKING FOR ME!!!

**Comment by OskarD** [comment]
@hloriana what did your team find?

**Comment by hloriana** [comment]
@OskarD If you're still running into this issue, can you please make sure that the parameters.json file generated when importing auth has the correct file path? It should be `amplify/backend/auth/appXXXXXX/parameters.json`.

**Comment by raffclar** [comment]
> @OskarD and @newilu If you're still running into this issue, can you please make sure that the parameters.json file generated when importing auth has the correct file path? It should be `amplify/backend/auth/appXXXXXX/parameters.json`.

In my case the parameters.json file was nested inside `build` like so `amplify/backend/auth/appXXXXXX/build/parameters.json`. Moving the parameters.json up one level fixed the issue. I'd like to know what caused this but thanks for answer.

**Comment by newilu** [comment]
wel if someone still having this issue - i've tried to recreate whole app (amplify, cognito, api (appsync)) and that helped me) enjoy)
