### ISSUE TITLE
Nextjs Frontend build fails, Starting SSR Build Error command killed with Sigkill

### ISSUE THREAD

**Issue by edcvb00** [aws-amplify/amplify-console#2362]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1n0jvx24rxomq

### Region

us-east-1

### Amplify Console feature

Build settings, Logging

### Describe the bug

Build fails continuously at this stage with the following logs. I can build and deploy on both a local environment and vercel. This only seems to be happening with amplify. 

Edited repository name in logs.

2021-11-03T13:37:31.214Z [INFO]: Starting SSR Build...
2021-11-03T13:40:14.853Z [ERROR]: error:
                                  Error: Command was killed with SIGKILL (Forced termination): node_modules/.bin/next build
                                  Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
                                  See here for more info: https://nextjs.org/docs/messages/built-in-css-disabled
                                  info  - Loaded env from /codebuild/output/src292403481/src/repository/.env
                                  info  - Using webpack 4. Reason: webpack5 flag is set to false in next.config.js https://nextjs.org/docs/messages/webpack5
                                  info  - Checking validity of types...
                                  info  - Creating an optimized production build...
                                  info  - Using external babel configuration from /codebuild/output/src292403481/src/repository/.babelrc
                                  at makeError (/root/.//node_modules/execa/lib/error.js:60:11)
                                  at handlePromise (/root/.//node_modules/execa/index.js:118:26)
                                  at runMicrotasks (<anonymous>)
                                  at processTicksAndRejections (node:internal/process/task_queues:96:5)
                                  at async Builder.build (/root/.//node_modules/@sls-next/lambda-at-edge/dist/build.js:376:13) {
                                  shortMessage: 'Command was killed with SIGKILL (Forced termination): node_modules/.bin/next build',
                                  command: 'node_modules/.bin/next build',
                                  escapedCommand: '"node_modules/.bin/next" build',
                                  exitCode: undefined,
                                  signal: 'SIGKILL',
                                  signalDescription: 'Forced termination',
                                  stdout: 'info  - Loaded env from /codebuild/output/src292403481/src/repository/.env\n' +
                                  'info  - Using webpack 4. Reason: webpack5 flag is set to false in next.config.js https://nextjs.org/docs/messages/webpack5\n' +
                                  'info  - Checking validity of types...\n' +
                                  'info  - Creating an optimized production build...\n' +
                                  'info  - Using external babel configuration from /codebuild/output/src292403481/src/repository/.babelrc',
                                  stderr: 'Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.\n' +
                                  'See here for more info: https://nextjs.org/docs/messages/built-in-css-disabled\n',
                                  failed: true,
                                  timedOut: false,
                                  isCanceled: false,
                                  killed: false
                                  }
                                  [G[?25h[G[J
                                  133s › d1n0jvx24rxomq › Error: Command was killed with SIGKILL (Forced termination): node_modules/.bin/next build
                                  Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
                                  See here for more info: https://nextjs.org/docs/messages/built-in-css-disabled
                                  info  - Loaded env from /codebuild/output/src292403481/src/repository/.env
                                  info  - Using webpack 4. Reason: webpack5 flag is set to false in next.config.js https://nextjs.org/docs/messages/webpack5
                                  info  - Checking validity of types...
                                  info  - Creating an optimized production build...
                                  info  - Using external babel configuration from /codebuild/output/src292403481/src/repository/.babelrc
                                  [G[?25h
Terminating logging...

### Expected behavior

Build to succeed, I have tried debugging any webpack or babel errors, but without success. Also cannot reproduce in the local environment or deploying with vercel. 

### Reproduction steps

1.New project from Github repository
2.Default image
3.amplify.yml as below
4.Redeploy this version

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - rm -rf node_modules/
        - nvm install 16
        - yarn install
        - export NODE_OPTIONS="--max-old-space-size=8120" 
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
```

**Comment by hloriana** [comment]
Hi @edcvb00 👋🏽, thanks for raising this issue. Can you try changing the export command to `NODE_OPTIONS='--max_old_space_size=4096'`

**Comment by edcvb00** [comment]
Hi @hloriana thanks for the quick response! I edited my build file and tried to redeploy with the new node options. Unfortunately I still got the same sigkill error at the SSR Build stage.

**Comment by hloriana** [comment]
@edcvb00 thank you for trying that. I'm bringing this issue up to the team for further investigation.

**Comment by ashish979** [comment]
Hi @infinonly Did you find the solution to this? I am also facing the same issue and could not resolve it.

**Comment by infinonly** [comment]
@ashish979  no, I’ve been using vercel. Still seems to be an amplify only issue can’t reproduce in other environments

**Comment by ashish979** [comment]
@hloriana Is there any update on the investigation? 
I am trying to deploy a next.js app on aws amplify but getting the error mentioned in this issue.

**Comment by andrewvenson** [comment]
Having this same exact issue. Logs not really descriptive on the reason for forced termination.

**Comment by brysadler** [comment]
I'm seeing `'info - Using webpack 4. Reason: webpack5 flag is set to false in next.config.js`. Removing `webpack5: false` from next.config.js seems to have done the trick for me
