### ISSUE TITLE
Amplify Console - 'craco build' not working

### ISSUE THREAD

**Issue by iamsid47** [aws-amplify/amplify-console#2446]
**Issue**
I wanted to deploy my react-js app to the Amplify Console. Although, I have been getting build errors whenever I try to deploy. Although, when building the app locally, or on Netlify, the build process returns no errors. Even when running ```npm start```, the app starts properly without errors.

**Additional details**
The main issue starts when the build command runs during the deployment. 
I have been using Craco for my react app. So, whenever ```npm run build``` is used, it starts ```craco build```. Although, during the very time, Amplify Console throws an error.

**What AWS Services are you utilizing?**
Currently, the app is independent of any services. Just using Amplify Console. All the required dependencies are already present in the ```package.json``` file. So, no issues with that too.

**Provide additional details e.g. code snippets**
Here are the build settings  (Pretty Default) -

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

The Error ----

```
2021-12-13T09:48:01.717Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
2021-12-13T09:48:01.717Z [INFO]: # Executing command: npm run build
2021-12-13T09:48:01.882Z [INFO]: > codemugg-pvt@0.1.0 build /codebuild/output/src729230013/src/web-pvt
                                 > craco build
2021-12-13T09:48:03.941Z [INFO]: Creating an optimized production build...
2021-12-13T09:48:23.230Z [INFO]: Failed to compile.
2021-12-13T09:48:23.232Z [INFO]: ./src/index.css
                                 Error: PostCSS plugin autoprefixer requires PostCSS 8.
                                 Migration guide for end-users:
                                 https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
2021-12-13T09:48:23.271Z [WARNING]: npm
2021-12-13T09:48:23.271Z [WARNING]: ERR! code ELIFECYCLE
                                    npm ERR! errno 1
2021-12-13T09:48:23.273Z [WARNING]: npm
2021-12-13T09:48:23.273Z [WARNING]: ERR! codemugg-pvt@0.1.0 build: `craco build`
                                    npm ERR! Exit status 1
                                    npm ERR!
                                    npm ERR! Failed at the codemugg-pvt@0.1.0 build script.
                                    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-12-13T09:48:23.278Z [WARNING]: 
2021-12-13T09:48:23.278Z [WARNING]: npm ERR! A complete log of this run can be found in:
                                    npm ERR!     /root/.npm/_logs/2021-12-13T09_48_23_274Z-debug.log
2021-12-13T09:48:23.278Z [HELP]: Outputting the npm debug log
                                 0 info it worked if it ends with ok
                                 1 verbose cli [
                                 1 verbose cli   '/root/.nvm/versions/node/v12.21.0/bin/node',
                                 1 verbose cli   '/root/.nvm/versions/node/v12.21.0/bin/npm',
                                 1 verbose cli   'run',
                                 1 verbose cli   'build'
                                 1 verbose cli ]
                                 2 info using npm@6.14.11
                                 3 info using node@v12.21.0
                                 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
                                 5 info lifecycle codemugg-pvt@0.1.0~prebuild: codemugg-pvt@0.1.0
                                 6 info lifecycle codemugg-pvt@0.1.0~build: codemugg-pvt@0.1.0
                                 7 verbose lifecycle codemugg-pvt@0.1.0~build: unsafe-perm in lifecycle true
                                 8 verbose lifecycle codemugg-pvt@0.1.0~build: PATH: /root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/codebuild/output/src729230013/src/web-pvt/node_modules/.bin:/usr/local/rvm/gems/ruby-2.4.6/bin:/usr/local/rvm/gems/ruby-2.4.6@global/bin:/usr/local/rvm/rubies/ruby-2.4.6/bin:/usr/local/rvm/bin:/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:/root/.nvm/versions/node/v12.21.0/bin:/root/.local/bin:/root/.local/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.dotnet/tools
                                 9 verbose lifecycle codemugg-pvt@0.1.0~build: CWD: /codebuild/output/src729230013/src/web-pvt
                                 10 silly lifecycle codemugg-pvt@0.1.0~build: Args: [ '-c', 'craco build' ]
                                 11 silly lifecycle codemugg-pvt@0.1.0~build: Returned: code: 1  signal: null
                                 12 info lifecycle codemugg-pvt@0.1.0~build: Failed to exec build script
                                 13 verbose stack Error: codemugg-pvt@0.1.0 build: `craco build`
                                 13 verbose stack Exit status 1
                                 13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
                                 13 verbose stack     at EventEmitter.emit (events.js:314:20)
                                 13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
                                 13 verbose stack     at ChildProcess.emit (events.js:314:20)
                                 13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
                                 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
                                 14 verbose pkgid codemugg-pvt@0.1.0
                                 15 verbose cwd /codebuild/output/src729230013/src/web-pvt
                                 16 verbose Linux 4.14.252-195.483.amzn2.x86_64
                                 17 verbose argv "/root/.nvm/versions/node/v12.21.0/bin/node" "/root/.nvm/versions/node/v12.21.0/bin/npm" "run" "build"
                                 18 verbose node v12.21.0
                                 19 verbose npm  v6.14.11
                                 20 error code ELIFECYCLE
                                 21 error errno 1
                                 22 error codemugg-pvt@0.1.0 build: `craco build`
                                 22 error Exit status 1
                                 23 error Failed at the codemugg-pvt@0.1.0 build script.
                                 23 error This is probably not a problem with npm. There is likely additional logging output above.
                                 24 verbose exit [ 1, true ]
2021-12-13T09:48:23.281Z [ERROR]: !!! Build failed
2021-12-13T09:48:23.281Z [ERROR]: !!! Non-Zero Exit Code detected
2021-12-13T09:48:23.281Z [INFO]: # Starting environment caching...
2021-12-13T09:48:23.282Z [INFO]: # Environment caching completed
```

Note - The repository used for this build is a Github organization's private repository. Although, access was granted to Amplify Console.

**Comment by iamsid47** [comment]
Got it sorted out. 
The issue was in the Autoprefixer version. I think Postcss supports version 9 and the one I was using was 10. That is why it wasn't  getting deployed.
