### ISSUE TITLE
How can I set the lambda node version?

### ISSUE THREAD

**Issue by NoCtrlZ** [aws-amplify/amplify-console#2483]
I am using lambda right now and in development environment, I am using node version `14.18.2`.
The error happened when the amplify backend deployment script ran.
How can I set the lambda node version?
```
                                 ## Checking for associated backend environment...
                                 ## Backend environment association found
2022-01-04T12:01:27.115Z [INFO]: [0mAmplify AppID found: d34ho3c461rmfp. Amplify App name is: app[0m
2022-01-04T12:01:27.182Z [INFO]: [0mBackend environment prod found in Amplify Console app: app[0m
2022-01-04T12:01:41.789Z [WARNING]: - Fetching updates to backend environment: prod from the cloud.
2022-01-04T12:01:52.004Z [WARNING]: - Building resource api/app
2022-01-04T12:01:52.051Z [WARNING]: ✔ Successfully pulled backend environment prod from the cloud.
2022-01-04T12:01:52.163Z [INFO]: 
2022-01-04T12:02:05.310Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2022-01-04T12:02:11.365Z [WARNING]: - Initializing your environment: prod
2022-01-04T12:02:22.266Z [WARNING]: - Building resource api/app
2022-01-04T12:02:22.311Z [WARNING]: ✔ Initialized provider successfully.
2022-01-04T12:02:22.734Z [INFO]: 
2022-01-04T12:02:22.734Z [INFO]: [0mSuggested configuration for new layer versions:[0m
2022-01-04T12:02:22.735Z [INFO]: 
2022-01-04T12:02:22.737Z [INFO]: [0mappLayer[0m
                                 [0m  - Description: Updated layer version  2022-01-04T12:02:22.734Z[0m
2022-01-04T12:02:22.737Z [INFO]: 
2022-01-04T12:02:35.459Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2022-01-04T12:02:35.461Z [WARNING]: ✖ There was an error initializing your environment.
2022-01-04T12:02:35.469Z [INFO]: [0mError: Packaging lambda function failed with the error [0m
                                 [0mCommand failed with exit code 1: yarn --production[0m
                                 [0merror @typescript-eslint/eslint-plugin@5.8.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "12.21.0"[0m
                                 [0merror Found incompatible module.[0m
                                 [0myarn install v1.22.0[0m
                                 [0m[1/4] Resolving packages...[0m
                                 [0m[2/4] Fetching packages...[0m
                                 [0minfo fsevents@2.3.2: The platform "linux" is incompatible with this module.[0m
                                 [0minfo "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.[0m
                                 [0minfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.[0m
                                 [0m    at runPackageManager (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:66:13)[0m
                                 [0m    at installDependencies (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:40:3)[0m
                                 [0m    at Object.buildResource [as build] (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:13:5)[0m
                                 [0m    at buildLayer (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/buildLayer.ts:46:40)[0m
                                 [0m    at prepareResource (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:605:33)[0m
                                 [0m    at async Promise.all (index 0)[0m
                                 [0m    at prepareBuildableResources (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:601:10)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:173:5)[0m
2022-01-04T12:02:35.497Z [ERROR]: !!! Build failed
2022-01-04T12:02:35.498Z [ERROR]: !!! Non-Zero Exit Code detected
2022-01-04T12:02:35.498Z [INFO]: # Starting environment caching...
2022-01-04T12:02:35.498Z [INFO]: # Uploading environment cache artifact...
2022-01-04T12:02:35.583Z [INFO]: # Environment caching completed
Terminating logging...
```

Thank you!

**Comment by joecritch** [comment]
@NoCtrlZ You should be able to override the Node version in 'Your Amplify app > Build settings > Build image settings > Live package updates'. (Or, if you're doing this with IaC, you can use the `_LIVE_UPDATES` environment variable)

![Screenshot 2022-01-04 at 14 59 06](https://user-images.githubusercontent.com/24449/148078406-e4869c36-9540-4090-be92-03696f6c67d2.png)

**Comment by hloriana** [comment]
Hi @NoCtrlZ in addition to the solution provided above, here is the documentation: https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup-live-updates

**Comment by NoCtrlZ** [comment]
Thank you!
It works!
