### ISSUE TITLE
ExpiredToken: The provided token has expired

### ISSUE THREAD

**Issue by gakinson** [aws-amplify/amplify-console#2557]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1he6253vtkqx8

### Region

us-east-2

### Amplify Console feature

Backend builds

### Describe the bug

All of our builds are getting the following error at the last stage of the amplify backend build and we are unable to complete our deployments.

```
2022-01-31T07:49:57.016Z [INFO]: 
2022-01-31T07:49:57.018Z [INFO]: DELETE_COMPLETE LambdaLayerVersion76a0dd89 AWS::Lambda::LayerVersion Mon Jan 31 2022 07:49:51 GMT+0000 (Coordinated Universal Time)
2022-01-31T07:50:06.188Z [WARNING]: ⠙ Deploying (3 of 3)
2022-01-31T07:50:06.248Z [WARNING]: ⠹ Waiting for DynamoDB indices to be ready
2022-01-31T07:50:06.248Z [WARNING]: ⠸ Deploying (4 of 3)
2022-01-31T07:50:06.249Z [WARNING]: ✔ Deployed
2022-01-31T08:01:23.541Z [WARNING]: - Uploading files...
2022-01-31T08:01:24.223Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2022-01-31T08:01:24.292Z [WARNING]: ✖ There was an error initializing your environment.
2022-01-31T08:01:24.308Z [INFO]: [0mExpiredToken: The provided token has expired.[0m
                                 [0m    at Request.extractError (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:710:35)[0m
                                 [0m    at Request.callListeners (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)[0m
                                 [0m    at Request.emit (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)[0m
                                 [0m    at Request.emit (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:686:14)[0m
                                 [0m    at Request.transition (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)[0m
                                 [0m    at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)[0m
                                 [0m    at /root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10[0m
                                 [0m    at Request.<anonymous> (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)[0m
                                 [0m    at Request.<anonymous> (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:12)[0m
                                 [0m    at Request.callListeners (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)[0m
                                 [0m    at Request.emit (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)[0m
                                 [0m    at Request.emit (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:686:14)[0m
                                 [0m    at Request.transition (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)[0m
                                 [0m    at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)[0m
                                 [0m    at /root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10[0m
                                 [0m    at Request.<anonymous> (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)[0m
                                 [0m    at Request.<anonymous> (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:12)[0m
                                 [0m    at Request.callListeners (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)[0m
                                 [0m    at callNextListener (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)[0m
                                 [0m    at IncomingMessage.onEnd (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:335:13)[0m
                                 [0m    at IncomingMessage.emit (events.js:412:35)[0m
                                 [0m    at IncomingMessage.emit (domain.js:475:12)[0m
                                 [0m    at endReadableNT (internal/streams/readable.js:1334:12)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:82:21) {[0m
                                 [0m  code: 'ExpiredToken',[0m
                                 [0m  region: null,[0m
                                 [0m  time: 2022-01-31T08:01:24.221Z,[0m
                                 [0m  requestId: 'MWQN4BDGT76ZP5S6',[0m
                                 [0m  extendedRequestId: 'Oy58ypqGjvFJShaNCpv+rpFKgfzd1abvWI5mc+fvQL+ICY6/7XBXijnHq4E0y39ZBhh1eNsCZMU=',[0m
                                 [0m  cfId: undefined,[0m
                                 [0m  statusCode: 400,[0m
                                 [0m  retryable: true[0m
                                 [0m}[0m
2022-01-31T08:01:24.362Z [ERROR]: !!! Build failed
2022-01-31T08:01:24.363Z [ERROR]: !!! Non-Zero Exit Code detected
```

### Expected behavior

Build succeeds

### Reproduction steps

run deploy

### Build Settings

```yaml
version: 1
backend:
  phases:
    preBuild:
      commands:
        - nvm use ${VERSION_NODE_DEFAULT}
    build:
      commands:
        - update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.8 11
        - /usr/local/bin/pip3.8 install --user pipenv
        - npm i -S graphql-ttl-transformer
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - echo 'sentry token:'
        - echo $SENTRY_AUTH_TOKEN
        - npm run release:${STAGE}
    postBuild:
      commands:
        - node export-lib-to-json.js
        - sh export-lib-json-to-s3.sh
  artifacts:
    baseDirectory: build
    files:
      - '**/*'

test:
  phases:
    preTest:
      commands:
        - npm ci
        - npm install --save-dev @babel/core @babel/cli @babel/preset-env
        - npm install wait-on
        - npm install pm2
        - ./node_modules/.bin/babel src -d build
        - npx pm2 start npm -- start
        - 'npx wait-on http://localhost:3000'
    test:
      commands:
        - 'npx cypress run'
    postTest:
      commands:
        - npx pm2 kill
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
```

**Comment by tomhirschfeld** [comment]
Hi @renebrandel @litwicki,

We're still blocked here. I don't mean to be a pain but this is blocking our deployments. From our explorations here it looks like it could be a simple fix and is related to token expiry due to our app being much larger than most amplify apps. Any chance you could connect us with an engineer we can work with to unblock this?

**Comment by ferdingler** [comment]
Hi @tomhirschfeld , this seems to be related with your build times taking longer than 1 hour. One of my colleagues noticed that your build was reduced to 25 minutes and it appeared to finish successfuly. Is this not the case?

**Comment by tomhirschfeld** [comment]
hi @ferdingler, thanks for the reply 

we reduced the build times to 25 minutes by making each deploy very small by reducing the number of changes in the graphql schema. When we include more than a small number of updates to our graphql schema the build fails. I believe we are the largest, or one of the largest projects using the amplify framework in terms of resource use and we have had other bugs related to scalability issues. We have an email thread right now with @litwicki and @renebrandel with the following context from my colleague @gakinson 

```
I have been debugging this issue most of today trying to get our builds to become unblocked.

Here are some of my findings.

The main issue seems to consistently keep happening when there is a staged/tiered deployment. This is when you execute two versions of the stack, which seems to be for API related changes where dynamodb table indexes are involved. The deployment gets to the end where it will say "Deployed (2 of 2)" and then it will hang for approximately 15 minutes. After that time it will then spit out saying that it is deployed and then it will try to upload the meta and current stack files. At this point, it will then fail saying that the token is expired. See snippet below.

My guess here is that the amplify CLI is creating instances to various AWS services with an assumed IAM role which has the session duration set too low. I couldn't quite figure out what the duration you are using, whether that is 15 minutes or an hour. I was looking through your code and found a section here where you are setting the duration: 

https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-provider-awscloudformation/src/system-config-manager.ts#L130-L137 

I am not sure where you are getting this value from, is it the session duration on the iam role that is configured on the amplify app level?

Some more debugging I did was inspect the deployment-state file which seems to be updated correctly as the deployment happens. I managed to find an old build of ours that had a staged/tiered deployment which succeeded but then failed on the front-end due to a token expiry. So, from this I do not think it is the tiered/staged logic failing and that it is more isolated to these durations on the credentials/tokens retrieved from STS.

After a bunch of fiddling around with deploying, I was able to create a non staged/tiered deployment which completed in approximately 25 minutes (backend) which succeeded.

Not sure if any of this helps you, but I thought I would share.





2022-01-31T22:15:17.591Z [WARNING]: ⠧ Deploying (2 of 2)
2022-01-31T22:15:17.653Z [WARNING]: ⠇ Waiting for DynamoDB indices to be ready
2022-01-31T22:15:17.654Z [WARNING]: ⠏ Deploying (3 of 2)
2022-01-31T22:15:17.654Z [WARNING]: ✔ Deployed
2022-01-31T22:27:43.049Z [WARNING]: - Uploading files...
2022-01-31T22:27:43.324Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2022-01-31T22:27:43.423Z [WARNING]: ✖ There was an error initializing your environment.
2022-01-31T22:27:43.439Z [INFO]: [0mExpiredToken: The provided token has expired. [0m 

```

**Comment by ferdingler** [comment]
@tomhirschfeld thanks for the detailed response. We confirmed that this is related to the expiration time we set on the temporary credentials we embed during builds. We will work on a fix to support longer running builds. But in the meantime, anything you can do to keep the build duration < 45 minutes will be helpful to give us some time to work on this. Will keep this thread updated with more information.

**Comment by gakinson** [comment]
Hello,

Following up on this to see if there has been any work on fixing this?

Thank you

**Comment by calavera** [comment]
we have increased the expiration timeout for that token to 60 minutes. That's how much we can extend it without major changes internally.

**Comment by iShavgula-TacTill** [comment]
Hello,

I'm getting this issue every second build as the build time takes around 60 minutes.
Is there another increase planned for the nearest future ?

<img width="552" alt="Capture d’écran 2022-10-20 à 20 19 56" src="https://user-images.githubusercontent.com/15924394/197027499-6053a3e7-824a-4c75-94fa-54359daa4d53.png">

Here is this screenshot, 5:32 build time correspond to 60min+ failed build. 


By the way, I think that the `Building custom resources` phase is executed twice and I do have many custom resources and building them takes around 10-15 minutes per build.

Also, after the resources are updated using the `CloudFormation` (which takes 3-5 minutes), about 20-22 minutes are consumed by doing something that corresponds to this into logs : `[INFO]: [K`.

After that, uploading files takes about 7-10+ minutes.

<img width="635" alt="Capture d’écran 2022-10-20 à 20 26 14" src="https://user-images.githubusercontent.com/15924394/197028600-d2153507-6b44-4ca2-95e4-bd24ffb574f2.png">

Please, let me know if I can provide you with more information.

Thanks
