### ISSUE TITLE
amplify build failed with AlreadyExistsException (bucket exists)

### ISSUE THREAD

**Issue by kasukur** [aws-amplify/amplify-console#2604]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-1:accountId:apps/d2j3vm4n1gru98

### Region

us-east-1

### Amplify Console feature

Backend builds

### Describe the bug

I am trying to deploy an amplify app as per https://webapp.serverlessworkshops.io/staticwebhosting/deploy/ but the build is failing because of an existing bucket. I don't have any buckets with that name. I understand that the buckets are global but not sure how to workaround this

```
2022-02-25T03:31:32.457Z [INFO]: An error occurred when creating the CloudFormation stack
2022-02-25T03:31:32.459Z [WARNING]: ✖ Root stack creation failed
2022-02-25T03:31:32.464Z [INFO]: AlreadyExistsException: Stack [amplify-wildrydes-prod-32220] already exists
                                 at Request.extractError (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
                                 at Request.callListeners (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:686:14)
                                 at Request.transition (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                 at Request.emit (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:686:14)
                                 at Request.transition (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                 at callNextListener (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
                                 at IncomingMessage.onEnd (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:335:13)
                                 at IncomingMessage.emit (events.js:412:35)
                                 at IncomingMessage.emit (domain.js:475:12)
                                 at endReadableNT (internal/streams/readable.js:1334:12)
                                 at processTicksAndRejections (internal/process/task_queues.js:82:21) {
                                 code: 'AlreadyExistsException',
                                 time: 2022-02-25T03:31:32.456Z,
                                 requestId: '92bb3d71-1610-43c4-a385-54cb25e459cd',
                                 statusCode: 400,
                                 retryable: false,
                                 retryDelay: 81.16703459454344
                                 }
2022-02-25T03:31:32.487Z [ERROR]: !!! Build failed
2022-02-25T03:31:32.487Z [ERROR]: !!! Non-Zero Exit Code detected
2022-02-25T03:31:32.488Z [INFO]: # Starting environment caching...
2022-02-25T03:31:32.488Z [INFO]: # Environment caching completed
Terminating logging...
```

### Expected behavior

Build to complete successfully. 

### Reproduction steps

Deploy the app as per instructions at https://webapp.serverlessworkshops.io/staticwebhosting/deploy/

**Comment by spina-a-d** [comment]
Got the same issue on a long-existing project that has always worked.  Now all-of-a-sudden it says I can't deploy to the existing deployment bucket, which doesn't make sense, because it always existed before as well, that's where it deploys to.

**Comment by hikeeba** [comment]
I'm getting this on an Amplify branch. Says the Amplify branch already exists, and it sure does, that's how I set up CI/CD...

**Comment by hikeeba** [comment]
Not sure if this is the same issue or not, but it looks slightly similar.

```
2022-03-18T19:19:42.525Z [INFO]: CREATE_IN_PROGRESS AmplifyBranch AWS::Amplify::Branch Fri Mar 18 2022 19:19:39 GMT+0000 (Coordinated Universal Time)
                                 CREATE_FAILED      AmplifyBranch AWS::Amplify::Branch Fri Mar 18 2022 19:19:41 GMT+0000 (Coordinated Universal Time) Resource handler returned message: "Invalid request provided: Failed to create branch. The branch main already exists for the app d2d5rf58axme3s (Service: Amplify, Status Code: 400, Request ID: e64321e8-fca8-4c8d-b531-605dfba1caf7, Extended Request ID: null)" (RequestToken: b3dc4954-fbd3-d406-9970-3c7796b54ca1, HandlerErrorCode: InvalidRequest)
```

**Comment by hloriana** [comment]
Hi @hikeeba @spina-a-d can you also share your App IDs?

**Comment by hikeeba** [comment]
My App ID is `d2d5rf58axme3s`. This issue went away after doing an env pull and the trying again. Not sure if it is related to the issue reported here.

**Comment by spina-a-d** [comment]
@hloriana the App ID for me should be `d2gc0o88uvhlzz`. I just tried re-running the pipeline now to see if anything had changed, and still the same issue.

@hikeeba Could you describe exactly how you fixed it?

**Comment by hloriana** [comment]
@spina-a-d thank you for providing this information. Taking a look.

**Comment by hikeeba** [comment]
I think my issue was different, and it seemed to resolve itself after about 15 minutes. I just did a env pull and the tried again and it started working.

**Comment by spina-a-d** [comment]
> @spina-a-d thank you for providing this information. Taking a look.

Did you find anything, it still doesn't seem to work?
