### ISSUE TITLE
Creating backend on Amplify Console fails

### ISSUE THREAD

**Issue by redeian** [aws-amplify/amplify-console#274]
I push the project as usual (simply push codes to a repository). It worked before. Then today it gave me error.

I have try adding this command to my build setting, but it still gives me the error.
```
version: 0.1
backend:
  phases:
    build:
      commands:
        - envCache --set stackInfo ""
        - amplifyPush --simple
```

# The error:

```
                                 # Starting phase: build
                                 # Executing command: envCache --set stackInfo
2019-11-27T12:42:12.732Z [INFO]: # Executing command: amplifyPush --simple
2019-11-27T12:42:13.238Z [INFO]: Failed to pull the backend.
2019-11-27T12:42:13.241Z [INFO]: TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. Received type undefined
                                 at Object.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/lib/attach-backend-steps/a10-queryProvider.js:19:32)
                                 at Generator.next (<anonymous>)
                                 at fulfilled (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/lib/attach-backend-steps/a10-queryProvider.js:5:58)
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
                                 at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
                                 at startup (internal/bootstrap/node.js:283:19)
2019-11-27T12:42:13.270Z [ERROR]: !!! Build failed
2019-11-27T12:42:13.271Z [ERROR]: !!! Non-Zero Exit Code detected
2019-11-27T12:42:13.271Z [INFO]: # Starting environment caching...
2019-11-27T12:42:13.271Z [INFO]: # Environment caching completed
Terminating logging...
```

Thank you!

**Comment by abhinavjayanthy** [comment]
I'm having the same issue. 
```
2019-11-27T14:33:57.472Z [INFO]: Git SSH Key acquired
2019-11-27T14:33:57.555Z [INFO]: # Cloning repository: git@github.com:abhinavjayanthy/xxxxxxx.git
2019-11-27T14:33:57.733Z [INFO]: Agent pid 69
2019-11-27T14:33:57.738Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2019-11-27T14:33:57.962Z [INFO]: Cloning into 'xxxxxxx'...
2019-11-27T14:33:58.241Z [INFO]: Warning: Permanently added the RSA host key for IP address '1xxxxxx' to the list of known hosts.
2019-11-27T14:34:00.434Z [INFO]: # Checking for Git submodules at: /codebuild/output/src774990783/src/xxxxxxx/.gitmodules
2019-11-27T14:34:00.628Z [INFO]: # Retrieving cache...
2019-11-27T14:34:00.702Z [INFO]: # Extracting cache...
2019-11-27T14:34:00.709Z [INFO]: # Extraction completed
2019-11-27T14:34:00.710Z [INFO]: # Retrieving environment cache...
2019-11-27T14:34:00.750Z [INFO]: # Retrieved environment cache
2019-11-27T14:34:00.751Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2019-11-27T14:34:09.108Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 1.12.0 to 4.1.1...
2019-11-27T14:34:57.914Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
2019-11-27T14:35:06.237Z [INFO]: ## Successfully created new backend environment
2019-11-27T14:35:07.178Z [INFO]: ## Starting Backend Build
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2019-11-27T14:35:07.593Z [INFO]: Failed to pull the backend.
2019-11-27T14:35:07.595Z [INFO]: TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. Received type undefined
                                 at Object.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/lib/attach-backend-steps/a10-queryProvider.js:19:32)
                                 at Generator.next (<anonymous>)
                                 at fulfilled (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/lib/attach-backend-steps/a10-queryProvider.js:5:58)
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
                                 at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
                                 at startup (internal/bootstrap/node.js:283:19)
2019-11-27T14:35:07.631Z [ERROR]: !!! Build failed
2019-11-27T14:35:07.770Z [ERROR]: !!! Non-Zero Exit Code detected
2019-11-27T14:35:07.770Z [INFO]: # Starting environment caching...
2019-11-27T14:35:07.771Z [INFO]: # Environment caching completed
Terminating logging...

```

**Comment by anatonie** [comment]
Hi @redeian @abhinavjayanthy can you guys please share your appArns (can be found in general settings)? Thank you!

**Comment by abhinavjayanthy** [comment]
@anatonie `arn:aws:amplify:us-east-1:931914093943:apps/d3h5e1ydk6xaq5`

**Comment by swaminator** [comment]
we're looking at this with priority. Couple of questions.

Can you please share your appid? Found in App settings > General
Also share your build settings (App settings > Build settings or if you store in your repo then the amplify.yml)
About these backends: Were they created via Console or CLI?

**Comment by abhinavjayanthy** [comment]
@swaminator Here are my Build settings 

```
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```

I've created this using CLI

**Comment by anatonie** [comment]
@abhinavjayanthy Is this an existing environment (one that has been deployed via amplify push)?

**Comment by abhinavjayanthy** [comment]
@anatonie Yes, this was an existing env, since the deploys started to fail, all I did was delete the app from the AWS console and re-created it again which ofcourse did not fix the issue. Right now I changed the AWS Amplify CLI version from `Latest` to `3.17.0` and I'm able to deploy.

**Comment by UnleashedMind** [comment]
the latest version of the CLI v4.2.0 should have fixed it

**Comment by swaminator** [comment]
@abhinavjayanthy @redeian could you please verify if this works for you?

**Comment by swaminator** [comment]
Issue has been fixed. Please re-open if you find a similar issue.
