### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. 

### ISSUE THREAD

**Issue by blomm** [aws-amplify/amplify-console#275]
I really don't know what's happened here.  The amplify pipeline is now failing at the backend stage with the following:

```
Executing command: amplifyPush --simple
2019-11-27T12:32:04.224Z [INFO]: Failed to pull the backend.
2019-11-27T12:32:04.227Z [INFO]: TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. Received type undefined
                                 at Object.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/lib/attach-backend-steps/a10-queryProvider.js:19:32)
                                 at Generator.next (<anonymous>)
                                 at fulfilled (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/lib/attach-backend-steps/a10-queryProvider.js:5:58)
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
                                 at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
                                 at startup (internal/bootstrap/node.js:283:19)
```
... Google is not showing anything for 'failed to pull the backend'

**To Reproduce**
Try to build an amplify project backend

**Comment by abhinavjayanthy** [comment]
I'm having the same issue as well.

```
2019-11-27T14:34:57.914Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
2019-11-27T14:35:06.237Z [INFO]: ## Successfully created new backend environment
2019-11-27T14:35:07.178Z [INFO]: ## Starting Backend Build
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2019-11-27T14:35:07.593Z [INFO]: Failed to pull the backend.
2019-11-27T14:35:07.595Z [INFO]: TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. Received type undefined
                                 at Object.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/lib/attach-backend-steps/a10-queryProvider.js:19:32)
                                 at Generator.next (<anonymous>)
                                 at fulfilled (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/lib/attach-backend-steps/a10-queryProvider.js:5:58)
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
                                 at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
                                 at startup (internal/bootstrap/node.js:283:19)
2019-11-27T14:35:07.631Z [ERROR]: !!! Build failed
2019-11-27T14:35:07.770Z [ERROR]: !!! Non-Zero Exit Code detected
2019-11-27T14:35:07.770Z [INFO]: # Starting environment caching...
2019-11-27T14:35:07.771Z [INFO]: # Environment caching completed
Terminating logging...
```

**Comment by swaminator** [comment]
@blomm @abhinavjayanthy we're looking at this with priority. Couple of questions.
1. Can you please share your appid? Found in App settings > General
2. Also share your build settings (App settings > Build settings or if you store in your repo then the `amplify.yml`)
3. About these backends: Were they created via Console or CLI?

**Comment by swaminator** [comment]
#274

**Comment by user-0320** [comment]
This seems to be a bug in the latest version (as of 2019/11/26) of AWS Amplify CLI: 4.1.1 and 4.0.0.
A band-aid solution:
1. Go to Amplify Console
2. Select build settings
3. Change the value to use for AWS Amplify  CLI version from `Latest` to `3.17.0`

**Comment by abhinavjayanthy** [comment]
@user-0320  Thanks! That seems to work!

**Comment by swaminator** [comment]
@blomm @abhinavjayanthy please try installing the latest version of the cli to see if it fixed it https://github.com/aws-amplify/amplify-console/issues/274#issuecomment-559218457

**Comment by heitorlessa** [comment]
Not sure if it's your case but I just got migrated from 3.17 to 4.1 and the following command fixed mine:

``amplify plugin scan``

**Comment by blomm** [comment]
4.2 seems to have resolved the issues.
Frustratingly this cost me a day of work, thinking that I had done something wrong.

**Comment by NelsonG-C** [comment]
I have been using Amplify cli version 1.7.8 and needing to update to use the added multi auth feature. However, I'm getting a similar error as above after updating to version 4.13.4.

`The 'request' argument must be string. Received type undefined
TypeError [ERR_INVALID_ARG_TYPE]: The 'request' argument must be string. Received type undefined
    at C:\Users\nelso\AppData\Local\Yarn\Data\global\node_modules\esm\esm.js:1:224803
    at Object.<anonymous> (C:\Users\nelso\AppData\Local\Yarn\Data\global\node_modules\esm\esm.js:1:251922)
    at Object.t (C:\Users\nelso\AppData\Local\Yarn\Data\global\node_modules\esm\esm.js:1:279775)
    at n (C:\Users\nelso\AppData\Local\Yarn\Data\global\node_modules\esm\esm.js:1:279589)
    at providers.forEach.providerName (C:\Users\nelso\AppData\Local\Yarn\Data\global\node_modules\@aws-amplify\cli\lib\extensions\amplify-helpers\show-helpful-provider-links.js:11:30)
    at Array.forEach (<anonymous>)
    at AmplifyToolkit.showHelpfulProviderLinks [as _showHelpfulProviderLinks] (C:\Users\nelso\AppData\Local\Yarn\Data\global\node_modules\@aws-amplify\cli\lib\extensions\amplify-helpers\show-helpful-provider-links.js:10:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

I'm wondering if this is due to some breaking changes between the versions I'm updating from, or perhaps something else. I'm on Windows, using Bash console.

Can someone advise me what else I may need updating here, or how they dealt with a similar problem?

**Comment by Joycehao19** [comment]
@NelsonG-C Can you try v4.2.0?

**Comment by NelsonG-C** [comment]
@Joycehao19 Still receiving the same error on v4.2.0.
What I have noticed is that I seem to be having a similar issue as @DavidNelson was in this comment thread [#2595](https://github.com/aws-amplify/amplify-cli/issues/2595). 

My active plugin list is as below:

core: @aws-amplify/cli@4.2.0
{ packageName: '@aws-amplify/cli',
  packageVersion: '4.2.0',
  packageLocation:
   'C:\\Users\\nelso\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\@aws-amplify\\cli\\',
  manifest:
   { name: 'core',
     type: 'core',
     commands:
      [ 'categories',
        'configure',
        'console',
        'delete',
        'env',
        'help',
        'init',
        'migrate',
        'publish',
        'push',
        'pull',
        'run',
        'status',
        'plugin',
        'version' ],
     commandAliases: { h: 'help', serve: 'run', ls: 'status' } } }

Unfortunately, I can't see an explanation as to how that issue was resolved.

I'm using Yarn as my package manager.

`amplify plugin scan` doesnt seem to fix the issue either. I'm wondering if this is because my previous amplify version 1.7.8 is much older?

**Comment by NelsonG-C** [comment]
@Joycehao19 any advice for the above?
