### ISSUE TITLE
One click deploy from another repo

### ISSUE THREAD

**Issue by dabit3** [aws-amplify/amplify-console#32]
One click deploy does not seem to be working from the AWS Amplify Auth Starters repo:

https://github.com/aws-samples/aws-amplify-auth-starters

Build breaks on the back end.

**Comment by swaminator** [comment]
Reproduced with following Error:
```
 CREATE_COMPLETE UserPoolClientRole AWS::IAM::Role Mon Aug 05 2019 16:45:58 GMT+0000 (Coordinated Universal Time)
2019-08-05T16:46:09.192Z [INFO]: 
0
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
                                 message: 'Resource is not in the state stackUpdateComplete',
                                 code: 'ResourceNotReady',
                                 retryable: false,
                                 time: 2019-08-05T16:47:09.235Z,
                                 statusCode: 200,
                                 retryDelay: 30000 }
2019-08-05T16:47:14.311Z [ERROR]: !!! Build failed
2019-08-05T16:47:14.413Z [ERROR]: !!! Non-Zero Exit Code detected
2019-08-05T16:47:14.413Z [INFO]: # Starting environment caching...
2019-08-05T16:47:14.414Z [INFO]: # Environment caching completed
Terminating logging...
```

**Comment by swaminator** [comment]
Noticed this error:
```
2019-08-05T18:58:48.451Z [INFO]: CREATE_FAILED UserPoolClientLambda                                                                 AWS::Lambda::Function      Mon Aug 05 2019 18:58:47 GMT+0000 (Coordinated Universal Time) The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs10.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 2745dea9-a7be-46a2-b5f1-9e1d546ff431)
```

**Comment by swaminator** [comment]
#19

**Comment by dabit3** [comment]
Thanks @swaminator.

This error was because I already have an existing fork in my GitHub account. Upon deleting the old fork and re-deploying via the one-click deploy button, everything works as expected.
