### ISSUE TITLE
Console broken again Throttling: Rate exceeded (probably related to aws-amplify/cli 4.6.0)

### ISSUE THREAD

**Issue by BardiaN** [aws-amplify/amplify-console#324]
This issue has happened before and also solved before like in #88 
So again the same story, all resources could be pushed via `amplify push` on my local system without a single issue, but build pipeline fails to build it with the error below:
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2019-12-17T17:22:04.214Z [INFO]: 
2019-12-17T17:22:04.216Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html
2019-12-17T17:22:04.619Z [INFO]: Amplify AppID found: d1haz5673z20fp. Amplify App name is: fcf-personalization}
2019-12-17T17:22:04.752Z [INFO]: Backend environment dev found in Amplify Console app: fcf-personalization
2019-12-17T17:22:47.891Z [INFO]: 
2019-12-17T17:22:48.398Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2019-12-17T17:22:50.369Z [WARNING]: - Initializing your environment: dev
2019-12-17T17:23:30.227Z [WARNING]: ✔ Initialized provider successfully.
2019-12-17T17:23:33.649Z [WARNING]: - Updating resources in the cloud. This may take a few minutes...
2019-12-17T17:23:34.068Z [INFO]: Throttling: Rate exceeded
                                 at Request.extractError (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
2019-12-17T17:23:34.070Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2019-12-17T17:23:34.071Z [WARNING]: ✖ There was an error initializing your environment.
2019-12-17T17:23:34.071Z [INFO]: init failed
2019-12-17T17:23:34.073Z [INFO]: Error: Project stack doesn't exist
                                 at Response.cfnModel.describeStacks.err (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:232:22)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:364:18)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
2019-12-17T17:23:34.215Z [ERROR]: !!! Build failed
2019-12-17T17:23:34.215Z [ERROR]: !!! Non-Zero Exit Code detected
2019-12-17T17:23:34.215Z [INFO]: # Starting environment caching...
2019-12-17T17:23:34.216Z [INFO]: # Environment caching completed

**Comment by kaustavghosh06** [comment]
@BardiaN Are you able to reproduce this error? Can you re-build the backend of your app?

**Comment by BardiaN** [comment]
> @BardiaN Are you able to reproduce this error continuously? Can you redeploy the build of your app to check?

Hey @kaustavghosh06 
Thanks for your reply. Well, as I mentioned in the issue description, I can easily deploy all resources by running ‘amplify push’ on my local system. I’m using Amplify CLI V4.6.0. (Same as the console is using currently)
Also, if I push “redeploy this version” button, it might work, I really don’t know what it depends on.
If you guys think posting my appId could help, I’ll post it.

**Comment by swaminator** [comment]
@BardiaN CFN is throttling the calls as we're requesting information from the stack to display logs. If you are doing simultaneous backend builds or done a push back-back this error can pop up. We are working on a fix to handle this scenario more gracefully.

**Comment by BardiaN** [comment]
> @BardiaN CFN is throttling the calls as we're requesting information from the stack to display logs. If you are doing simultaneous backend builds or done a push back-back this error can pop up. We are working on a fix to handle this scenario more gracefully.

@swaminator Thanks for getting back to me. Actually, no, I haven’t throttled it at all!
I simply merged a request in my git system which caused a new build and it went straight to failed status. After that, I tried deploying using my local CLI and it worked, but the problem is that my CLI can’t deploy the frontend, so I’m stuck.
I event tried changing the CLI version in my build settings, still the same.

**Comment by kaustavghosh06** [comment]
@BardiaN  Can you please re-deploy the app using the latest version of the CLI using the console now? If you see the same error, could you please provide your appID?

**Comment by BardiaN** [comment]
> @BardiaN Can you please re-deploy the app using the latest version of the CLI using the console now? If you see the same error, could you please provide your appID?

I just did and same thing happened. So here’s my appId: d1haz5673z20fp
