### ISSUE TITLE
Amplify previews build failed after @aws-amplify/cli 4.8.0

### ISSUE THREAD

**Issue by yinlinchen** [aws-amplify/amplify-console#355]
Hi!

We found that the Previews failed to build when the @aws-amplify/cli 4.8.0+. We have a project deployed in the Amplify console and use @aws-amplify/cli 4.5.0 last year. Our build settings using Amplify CLI latest version. 

We found that the build failed in Previews when we submit new PR due to``` Current environment cannot be determined``` when using @aws-amplify/cli  is 4.11.0. We change the build setting back to @aws-amplify/cli 4.5.0 and the build is successful. After testing each different versions. We found that till @aws-amplify/cli 4.7.0 our build is successful and build is failed from version 4.8.0 to 4.11.0. 

Please check below messages and let us know what changes from our end need to be done in order to use latest version. Thanks! 

See below error message using 4.9.0.
```
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-01-10T14:34:17.925Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2020-01-10T14:34:17.935Z [INFO]: # Start initializing Amplify environment: devupdate
2020-01-10T14:34:17.937Z [INFO]: # Initializing new Amplify environment: devupdate (amplify init)
2020-01-10T14:34:18.400Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-01-10T14:34:20.616Z [INFO]: 
2020-01-10T14:34:20.621Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html
                                 init failed
2020-01-10T14:34:20.625Z [INFO]: { UndeterminedEnvironmentError: Current environment cannot be determined
                                 Use 'amplify init' in the root of your app directory to initialize your project with Amplify
                                 at getEnvInfo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/get-env-info.js:19:15)
                                 at AmplifyToolkit.getProjectDetails [as _getProjectDetails] (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/get-project-details.js:14:26)
                                 at Object.run (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/amplify-service-migrate.js:9:42)
                                 at Object.run (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js:80:33)
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
                                 at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
                                 at startup (internal/bootstrap/node.js:283:19)
                                 at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3) name: 'UndeterminedEnvironmentError' }
2020-01-10T14:34:20.666Z [ERROR]: !!! Build failed
2020-01-10T14:34:20.761Z [ERROR]: !!! Non-Zero Exit Code detected
2020-01-10T14:34:20.761Z [INFO]: # Starting environment caching...
2020-01-10T14:34:20.762Z [INFO]: # Environment caching completed
Terminating logging... 
```

See below message for the successful using 4.7.0
```
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-01-10T14:53:29.689Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2020-01-10T14:53:29.698Z [INFO]: # Start initializing Amplify environment: devupdate
2020-01-10T14:53:29.700Z [INFO]: # Initializing new Amplify environment: devupdate (amplify init)
2020-01-10T14:53:30.215Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2020-01-10T14:53:32.701Z [INFO]: 
2020-01-10T14:53:32.706Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html
2020-01-10T14:53:32.718Z [WARNING]: - Initializing your environment: devupdate
2020-01-10T14:53:32.992Z [WARNING]: ✔ Initialized provider successfully.
2020-01-10T14:53:33.023Z [INFO]: The following types do not have '@auth' enabled. Consider using @auth with @model
2020-01-10T14:53:33.024Z [INFO]: - Collection
                                 - Archive
                                 Learn more about @auth here: https://aws-amplify.github.io/docs/cli-toolchain/graphql#auth
2020-01-10T14:53:33.165Z [INFO]: GraphQL schema compiled successfully.
                                 Edit your schema at /codebuild/output/src967976075/src/iawa_v2/amplify/backend/api/collectionarchives/schema.graphql or place .graphql files in a directory at /codebuild/output/src967976075/src/iawa_v2/amplify/backend/api/collectionarchives/schema
2020-01-10T14:53:33.170Z [WARNING]: - Updating resources in the cloud. This may take a few minutes...
2020-01-10T14:53:34.312Z [WARNING]: ✔ All resources are updated in the cloud
2020-01-10T14:53:34.314Z [INFO]: 
2020-01-10T14:53:34.386Z [INFO]: Initialized your environment successfully.
2020-01-10T14:53:34.388Z [INFO]: Your project has been successfully initialized and connected to the cloud!
                                 Some next steps:
                                 "amplify status" will show you what you've added already and if it's locally configured or deployed
                                 "amplify <category> add" will allow you to add features like user login or a backend API
                                 "amplify push" will build all your local backend resources and provision it in the cloud
                                 “amplify console” to open the Amplify Console and view your project status
                                 "amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud
                                 Pro tip:
                                 Try "amplify add api" to create a backend API and then "amplify publish" to deploy everything
2020-01-10T14:53:34.425Z [INFO]: # Environment devupdate details:
2020-01-10T14:53:34.926Z [INFO]: 
2020-01-10T14:53:34.927Z [INFO]: devupdate
....
2020-01-10T14:53:35.464Z [INFO]: # Completed phase: build
```

**Comment by swaminator** [comment]
@yinlinchen can you share your build settings?

**Comment by thedgbrt** [comment]
Just experienced the same problem now. I had updated to 4.11 a week ago, and did a ton of builds, but now I have this error too.

**Comment by yinlinchen** [comment]
@swaminator Please see the build settings below
```
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
  phases:
    preTest:
      commands:
        - npm install
        - npm install wait-on
        - npm install  mocha@5.2.0 mochawesome mochawesome-merge mochawesome-report-generator
        - 'npm start & npx wait-on http://localhost:3000'
    test:
      commands:
        - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge --reportDir cypress/report/mochawesome-report > cypress/report/mochawesome.json
```

**Comment by Joycehao19** [comment]
Hello @yinlinchen , do you still face this issue?

**Comment by yinlinchen** [comment]
Hi @Joycehao19, I didn't have this issue after I upgraded to Amplify/CLI 4.13+
