### ISSUE TITLE
Cannot create new env: AlreadyExistsException: Stack [amplify-myproj-samdev-152827] already exists

### ISSUE THREAD

**Issue by elimence** [aws-amplify/amplify-console#437]
**Describe the bug**
I cloned an existing project and initialized an env called `prod`.
I tried creating a new env `samdev` (I removed it with `amplify env remove` earlier when `amplify push` kept failing on that env) but I keep getting the following error:
```
⠴ Initializing project in the cloud...An error occurred when creating the CloudFormation stack
✖ Root stack creation failed
init failed
AlreadyExistsException: Stack [amplify-myproj-samdev-152827] already exists
    at Request.extractError (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/elimence/.nvm/versions/node/v13.2.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'Stack [amplify-myproj-samdev-152827] already exists',
  code: 'AlreadyExistsException',
  time: 2020-01-28T00:00:36.146Z,
  requestId: '0779f95e-af14-4890-9e51-d05f1812733e',
  statusCode: 400,
  retryable: false,
  retryDelay: 27.05650614071111
}
```

Running `amplify env remove samdev` says the env doesn't exist

I also check https://console.aws.amazon.com/appsync/home?region=us-east-1#/apis and there's no trace of samdev

**Amplify CLI Version**
4.13.1

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 13.2.0

**Comment by swaminator** [comment]
@olivoil @elimence did you get your issue resolved?

**Comment by elimence** [comment]
@swaminator Yes, my issue is resolved.

**Comment by adi518** [comment]
No actual solution in this thread, but I'll add my case. This can result from a crash while trying to deploy. In my case I had to manually delete stack leftovers that were created during a PR preview deploy (where it creates a new environment for the pull request).
