### ISSUE TITLE
Unable to build and deploy app which works locally

### ISSUE THREAD

**Issue by JamieMason** [aws-amplify/amplify-console#49]
Hi,
I created https://github.com/JamieMason/serverless-graphql-aws-gatsby by following along with the Tutorial at https://www.youtube.com/watch?v=U6trl0_ynuM&t=4127s. It works locally, `yarn start` will launch a site which hits GraphQL in AWS that calls a Function in AWS and returns the expected data.

Attempting to deploy the App fails for `Resource is not in the state stackUpdateComplete` and I don't know how to proceed. 

Please could you let me know what I can do to get past this issue?

```
AMPLIFY APP
serverless-graphql-aws-gatsby

SOURCE
https://github.com/JamieMason/serverless-graphql-aws-gatsby

APP ARN
arn:aws:amplify:eu-west-1:693340411157:apps/d131w18e6nt47w

BUILD SETTINGS
Using default amplify.yml displayed in Amplify Console

BRANCHES
master

NUMBER OF BACKEND ENVIRONMENTS CREATED WITH THE AMPLIFY CLI
Just one, as far as I know

BUILD ERROR OUTPUT
--------------------------------------------------------------------------------
# Starting phase: build
# Executing command: amplifyPush --simple
2019-08-12T23:21:24.625Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2019-08-12T23:21:24.635Z [INFO]: # Start initializing Amplify environment: dev
# Initializing new Amplify environment: dev (amplify init)
2019-08-12T23:21:35.681Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2019-08-12T23:21:37.519Z [INFO]:
2019-08-12T23:21:37.522Z [INFO]: For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html
2019-08-12T23:21:37.614Z [WARNING]: - Initializing your environment: dev
2019-08-12T23:21:37.961Z [WARNING]: ✔ Initialized provider successfully.
2019-08-12T23:21:40.293Z [INFO]: GraphQL schema compiled successfully.
Edit your schema at /codebuild/output/src110245001/src/serverless-graphql-aws-gatsby/amplify/backend/api/confweather/schema.graphql or place .graphql files in a directory at /codebuild/output/src110245001/src/serverless-graphql-aws-gatsby/amplify/backend/api/confweather/schema
2019-08-12T23:21:41.386Z [WARNING]: - Updating resources in the cloud. This may take a few minutes...
2019-08-12T23:21:46.802Z [INFO]:
2019-08-12T23:21:46.806Z [INFO]: UPDATE_IN_PROGRESS conf-weather-dev-20190812225817 AWS::CloudFormation::Stack Mon Aug 12 2019 23:21:41 GMT+0000 (Coordinated Universal Time) User Initiated
UPDATE_IN_PROGRESS functionweather                 AWS::CloudFormation::Stack Mon Aug 12 2019 23:21:45 GMT+0000 (Coordinated Universal Time)
UPDATE_IN_PROGRESS apiconfweather                  AWS::CloudFormation::Stack Mon Aug 12 2019 23:21:46 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:21:46.897Z [INFO]:
2019-08-12T23:21:46.897Z [INFO]: UPDATE_IN_PROGRESS conf-weather-dev-20190812225817-apiconfweather-CJ4TKER9E741 AWS::CloudFormation::Stack Mon Aug 12 2019 23:21:46 GMT+0000 (Coordinated Universal Time) User Initiated
2019-08-12T23:21:46.955Z [INFO]:
2019-08-12T23:21:46.956Z [INFO]: UPDATE_IN_PROGRESS conf-weather-dev-20190812225817-functionweather-1TSECBPID1P0O AWS::CloudFormation::Stack Mon Aug 12 2019 23:21:46 GMT+0000 (Coordinated Universal Time) User Initiated
2019-08-12T23:21:51.889Z [INFO]:
2019-08-12T23:21:51.891Z [INFO]: UPDATE_IN_PROGRESS LambdaFunction AWS::Lambda::Function Mon Aug 12 2019 23:21:49 GMT+0000 (Coordinated Universal Time)
UPDATE_COMPLETE    LambdaFunction AWS::Lambda::Function Mon Aug 12 2019 23:21:50 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:21:56.835Z [INFO]:
2019-08-12T23:21:56.837Z [INFO]: UPDATE_IN_PROGRESS GraphQLSchema AWS::AppSync::GraphQLSchema Mon Aug 12 2019 23:21:52 GMT+0000 (Coordinated Universal Time)
UPDATE_IN_PROGRESS GraphQLAPIKey AWS::AppSync::ApiKey        Mon Aug 12 2019 23:21:52 GMT+0000 (Coordinated Universal Time)
UPDATE_COMPLETE    GraphQLAPIKey AWS::AppSync::ApiKey        Mon Aug 12 2019 23:21:54 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:21:56.892Z [INFO]:
2019-08-12T23:21:56.894Z [INFO]: UPDATE_COMPLETE_CLEANUP_IN_PROGRESS conf-weather-dev-20190812225817-functionweather-1TSECBPID1P0O AWS::CloudFormation::Stack Mon Aug 12 2019 23:21:52 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:22:01.902Z [INFO]:
2019-08-12T23:22:01.903Z [INFO]: UPDATE_COMPLETE functionweather AWS::CloudFormation::Stack Mon Aug 12 2019 23:21:56 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:22:06.862Z [INFO]:
2019-08-12T23:22:06.865Z [INFO]: UPDATE_COMPLETE GraphQLSchema AWS::AppSync::GraphQLSchema Mon Aug 12 2019 23:22:06 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:22:11.837Z [INFO]:
2019-08-12T23:22:11.838Z [INFO]: UPDATE_IN_PROGRESS FunctionDirectiveStack AWS::CloudFormation::Stack Mon Aug 12 2019 23:22:08 GMT+0000 (Coordinated Universal Time)
UPDATE_IN_PROGRESS Conference             AWS::CloudFormation::Stack Mon Aug 12 2019 23:22:09 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:22:12.030Z [INFO]:
2019-08-12T23:22:12.030Z [INFO]: UPDATE_IN_PROGRESS conf-weather-dev-20190812225817-apiconfweather-CJ4TKER9E741-Conference-8WEWZC4QTMIL AWS::CloudFormation::Stack Mon Aug 12 2019 23:22:09 GMT+0000 (Coordinated Universal Time) User Initiated
2019-08-12T23:22:12.117Z [INFO]:
2019-08-12T23:22:12.118Z [INFO]: UPDATE_IN_PROGRESS conf-weather-dev-20190812225817-apiconfweather-CJ4TKER9E741-FunctionDirectiveStack-8YJDFM7X5EBK AWS::CloudFormation::Stack Mon Aug 12 2019 23:22:09 GMT+0000 (Coordinated Universal Time) User Initiated
2019-08-12T23:22:17.032Z [INFO]:
2019-08-12T23:22:17.034Z [INFO]: UPDATE_IN_PROGRESS DeleteConferenceResolver AWS::AppSync::Resolver Mon Aug 12 2019 23:22:15 GMT+0000 (Coordinated Universal Time)
UPDATE_FAILED      ConferenceTable          AWS::DynamoDB::Table   Mon Aug 12 2019 23:22:15 GMT+0000 (Coordinated Universal Time) CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename Conference-zpgb2rzmqnfwnabcrnfrtti2qu-dev and update the stack again.
UPDATE_FAILED      GetConferenceResolver    AWS::AppSync::Resolver Mon Aug 12 2019 23:22:16 GMT+0000 (Coordinated Universal Time) Resource update cancelled
UPDATE_FAILED      DeleteConferenceResolver AWS::AppSync::Resolver Mon Aug 12 2019 23:22:16 GMT+0000 (Coordinated Universal Time) Resource update cancelled
2019-08-12T23:22:17.126Z [INFO]:
2019-08-12T23:22:17.127Z [INFO]: UPDATE_IN_PROGRESS InvokeWeatherLambdaDataSource AWS::AppSync::FunctionConfiguration Mon Aug 12 2019 23:22:15 GMT+0000 (Coordinated Universal Time)
UPDATE_COMPLETE    InvokeWeatherLambdaDataSource AWS::AppSync::FunctionConfiguration Mon Aug 12 2019 23:22:16 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:22:17.340Z [INFO]:
2019-08-12T23:22:17.340Z [INFO]: UPDATE_ROLLBACK_IN_PROGRESS conf-weather-dev-20190812225817-apiconfweather-CJ4TKER9E741-Conference-8WEWZC4QTMIL AWS::CloudFormation::Stack Mon Aug 12 2019 23:22:17 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to update: [DeleteConferenceResolver, GetConferenceResolver, ConferenceTable].
2019-08-12T23:22:21.852Z [INFO]:
2019-08-12T23:22:21.854Z [INFO]: UPDATE_FAILED Conference AWS::CloudFormation::Stack Mon Aug 12 2019 23:22:20 GMT+0000 (Coordinated Universal Time) Embedded stack arn:aws:cloudformation:eu-west-1:693340411157:stack/conf-weather-dev-20190812225817-apiconfweather-CJ4TKER9E741-Conference-8WEWZC4QTMIL/adf02a00-bd4d-11e9-b172-0254d350c81a was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [DeleteConferenceResolver, GetConferenceResolver, ConferenceTable].
2019-08-12T23:22:22.150Z [INFO]:
2019-08-12T23:22:22.150Z [INFO]: UPDATE_ROLLBACK_IN_PROGRESS conf-weather-dev-20190812225817-apiconfweather-CJ4TKER9E741-FunctionDirectiveStack-8YJDFM7X5EBK AWS::CloudFormation::Stack Mon Aug 12 2019 23:22:20 GMT+0000 (Coordinated Universal Time) Initiated by parent stack
UPDATE_IN_PROGRESS          ConferenceweatherResolver                                                                       AWS::AppSync::Resolver     Mon Aug 12 2019 23:22:20 GMT+0000 (Coordinated Universal Time)
UPDATE_FAILED               ConferenceweatherResolver                                                                       AWS::AppSync::Resolver     Mon Aug 12 2019 23:22:20 GMT+0000 (Coordinated Universal Time) Resource update cancelled
2019-08-12T23:22:31.862Z [INFO]:
2019-08-12T23:22:31.865Z [INFO]: UPDATE_FAILED               FunctionDirectiveStack                                      AWS::CloudFormation::Stack Mon Aug 12 2019 23:22:31 GMT+0000 (Coordinated Universal Time) Resource update cancelled
UPDATE_ROLLBACK_IN_PROGRESS conf-weather-dev-20190812225817-apiconfweather-CJ4TKER9E741 AWS::CloudFormation::Stack Mon Aug 12 2019 23:22:31 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to update: [Conference, FunctionDirectiveStack].
2019-08-12T23:22:36.769Z [INFO]:
2019-08-12T23:22:36.771Z [INFO]: UPDATE_FAILED               apiconfweather                  AWS::CloudFormation::Stack Mon Aug 12 2019 23:22:33 GMT+0000 (Coordinated Universal Time) Embedded stack arn:aws:cloudformation:eu-west-1:693340411157:stack/conf-weather-dev-20190812225817-apiconfweather-CJ4TKER9E741/a2d091a0-bd4d-11e9-adb7-02135cc8443e was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: The following resource(s) failed to update: [Conference, FunctionDirectiveStack].
UPDATE_ROLLBACK_IN_PROGRESS conf-weather-dev-20190812225817 AWS::CloudFormation::Stack Mon Aug 12 2019 23:22:34 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to update: [apiconfweather].
2019-08-12T23:22:51.842Z [INFO]:
2019-08-12T23:22:51.843Z [INFO]: UPDATE_IN_PROGRESS apiconfweather  AWS::CloudFormation::Stack Mon Aug 12 2019 23:22:48 GMT+0000 (Coordinated Universal Time)
UPDATE_IN_PROGRESS functionweather AWS::CloudFormation::Stack Mon Aug 12 2019 23:22:48 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:22:51.900Z [INFO]:
2019-08-12T23:22:51.901Z [INFO]: UPDATE_ROLLBACK_IN_PROGRESS conf-weather-dev-20190812225817-functionweather-1TSECBPID1P0O AWS::CloudFormation::Stack Mon Aug 12 2019 23:22:49 GMT+0000 (Coordinated Universal Time) User Initiated
UPDATE_IN_PROGRESS          LambdaFunction                                                AWS::Lambda::Function      Mon Aug 12 2019 23:22:50 GMT+0000 (Coordinated Universal Time)
UPDATE_COMPLETE             LambdaFunction                                                AWS::Lambda::Function      Mon Aug 12 2019 23:22:51 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:22:56.834Z [INFO]:
2019-08-12T23:22:56.836Z [INFO]: UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS conf-weather-dev-20190812225817-functionweather-1TSECBPID1P0O AWS::CloudFormation::Stack Mon Aug 12 2019 23:22:52 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:23:01.808Z [INFO]:
2019-08-12T23:23:01.809Z [INFO]: UPDATE_COMPLETE functionweather AWS::CloudFormation::Stack Mon Aug 12 2019 23:22:59 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:23:21.955Z [INFO]:
2019-08-12T23:23:21.957Z [INFO]: UPDATE_IN_PROGRESS GraphQLSchema AWS::AppSync::GraphQLSchema Mon Aug 12 2019 23:23:17 GMT+0000 (Coordinated Universal Time)
UPDATE_IN_PROGRESS GraphQLAPIKey AWS::AppSync::ApiKey        Mon Aug 12 2019 23:23:18 GMT+0000 (Coordinated Universal Time)
UPDATE_COMPLETE    GraphQLAPIKey AWS::AppSync::ApiKey        Mon Aug 12 2019 23:23:19 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:23:31.911Z [INFO]:
2019-08-12T23:23:31.913Z [INFO]: UPDATE_COMPLETE    GraphQLSchema          AWS::AppSync::GraphQLSchema Mon Aug 12 2019 23:23:30 GMT+0000 (Coordinated Universal Time)
UPDATE_IN_PROGRESS Conference             AWS::CloudFormation::Stack  Mon Aug 12 2019 23:23:31 GMT+0000 (Coordinated Universal Time)
UPDATE_IN_PROGRESS FunctionDirectiveStack AWS::CloudFormation::Stack  Mon Aug 12 2019 23:23:31 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:23:52.100Z [INFO]:
2019-08-12T23:23:52.102Z [INFO]: UPDATE_IN_PROGRESS                           InvokeWeatherLambdaDataSource                                                                   AWS::AppSync::FunctionConfiguration Mon Aug 12 2019 23:23:47 GMT+0000 (Coordinated Universal Time)
UPDATE_COMPLETE                              InvokeWeatherLambdaDataSource                                                                   AWS::AppSync::FunctionConfiguration Mon Aug 12 2019 23:23:50 GMT+0000 (Coordinated Universal Time)
UPDATE_COMPLETE                              ConferenceweatherResolver                                                                       AWS::AppSync::Resolver              Mon Aug 12 2019 23:23:51 GMT+0000 (Coordinated Universal Time)
UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS conf-weather-dev-20190812225817-apiconfweather-CJ4TKER9E741-FunctionDirectiveStack-8YJDFM7X5EBK AWS::CloudFormation::Stack          Mon Aug 12 2019 23:23:51 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:23:52.210Z [INFO]:
2019-08-12T23:23:52.211Z [INFO]: UPDATE_COMPLETE                              GetConferenceResolver                                                               AWS::AppSync::Resolver     Mon Aug 12 2019 23:23:48 GMT+0000 (Coordinated Universal Time)
UPDATE_COMPLETE                              DeleteConferenceResolver                                                            AWS::AppSync::Resolver     Mon Aug 12 2019 23:23:48 GMT+0000 (Coordinated Universal Time)
UPDATE_COMPLETE                              ConferenceTable                                                                     AWS::DynamoDB::Table       Mon Aug 12 2019 23:23:48 GMT+0000 (Coordinated Universal Time)
UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS conf-weather-dev-20190812225817-apiconfweather-CJ4TKER9E741-Conference-8WEWZC4QTMIL AWS::CloudFormation::Stack Mon Aug 12 2019 23:23:48 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:23:56.921Z [INFO]:
2019-08-12T23:23:56.924Z [INFO]: UPDATE_COMPLETE                              Conference                                                  AWS::CloudFormation::Stack Mon Aug 12 2019 23:23:53 GMT+0000 (Coordinated Universal Time)
UPDATE_COMPLETE                              FunctionDirectiveStack                                      AWS::CloudFormation::Stack Mon Aug 12 2019 23:23:53 GMT+0000 (Coordinated Universal Time)
UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS conf-weather-dev-20190812225817-apiconfweather-CJ4TKER9E741 AWS::CloudFormation::Stack Mon Aug 12 2019 23:23:55 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:24:11.832Z [INFO]:
2019-08-12T23:24:11.833Z [INFO]: UPDATE_COMPLETE                              apiconfweather                  AWS::CloudFormation::Stack Mon Aug 12 2019 23:24:07 GMT+0000 (Coordinated Universal Time)
UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS conf-weather-dev-20190812225817 AWS::CloudFormation::Stack Mon Aug 12 2019 23:24:07 GMT+0000 (Coordinated Universal Time)
UPDATE_IN_PROGRESS                           apiconfweather                  AWS::CloudFormation::Stack Mon Aug 12 2019 23:24:08 GMT+0000 (Coordinated Universal Time)
UPDATE_IN_PROGRESS                           functionweather                 AWS::CloudFormation::Stack Mon Aug 12 2019 23:24:08 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:24:11.891Z [INFO]:
2019-08-12T23:24:11.894Z [INFO]: UPDATE_ROLLBACK_COMPLETE conf-weather-dev-20190812225817-functionweather-1TSECBPID1P0O AWS::CloudFormation::Stack Mon Aug 12 2019 23:24:09 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:24:21.845Z [INFO]:
2019-08-12T23:24:21.847Z [INFO]: UPDATE_COMPLETE functionweather AWS::CloudFormation::Stack Mon Aug 12 2019 23:24:19 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:24:22.048Z [INFO]:
2019-08-12T23:24:22.049Z [INFO]: UPDATE_IN_PROGRESS       Conference                                                  AWS::CloudFormation::Stack Mon Aug 12 2019 23:24:09 GMT+0000 (Coordinated Universal Time)
UPDATE_IN_PROGRESS       FunctionDirectiveStack                                      AWS::CloudFormation::Stack Mon Aug 12 2019 23:24:09 GMT+0000 (Coordinated Universal Time)
UPDATE_COMPLETE          Conference                                                  AWS::CloudFormation::Stack Mon Aug 12 2019 23:24:20 GMT+0000 (Coordinated Universal Time)
UPDATE_COMPLETE          FunctionDirectiveStack                                      AWS::CloudFormation::Stack Mon Aug 12 2019 23:24:20 GMT+0000 (Coordinated Universal Time)
UPDATE_ROLLBACK_COMPLETE conf-weather-dev-20190812225817-apiconfweather-CJ4TKER9E741 AWS::CloudFormation::Stack Mon Aug 12 2019 23:24:20 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:24:22.207Z [INFO]:
2019-08-12T23:24:22.207Z [INFO]: UPDATE_ROLLBACK_COMPLETE conf-weather-dev-20190812225817-apiconfweather-CJ4TKER9E741-FunctionDirectiveStack-8YJDFM7X5EBK AWS::CloudFormation::Stack Mon Aug 12 2019 23:24:10 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:24:31.855Z [INFO]:
2019-08-12T23:24:31.857Z [INFO]: UPDATE_COMPLETE          apiconfweather                  AWS::CloudFormation::Stack Mon Aug 12 2019 23:24:30 GMT+0000 (Coordinated Universal Time)
UPDATE_ROLLBACK_COMPLETE conf-weather-dev-20190812225817 AWS::CloudFormation::Stack Mon Aug 12 2019 23:24:30 GMT+0000 (Coordinated Universal Time)
2019-08-12T23:24:41.991Z [WARNING]: Error updating cloudformation stack
2019-08-12T23:24:42.071Z [INFO]: Following resources failed
2019-08-12T23:24:42.073Z [INFO]: Resource Name: arn:aws:appsync:eu-west-1:693340411157:apis/zpgb2rzmqnfwnabcrnfrtti2qu/types/Mutation/resolvers/deleteConference (AWS::AppSync::Resolver)
Event Type: update
Reason: Resource update cancelled
URL: https://console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stacks/arn%3Aaws%3Acloudformation%3Aeu-west-1%3A693340411157%3Astack%2Fconf-weather-dev-20190812225817-apiconfweather-CJ4TKER9E741-Conference-8WEWZC4QTMIL%2Fadf02a00-bd4d-11e9-b172-0254d350c81a/events
Resource Name: arn:aws:appsync:eu-west-1:693340411157:apis/zpgb2rzmqnfwnabcrnfrtti2qu/types/Query/resolvers/getConference (AWS::AppSync::Resolver)
Event Type: update
Reason: Resource update cancelled
URL: https://console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stacks/arn%3Aaws%3Acloudformation%3Aeu-west-1%3A693340411157%3Astack%2Fconf-weather-dev-20190812225817-apiconfweather-CJ4TKER9E741-Conference-8WEWZC4QTMIL%2Fadf02a00-bd4d-11e9-b172-0254d350c81a/events
Resource Name: Conference-zpgb2rzmqnfwnabcrnfrtti2qu (AWS::DynamoDB::Table)
Event Type: update
Reason: CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename Conference-zpgb2rzmqnfwnabcrnfrtti2qu-dev and update the stack again.
URL: https://console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stacks/arn%3Aaws%3Acloudformation%3Aeu-west-1%3A693340411157%3Astack%2Fconf-weather-dev-20190812225817-apiconfweather-CJ4TKER9E741-Conference-8WEWZC4QTMIL%2Fadf02a00-bd4d-11e9-b172-0254d350c81a/events
Resource Name: arn:aws:appsync:eu-west-1:693340411157:apis/zpgb2rzmqnfwnabcrnfrtti2qu/types/Conference/resolvers/weather (AWS::AppSync::Resolver)
Event Type: update
Reason: Resource update cancelled
URL: https://console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stacks/arn%3Aaws%3Acloudformation%3Aeu-west-1%3A693340411157%3Astack%2Fconf-weather-dev-20190812225817-apiconfweather-CJ4TKER9E741-FunctionDirectiveStack-8YJDFM7X5EBK%2Fadee0720-bd4d-11e9-aaac-06c34fd08df4/events
init failed
2019-08-12T23:24:42.074Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
   ✖ There was an error initializing your environment.
2019-08-12T23:24:42.076Z [INFO]: { ResourceNotReady: Resource is not in the state stackUpdateComplete
at constructor.setError (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/resource_waiter.js:182:47)
at Request.CHECK_ACCEPTORS (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/resource_waiter.js:44:12)
at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
message: 'Resource is not in the state stackUpdateComplete',
code: 'ResourceNotReady',
retryable: false,
time: 2019-08-12T23:24:41.990Z,
statusCode: 200,
retryDelay: 30000 }
2019-08-12T23:24:42.129Z [ERROR]: !!! Build failed
2019-08-12T23:24:42.129Z [ERROR]: !!! Non-Zero Exit Code detected
2019-08-12T23:24:42.129Z [INFO]: # Starting environment caching...
2019-08-12T23:24:42.130Z [INFO]: # Environment caching completed
Terminating logging...
```

Thanks a lot.

**Comment by JamieMason** [comment]
Closing as the stacks etc no longer exist. Based on [this comment in aws-amplify/amplify-cli](https://github.com/aws-amplify/amplify-cli/issues/373#issuecomment-434408098) I will try removing all resources created in AWS and recreate the project using Node.js 8.16.0.
