### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir on Console Build

### ISSUE THREAD

**Issue by KrustyHack** [aws-amplify/amplify-console#503]
Ay,

My Amplify Console build doesn't work anymore :+1: 

```
2020-03-10T21:31:26.828Z [INFO]: { Error: ENOENT: no such file or directory, scandir '/codebuild/output/src648673267/src/ssl-dog-angular-application/amplify/backend/function/ssldoga252f29d'
                                 at Object.readdirSync (fs.js:790:3)
                                 at validateCfnTemplates (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:198:22)
                                 at Object.run (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:35:5)
                                 at Object.pushResources (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/index.js:39:25)
                                 at providerPushTasks.push (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/initialize-env.js:64:61)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
                                 errno: -2,
                                 syscall: 'scandir',
                                 code: 'ENOENT',
                                 path:
                                 '/codebuild/output/src648673267/src/ssl-dog-angular-application/amplify/backend/function/ssldoga252f29d' }
```

This function `ssldoga252f29d` doesn't exist anymore in my Amplify project. I have removed it and did `amplify push`.

But it seems still in my `backend-config.json`, and it come back each time I do `amplify pull` : 

```
	"function": {
		"ssldoga252f29d": {
			"service": "Lambda",
			"providerPlugin": "awscloudformation",
			"build": true
		}
	}
```

How is it possible ?

**Comment by KrustyHack** [comment]
Ay,

Problem fixed. I don't know how but after deleting, recloning my local repo and playing around with `amplify push` and `amplify pull` it works fine now...

**Comment by ohsik** [comment]
I think I'm having the same issue but not sure what to do haha

**Comment by KrustyHack** [comment]
Ay @ohsik,

Unfortunately I can't help you a lot. As I said I made lof of manipulations and tadaaaa it worked again... :'D

Maybe try recloning the repo and playing with `amplify pull/push` as I did ?

**Comment by catherine-augustine** [comment]
I too have this same issue . Not sure how I can resolve.
