### ISSUE TITLE
Console bug when clicking Retry button for failed Domain configuration

### ISSUE THREAD

**Issue by brettstack** [aws-amplify/amplify-console#512]
**Issue/question**
Failed "Domain Activation" step. Clicking "Retry" button does nothing and shows the following error message in the developer console.

**Error message**

```
main.js:41 Uncaught TypeError: Cannot read property 'isFailed' of undefined
    at main.js:41
    at Array.filter (<anonymous>)
    at main.js:41
    at Array.forEach (<anonymous>)
    at t.n.getFailedOps (main.js:41)
    at t.render (main.js:41)
    at d._renderValidatedComponentWithoutOwnerOrContext (main.js:102)
    at d._renderValidatedComponent (main.js:102)
    at d._updateRenderedComponent (main.js:102)
    at d._performComponentUpdate (main.js:102)
(anonymous) @ main.js:41
(anonymous) @ main.js:41
n.getFailedOps @ main.js:41
t.render @ main.js:41
_renderValidatedComponentWithoutOwnerOrContext @ main.js:102
_renderValidatedComponent @ main.js:102
_updateRenderedComponent @ main.js:102
_performComponentUpdate @ main.js:102
updateComponent @ main.js:102
receiveComponent @ main.js:102
receiveComponent @ main.js:41
_updateRenderedComponent @ main.js:102
_performComponentUpdate @ main.js:102
updateComponent @ main.js:102
receiveComponent @ main.js:102
receiveComponent @ main.js:41
_updateRenderedComponent @ main.js:102
_performComponentUpdate @ main.js:102
updateComponent @ main.js:102
performUpdateIfNecessary @ main.js:102
performUpdateIfNecessary @ main.js:41
s @ main.js:35
perform @ main.js:41
perform @ main.js:41
perform @ main.js:35
U @ main.js:35
closeAll @ main.js:41
perform @ main.js:41
batchedUpdates @ main.js:102
l @ main.js:35
r @ main.js:41
enqueueSetState @ main.js:41
r.setState @ main.js:81
d.onStateChange @ main.js:81
notify @ main.js:102
e.notifyNestedSubs @ main.js:102
d.onStateChange @ main.js:81
notify @ main.js:102
e.notifyNestedSubs @ main.js:102
d.onStateChange @ main.js:81
notify @ main.js:102
e.notifyNestedSubs @ main.js:102
d.onStateChange @ main.js:81
notify @ main.js:102
e.notifyNestedSubs @ main.js:102
d.onStateChange @ main.js:81
d @ main.js:81
(anonymous) @ main.js:102
(anonymous) @ main.js:102
onClick @ main.js:55
wrappedCallback @ main.js:30
r @ main.js:29
t @ main.js:29
c @ main.js:8
Show 24 more frames
main.js:35 uncaught at o TypeError: Cannot read property 'isFailed' of undefined
    at https://d2ehysm26eepwv.cloudfront.net/8b336fdb8cf81f046d9d8502971739819164e4c3/main.js:41:77540
    at Array.filter (<anonymous>)
    at https://d2ehysm26eepwv.cloudfront.net/8b336fdb8cf81f046d9d8502971739819164e4c3/main.js:41:77485
    at Array.forEach (<anonymous>)
    at t.n.getFailedOps (https://d2ehysm26eepwv.cloudfront.net/8b336fdb8cf81f046d9d8502971739819164e4c3/main.js:41:77434)
    at t.render (https://d2ehysm26eepwv.cloudfront.net/8b336fdb8cf81f046d9d8502971739819164e4c3/main.js:41:78263)
    at d._renderValidatedComponentWithoutOwnerOrContext (https://d2ehysm26eepwv.cloudfront.net/8b336fdb8cf81f046d9d8502971739819164e4c3/main.js:102:327322)
    at d._renderValidatedComponent (https://d2ehysm26eepwv.cloudfront.net/8b336fdb8cf81f046d9d8502971739819164e4c3/main.js:102:327449)
    at d._updateRenderedComponent (https://d2ehysm26eepwv.cloudfront.net/8b336fdb8cf81f046d9d8502971739819164e4c3/main.js:102:326753)
    at d._performComponentUpdate (https://d2ehysm26eepwv.cloudfront.net/8b336fdb8cf81f046d9d8502971739819164e4c3/main.js:102:326554)
```

**Comment by kahdojay** [comment]
@brettstack Thanks for reporting this - we've added this to our backlog and will need to prioritize a fix.

Can you provide a little more context, e.g. were there any other errors in the process? (for example, CNAME already associated with existing resource).

In the meantime, a workaround may be to delete and recreate the domain in the Amplify Console. Please let us know if this helps or if you have any other questions.

**Comment by brettstack** [comment]
I forget what the error in the process was, and yes I just deleted and recreated.

**Comment by OzzieOrca** [comment]
Happened to me too. I was trying to migrate a domain off a custom Cloudfront setup to Amplify. Doesn't tell me which CNAME is conflicting and the retry button throws this error. I've deleted the domain from Amplify and readded it several times but I've deleted all the CNAME records I feel comfortable with without breaking other services and am still getting the error.

**Comment by OzzieOrca** [comment]
I finally found the error. If you previously had a domain setup with Cloudfront, you have to go **into the Cloudfront console** and delete the domain from the **Alternate Domain Names
(CNAMEs)** field (under the general tab).

I made a PR to the docs at https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error. I wasted several hours trying to delete things out of the Route53 console... 😞 

I think it would be helpful for the Amplify console to state which domain/subdomain the conflict is with and also add messaging that you have to make changes **in the Cloudfront console**.

**Comment by swaminator** [comment]
This has been fixed. Closing.
