### ISSUE TITLE
Not able to build in amplify (See Log below)

### ISSUE THREAD

**Issue by kakriti007** [aws-amplify/amplify-console#536]
I was trying to build using amplify, but I am getting the following error over and over again.

Can someone help me understand where I am going wrong?

2020-03-23T03:07:38.499Z [INFO]: Git SSH Key acquired
2020-03-23T03:07:38.569Z [INFO]: # Cloning repository: git@github.com:kakriti007/developerCode.git
2020-03-23T03:07:38.742Z [INFO]: Agent pid 122
2020-03-23T03:07:38.766Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2020-03-23T03:07:38.981Z [INFO]: Cloning into 'developerCode'...
2020-03-23T03:07:39.254Z [INFO]: Warning: Permanently added the RSA host key for IP address '192.30.255.113' to the list of known hosts.
2020-03-23T03:07:46.121Z [INFO]: Checking out files:  39% (26675/66880)
2020-03-23T03:07:46.164Z [INFO]: Checking out files:  40% (26752/66880)
2020-03-23T03:07:46.270Z [INFO]: Checking out files:  41% (27421/66880)
2020-03-23T03:07:46.383Z [INFO]: Checking out files:  42% (28090/66880)
2020-03-23T03:07:46.452Z [INFO]: Checking out files:  43% (28759/66880)
2020-03-23T03:07:46.482Z [INFO]: Checking out files:  44% (29428/66880)
2020-03-23T03:07:46.535Z [INFO]: Checking out files:  45% (30096/66880)
2020-03-23T03:07:46.591Z [INFO]: Checking out files:  46% (30765/66880)
2020-03-23T03:07:46.605Z [INFO]: Checking out files:  47% (31434/66880)
2020-03-23T03:07:46.645Z [INFO]: Checking out files:  48% (32103/66880)
2020-03-23T03:07:46.667Z [INFO]: Checking out files:  49% (32772/66880)
2020-03-23T03:07:46.677Z [INFO]: Checking out files:  50% (33440/66880)
2020-03-23T03:07:46.692Z [INFO]: Checking out files:  51% (34109/66880)
2020-03-23T03:07:46.701Z [INFO]: Checking out files:  52% (34778/66880)
2020-03-23T03:07:46.712Z [INFO]: Checking out files:  53% (35447/66880)
2020-03-23T03:07:46.728Z [INFO]: Checking out files:  54% (36116/66880)
2020-03-23T03:07:46.763Z [INFO]: Checking out files:  55% (36784/66880)
2020-03-23T03:07:46.785Z [INFO]: Checking out files:  56% (37453/66880)
2020-03-23T03:07:46.860Z [INFO]: Checking out files:  57% (38122/66880)
2020-03-23T03:07:46.915Z [INFO]: Checking out files:  58% (38791/66880)
2020-03-23T03:07:46.991Z [INFO]: Checking out files:  59% (39460/66880)
2020-03-23T03:07:47.012Z [INFO]: Checking out files:  60% (40128/66880)
2020-03-23T03:07:47.023Z [INFO]: Checking out files:  61% (40797/66880)
2020-03-23T03:07:47.038Z [INFO]: Checking out files:  62% (41466/66880)
2020-03-23T03:07:47.060Z [INFO]: Checking out files:  63% (42135/66880)
2020-03-23T03:07:47.079Z [INFO]: Checking out files:  64% (42804/66880)
2020-03-23T03:07:47.100Z [INFO]: Checking out files:  65% (43472/66880)
2020-03-23T03:07:47.110Z [INFO]: Checking out files:  66% (44141/66880)
2020-03-23T03:07:47.121Z [INFO]: Checking out files:  66% (44758/66880)
2020-03-23T03:07:47.122Z [INFO]: Checking out files:  67% (44810/66880)
2020-03-23T03:07:47.137Z [INFO]: Checking out files:  68% (45479/66880)
2020-03-23T03:07:47.167Z [INFO]: Checking out files:  69% (46148/66880)
2020-03-23T03:07:47.205Z [INFO]: Checking out files:  70% (46816/66880)
2020-03-23T03:07:47.224Z [INFO]: Checking out files:  71% (47485/66880)
2020-03-23T03:07:47.249Z [INFO]: Checking out files:  72% (48154/66880)
2020-03-23T03:07:47.280Z [INFO]: Checking out files:  73% (48823/66880)
2020-03-23T03:07:47.308Z [INFO]: Checking out files:  74% (49492/66880)
2020-03-23T03:07:47.341Z [INFO]: Checking out files:  75% (50160/66880)
2020-03-23T03:07:47.376Z [INFO]: Checking out files:  76% (50829/66880)
2020-03-23T03:07:47.389Z [INFO]: Checking out files:  77% (51498/66880)
2020-03-23T03:07:47.404Z [INFO]: Checking out files:  78% (52167/66880)
2020-03-23T03:07:47.419Z [INFO]: Checking out files:  79% (52836/66880)
2020-03-23T03:07:47.450Z [INFO]: Checking out files:  80% (53504/66880)
2020-03-23T03:07:47.480Z [INFO]: Checking out files:  81% (54173/66880)
2020-03-23T03:07:47.507Z [INFO]: Checking out files:  82% (54842/66880)
2020-03-23T03:07:47.524Z [INFO]: Checking out files:  83% (55511/66880)
2020-03-23T03:07:47.536Z [INFO]: Checking out files:  84% (56180/66880)
2020-03-23T03:07:47.547Z [INFO]: Checking out files:  85% (56848/66880)
2020-03-23T03:07:47.557Z [INFO]: Checking out files:  86% (57517/66880)
2020-03-23T03:07:47.573Z [INFO]: Checking out files:  87% (58186/66880)
2020-03-23T03:07:47.584Z [INFO]: Checking out files:  88% (58855/66880)
2020-03-23T03:07:47.595Z [INFO]: Checking out files:  89% (59524/66880)
2020-03-23T03:07:47.607Z [INFO]: Checking out files:  90% (60192/66880)
2020-03-23T03:07:47.618Z [INFO]: Checking out files:  91% (60861/66880)
2020-03-23T03:07:47.627Z [INFO]: Checking out files:  92% (61530/66880)
2020-03-23T03:07:47.637Z [INFO]: Checking out files:  93% (62199/66880)
2020-03-23T03:07:47.662Z [INFO]: Checking out files:  94% (62868/66880)
2020-03-23T03:07:47.689Z [INFO]: Checking out files:  95% (63536/66880)
2020-03-23T03:07:47.710Z [INFO]: Checking out files:  96% (64205/66880)
2020-03-23T03:07:47.744Z [INFO]: Checking out files:  97% (64874/66880)
2020-03-23T03:07:47.865Z [INFO]: Checking out files:  98% (65543/66880)
2020-03-23T03:07:47.888Z [INFO]: Checking out files:  99% (66212/66880)
2020-03-23T03:07:47.919Z [INFO]: Checking out files: 100% (66880/66880)
2020-03-23T03:07:47.920Z [INFO]: Checking out files: 100% (66880/66880), done.
2020-03-23T03:07:48.002Z [INFO]: # Checking for Git submodules at: /codebuild/output/src033199703/src/developerCode/.gitmodules
2020-03-23T03:07:48.028Z [INFO]: # Retrieving cache...
2020-03-23T03:07:48.050Z [INFO]: # Extracting cache...
2020-03-23T03:07:48.058Z [INFO]: # Extraction completed
2020-03-23T03:07:48.058Z [INFO]: # Retrieving environment cache...
2020-03-23T03:07:48.076Z [INFO]: # Retrieved environment cache
2020-03-23T03:07:48.077Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2020-03-23T03:07:55.987Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 1.12.0 to 4.17.1...
2020-03-23T03:08:39.585Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
2020-03-23T03:08:46.736Z [INFO]: ## Starting Frontend Build
                                 # Starting phase: preBuild
                                 # Executing command: npm ci
2020-03-23T03:08:47.142Z [WARNING]: npm
2020-03-23T03:08:47.142Z [WARNING]: WARN prepare removing existing node_modules/ before installation
2020-03-23T03:09:03.276Z [INFO]: > fsevents@1.2.12 install /codebuild/output/src033199703/src/developerCode/node_modules/@angular-devkit/core/node_modules/fsevents
                                 > node-gyp rebuild
2020-03-23T03:09:03.389Z [WARNING]: gyp
2020-03-23T03:09:03.390Z [WARNING]: info it worked if it ends with ok
2020-03-23T03:09:03.391Z [WARNING]: gyp
2020-03-23T03:09:03.392Z [WARNING]: info using node-gyp@3.8.0
                                    gyp info using node@10.16.0 | linux | x64
2020-03-23T03:09:04.191Z [WARNING]: gyp info
2020-03-23T03:09:04.191Z [WARNING]: spawn /usr/bin/python2
                                    gyp info spawn args [ '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
                                    gyp info spawn args   'binding.gyp',
                                    gyp info spawn args   '-f',
                                    gyp info spawn args   'make',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/codebuild/output/src033199703/src/developerCode/node_modules/@angular-devkit/core/node_modules/fsevents/build/config.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
                                    gyp info
2020-03-23T03:09:04.191Z [WARNING]: spawn args   '-I',
                                    gyp info spawn args   '/root/.node-gyp/10.16.0/include/node/common.gypi',
                                    gyp info spawn args   '-Dlibrary=shared_library',
                                    gyp info spawn args   '-Dvisibility=default',
                                    gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.16.0',
                                    gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp',
                                    gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/10.16.0/<(target_arch)/node.lib',
                                    gyp info
2020-03-23T03:09:04.192Z [WARNING]: spawn args   '-Dmodule_root_dir=/codebuild/output/src033199703/src/developerCode/node_modules/@angular-devkit/core/node_modules/fsevents',
                                    gyp info spawn args   '-Dnode_engine=v8',
                                    gyp info spawn args   '--depth=.',
                                    gyp info spawn args   '--no-parallel',
                                    gyp info spawn args   '--generator-output',
                                    gyp info spawn args
2020-03-23T03:09:04.192Z [WARNING]: 'build',
                                    gyp info spawn args   '-Goutput_dir=.' ]
2020-03-23T03:09:05.714Z [WARNING]: gyp
2020-03-23T03:09:05.715Z [WARNING]: info spawn make
                                    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2020-03-23T03:09:05.716Z [INFO]: make: Entering directory `/codebuild/output/src033199703/src/developerCode/node_modules/@angular-devkit/core/node_modules/fsevents/build'
2020-03-23T03:09:05.717Z [INFO]: SOLINK_MODULE(target) Release/obj.target/.node
2020-03-23T03:09:06.129Z [INFO]: COPY Release/.node
2020-03-23T03:09:06.135Z [INFO]: make: Leaving directory `/codebuild/output/src033199703/src/developerCode/node_modules/@angular-devkit/core/node_modules/fsevents/build'
2020-03-23T03:09:06.135Z [WARNING]: gyp info
2020-03-23T03:09:06.136Z [WARNING]: ok
2020-03-23T03:09:06.227Z [INFO]: > fsevents@1.2.12 install /codebuild/output/src033199703/src/developerCode/node_modules/webpack-dev-server/node_modules/fsevents
                                 > node-gyp rebuild
2020-03-23T03:09:06.315Z [WARNING]: gyp
2020-03-23T03:09:06.315Z [WARNING]: 
2020-03-23T03:09:06.315Z [WARNING]: info it worked if it ends with ok
2020-03-23T03:09:06.317Z [WARNING]: gyp
2020-03-23T03:09:06.317Z [WARNING]: info using node-gyp@3.8.0
                                    gyp info using node@10.16.0 | linux | x64
2020-03-23T03:09:06.443Z [WARNING]: gyp
2020-03-23T03:09:06.444Z [WARNING]: info spawn /usr/bin/python2
                                    gyp info spawn args [ '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
                                    gyp info spawn args   'binding.gyp',
                                    gyp info spawn args   '-f',
                                    gyp info spawn args   'make',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/codebuild/output/src033199703/src/developerCode/node_modules/webpack-dev-server/node_modules/fsevents/build/config.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.node-gyp/10.16.0/include/node/common.gypi',
                                    gyp info spawn args   '-Dlibrary=shared_library',
                                    gyp info spawn args   '-Dvisibility=default',
                                    gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.16.0',
                                    gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp',
                                    gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/10.16.0/<(target_arch)/node.lib',
                                    gyp info spawn args   '-Dmodule_root_dir=/codebuild/output/src033199703/src/developerCode/node_modules/webpack-dev-server/node_modules/fsevents',
                                    gyp info spawn args   '-Dnode_engine=v8',
                                    gyp
2020-03-23T03:09:06.444Z [WARNING]: info spawn args   '--depth=.',
                                    gyp info spawn args   '--no-parallel',
                                    gyp info spawn args   '--generator-output',
                                    gyp info spawn args   'build',
                                    gyp info spawn args   '-Goutput_dir=.' ]
2020-03-23T03:09:06.487Z [WARNING]: gyp
2020-03-23T03:09:06.488Z [WARNING]: info spawn make
                                    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2020-03-23T03:09:06.489Z [INFO]: make: Entering directory `/codebuild/output/src033199703/src/developerCode/node_modules/webpack-dev-server/node_modules/fsevents/build'
2020-03-23T03:09:06.490Z [INFO]: SOLINK_MODULE(target) Release/obj.target/.node
2020-03-23T03:09:06.534Z [INFO]: COPY Release/.node
2020-03-23T03:09:06.540Z [INFO]: make: Leaving directory `/codebuild/output/src033199703/src/developerCode/node_modules/webpack-dev-server/node_modules/fsevents/build'
2020-03-23T03:09:06.541Z [WARNING]: gyp
2020-03-23T03:09:06.541Z [WARNING]: info ok
2020-03-23T03:09:06.583Z [INFO]: > fsevents@1.2.12 install /codebuild/output/src033199703/src/developerCode/node_modules/watchpack/node_modules/fsevents
                                 > node-gyp rebuild
2020-03-23T03:09:06.669Z [WARNING]: gyp
2020-03-23T03:09:06.669Z [WARNING]: 
2020-03-23T03:09:06.670Z [WARNING]: info it worked if it ends with ok
2020-03-23T03:09:06.671Z [WARNING]: gyp
2020-03-23T03:09:06.671Z [WARNING]: info using node-gyp@3.8.0
                                    gyp info using node@10.16.0 | linux | x64
2020-03-23T03:09:06.801Z [WARNING]: gyp
2020-03-23T03:09:06.801Z [WARNING]: info spawn /usr/bin/python2
                                    gyp info spawn args [ '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
                                    gyp info spawn args   'binding.gyp',
                                    gyp info spawn args   '-f',
                                    gyp info spawn args   'make',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/codebuild/output/src033199703/src/developerCode/node_modules/watchpack/node_modules/fsevents/build/config.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.node-gyp/10.16.0/include/node/common.gypi',
                                    gyp info spawn args   '-Dlibrary=shared_library',
                                    gyp info spawn args   '-Dvisibility=default',
                                    gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.16.0',
                                    gyp info spawn args
2020-03-23T03:09:06.802Z [WARNING]: '-Dnode_gyp_dir=/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp',
                                    gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/10.16.0/<(target_arch)/node.lib',
                                    gyp info spawn args   '-Dmodule_root_dir=/codebuild/output/src033199703/src/developerCode/node_modules/watchpack/node_modules/fsevents',
                                    gyp info spawn args   '-Dnode_engine=v8',
                                    gyp info spawn args   '--depth=.',
                                    gyp info spawn args   '--no-parallel',
                                    gyp info spawn args   '--generator-output',
                                    gyp info spawn args   'build',
                                    gyp info spawn args   '-Goutput_dir=.' ]
2020-03-23T03:09:06.845Z [WARNING]: gyp
2020-03-23T03:09:06.845Z [WARNING]: info spawn make
                                    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2020-03-23T03:09:06.846Z [INFO]: make: Entering directory `/codebuild/output/src033199703/src/developerCode/node_modules/watchpack/node_modules/fsevents/build'
2020-03-23T03:09:06.847Z [INFO]: SOLINK_MODULE(target) Release/obj.target/.node
2020-03-23T03:09:06.892Z [INFO]: COPY Release/.node
2020-03-23T03:09:06.898Z [INFO]: make: Leaving directory `/codebuild/output/src033199703/src/developerCode/node_modules/watchpack/node_modules/fsevents/build'
2020-03-23T03:09:06.898Z [WARNING]: gyp
2020-03-23T03:09:06.899Z [WARNING]: info ok
2020-03-23T03:09:06.998Z [INFO]: > node-sass@4.10.0 install /codebuild/output/src033199703/src/developerCode/node_modules/node-sass
                                 > node scripts/install.js
2020-03-23T03:09:07.758Z [INFO]: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.10.0/linux-x64-64_binding.node
2020-03-23T03:09:08.704Z [INFO]: Download complete
2020-03-23T03:09:08.707Z [INFO]: Binary saved to /codebuild/output/src033199703/src/developerCode/node_modules/node-sass/vendor/linux-x64-64/binding.node
2020-03-23T03:09:08.744Z [INFO]: > node-sass@4.10.0 postinstall /codebuild/output/src033199703/src/developerCode/node_modules/node-sass
                                 > node scripts/build.js
2020-03-23T03:09:08.879Z [INFO]: Binary found at /codebuild/output/src033199703/src/developerCode/node_modules/node-sass/vendor/linux-x64-64/binding.node
2020-03-23T03:09:08.880Z [INFO]: Testing binary
2020-03-23T03:09:08.952Z [INFO]: Binary is fine
2020-03-23T03:09:08.968Z [INFO]: > core-js@2.6.11 postinstall /codebuild/output/src033199703/src/developerCode/node_modules/babel-runtime/node_modules/core-js
                                 > node -e "try{require('./postinstall')}catch(e){}"
2020-03-23T03:09:09.151Z [INFO]: > fsevents@1.2.12 install /codebuild/output/src033199703/src/developerCode/node_modules/@angular/cli/node_modules/fsevents
                                 > node-gyp rebuild
2020-03-23T03:09:09.243Z [WARNING]: gyp
2020-03-23T03:09:09.243Z [WARNING]: 
2020-03-23T03:09:09.243Z [WARNING]: info it worked if it ends with ok
2020-03-23T03:09:09.245Z [WARNING]: gyp
2020-03-23T03:09:09.245Z [WARNING]: info using node-gyp@3.8.0
                                    gyp info using node@10.16.0 | linux | x64
2020-03-23T03:09:09.377Z [WARNING]: gyp
2020-03-23T03:09:09.378Z [WARNING]: info spawn /usr/bin/python2
                                    gyp info spawn args [ '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
                                    gyp info spawn args   'binding.gyp',
                                    gyp info spawn args   '-f',
                                    gyp info spawn args   'make',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/codebuild/output/src033199703/src/developerCode/node_modules/@angular/cli/node_modules/fsevents/build/config.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.node-gyp/10.16.0/include/node/common.gypi',
                                    gyp info spawn args   '-Dlibrary=shared_library',
                                    gyp info spawn args   '-Dvisibility=default',
                                    gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.16.0',
                                    gyp info
2020-03-23T03:09:09.378Z [WARNING]: spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp',
                                    gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/10.16.0/<(target_arch)/node.lib',
                                    gyp info spawn args   '-Dmodule_root_dir=/codebuild/output/src033199703/src/developerCode/node_modules/@angular/cli/node_modules/fsevents',
                                    gyp info spawn args   '-Dnode_engine=v8',
                                    gyp info spawn args   '--depth=.',
                                    gyp info spawn args   '--no-parallel',
                                    gyp info spawn args   '--generator-output',
                                    gyp info spawn args   'build',
                                    gyp info spawn args   '-Goutput_dir=.' ]
2020-03-23T03:09:09.422Z [WARNING]: gyp
2020-03-23T03:09:09.423Z [WARNING]: info spawn make
                                    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2020-03-23T03:09:09.424Z [INFO]: make: Entering directory `/codebuild/output/src033199703/src/developerCode/node_modules/@angular/cli/node_modules/fsevents/build'
2020-03-23T03:09:09.424Z [INFO]: SOLINK_MODULE(target) Release/obj.target/.node
2020-03-23T03:09:09.471Z [INFO]: COPY Release/.node
2020-03-23T03:09:09.477Z [INFO]: make: Leaving directory `/codebuild/output/src033199703/src/developerCode/node_modules/@angular/cli/node_modules/fsevents/build'
2020-03-23T03:09:09.477Z [WARNING]: gyp
2020-03-23T03:09:09.478Z [WARNING]: info ok
2020-03-23T03:09:09.551Z [INFO]: > core-js@3.6.4 postinstall /codebuild/output/src033199703/src/developerCode/node_modules/core-js
                                 > node -e "try{require('./postinstall')}catch(e){}"
2020-03-23T03:09:09.656Z [INFO]: added 1672 packages in 22.535s
2020-03-23T03:09:09.669Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
2020-03-23T03:09:09.670Z [INFO]: # Executing command: npm run build
2020-03-23T03:09:09.849Z [INFO]: > new-impact@0.0.0 build /codebuild/output/src033199703/src/developerCode
                                 > ng build
2020-03-23T03:09:29.094Z [INFO]: Date: 2020-03-23T03:09:29.093Z
                                 Hash: fc6e1f06f0a9610c9579
                                 Time: 16891ms
                                 chunk {main} main.js, main.js.map (main) 92.4 kB [initial] [rendered]
                                 chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 175 kB [initial] [rendered]
                                 chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
                                 chunk {styles} styles.js, styles.js.map (styles) 27.8 kB [initial] [rendered]
                                 chunk {vendor} vendor.js, vendor.js.map (vendor) 13.6 MB [initial] [rendered]
2020-03-23T03:09:29.095Z [INFO]: 
2020-03-23T03:09:29.096Z [WARNING]: ERROR in ./node_modules/d3plus/es/index.js
                                    Module not found: Error: Can't resolve './build/package' in '/codebuild/output/src033199703/src/developerCode/node_modules/d3plus/es'
                                    ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/jit-polyfills.js
                                    Module not found: Error: Can't resolve 'core-js/es7/reflect' in '/codebuild/output/src033199703/src/developerCode/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models'
2020-03-23T03:09:29.146Z [WARNING]: npm
2020-03-23T03:09:29.147Z [WARNING]: ERR! code ELIFECYCLE
                                    npm ERR! errno 1
                                    npm ERR! new-impact@0.0.0 build: `ng build`
                                    npm ERR! Exit status 1
                                    npm ERR!
                                    npm ERR! Failed at the new-impact@0.0.0 build script.
                                    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-03-23T03:09:29.152Z [WARNING]: npm ERR! A complete log of this run can be found in:
                                    npm ERR!     /root/.npm/_logs/2020-03-23T03_09_29_147Z-debug.log
2020-03-23T03:09:29.152Z [HELP]: Outputting the npm debug log
                                 0 info it worked if it ends with ok
                                 1 verbose cli [ '/root/.nvm/versions/node/v10.16.0/bin/node',
                                 1 verbose cli   '/root/.nvm/versions/node/v10.16.0/bin/npm',
                                 1 verbose cli   'run',
                                 1 verbose cli   'build' ]
                                 2 info using npm@6.9.0
                                 3 info using node@v10.16.0
                                 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
                                 5 info lifecycle new-impact@0.0.0~prebuild: new-impact@0.0.0
                                 6 info lifecycle new-impact@0.0.0~build: new-impact@0.0.0
                                 7 verbose lifecycle new-impact@0.0.0~build: unsafe-perm in lifecycle true
                                 8 verbose lifecycle new-impact@0.0.0~build: PATH: /root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/codebuild/output/src033199703/src/developerCode/node_modules/.bin:/usr/local/rvm/gems/ruby-2.4.6/bin:/usr/local/rvm/gems/ruby-2.4.6@global/bin:/usr/local/rvm/rubies/ruby-2.4.6/bin:/usr/local/rvm/bin:/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:/root/.nvm/versions/node/v10.16.0/bin:/root/.local/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
                                 9 verbose lifecycle new-impact@0.0.0~build: CWD: /codebuild/output/src033199703/src/developerCode
                                 10 silly lifecycle new-impact@0.0.0~build: Args: [ '-c', 'ng build' ]
                                 11 silly lifecycle new-impact@0.0.0~build: Returned: code: 1  signal: null
                                 12 info lifecycle new-impact@0.0.0~build: Failed to exec build script
                                 13 verbose stack Error: new-impact@0.0.0 build: `ng build`
                                 13 verbose stack Exit status 1
                                 13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
                                 13 verbose stack     at EventEmitter.emit (events.js:198:13)
                                 13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
                                 13 verbose stack     at ChildProcess.emit (events.js:198:13)
                                 13 verbose stack     at maybeClose (internal/child_process.js:982:16)
                                 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
                                 14 verbose pkgid new-impact@0.0.0
                                 15 verbose cwd /codebuild/output/src033199703/src/developerCode
                                 16 verbose Linux 4.14.165-103.209.amzn1.x86_64
                                 17 verbose argv "/root/.nvm/versions/node/v10.16.0/bin/node" "/root/.nvm/versions/node/v10.16.0/bin/npm" "run" "build"
                                 18 verbose node v10.16.0
                                 19 verbose npm  v6.9.0
                                 20 error code ELIFECYCLE
                                 21 error errno 1
                                 22 error new-impact@0.0.0 build: `ng build`
                                 22 error Exit status 1
                                 23 error Failed at the new-impact@0.0.0 build script.
                                 23 error This is probably not a problem with npm. There is likely additional logging output above.
                                 24 verbose exit [ 1, true ]
2020-03-23T03:09:29.154Z [ERROR]: !!! Build failed
2020-03-23T03:09:29.244Z [ERROR]: !!! Non-Zero Exit Code detected
2020-03-23T03:09:29.244Z [INFO]: # Starting environment caching...
2020-03-23T03:09:29.245Z [INFO]: # Environment caching completed
Terminating logging...

**Comment by Joycehao19** [comment]
Closing this issue, please feel free to reopen it if you have the same issue.
