### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by hanneslehemets** [aws-amplify/amplify-console#575]
**App Id**: d2iv52gbkq2uwx
**Region**: eu-central-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

Something went wrong. Please refer to our troubleshooting guide below to diagnose the issue. After fixing the issue, choose retry below. If retrying fails, please create an issue in our GitHub issue tracker.
Error message: The status of this certificate request is "Failed". One or more domain names have failed validation due to a Certificate Authority Authentication error. Learn more: https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-caa.html

**Comment by hanneslehemets** [comment]
After Retry button click:

main.js:35 uncaught at o TypeError: Cannot read property 'isFailed' of undefined
    at https://dfc9lxyf3efp5.cloudfront.net/b819d3b5c68b2b4c707ab22ecddac77032f74f79/main.js:41:77540
    at Array.filter (<anonymous>)
    at https://dfc9lxyf3efp5.cloudfront.net/b819d3b5c68b2b4c707ab22ecddac77032f74f79/main.js:41:77485
    at Array.forEach (<anonymous>)
    at t.n.getFailedOps (https://dfc9lxyf3efp5.cloudfront.net/b819d3b5c68b2b4c707ab22ecddac77032f74f79/main.js:41:77434)
    at t.render (https://dfc9lxyf3efp5.cloudfront.net/b819d3b5c68b2b4c707ab22ecddac77032f74f79/main.js:41:78263)
    at d._renderValidatedComponentWithoutOwnerOrContext (https://dfc9lxyf3efp5.cloudfront.net/b819d3b5c68b2b4c707ab22ecddac77032f74f79/main.js:102:327316)
    at d._renderValidatedComponent (https://dfc9lxyf3efp5.cloudfront.net/b819d3b5c68b2b4c707ab22ecddac77032f74f79/main.js:102:327443)
    at d._updateRenderedComponent (https://dfc9lxyf3efp5.cloudfront.net/b819d3b5c68b2b4c707ab22ecddac77032f74f79/main.js:102:326747)
    at d._performComponentUpdate (https://dfc9lxyf3efp5.cloudfront.net/b819d3b5c68b2b4c707ab22ecddac77032f74f79/main.js:102:326548)
d @ main.js:35
(anonymous) @ main.js:81
r @ main.js:81
s @ main.js:81
o @ main.js:81
E @ main.js:81
M @ main.js:81
(anonymous) @ main.js:81
k @ main.js:81
M @ main.js:81
b @ main.js:81
r @ main.js:81
Promise.then (async)
C @ main.js:81
U @ main.js:81
M @ main.js:81
b @ main.js:81
s @ main.js:81
T @ main.js:81
M @ main.js:81
b @ main.js:81
s @ main.js:81
T @ main.js:81
U @ main.js:81
M @ main.js:81
b @ main.js:81
r @ main.js:81
t @ main.js:81
r @ main.js:81
Promise.then (async)
C @ main.js:81
M @ main.js:81
(anonymous) @ main.js:81
R @ main.js:81
M @ main.js:81
b @ main.js:81
r @ main.js:81
v @ main.js:81
e.cont @ main.js:81
b @ main.js:81
r @ main.js:81
v @ main.js:81
e.cont @ main.js:81
b @ main.js:81
r @ main.js:81
o @ main.js:81
t @ main.js:81
r @ main.js:81
(anonymous) @ main.js:81
r @ main.js:81
s @ main.js:81
o @ main.js:81
E @ main.js:81
M @ main.js:81
(anonymous) @ main.js:81
k @ main.js:81
M @ main.js:81
b @ main.js:81
r @ main.js:81
Promise.then (async)
C @ main.js:81
U @ main.js:81
M @ main.js:81
b @ main.js:81
s @ main.js:81
T @ main.js:81
M @ main.js:81
b @ main.js:81
s @ main.js:81
T @ main.js:81
U @ main.js:81
M @ main.js:81
b @ main.js:81
r @ main.js:81
t @ main.js:81
r @ main.js:81
Promise.then (async)
C @ main.js:81
M @ main.js:81
(anonymous) @ main.js:81
R @ main.js:81
M @ main.js:81
b @ main.js:81
r @ main.js:81
v @ main.js:81
e.cont @ main.js:81
b @ main.js:81
r @ main.js:81
v @ main.js:81
e.cont @ main.js:81
b @ main.js:81
r @ main.js:81
o @ main.js:81
t @ main.js:81
r @ main.js:81
(anonymous) @ main.js:81
r @ main.js:81
s @ main.js:81
o @ main.js:81
E @ main.js:81
M @ main.js:81
(anonymous) @ main.js:81
k @ main.js:81
M @ main.js:81
b @ main.js:81
r @ main.js:81
Promise.then (async)
C @ main.js:81
U @ main.js:81
M @ main.js:81
b @ main.js:81
s @ main.js:81
T @ main.js:81
M @ main.js:81
b @ main.js:81
s @ main.js:81
T @ main.js:81
U @ main.js:81
M @ main.js:81
b @ main.js:81
r @ main.js:81
t @ main.js:81
r @ main.js:81
Promise.then (async)
C @ main.js:81
M @ main.js:81
(anonymous) @ main.js:81
R @ main.js:81
M @ main.js:81
b @ main.js:81
r @ main.js:81
t @ main.js:81
r @ main.js:81
s @ main.js:81
t @ main.js:41
(anonymous) @ main.js:41
(anonymous) @ main.js:41
t @ main.js:41
(anonymous) @ main.js:102
dispatch @ main.js:102
(anonymous) @ main.js:35
(anonymous) @ main.js:81
r @ main.js:81
s @ main.js:81
o @ main.js:81
E @ main.js:81
M @ main.js:81
(anonymous) @ main.js:81
k @ main.js:81
M @ main.js:81
b @ main.js:81
r @ main.js:81
Promise.then (async)
C @ main.js:81
U @ main.js:81
M @ main.js:81
b @ main.js:81
s @ main.js:81
T @ main.js:81
M @ main.js:81
b @ main.js:81
s @ main.js:81
w @ main.js:81
M @ main.js:81
b @ main.js:81
r @ main.js:81
s @ main.js:81
t @ main.js:41
(anonymous) @ main.js:41
(anonymous) @ main.js:41
r @ main.js:81
s @ main.js:81
o @ main.js:81
(anonymous) @ main.js:41
t @ main.js:41
(anonymous) @ main.js:102
(anonymous) @ main.js:102
t.componentWillMount @ main.js:81
performInitialMount @ main.js:102
mountComponent @ main.js:102
mountComponent @ main.js:41
performInitialMount @ main.js:102
mountComponent @ main.js:102
mountComponent @ main.js:41
performInitialMount @ main.js:102
mountComponent @ main.js:102
mountComponent @ main.js:41
performInitialMount @ main.js:102
mountComponent @ main.js:102
mountComponent @ main.js:41
performInitialMount @ main.js:102
mountComponent @ main.js:102
mountComponent @ main.js:41
performInitialMount @ main.js:102
mountComponent @ main.js:102
mountComponent @ main.js:41
performInitialMount @ main.js:102
mountComponent @ main.js:102
mountComponent @ main.js:41
performInitialMount @ main.js:102
mountComponent @ main.js:102
mountComponent @ main.js:41
performInitialMount @ main.js:102
mountComponent @ main.js:102
mountComponent @ main.js:41
performInitialMount @ main.js:102
mountComponent @ main.js:102
mountComponent @ main.js:41
a @ main.js:81
perform @ main.js:41
s @ main.js:81
perform @ main.js:41
batchedUpdates @ main.js:102
i @ main.js:35
_renderNewRootComponent @ main.js:81
_renderSubtreeIntoContainer @ main.js:81
render @ main.js:81
(anonymous) @ main.js:81
setTimeout (async)
(anonymous) @ main.js:81
t @ main.js:1
(anonymous) @ main.js:102
t @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
