### ISSUE TITLE
Deployment fails on "amplify publish"

### ISSUE THREAD

**Issue by lee-merrill** [aws-amplify/amplify-console#656]
My ARN is arn:aws:amplify:us-east-1:556961531046:apps/d3fjd2czg1c5dd

When I do an "amplify publish", I get:

✔ Zipping artifacts completed.
✖ Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
App d3bd4mny5g2wb4 not found.
NotFoundException: App d3bd4mny5g2wb4 not found.
    at Object.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/event_listeners.js:307:13)
    at IncomingMessage.emit (events.js:215:7)

"amplify pull --appId d3bd4mny5g2wb4 --envName blocledger" works (using the app id that it can't find above).

**Comment by lee-merrill** [comment]
That ARN should have been arn:aws:amplify:us-east-1:556961531046:apps/d2d3y5fqocr2ed

**Comment by Joycehao19** [comment]
Hi, @lee-merrill sorry you are facing this issue. Do you mean when you do `amplify publish` locally, and it failed? Did you try upgrade amplify cli tool -> npm install -g @aws-amplify/cli@latest and run `amplify publish`?

**Comment by lee-merrill** [comment]
Thanks for your reply. Yes, I ran "amplify publish" locally, and I had 
the 4.18.1 version, I upgraded and I now have version 4.19.0, but I 
still see the problem.

Lee

**Comment by swaminator** [comment]
@lee-merrill you are probably in a different region on your local AWS profile (vs the app that's in the cloud). Which region is your amplify console app in?

**Comment by lee-merrill** [comment]
I'm using us-east-1.

Lee

**Comment by swaminator** [comment]
can you see what region your local profile is in? It might be a different region. When you type `amplify console` from the CLI does it open your app?

**Comment by lee-merrill** [comment]
My $HOME/.aws/config file has "region=us-east-1", and typing "amplify 
console" brings up the Amplify console web page.

Lee

**Comment by swaminator** [comment]
When you open the Amplify console web page, can you goto App settings > General and see what the appID is?

**Comment by AnlyDcouth** [comment]
Hi,

I know its not relevant to the question but how long does it take to complete zipping artefacts.
My application is taking more than 12 hours and the zipped file is around 750GB so far
