### ISSUE TITLE
Manual deployment not working with S3

### ISSUE THREAD

**Issue by jcalvoch** [aws-amplify/amplify-console#677]
On the past few months we have been using manual deployment using a S3 bucket since drag and drop is almost always broken. Now not even S3 bucket is working anymore. When I select any of my S3 buckets and then click to expand on the "Zip file" field I am not seeing any file anymore, the list doesn't populate any file whatsoever.

App: https://prod.d2keoun3hapo8.amplifyapp.com/

**Comment by jcalvoch** [comment]
Additional info. Getting the following on my browser's console when I try to select any of the available buckets:

main.js:81 POST https://us-west-2.console.aws.amazon.com/amplify/api/s3 400 (Bad Request)
handleRequest @ main.js:81
a @ main.js:81
(anonymous) @ main.js:81
callListeners @ main.js:55
emit @ main.js:55
emitEvent @ main.js:81
e @ main.js:81
n.runTo @ main.js:81
(anonymous) @ main.js:81
(anonymous) @ main.js:81
(anonymous) @ main.js:81
callListeners @ main.js:55
emit @ main.js:55
emitEvent @ main.js:81
e @ main.js:81
n.runTo @ main.js:81
(anonymous) @ main.js:81
(anonymous) @ main.js:81
(anonymous) @ main.js:81
callListeners @ main.js:55
emit @ main.js:55
emitEvent @ main.js:81
e @ main.js:81
n.runTo @ main.js:81
(anonymous) @ main.js:81
(anonymous) @ main.js:81
(anonymous) @ main.js:81
callListeners @ main.js:55
emit @ main.js:55
emitEvent @ main.js:81
e @ main.js:81
n.runTo @ main.js:81
(anonymous) @ main.js:81
(anonymous) @ main.js:81
(anonymous) @ main.js:81
callListeners @ main.js:55
emit @ main.js:55
emitEvent @ main.js:81
e @ main.js:81
n.runTo @ main.js:81
runTo @ main.js:81
(anonymous) @ main.js:81
promise @ main.js:81
e.getBucketLocation @ main.js:41
(anonymous) @ main.js:41
r @ main.js:41
(anonymous) @ main.js:41
(anonymous) @ main.js:41
i @ main.js:41
n.inCurrentRegion @ main.js:41
(anonymous) @ main.js:41
r @ main.js:41
(anonymous) @ main.js:41
(anonymous) @ main.js:41
i @ main.js:41
n.onS3BucketChange @ main.js:41
onChange @ main.js:41
wrappedCallback @ main.js:30
r @ main.js:29
t @ main.js:29
e.selectOption @ main.js:21
(anonymous) @ main.js:21
r @ main.js:29
t @ main.js:29
selectable.u.onmouseup @ main.js:12
Show 35 more frames
main.js:81 Uncaught (in promise) InvalidToken: The provided token is malformed or otherwise invalid.
    at constructor.extractError (https://d1cr1y5smcf7os.cloudfront.net/8649469f7ec011c3e948562abac13b89ef1db83a/main.js:81:1425073)
    at constructor.callListeners (https://d1cr1y5smcf7os.cloudfront.net/8649469f7ec011c3e948562abac13b89ef1db83a/main.js:55:147691)
    at constructor.emit (https://d1cr1y5smcf7os.cloudfront.net/8649469f7ec011c3e948562abac13b89ef1db83a/main.js:55:147402)
    at constructor.emitEvent (https://d1cr1y5smcf7os.cloudfront.net/8649469f7ec011c3e948562abac13b89ef1db83a/main.js:81:1391868)
    at constructor.e (https://d1cr1y5smcf7os.cloudfront.net/8649469f7ec011c3e948562abac13b89ef1db83a/main.js:81:1387510)
    at n.runTo (https://d1cr1y5smcf7os.cloudfront.net/8649469f7ec011c3e948562abac13b89ef1db83a/main.js:81:1440206)
    at https://d1cr1y5smcf7os.cloudfront.net/8649469f7ec011c3e948562abac13b89ef1db83a/main.js:81:1440411
    at constructor.<anonymous> (https://d1cr1y5smcf7os.cloudfront.net/8649469f7ec011c3e948562abac13b89ef1db83a/main.js:81:1387720)
    at constructor.<anonymous> (https://d1cr1y5smcf7os.cloudfront.net/8649469f7ec011c3e948562abac13b89ef1db83a/main.js:81:1391923)
    at constructor.callListeners (https://d1cr1y5smcf7os.cloudfront.net/8649469f7ec011c3e948562abac13b89ef1db83a/main.js:55:147797)

**Comment by kahdojay** [comment]
@jcalvoch Thanks for reporting - we are investigating. When was the last time S3 deploy worked for you?

**Comment by jcalvoch** [comment]
@kahdojay Thank you, on April 30th we were able to deploy using S3 without problems. After that we didn't try to deploy anything until yesterday where it failed.

**Comment by kahdojay** [comment]
@jcalvoch can you give it another try?

**Comment by jcalvoch** [comment]
Hey @kahdojay. Yes, this is working now. Thank you very much.

**Comment by kahdojay** [comment]
Thanks for confirming @jcalvoch - you also mentioned in your original post about drag and drop manual deploy issues as well. If you have the time to describe it and provide steps to reproduce in a new issue we can investigate that as well.
