### ISSUE TITLE
Missing react-router-dom module in AWS

### ISSUE THREAD

**Issue by MatthiasLHK** [aws-amplify/amplify-console#696]
**App Id**:
**Region**:
**Step**:
**Status**:

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Can't get my React app to build in AWS amplify. It fails as they say there is no react-router-dom module found. How do i add that to my AWS? I can run npm run build locally and it is successful.

**Error message**
If there is an error message, please include it here. 
2020-05-21T07:41:31.605Z [INFO]: Git SSH Key acquired
2020-05-21T07:41:31.671Z [INFO]: # Cloning repository: ----
2020-05-21T07:41:31.804Z [INFO]: ----
2020-05-21T07:41:31.871Z [INFO]: Identity added: ----
2020-05-21T07:41:32.103Z [INFO]: Cloning into '----'...
2020-05-21T07:41:32.407Z [INFO]: Warning: Permanently added the RSA host key for IP address '----' to the list of known hosts.
2020-05-21T07:41:32.874Z [INFO]: # Checking for Git submodules at: /codebuild/output/src160376512/src/AutoCropperWebApp/.gitmodules
2020-05-21T07:41:32.995Z [INFO]: # Retrieving cache...
2020-05-21T07:41:33.065Z [INFO]: # Extracting cache...
2020-05-21T07:41:33.076Z [INFO]: # Extraction completed
2020-05-21T07:41:33.076Z [INFO]: # Retrieving environment cache...
2020-05-21T07:41:33.099Z [INFO]: # Retrieved environment cache
2020-05-21T07:42:01.306Z [INFO]: ## Starting Frontend Build
                                 # Starting phase: preBuild
                                 # Executing command: npm ci
2020-05-21T07:42:11.167Z [INFO]: > core-js@2.6.11 postinstall /codebuild/output/src160376512/src/AutoCropperWebApp/node_modules/babel-runtime/node_modules/core-js
                                 > node -e "try{require('./postinstall')}catch(e){}"
2020-05-21T07:42:11.241Z [INFO]: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
                                 The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
                                 > https://opencollective.com/core-js
                                 > https://www.patreon.com/zloirock
                                 Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
2020-05-21T07:42:11.317Z [INFO]: > fsevents@1.2.13 install /codebuild/output/src160376512/src/AutoCropperWebApp/node_modules/webpack-dev-server/node_modules/fsevents
                                 > node install.js
2020-05-21T07:42:11.373Z [INFO]: 
2020-05-21T07:42:11.374Z [INFO]: Skipping 'fsevents' build as platform linux is not supported
2020-05-21T07:42:11.385Z [INFO]: > fsevents@1.2.13 install /codebuild/output/src160376512/src/AutoCropperWebApp/node_modules/watchpack-chokidar2/node_modules/fsevents
                                 > node install.js
2020-05-21T07:42:11.438Z [INFO]: 
2020-05-21T07:42:11.439Z [INFO]: Skipping 'fsevents' build as platform linux is not supported
2020-05-21T07:42:11.513Z [INFO]: > core-js@3.6.5 postinstall /codebuild/output/src160376512/src/AutoCropperWebApp/node_modules/core-js
                                 > node -e "try{require('./postinstall')}catch(e){}"
2020-05-21T07:42:11.676Z [INFO]: > fsevents@1.2.13 install /codebuild/output/src160376512/src/AutoCropperWebApp/node_modules/jest-haste-map/node_modules/fsevents
                                 > node install.js
2020-05-21T07:42:11.729Z [INFO]: 
2020-05-21T07:42:11.730Z [INFO]: Skipping 'fsevents' build as platform linux is not supported
2020-05-21T07:42:11.781Z [INFO]: > core-js-pure@3.6.5 postinstall /codebuild/output/src160376512/src/AutoCropperWebApp/node_modules/core-js-pure
                                 > node -e "try{require('./postinstall')}catch(e){}"
2020-05-21T07:42:11.890Z [INFO]: added 1655 packages in 9.801s
2020-05-21T07:42:11.904Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
2020-05-21T07:42:11.905Z [INFO]: # Executing command: npm run build
2020-05-21T07:42:12.074Z [INFO]: > autocropper_frontend@0.1.0 build /codebuild/output/src160376512/src/AutoCropperWebApp
                                 > react-scripts build
2020-05-21T07:42:12.920Z [INFO]: Creating an optimized production build...
2020-05-21T07:42:14.491Z [INFO]: Failed to compile.
2020-05-21T07:42:14.493Z [INFO]: ./src/App.js
                                 Cannot find module: 'react-router-dom'. Make sure this package is installed.
                                 You can install this package by running: npm install react-router-dom.
2020-05-21T07:42:14.501Z [WARNING]: npm
2020-05-21T07:42:14.502Z [WARNING]: ERR! code ELIFECYCLE
                                    npm ERR! errno 1
                                    npm ERR! autocropper_frontend@0.1.0 build: `react-scripts build`
                                    npm ERR! Exit status 1
                                    npm ERR!
                                    npm ERR! Failed at the autocropper_frontend@0.1.0 build script.
                                    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-05-21T07:42:14.512Z [WARNING]: 
2020-05-21T07:42:14.513Z [WARNING]: npm ERR! A complete log of this run can be found in:
                                    npm ERR!     /root/.npm/_logs/2020-05-21T07_42_14_504Z-debug.log
2020-05-21T07:42:14.513Z [HELP]: Outputting the npm debug log
                                 0 info it worked if it ends with ok
                                 1 verbose cli [ '/root/.nvm/versions/node/v10.16.0/bin/node',
                                 1 verbose cli   '/root/.nvm/versions/node/v10.16.0/bin/npm',
                                 1 verbose cli   'run',
                                 1 verbose cli   'build' ]
                                 2 info using npm@6.9.0
                                 3 info using node@v10.16.0
                                 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
                                 5 info lifecycle autocropper_frontend@0.1.0~prebuild: autocropper_frontend@0.1.0
                                 6 info lifecycle autocropper_frontend@0.1.0~build: autocropper_frontend@0.1.0
                                 7 verbose lifecycle autocropper_frontend@0.1.0~build: unsafe-perm in lifecycle true
                                 8 verbose lifecycle autocropper_frontend@0.1.0~build: PATH: /root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/codebuild/output/src160376512/src/AutoCropperWebApp/node_modules/.bin:/usr/local/rvm/gems/ruby-2.4.6/bin:/usr/local/rvm/gems/ruby-2.4.6@global/bin:/usr/local/rvm/rubies/ruby-2.4.6/bin:/usr/local/rvm/bin:/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:/root/.nvm/versions/node/v10.16.0/bin:/root/.local/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
                                 9 verbose lifecycle autocropper_frontend@0.1.0~build: CWD: /codebuild/output/src160376512/src/AutoCropperWebApp
                                 10 silly lifecycle autocropper_frontend@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
                                 11 silly lifecycle autocropper_frontend@0.1.0~build: Returned: code: 1  signal: null
                                 12 info lifecycle autocropper_frontend@0.1.0~build: Failed to exec build script
                                 13 verbose stack Error: autocropper_frontend@0.1.0 build: `react-scripts build`
                                 13 verbose stack Exit status 1
                                 13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
                                 13 verbose stack     at EventEmitter.emit (events.js:198:13)
                                 13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
                                 13 verbose stack     at ChildProcess.emit (events.js:198:13)
                                 13 verbose stack     at maybeClose (internal/child_process.js:982:16)
                                 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
                                 14 verbose pkgid autocropper_frontend@0.1.0
                                 15 verbose cwd /codebuild/output/src160376512/src/AutoCropperWebApp
                                 16 verbose Linux 4.14.173-106.229.amzn1.x86_64
                                 17 verbose argv "/root/.nvm/versions/node/v10.16.0/bin/node" "/root/.nvm/versions/node/v10.16.0/bin/npm" "run" "build"
                                 18 verbose node v10.16.0
                                 19 verbose npm  v6.9.0
                                 20 error code ELIFECYCLE
                                 21 error errno 1
                                 22 error autocropper_frontend@0.1.0 build: `react-scripts build`
                                 22 error Exit status 1
                                 23 error Failed at the autocropper_frontend@0.1.0 build script.
                                 23 error This is probably not a problem with npm. There is likely additional logging output above.
                                 24 verbose exit [ 1, true ]
2020-05-21T07:42:14.515Z [ERROR]: !!! Build failed
2020-05-21T07:42:14.598Z [ERROR]: !!! Non-Zero Exit Code detected
2020-05-21T07:42:14.599Z [INFO]: # Starting environment caching...
2020-05-21T07:42:14.599Z [INFO]: # Environment caching completed
Terminating logging...
 

**Additional information**
import React, {useState} from 'react';
import {BrowserRouter as Router, Route, Switch, Redirect} from "react-router-dom";
import "semantic-ui-css/semantic.min.css";
import {Button} from "semantic-ui-react";
import NavigationContainer from "./component/navigation/NavigationContainer";
import './App.css';
import {
    HOME_PATH,
    MAIN_PATH,
    ABOUT_PATH,
    SET_DATA_PATH,
    PROFILE_PATH
} from "./utils/Constants";
import Home from "./component/pages/Home";
import About from "./component/pages/About";
import SetData from "./component/pages/SetData";
import Profile from "./component/pages/Profile";

function App() {
  return (
    <div className="App">

        <Router>
         <NavigationContainer>
        <Switch>
            <Route path = {HOME_PATH} exact component = {Home} />
            <Route path = {ABOUT_PATH} exact component = {About} />
            <Route path = {PROFILE_PATH} exact component = {Profile} />
            <Route path = {SET_DATA_PATH} exact component = {SetData} />
        <Route>
        <Redirect to = {HOME_PATH} />
        </Route>
        </Switch>
        </NavigationContainer>
        </Router>

    </div>
  );
}

export default App;

**Comment by Athena96** [comment]
Hi @MatthiasLHK can you share your `package.json` (minus any sensitive info). Thanks

**Comment by Joycehao19** [comment]
Hello, you could also add a preBuild section in your amplify.yml and install react-router-dom module
something like:
```
preBuild:
    commands:
        - npm install --save react-router-dom
```

Closing for now, if you still have the issue, feel free to reopen the issue
