### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by gsans** [aws-amplify/amplify-console#75]
**Describe the bug**
Build *Backend* shows errors creating resources.

**To Reproduce**
Redeploy

**Expected behavior**
To be able to deploy without errors.

**Additional context**
App name: 
braziljs-find-keanu-angular

App ARN: 
arn:aws:amplify:ap-northeast-1:664371068953:apps/d1gum2cbxi0tzw

**Sample code**
NA

**Comment by swaminator** [comment]
@gsans can you share the build error?

**Comment by gsans** [comment]
Sure. There are quite a few of them. I figured you could reproduce them.

```
CREATE_FAILED      S3Bucket AWS::S3::Bucket Fri Aug 23 2019 18:02:58 GMT+0000 (Coordinated Universal Time) amplify-ml-app0697f256f0964e28bcf798127f719121-master already exists
2019-08-23T18:02:59.107Z [INFO]: 
2019-08-23T18:02:59.108Z [INFO]: CREATE_IN_PROGRESS amplify-ml-app-master-20190823180145-authamplifymlappa5e9d939-1IKURYXTN5Q5I AWS::CloudFormation::Stack Fri Aug 23 2019 18:02:54 GMT+0000 (Coordinated Universal Time) User Initiated
2019-08-23T18:02:59.211Z [INFO]: 
2019-08-23T18:02:59.211Z [INFO]: CREATE_IN_PROGRESS IdentifyEntitiesPolicy AWS::IAM::Policy Fri Aug 23 2019 18:02:55 GMT+0000 (Coordinated Universal Time)
2019-08-23T18:02:59.316Z [INFO]: 
2019-08-23T18:02:59.316Z [INFO]: CREATE_IN_PROGRESS InterpretPolicy AWS::IAM::Policy Fri Aug 23 2019 18:02:56 GMT+0000 (Coordinated Universal Time)
2019-08-23T18:03:03.508Z [INFO]: 
2019-08-23T18:03:03.509Z [INFO]: CREATE_IN_PROGRESS PollyPolicy AWS::IAM::Policy Fri Aug 23 2019 18:03:01 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
2019-08-23T18:03:03.615Z [INFO]: 
2019-08-23T18:03:03.616Z [INFO]: CREATE_IN_PROGRESS TranslatePolicy AWS::IAM::Policy Fri Aug 23 2019 18:02:59 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
2019-08-23T18:03:03.714Z [INFO]: 
2019-08-23T18:03:03.714Z [INFO]: CREATE_IN_PROGRESS identifyLabelssPolicy AWS::IAM::Policy Fri Aug 23 2019 18:03:01 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
2019-08-23T18:03:03.811Z [INFO]: 
2019-08-23T18:03:03.811Z [INFO]: CREATE_IN_PROGRESS IdentifyTextPolicy AWS::IAM::Policy Fri Aug 23 2019 18:02:59 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
2019-08-23T18:03:03.916Z [INFO]: 
2019-08-23T18:03:03.917Z [INFO]: CREATE_IN_PROGRESS PollyPolicy AWS::IAM::Policy Fri Aug 23 2019 18:02:59 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
2019-08-23T18:03:04.116Z [INFO]: 
2019-08-23T18:03:04.117Z [INFO]: CREATE_FAILED amplify-ml-app-master-20190823180145-storagestorage0aef210a-38CW2HPU0L2Z AWS::CloudFormation::Stack Fri Aug 23 2019 18:02:59 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to create: [S3Bucket].
2019-08-23T18:03:04.129Z [INFO]: 
2019-08-23T18:03:04.130Z [INFO]: CREATE_IN_PROGRESS SNSRole                                                                     AWS::IAM::Role             Fri Aug 23 2019 18:03:00 GMT+0000 (Coordinated Universal Time)
                                 CREATE_FAILED      SNSRole                                                                     AWS::IAM::Role             Fri Aug 23 2019 18:03:01 GMT+0000 (Coordinated Universal Time) amplifa5e9d939_sns-role-master already exists
                                 CREATE_FAILED      amplify-ml-app-master-20190823180145-authamplifymlappa5e9d939-1IKURYXTN5Q5I AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:02 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to create: [SNSRole].
2019-08-23T18:03:04.218Z [INFO]: 
2019-08-23T18:03:04.218Z [INFO]: CREATE_IN_PROGRESS IdentifyEntitiesPolicy AWS::IAM::Policy Fri Aug 23 2019 18:02:59 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
2019-08-23T18:03:04.315Z [INFO]: 
2019-08-23T18:03:04.315Z [INFO]: CREATE_IN_PROGRESS InterpretPolicy AWS::IAM::Policy Fri Aug 23 2019 18:02:59 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
2019-08-23T18:03:08.357Z [INFO]: 
2019-08-23T18:03:08.360Z [INFO]: CREATE_FAILED                                predictionsspeechGenerator59b46d5f   AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:04 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
                                 CREATE_FAILED                                storagestorage0aef210a               AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:03 GMT+0000 (Coordinated Universal Time) Embedded stack arn:aws:cloudformation:ap-northeast-1:664371068953:stack/amplify-ml-app-master-20190823180145-storagestorage0aef210a-38CW2HPU0L2Z/39c39820-c5d0-11e9-901c-0a5da605f772 was not successfully created: The following resource(s) failed to create: [S3Bucket].
                                 CREATE_FAILED                                predictionsinterpretText093cac2e     AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:04 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
                                 CREATE_FAILED                                predictionsidentifyText9eedb9e4      AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:04 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
                                 CREATE_FAILED                                predictionsidentifyEntities16ed24bf  AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:04 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
                                 CREATE_FAILED                                predictionsidentifyLabels1e6736c0    AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:04 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
                                 CREATE_FAILED                                predictionstranslateText17f9cb28     AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:04 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
                                 CREATE_FAILED                                UpdateRolesWithIDPFunctionRole       AWS::IAM::Role             Fri Aug 23 2019 18:03:04 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
                                 CREATE_FAILED                                predictionstranscriptionddb3262f     AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:04 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
                                 CREATE_FAILED                                authamplifymlappa5e9d939             AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:04 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
                                 UPDATE_ROLLBACK_IN_PROGRESS                  amplify-ml-app-master-20190823180145 AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:05 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to create: [predictionsidentifyText9eedb9e4, predictionsinterpretText093cac2e, storagestorage0aef210a, predictionstranscriptionddb3262f, UpdateRolesWithIDPFunctionRole, predictionsidentifyLabels1e6736c0, predictionsspeechGenerator59b46d5f, predictionstranslateText17f9cb28, predictionsidentifyEntities16ed24bf, authamplifymlappa5e9d939].
                                 UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS amplify-ml-app-master-20190823180145 AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:07 GMT+0000 (Coordinated Universal Time)
2019-08-23T18:03:13.379Z [INFO]: 
2019-08-23T18:03:13.381Z [INFO]: DELETE_IN_PROGRESS predictionstranscriptionddb3262f    AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time)
                                 DELETE_IN_PROGRESS predictionstranslateText17f9cb28    AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time)
                                 DELETE_IN_PROGRESS storagestorage0aef210a              AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time)
                                 DELETE_IN_PROGRESS predictionsidentifyLabels1e6736c0   AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time)
                                 DELETE_IN_PROGRESS predictionsidentifyText9eedb9e4     AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time)
                                 DELETE_IN_PROGRESS authamplifymlappa5e9d939            AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time)
                                 DELETE_IN_PROGRESS predictionsidentifyEntities16ed24bf AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time)
                                 DELETE_IN_PROGRESS UpdateRolesWithIDPFunctionRole      AWS::IAM::Role             Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time)
                                 DELETE_IN_PROGRESS predictionsinterpretText093cac2e    AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time)
                                 DELETE_IN_PROGRESS predictionsspeechGenerator59b46d5f  AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE    UpdateRolesWithIDPFunctionRole      AWS::IAM::Role             Fri Aug 23 2019 18:03:12 GMT+0000 (Coordinated Universal Time)
2019-08-23T18:03:13.515Z [INFO]: 
2019-08-23T18:03:13.516Z [INFO]: DELETE_IN_PROGRESS amplify-ml-app-master-20190823180145-predictionsinterpretText093cac2e-12F5TDOINCFCG AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time) User Initiated
                                 CREATE_FAILED      InterpretPolicy                                                                     AWS::IAM::Policy           Fri Aug 23 2019 18:03:10 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
2019-08-23T18:03:13.619Z [INFO]: 
2019-08-23T18:03:13.619Z [INFO]: DELETE_IN_PROGRESS amplify-ml-app-master-20190823180145-predictionsidentifyEntities16ed24bf-13GB72CQFA08Q AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time) User Initiated
                                 CREATE_FAILED      IdentifyEntitiesPolicy                                                                 AWS::IAM::Policy           Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
2019-08-23T18:03:13.719Z [INFO]: 
2019-08-23T18:03:13.719Z [INFO]: DELETE_IN_PROGRESS amplify-ml-app-master-20190823180145-predictionstranscriptionddb3262f-2RZWHG3GOLKL AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time) User Initiated
                                 CREATE_FAILED      PollyPolicy                                                                        AWS::IAM::Policy           Fri Aug 23 2019 18:03:10 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
2019-08-23T18:03:13.815Z [INFO]: 
2019-08-23T18:03:13.816Z [INFO]: DELETE_IN_PROGRESS amplify-ml-app-master-20190823180145-authamplifymlappa5e9d939-1IKURYXTN5Q5I AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time) User Initiated
                                 DELETE_COMPLETE    SNSRole                                                                     AWS::IAM::Role             Fri Aug 23 2019 18:03:11 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE    amplify-ml-app-master-20190823180145-authamplifymlappa5e9d939-1IKURYXTN5Q5I AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:12 GMT+0000 (Coordinated Universal Time)
2019-08-23T18:03:13.920Z [INFO]: 
2019-08-23T18:03:13.920Z [INFO]: DELETE_IN_PROGRESS amplify-ml-app-master-20190823180145-predictionsidentifyText9eedb9e4-12QWYBPGKRMTE AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time) User Initiated
                                 CREATE_FAILED      IdentifyTextPolicy                                                                 AWS::IAM::Policy           Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
2019-08-23T18:03:14.025Z [INFO]: 
2019-08-23T18:03:14.025Z [INFO]: DELETE_IN_PROGRESS amplify-ml-app-master-20190823180145-predictionsidentifyLabels1e6736c0-1C9WCOQ9PRZ3L AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time) User Initiated
                                 CREATE_FAILED      identifyLabelssPolicy                                                                AWS::IAM::Policy           Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
2019-08-23T18:03:14.121Z [INFO]: 
2019-08-23T18:03:14.122Z [INFO]: DELETE_IN_PROGRESS amplify-ml-app-master-20190823180145-storagestorage0aef210a-38CW2HPU0L2Z AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time) User Initiated
                                 DELETE_SKIPPED     S3Bucket                                                                 AWS::S3::Bucket            Fri Aug 23 2019 18:03:11 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE    amplify-ml-app-master-20190823180145-storagestorage0aef210a-38CW2HPU0L2Z AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:11 GMT+0000 (Coordinated Universal Time)
2019-08-23T18:03:14.221Z [INFO]: 
2019-08-23T18:03:14.221Z [INFO]: DELETE_IN_PROGRESS amplify-ml-app-master-20190823180145-predictionstranslateText17f9cb28-1VZIC8GOSHEUP AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time) User Initiated
                                 CREATE_FAILED      TranslatePolicy                                                                     AWS::IAM::Policy           Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
2019-08-23T18:03:14.323Z [INFO]: 
2019-08-23T18:03:14.324Z [INFO]: DELETE_IN_PROGRESS amplify-ml-app-master-20190823180145-predictionsspeechGenerator59b46d5f-1BL75R1RJ6T70 AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:09 GMT+0000 (Coordinated Universal Time) User Initiated
                                 CREATE_FAILED      PollyPolicy                                                                           AWS::IAM::Policy           Fri Aug 23 2019 18:03:10 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
2019-08-23T18:03:23.371Z [INFO]: 
2019-08-23T18:03:23.373Z [INFO]: DELETE_COMPLETE storagestorage0aef210a   AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:20 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE authamplifymlappa5e9d939 AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:20 GMT+0000 (Coordinated Universal Time)
2019-08-23T18:03:28.544Z [INFO]: 
2019-08-23T18:03:28.545Z [INFO]: DELETE_IN_PROGRESS PollyPolicy AWS::IAM::Policy Fri Aug 23 2019 18:03:26 GMT+0000 (Coordinated Universal Time)
2019-08-23T18:03:28.634Z [INFO]: 
2019-08-23T18:03:28.635Z [INFO]: DELETE_IN_PROGRESS InterpretPolicy AWS::IAM::Policy Fri Aug 23 2019 18:03:26 GMT+0000 (Coordinated Universal Time)
2019-08-23T18:03:28.741Z [INFO]: 
2019-08-23T18:03:28.742Z [INFO]: DELETE_IN_PROGRESS IdentifyEntitiesPolicy AWS::IAM::Policy Fri Aug 23 2019 18:03:26 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE    IdentifyEntitiesPolicy AWS::IAM::Policy Fri Aug 23 2019 18:03:28 GMT+0000 (Coordinated Universal Time)
2019-08-23T18:03:28.846Z [INFO]: 
2019-08-23T18:03:28.847Z [INFO]: DELETE_IN_PROGRESS PollyPolicy AWS::IAM::Policy Fri Aug 23 2019 18:03:26 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE    PollyPolicy AWS::IAM::Policy Fri Aug 23 2019 18:03:28 GMT+0000 (Coordinated Universal Time)
2019-08-23T18:03:28.935Z [INFO]: 
2019-08-23T18:03:28.935Z [INFO]: DELETE_IN_PROGRESS IdentifyTextPolicy AWS::IAM::Policy Fri Aug 23 2019 18:03:26 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE    IdentifyTextPolicy AWS::IAM::Policy Fri Aug 23 2019 18:03:28 GMT+0000 (Coordinated Universal Time)
2019-08-23T18:03:29.036Z [INFO]: 
2019-08-23T18:03:29.037Z [INFO]: DELETE_IN_PROGRESS identifyLabelssPolicy AWS::IAM::Policy Fri Aug 23 2019 18:03:26 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE    identifyLabelssPolicy AWS::IAM::Policy Fri Aug 23 2019 18:03:28 GMT+0000 (Coordinated Universal Time)
2019-08-23T18:03:29.237Z [INFO]: 
2019-08-23T18:03:29.237Z [INFO]: DELETE_IN_PROGRESS TranslatePolicy AWS::IAM::Policy Fri Aug 23 2019 18:03:26 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE    TranslatePolicy AWS::IAM::Policy Fri Aug 23 2019 18:03:28 GMT+0000 (Coordinated Universal Time)
2019-08-23T18:03:33.374Z [INFO]: 
2019-08-23T18:03:33.376Z [INFO]: DELETE_COMPLETE          predictionstranslateText17f9cb28     AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:31 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE          predictionsidentifyLabels1e6736c0    AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:31 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE          predictionsidentifyEntities16ed24bf  AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:31 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE          predictionsidentifyText9eedb9e4      AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:31 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE          predictionsinterpretText093cac2e     AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:31 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE          predictionstranscriptionddb3262f     AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:31 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE          predictionsspeechGenerator59b46d5f   AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:31 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_ROLLBACK_COMPLETE amplify-ml-app-master-20190823180145 AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:32 GMT+0000 (Coordinated Universal Time)
2019-08-23T18:03:33.535Z [INFO]: 
2019-08-23T18:03:33.535Z [INFO]: DELETE_COMPLETE PollyPolicy                                                                           AWS::IAM::Policy           Fri Aug 23 2019 18:03:28 GMT+0000 (Coordinated Universal Time)
                                 DELETE_COMPLETE amplify-ml-app-master-20190823180145-predictionsspeechGenerator59b46d5f-1BL75R1RJ6T70 AWS::CloudFormation::Stack Fri Aug 23 2019 18:03:29 GMT+0000 (Coordinated Universal Time)
2019-08-23T18:03:48.461Z [WARNING]: Error updating cloudformation stack
2019-08-23T18:03:53.470Z [INFO]: Following resources failed
2019-08-23T18:03:53.472Z [INFO]: Resource Name: S3Bucket (AWS::S3::Bucket)
                                 Event Type: create
                                 Reason: amplify-ml-app0697f256f0964e28bcf798127f719121-master already exists
                                 Resource Name: SNSRole (AWS::IAM::Role)
                                 Event Type: create
                                 Reason: amplifa5e9d939_sns-role-master already exists
                                 Resource Name: amplify-ml-app-20190823180145-authRole-idp (AWS::IAM::Role)
                                 Event Type: create
                                 Reason: Resource creation cancelled
                                 Resource Name: ampli-Inte-MERDRNT0SK8C (AWS::IAM::Policy)
                                 Event Type: create
                                 Reason: Resource creation cancelled
                                 Resource Name: ampli-Iden-1PHB31MCL03LQ (AWS::IAM::Policy)
                                 Event Type: create
                                 Reason: Resource creation cancelled
                                 Resource Name: ampli-Poll-ZCHQZAW6BTN2 (AWS::IAM::Policy)
                                 Event Type: create
                                 Reason: Resource creation cancelled
                                 Resource Name: ampli-Iden-DMOFTENNZ3YT (AWS::IAM::Policy)
                                 Event Type: create
                                 Reason: Resource creation cancelled
                                 Resource Name: ampli-iden-471OMTRU6HGA (AWS::IAM::Policy)
                                 Event Type: create
                                 Reason: Resource creation cancelled
                                 Resource Name: ampli-Tran-1JPAMAMGIZFND (AWS::IAM::Policy)
                                 Event Type: create
                                 Reason: Resource creation cancelled
                                 Resource Name: ampli-Poll-MXEI5DUMUN2P (AWS::IAM::Policy)
                                 Event Type: create
                                 Reason: Resource creation cancelled
                                 init failed
2019-08-23T18:03:53.473Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
                                    ✖ There was an error initializing your environment.
2019-08-23T18:03:53.476Z [INFO]: { ResourceNotReady: Resource is not in the state stackUpdateComplete
                                 at constructor.setError (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/resource_waiter.js:182:47)
                                 at Request.CHECK_ACCEPTORS (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/resource_waiter.js:44:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 message: 'Resource is not in the state stackUpdateComplete',
                                 code: 'ResourceNotReady',
                                 retryable: false,
                                 time: 2019-08-23T18:03:48.461Z,
                                 statusCode: 200,
                                 retryDelay: 30000 }
2019-08-23T18:03:53.554Z [ERROR]: !!! Build failed
2019-08-23T18:03:53.737Z [ERROR]: !!! Non-Zero Exit Code detected
2019-08-23T18:03:53.737Z [INFO]: # Starting environment caching...
2019-08-23T18:03:53.738Z [INFO]: # Environment caching completed
Terminating logging...
```
