### ISSUE TITLE
AWS Amplify build failed

### ISSUE THREAD

**Issue by deomanish** [aws-amplify/amplify-console#784]
AWS Amplify always filed to build. please suggest.

2020-06-23T05:25:17.762Z [INFO]: Git SSH Key acquired
2020-06-23T05:25:17.832Z [INFO]: # Cloning repository: git@bitbucket.org:appstacklabs/accessduoui.git
2020-06-23T05:25:17.956Z [INFO]: Agent pid 128
2020-06-23T05:25:17.993Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2020-06-23T05:25:18.222Z [INFO]: Cloning into 'accessduoui'...
2020-06-23T05:25:18.512Z [INFO]: Warning: Permanently added the RSA host key for IP address '18.205.93.0' to the list of known hosts.
2020-06-23T05:25:31.990Z [INFO]: Checking out files:  39% (18018/45865)
2020-06-23T05:25:31.999Z [INFO]: Checking out files:  40% (18346/45865)
2020-06-23T05:25:32.011Z [INFO]: Checking out files:  41% (18805/45865)
2020-06-23T05:25:32.028Z [INFO]: Checking out files:  42% (19264/45865)
2020-06-23T05:25:32.037Z [INFO]: Checking out files:  43% (19722/45865)
2020-06-23T05:25:32.044Z [INFO]: Checking out files:  44% (20181/45865)
2020-06-23T05:25:32.052Z [INFO]: Checking out files:  45% (20640/45865)
2020-06-23T05:25:32.059Z [INFO]: Checking out files:  46% (21098/45865)
2020-06-23T05:25:32.066Z [INFO]: Checking out files:  47% (21557/45865)
2020-06-23T05:25:32.074Z [INFO]: Checking out files:  48% (22016/45865)
2020-06-23T05:25:32.083Z [INFO]: Checking out files:  49% (22474/45865)
2020-06-23T05:25:32.098Z [INFO]: Checking out files:  50% (22933/45865)
2020-06-23T05:25:32.115Z [INFO]: Checking out files:  51% (23392/45865)
2020-06-23T05:25:32.132Z [INFO]: Checking out files:  52% (23850/45865)
2020-06-23T05:25:32.172Z [INFO]: Checking out files:  53% (24309/45865)
2020-06-23T05:25:32.185Z [INFO]: Checking out files:  54% (24768/45865)
2020-06-23T05:25:32.198Z [INFO]: Checking out files:  55% (25226/45865)
2020-06-23T05:25:32.208Z [INFO]: Checking out files:  56% (25685/45865)
2020-06-23T05:25:32.218Z [INFO]: Checking out files:  57% (26144/45865)
2020-06-23T05:25:32.238Z [INFO]: Checking out files:  58% (26602/45865)
2020-06-23T05:25:32.251Z [INFO]: Checking out files:  59% (27061/45865)
2020-06-23T05:25:32.273Z [INFO]: Checking out files:  60% (27519/45865)
2020-06-23T05:25:32.294Z [INFO]: Checking out files:  61% (27978/45865)
2020-06-23T05:25:32.309Z [INFO]: Checking out files:  62% (28437/45865)
2020-06-23T05:25:32.316Z [INFO]: Checking out files:  63% (28895/45865)
2020-06-23T05:25:32.327Z [INFO]: Checking out files:  64% (29354/45865)
2020-06-23T05:25:32.355Z [INFO]: Checking out files:  65% (29813/45865)
2020-06-23T05:25:32.382Z [INFO]: Checking out files:  66% (30271/45865)
2020-06-23T05:25:32.400Z [INFO]: Checking out files:  67% (30730/45865)
2020-06-23T05:25:32.416Z [INFO]: Checking out files:  68% (31189/45865)
2020-06-23T05:25:32.434Z [INFO]: Checking out files:  69% (31647/45865)
2020-06-23T05:25:32.451Z [INFO]: Checking out files:  70% (32106/45865)
2020-06-23T05:25:32.466Z [INFO]: Checking out files:  71% (32565/45865)
2020-06-23T05:25:32.476Z [INFO]: Checking out files:  72% (33023/45865)
2020-06-23T05:25:32.485Z [INFO]: Checking out files:  73% (33482/45865)
2020-06-23T05:25:32.493Z [INFO]: Checking out files:  74% (33941/45865)
2020-06-23T05:25:32.505Z [INFO]: Checking out files:  75% (34399/45865)
2020-06-23T05:25:32.520Z [INFO]: Checking out files:  76% (34858/45865)
2020-06-23T05:25:32.547Z [INFO]: Checking out files:  77% (35317/45865)
2020-06-23T05:25:32.573Z [INFO]: Checking out files:  78% (35775/45865)
2020-06-23T05:25:32.599Z [INFO]: Checking out files:  79% (36234/45865)
2020-06-23T05:25:32.624Z [INFO]: Checking out files:  80% (36692/45865)
2020-06-23T05:25:32.651Z [INFO]: Checking out files:  81% (37151/45865)
2020-06-23T05:25:32.677Z [INFO]: Checking out files:  82% (37610/45865)
2020-06-23T05:25:32.700Z [INFO]: Checking out files:  83% (38068/45865)
2020-06-23T05:25:32.713Z [INFO]: Checking out files:  84% (38527/45865)
2020-06-23T05:25:32.724Z [INFO]: Checking out files:  85% (38986/45865)
2020-06-23T05:25:32.733Z [INFO]: Checking out files:  86% (39444/45865)
2020-06-23T05:25:32.747Z [INFO]: Checking out files:  87% (39903/45865)
2020-06-23T05:25:32.779Z [INFO]: Checking out files:  88% (40362/45865)
2020-06-23T05:25:32.805Z [INFO]: Checking out files:  89% (40820/45865)
2020-06-23T05:25:32.832Z [INFO]: Checking out files:  90% (41279/45865)
2020-06-23T05:25:32.842Z [INFO]: Checking out files:  91% (41738/45865)
2020-06-23T05:25:32.990Z [INFO]: Checking out files:  91% (42032/45865)
2020-06-23T05:25:32.997Z [INFO]: Checking out files:  92% (42196/45865)
2020-06-23T05:25:33.018Z [INFO]: Checking out files:  93% (42655/45865)
2020-06-23T05:25:33.050Z [INFO]: Checking out files:  94% (43114/45865)
2020-06-23T05:25:33.071Z [INFO]: Checking out files:  95% (43572/45865)
2020-06-23T05:25:33.088Z [INFO]: Checking out files:  96% (44031/45865)
2020-06-23T05:25:33.108Z [INFO]: Checking out files:  97% (44490/45865)
2020-06-23T05:25:33.123Z [INFO]: Checking out files:  98% (44948/45865)
2020-06-23T05:25:33.139Z [INFO]: Checking out files:  99% (45407/45865)
2020-06-23T05:25:33.156Z [INFO]: Checking out files: 100% (45865/45865)
2020-06-23T05:25:33.156Z [INFO]: Checking out files: 100% (45865/45865), done.
2020-06-23T05:25:33.217Z [INFO]: # Checking for Git submodules at: /codebuild/output/src399389874/src/accessduoui/.gitmodules
2020-06-23T05:25:33.321Z [INFO]: # Retrieving cache...
2020-06-23T05:25:33.362Z [INFO]: # Extracting cache...
2020-06-23T05:25:33.373Z [INFO]: # Extraction completed
2020-06-23T05:25:33.373Z [INFO]: # Retrieving environment cache...
2020-06-23T05:25:33.409Z [INFO]: # Retrieved environment cache
2020-06-23T05:26:04.412Z [INFO]: ## Starting Frontend Build
                                 # Starting phase: preBuild
                                 # Executing command: npm ci
2020-06-23T05:26:05.529Z [WARNING]: npm
2020-06-23T05:26:05.531Z [WARNING]: WARN prepare removing existing node_modules/ before installation
2020-06-23T05:26:20.141Z [INFO]: > fsevents@1.2.13 install /codebuild/output/src399389874/src/accessduoui/node_modules/fsevents
                                 > node install.js
2020-06-23T05:26:20.199Z [INFO]: 
2020-06-23T05:26:20.201Z [INFO]: Skipping 'fsevents' build as platform linux is not supported
2020-06-23T05:26:20.234Z [INFO]: > uglifyjs-webpack-plugin@0.4.6 postinstall /codebuild/output/src399389874/src/accessduoui/node_modules/uglifyjs-webpack-plugin
                                 > node lib/post_install.js
2020-06-23T05:26:20.367Z [INFO]: > core-js@2.6.11 postinstall /codebuild/output/src399389874/src/accessduoui/node_modules/babel-runtime/node_modules/core-js
                                 > node -e "try{require('./postinstall')}catch(e){}"
2020-06-23T05:26:20.423Z [INFO]: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
                                 The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
                                 > https://opencollective.com/core-js
                                 > https://www.patreon.com/zloirock
                                 Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
2020-06-23T05:26:20.436Z [INFO]: > core-js@2.6.11 postinstall /codebuild/output/src399389874/src/accessduoui/node_modules/babel-register/node_modules/core-js
                                 > node -e "try{require('./postinstall')}catch(e){}"
2020-06-23T05:26:20.722Z [INFO]: > core-js@3.6.5 postinstall /codebuild/output/src399389874/src/accessduoui/node_modules/core-js
                                 > node -e "try{require('./postinstall')}catch(e){}"
2020-06-23T05:26:20.786Z [INFO]: > core-js-pure@3.6.5 postinstall /codebuild/output/src399389874/src/accessduoui/node_modules/core-js-pure
                                 > node -e "try{require('./postinstall')}catch(e){}"
2020-06-23T05:26:20.849Z [INFO]: added 1769 packages in 15.338s
2020-06-23T05:26:20.861Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
2020-06-23T05:26:20.862Z [INFO]: # Executing command: npm run build
2020-06-23T05:26:21.037Z [INFO]: > first-react@0.1.0 build /codebuild/output/src399389874/src/accessduoui
                                 > react-scripts build
2020-06-23T05:26:21.732Z [INFO]: Creating an optimized production build...
2020-06-23T05:26:43.919Z [INFO]: Failed to compile.
2020-06-23T05:26:43.922Z [INFO]: ./src/Menustyle.css
                                 Module build failed: BrowserslistError: Unknown browser query `dead`
                                 at Array.forEach (<anonymous>)
2020-06-23T05:26:43.952Z [WARNING]: npm
2020-06-23T05:26:43.953Z [WARNING]: ERR! code ELIFECYCLE
                                    npm ERR! errno 1
                                    npm ERR! first-react@0.1.0 build: `react-scripts build`
                                    npm ERR! Exit status 1
                                    npm ERR!
                                    npm ERR! Failed at the first-react@0.1.0 build script.
                                    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-06-23T05:26:43.959Z [WARNING]: 
2020-06-23T05:26:43.960Z [WARNING]: npm ERR! A complete log of this run can be found in:
                                    npm ERR!     /root/.npm/_logs/2020-06-23T05_26_43_953Z-debug.log
2020-06-23T05:26:43.960Z [HELP]: Outputting the npm debug log
                                 0 info it worked if it ends with ok
                                 1 verbose cli [ '/root/.nvm/versions/node/v10.16.0/bin/node',
                                 1 verbose cli   '/root/.nvm/versions/node/v10.16.0/bin/npm',
                                 1 verbose cli   'run',
                                 1 verbose cli   'build' ]
                                 2 info using npm@6.9.0
                                 3 info using node@v10.16.0
                                 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
                                 5 info lifecycle first-react@0.1.0~prebuild: first-react@0.1.0
                                 6 info lifecycle first-react@0.1.0~build: first-react@0.1.0
                                 7 verbose lifecycle first-react@0.1.0~build: unsafe-perm in lifecycle true
                                 8 verbose lifecycle first-react@0.1.0~build: PATH: /root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/codebuild/output/src399389874/src/accessduoui/node_modules/.bin:/usr/local/rvm/gems/ruby-2.4.6/bin:/usr/local/rvm/gems/ruby-2.4.6@global/bin:/usr/local/rvm/rubies/ruby-2.4.6/bin:/usr/local/rvm/bin:/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:/root/.nvm/versions/node/v10.16.0/bin:/root/.local/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
                                 9 verbose lifecycle first-react@0.1.0~build: CWD: /codebuild/output/src399389874/src/accessduoui
                                 10 silly lifecycle first-react@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
                                 11 silly lifecycle first-react@0.1.0~build: Returned: code: 1  signal: null
                                 12 info lifecycle first-react@0.1.0~build: Failed to exec build script
                                 13 verbose stack Error: first-react@0.1.0 build: `react-scripts build`
                                 13 verbose stack Exit status 1
                                 13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
                                 13 verbose stack     at EventEmitter.emit (events.js:198:13)
                                 13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
                                 13 verbose stack     at ChildProcess.emit (events.js:198:13)
                                 13 verbose stack     at maybeClose (internal/child_process.js:982:16)
                                 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
                                 14 verbose pkgid first-react@0.1.0
                                 15 verbose cwd /codebuild/output/src399389874/src/accessduoui
                                 16 verbose Linux 4.14.181-108.257.amzn1.x86_64
                                 17 verbose argv "/root/.nvm/versions/node/v10.16.0/bin/node" "/root/.nvm/versions/node/v10.16.0/bin/npm" "run" "build"
                                 18 verbose node v10.16.0
                                 19 verbose npm  v6.9.0
                                 20 error code ELIFECYCLE
                                 21 error errno 1
                                 22 error first-react@0.1.0 build: `react-scripts build`
                                 22 error Exit status 1
                                 23 error Failed at the first-react@0.1.0 build script.
                                 23 error This is probably not a problem with npm. There is likely additional logging output above.
                                 24 verbose exit [ 1, true ]
2020-06-23T05:26:43.962Z [ERROR]: !!! Build failed
2020-06-23T05:26:44.066Z [ERROR]: !!! Non-Zero Exit Code detected
2020-06-23T05:26:44.067Z [INFO]: # Starting environment caching...
2020-06-23T05:26:44.068Z [INFO]: # Environment caching completed
Terminating logging...

**Comment by swaminator** [comment]
This looks like an error in your frontend code. We cannot help with diagnosing individual build failure issues.
