### ISSUE TITLE
Problems publishing App 

### ISSUE THREAD

**Issue by yhuber** [aws-amplify/amplify-console#785]
I am trying to publish my App. It used to work fine, until I updated my auth with social Provider (federation). Now i get this error message:

2020-06-23T08:11:07.616Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2020-06-23T08:11:07.616Z [WARNING]: ✖ There was an error initializing your environment.
2020-06-23T08:11:07.616Z [INFO]: init failed
2020-06-23T08:11:07.617Z [INFO]: TypeError: Cannot read property 'Mappings' of undefined
                                 at collectTemplates (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/splitStack.js:78:36)
                                 at Object.splitStack [as default] (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/splitStack.js:208:20)
                                 at TransformFormatter.format (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/TransformFormatter.js:25:50)
                                 at GraphQLTransform.transform (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/GraphQLTransform.js:207:26)
                                 at _buildProject (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/lib/util/amplifyUtils.js:56:37)
2020-06-23T08:11:07.629Z [ERROR]: !!! Build failed
2020-06-23T08:11:07.629Z [ERROR]: !!! Non-Zero Exit Code detected
2020-06-23T08:11:07.629Z [INFO]: # Starting environment caching...
2020-06-23T08:11:07.630Z [INFO]: # Environment caching completed

**Comment by abhi7cr** [comment]
Hi @yhuber,

Could you give me the appid and region? The app was published through Amplify Console?

**Comment by yhuber** [comment]
Hi @abhi7cr sure: 

App-ID: d2qth7s9qped0u
region=eu-central-1

**Comment by yhuber** [comment]
@abhi7cr oh i missed that, I published through amplify cli in my terminal and then connected it in the Amplify console with a github repository

**Comment by abhi7cr** [comment]
@yhuber There is a related issue (**Cannot read property 'Mappings' of undefined**) in the cli project that was closed sometime back: https://github.com/aws-amplify/amplify-cli/issues/3576. The root cause mentioned there were duplicate files generated by text editors. Could you check if you have a similar state?  In your case, the cli command is executed via the amplifyPush script. 

If that's not the case, could you try to re-publish the App without the federation, just to confirm if the issue is with federation or not?

**Comment by yhuber** [comment]
Hi, 
I looked into that related issue and I also have duplicate files.. 
I've done all steps attilah suggested. But now i have the following error,
when trying to push the env to amplify with "amplify push" : 

```
There was an error initializing your environment.
ENOENT: no such file or directory, open '/Users/yannikhuber/Documents/masquick 2.0/Masquick/amplify/#current-cloud-backend/amplify-meta.json'
Error: ENOENT: no such file or directory, open '/Users/yannikhuber/Documents/masquick 2.0/Masquick/amplify/#current-cloud-backend/amplify-meta.json'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at AmplifyToolkit.readJsonFile [as _readJsonFile] (/usr/local/lib/node_modules/@aws-amplify/cli/src/extensions/amplify-helpers/read-json-file.js:14:33)
    at /usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initialize-env.js:35:50
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by yhuber** [comment]
`✖ There was an error pulling the backend environment prod.
An error occured during the push operation: ENOENT: no such file or directory, open '/Users/yannikhuber/Documents/masquick 2.0/Masquick/amplify/#current-cloud-backend/amplify-meta.json'`
