### ISSUE TITLE
ValidationError: No updates are to be performed.

### ISSUE THREAD

**Issue by devth** [aws-amplify/amplify-console#849]
I removed auth on my envs via `amplify auth remove`, `amplify push`ed, then `git push`ed to master. Amplify tried to build at that point but is now stuck in the build phase with the error:

```
2020-07-13T14:28:42.365Z [INFO]: ValidationError: No updates are to be performed.
                                 at Request.extractError (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:688:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:690:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
2020-07-13T14:28:42.378Z [ERROR]: !!! Build failed
2020-07-13T14:28:42.451Z [ERROR]: !!! Non-Zero Exit Code detected
```

**Comment by devth** [comment]
I deleted my amplify project and created a new one against the same backend role, and the same error occurred 🤔

**Comment by abhi7cr** [comment]
Hi @devth ,

Can you share your appId and region?

**Comment by devth** [comment]
I was able to get past it after fully deleting my project and all `./amplify/*` files.

`us-west-2` `docproject`

**Comment by abhi7cr** [comment]
Hi @devth,

Are you still facing the issue?

**Comment by devth** [comment]
No, but only because I deleted my project and started over. I've had to do that several times so far.

**Comment by abhi7cr** [comment]
Just to understand the steps to reproduce:

1) Add auth to an amplify project via CLI
2) Remove auth from the CLI (`amplify auth remove`)
3) Push the update to cloud (`amplify push`)
At this point, the `amplify` directory should reflect the removal of auth
4. Push the changes to git (`git push`)
5. The push triggers an update in Amplify Console, and the build fails saying there are no updates to be performed?

Are the above steps correct?

**Comment by devth** [comment]
Maybe, but I did a lot of other stuff along the way, and also had 2 environments that I added and removed `auth` from.

**Comment by swaminator** [comment]
Closing as this is not easily reproducible.
