### ISSUE TITLE
Failed to minify the bundle - Frontend Build step

### ISSUE THREAD

**Issue by blazinaj** [aws-amplify/amplify-console#891]
Our auto-deploys started failing due to an error in the Frontend Build step.

```
2020-07-23T16:03:08.961Z [INFO]: Creating an optimized production build...
2020-07-23T16:07:07.789Z [INFO]: Failed to compile.
                                 Failed to minify the bundle. Error: static/js/15.9f62c4c6.chunk.js from Terser
                                 Error: Call retries were exceeded
                                 at compiler.run (/codebuild/output/src730201856/src/rivial-information-security-center/node_modules/react-scripts/scripts/build.js:196:23)
                                 at finalCallback (/codebuild/output/src730201856/src/rivial-information-security-center/node_modules/webpack/lib/Compiler.js:257:39)
                                 at hooks.done.callAsync.err (/codebuild/output/src730201856/src/rivial-information-security-center/node_modules/webpack/lib/Compiler.js:273:13)
                                 at AsyncSeriesHook.eval [as callAsync] (eval at create (/codebuild/output/src730201856/src/rivial-information-security-center/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
                                 at AsyncSeriesHook.lazyCompileHook (/codebuild/output/src730201856/src/rivial-information-security-center/node_modules/tapable/lib/Hook.js:154:20)
                                 at onCompiled (/codebuild/output/src730201856/src/rivial-information-security-center/node_modules/webpack/lib/Compiler.js:271:21)
                                 at hooks.afterCompile.callAsync.err (/codebuild/output/src730201856/src/rivial-information-security-center/node_modules/webpack/lib/Compiler.js:681:15)
                                 at AsyncSeriesHook.eval [as callAsync] (eval at create (/codebuild/output/src730201856/src/rivial-information-security-center/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
                                 at AsyncSeriesHook.lazyCompileHook (/codebuild/output/src730201856/src/rivial-information-security-center/node_modules/tapable/lib/Hook.js:154:20)
                                 at compilation.seal.err (/codebuild/output/src730201856/src/rivial-information-security-center/node_modules/webpack/lib/Compiler.js:678:31)
                                 at AsyncSeriesHook.eval [as callAsync] (eval at create (/codebuild/output/src730201856/src/rivial-information-security-center/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
                                 at AsyncSeriesHook.lazyCompileHook (/codebuild/output/src730201856/src/rivial-information-security-center/node_modules/tapable/lib/Hook.js:154:20)
                                 at hooks.optimizeAssets.callAsync.err (/codebuild/output/src730201856/src/rivial-information-security-center/node_modules/webpack/lib/Compilation.js:1423:35)
                                 at AsyncSeriesHook.eval [as callAsync] (eval at create (/codebuild/output/src730201856/src/rivial-information-security-center/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
                                 at AsyncSeriesHook.lazyCompileHook (/codebuild/output/src730201856/src/rivial-information-security-center/node_modules/tapable/lib/Hook.js:154:20)
                                 at hooks.optimizeChunkAssets.callAsync.err (/codebuild/output/src730201856/src/rivial-information-security-center/node_modules/webpack/lib/Compilation.js:1414:32)
                                 Read more here: https://bit.ly/CRA-build-minify
```

This doesn't seem like a direct issue with Amplify Console, most likely with React: https://github.com/facebook/create-react-app/issues/6336.

This doesn't happen when we build locally, so I'm at a loss. Anyone have any ideas how to fix this? I've tried updating react-scripts, and adding Terser as a devDep but no luck.

**Comment by ganipcanot** [comment]
Have you tried this? https://github.com/aws-amplify/amplify-console/issues/742

**Comment by blazinaj** [comment]
Yeah, this is an issue with the frontend build step. We are thinking we might be using more than the 7GB of RAM that the environment has available. Is there any way to increase that?

**Comment by blazinaj** [comment]
#654
