### ISSUE TITLE
New Build Failed Error on Console

### ISSUE THREAD

**Issue by ernestostifano** [aws-amplify/amplify-console#900]
** Please describe which feature you have a question about? **
Error while building backend on console.

This is very frustrating, everything was working as expected regarding functions build process. I had to delete an re-create an Amplify App because of other bugs in the CLI. I updated to CLI 4.24.0 in the meantime from the immediate previous version and now I'm getting this error... Dependencies are correctly setup, it works locally. It seems that devDependencies from root package.json are not being installed. I spend more time creating/solving Amplify issues than working on the real thing.

** Provide additional details**
This is the downloaded log:
```txt
2020-07-26T13:48:48.042Z [INFO]: Git SSH Key acquired
2020-07-26T13:48:48.110Z [INFO]: # Cloning repository: git@bitbucket.org:XXXXXXXX/XXXXXXXX.git
2020-07-26T13:48:48.216Z [INFO]: Agent pid 126
2020-07-26T13:48:48.243Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2020-07-26T13:48:48.431Z [INFO]: Cloning into 'XXXXXXXX'...
2020-07-26T13:48:48.963Z [INFO]: Warning: Permanently added the RSA host key for IP address 'XXXXXXXX' to the list of known hosts.
2020-07-26T13:48:51.843Z [INFO]: # Checking for Git submodules at: /codebuild/output/src320501691/src/XXXXXXXX/.gitmodules
2020-07-26T13:48:51.962Z [INFO]: # Retrieving cache...
2020-07-26T13:48:51.978Z [INFO]: # Extracting cache...
2020-07-26T13:48:51.986Z [INFO]: # Extraction completed
2020-07-26T13:48:51.987Z [INFO]: # Retrieving environment cache...
2020-07-26T13:48:52.026Z [INFO]: # Retrieved environment cache
2020-07-26T13:48:52.027Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2020-07-26T13:49:00.959Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 1.12.0 to 4.25.0...
2020-07-26T13:49:46.427Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
2020-07-26T13:49:50.144Z [INFO]: ## Starting Backend Build
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-07-26T13:49:55.810Z [INFO]: 
2020-07-26T13:49:55.812Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html
2020-07-26T13:49:56.391Z [INFO]: Amplify AppID found: XXXXXXXX. Amplify App name is: XXXXXXXX
2020-07-26T13:49:56.576Z [INFO]: Backend environment dev found in Amplify Console app: XXXXXXXX
2020-07-26T13:50:08.492Z [INFO]: 
2020-07-26T13:50:08.494Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2020-07-26T13:50:19.061Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2020-07-26T13:50:23.003Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2020-07-26T13:50:23.004Z [WARNING]: ✖ There was an error initializing your environment.
2020-07-26T13:50:23.353Z [INFO]: Failed to pull the backend.
2020-07-26T13:50:23.354Z [INFO]: ,yarn run v1.16.0
                                 $ cd ./amplify/backend/function/XXXXXXXX && babel --root-mode upward ./uncompiled-src --out-dir ./src --copy-files && cd -
                                 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
                                 ,/bin/sh: babel: command not found
                                 error Command failed with exit code 127.
2020-07-26T13:50:23.364Z [INFO]: Error: ,yarn run v1.16.0
                                 $ cd ./amplify/backend/function/XXXXXXXX && babel --root-mode upward ./uncompiled-src --out-dir ./src --copy-files && cd -
                                 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
                                 ,/bin/sh: babel: command not found
                                 error Command failed with exit code 127.
                                 at runPackageManager (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:54:11)
                                 at runBuildScriptHook (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:24:5)
                                 at Object.buildResource (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/utils/legacyBuild.ts:14:7)
                                 at Object.build (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-nodejs-function-runtime-provider/src/index.ts:44:22)
                                 at buildResource (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/build-resources.js:49:36)
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
2020-07-26T13:50:23.379Z [ERROR]: !!! Build failed
2020-07-26T13:50:23.379Z [ERROR]: !!! Non-Zero Exit Code detected
2020-07-26T13:50:23.381Z [INFO]: # Starting environment caching...
2020-07-26T13:50:23.381Z [INFO]: # Environment caching completed
Terminating logging...
```

**Comment by ernestostifano** [comment]
I've just temporarily fixed this by adding `yarn install` as a pre-build command for the backend.

I say "temporarily" because I think there is a lot of work to do on your side to improve some of the current flows and correctly describe them in the documentation. I'll cross-reference this issue with https://github.com/aws-amplify/amplify-cli/issues/4868 because they are strictly related. I insist, Functions directory structure and building process is messed up.

Additionally, how is it possible for the backend building process to suffer a breaking change without any advise? If you read the [Build options page](https://docs.amplify.aws/cli/function/build-options) you'll see that adding `yarn install` as a pre-build command for the backend is not specified and was not required until now.

Finally, why mixing backend and frontend dependencies and building processes? Why should babel for the backend be defined in my frontend's `package.json` and why should building scripts for Functions be defined there too? Why do I have to install all of my frontend dependencies just for using Babel in the backend? I can think of many ways to hack the current recommended flow by adding some lines to the `amplify.yml` file, but I would like a better pattern to be developed and a better official solution to be proposed.

I know that this is an open source project and I don't want to be impolite, but at the end we are being charged for AWS services and we are putting our time and effort to adopt Amplify for our projects. Please help us doing that. Some issues should be avoided or quickly addressed. Documentation should be up to date. We are trying to help you improve your product.

**Comment by ernestostifano** [comment]
Another possible reason that I was thinking about for the sudden "change" could just be that backend building behaviour on `amplify push` is different than the one when backend is provisioned from the repository.

**Comment by garyleefight** [comment]
Sorry for the inconvenience. Looks like we didn't auto detect that you are using yarn. Is it because you missed yarn.lock in your root project folder? If not, can you share you appId, so that we can dig logs and see why it happens.

**Comment by ernestostifano** [comment]
@garyleefight thank you for your response. We always include `yarn.lock` file in VC to ensure everyone works with the same dependencies versions.

Unfortunately I've deleted and re-created the problematic APP and added the `yarn install` command from the beginning to avoid the issue.

However, even if there wasn't any `yarn.lock` or `package-lock.json` files, should't dependencies be installed anyway by using any package manager to ensure building process doesn't fail on cloud?

**Comment by garyleefight** [comment]
It should install dependencies with npm install by default. One possibility is that AWS Amplify console used the cache so didn't try to install your dependency once again
