### ISSUE TITLE
AccessDenied error when deploying backend

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-console#95]
Attempting to CI our dev branch using Amplify Console fails.

It seems to be a permissions issue but the amplifyconsole-backend-role role created using the defaults has AdministratorAccess.

Note this is the first deploy in a new AWS account if that is important.

This is the build log:

# Starting phase: build
# Executing command: amplifyPush --simple
2019-08-31T13:32:13.803Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2019-08-31T13:32:13.813Z [INFO]: # Start initializing Amplify environment: dev
# Initializing new Amplify environment: dev (amplify init)
019-08-31T13:32:08.202Z [INFO]: Git SSH Key acquired
2019-08-31T13:32:08.303Z [INFO]: # Cloning repository: git@bitbucket.org:jws2019/marketbox.git
2019-08-31T13:32:08.459Z [INFO]: Agent pid 69
2019-08-31T13:32:08.466Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2019-08-31T13:32:08.494Z [INFO]: Cloning into 'marketbox'...
2019-08-31T13:32:09.427Z [INFO]: Warning: Permanently added the RSA host key for IP address '18.205.93.0' to the list of known hosts.
2019-08-31T13:32:11.324Z [INFO]: # Checking for Git submodules at: /codebuild/output/src879933935/src/marketbox/.gitmodules
2019-08-31T13:32:11.443Z [INFO]: # Retrieving cache...
2019-08-31T13:32:11.499Z [INFO]: # Extracting cache...
2019-08-31T13:32:11.508Z [INFO]: # Extraction completed
2019-08-31T13:32:11.509Z [INFO]: # Retrieving environment cache...
2019-08-31T13:32:11.558Z [INFO]: # Retrieved environment cache
2019-08-31T13:32:11.559Z [WARNING]: ! Unable to patch packages...
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2019-08-31T13:32:13.803Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2019-08-31T13:32:13.813Z [INFO]: # Start initializing Amplify environment: dev
                                 # Initializing new Amplify environment: dev (amplify init)
2019-08-31T13:32:22.775Z [INFO]: Note: It is recommended to run this command from the root of your app directory
s/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 message: 'Access Denied',
                                 code: 'AccessDenied',
                                 region: null,
                                 time: 2019-08-31T13:32:25.478Z,
                                 requestId: '362C0F6B91B42952',
                                 extendedRequestId:
                                 'O/TpSdF7w8o4hzQDvGfYZ5wm40PHp36lkC/bVfiK6bNAtxgcgxKceR3NEVSqyehZjGD4ff90FwM=',
                                 cfId: undefined,
                                 statusCode: 403,
                                 retryable: false,
                                 retryDelay: 67.68424772299106 }
2019-08-31T13:32:25.561Z [ERROR]: !!! Build failed
2019-08-31T13:32:25.561Z [ERROR]: !!! Non-Zero Exit Code detected
2019-08-31T13:32:25.561Z [INFO]: # Starting environment caching...
2019-08-31T13:32:25.562Z [INFO]: # Environment caching completed
Terminating logging...

**Comment by nimacks** [comment]
Hi, can you provide your appId and region which your app is located?

**Comment by blairtaylor** [comment]
arn is arn:aws:amplify:us-east-1:102792536330:apps/dlodamgzbkkd3. region is us-east-1.

**Comment by nimacks** [comment]
@blairtaylor , you mention that this is a brand new AWS account. How did you setup permissions for the IAM User. Does this user have access to run CloudFormation?

**Comment by blairtaylor** [comment]
As I mentioned in the original post, the amplifyconsole-backend-role has AdministratorAccess as per the defaults.

**Comment by swaminator** [comment]
@blairtaylor we're not sure why you're getting this. Can you go to the IAM console > Roles and search for the `amplifyconsole-backend-role` > Trust relationships > edit. You should see:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "amplify.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

**Comment by blairtaylor** [comment]
Yes I see that policy.

Just tried it again. This is the build log. It looks like there is an issue deploying the aws sdk.

2019-09-27T00:15:51.138Z [INFO]: Git SSH Key acquired
2019-09-27T00:15:51.219Z [INFO]: # Cloning repository: git@bitbucket.org:<info>
2019-09-27T00:15:51.324Z [INFO]: Agent pid 72
2019-09-27T00:15:51.329Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2019-09-27T00:15:51.445Z [INFO]: Cloning into 'marketbox'...
2019-09-27T00:15:51.715Z [INFO]: Warning: Permanently added the RSA host key for IP address '18.205.93.2' to the list of known hosts.
2019-09-27T00:15:54.517Z [INFO]: # Checking for Git submodules at: /codebuild/output/src954281012/src/marketbox/.gitmodules
2019-09-27T00:15:54.619Z [INFO]: # Retrieving cache...
2019-09-27T00:15:54.653Z [INFO]: # Extracting cache...
2019-09-27T00:15:54.660Z [INFO]: # Extraction completed
2019-09-27T00:15:54.661Z [INFO]: # Retrieving environment cache...
2019-09-27T00:15:54.702Z [INFO]: # Retrieved environment cache
2019-09-27T00:16:01.873Z [INFO]: ## Starting Backend Build
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2019-09-27T00:16:01.878Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2019-09-27T00:16:01.901Z [INFO]: # Start initializing Amplify environment: dev
                                 # Initializing new Amplify environment: dev (amplify init)
2019-09-27T00:16:18.831Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2019-09-27T00:16:22.138Z [INFO]: 
2019-09-27T00:16:22.139Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html
2019-09-27T00:16:22.281Z [WARNING]: - Initializing your environment: dev
2019-09-27T00:16:22.609Z [WARNING]: ✖ There was an error initializing your environment.
2019-09-27T00:16:22.609Z [INFO]: init failed
2019-09-27T00:16:22.611Z [INFO]: { AccessDenied: Access Denied
                                 at Request.extractError (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:585:35)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 message: 'Access Denied',
                                 code: 'AccessDenied',
                                 region: null,
                                 time: 2019-09-27T00:16:22.608Z,
                                 requestId: 'F3739576AF6F43DA',
                                 extendedRequestId:
                                 'GIHOzsmGr4n23TpEBGY+haZ/7XPwO55Sf1qcSYvJbnF4rkY5uqAPqB6n8pTB8xeAByDFYqIHEDU=',
                                 cfId: undefined,
                                 statusCode: 403,
                                 retryable: false,
                                 retryDelay: 35.966987297925755 }
2019-09-27T00:16:22.679Z [ERROR]: !!! Build failed
2019-09-27T00:16:22.679Z [ERROR]: !!! Non-Zero Exit Code detected
2019-09-27T00:16:22.679Z [INFO]: # Starting environment caching...
2019-09-27T00:16:22.679Z [INFO]: # Environment caching completed
Terminating logging...

**Comment by AlexThomas90210** [comment]
Same problem, also in a brand new AWS account

**Comment by Joycehao19** [comment]
@AlexThomas90210 thanks for the tip. Can you look at the `teamprovider.json` inside the `amplify` folder? The accountIDs for resources there should match the account you're trying to deploy.

**Comment by swaminator** [comment]
@AlexThomas90210 can you please share your appiD? we'd like to investigate further.

**Comment by AlexThomas90210** [comment]
@swaminator Sorry for not updating, I have resolved it and it was more so a logical error with my aws account migration workflow than an issue with amplify. 

I cannot remember exactly what I did but it was something along the lines of:

1. I had env up in AWS account A called `dev`
2. I wanted to recreate env `dev` in AWS account B
3. I updated aws cli config xxxx with new access keys 
4. Tried to deploy to dev, assuming since no cloudformation template was presentin that account it would recreate the environment from scratch

I think to resolve it I just change the env name or else I nuked the previous account's environment.

I cant actually remember the specifics anymore sorry!

**Comment by jcvalerio** [comment]
@swaminator I have the same issue our appI is `d234qd3dwq9k16` at `us-east-1` region.

1. auto build stop working
2. remove the branch
2. adding back 
3. build starts

Bug we got the error below,
Even If we push another change to that branch nothing is fired on AWS Amplify Console.

Any ideas?

```
019-11-27T15:55:43.532Z [INFO]: Successfully added environment from your project
2019-11-27T15:55:43.550Z [INFO]: # Initializing existing Amplify environment: master (amplify init)
2019-11-27T15:55:46.316Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2019-11-27T15:55:47.199Z [WARNING]: - Initializing your environment: master
2019-11-27T15:55:47.283Z [WARNING]: ✖ There was an error initializing your environment.
2019-11-27T15:55:47.284Z [INFO]: init failed
2019-11-27T15:55:47.285Z [INFO]: { AccessDenied: Access Denied
                                 at Request.extractError (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:585:35)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 message: 'Access Denied',
                                 code: 'AccessDenied',
                                 region: null,
                                 time: 2019-11-27T15:55:47.281Z,
                                 requestId: '9EB3EB275E33A436',
                                 extendedRequestId:
                                 'gT6yL4mpB5ZEI8InawWDrrBxf8yW81Hg3OJlFVLLiBuqd3nj0lJPnTsyRZW898dG+eCeaZtMsgA=',
                                 cfId: undefined,
                                 statusCode: 403,
                                 retryable: false,
                                 retryDelay: 79.23623402882947 }
2019-11-27T15:55:47.328Z [ERROR]: !!! Build failed
2019-11-27T15:55:47.328Z [ERROR]: !!! Non-Zero Exit Code detected
2019-11-27T15:55:47.328Z [INFO]: # Starting environment caching...
2019-11-27T15:55:47.329Z [INFO]: # Environment caching completed
Terminating logging...
```

**Comment by swaminator** [comment]
@jcvalerio I think I know what's going on. Hunch is based on this SO issue: https://stackoverflow.com/questions/55941307/error-initializing-environment-after-running-amplify-init

What are the names of your backend envs?

**Comment by swaminator** [comment]
Actually @AlexThomas90210 solution might also help you: https://github.com/aws-amplify/amplify-console/issues/95#issuecomment-558854190

**Comment by jcvalerio** [comment]
@swaminator 

None of those works in our case.
Looking around we found this #88 

We were working with that version 2.0.0 , our envs *develop*, *PR*, etc. were building fine but *master* did not.

So, we change the version from 2.0.0 to *4.0.0* and build start working again.

I will say that I have no idea what happen on that env.
